/*
* 
* Copyright (c) 2001-2002. Centre for Research on Inner City Health, St. Michael's Hospital, Toronto. All Rights Reserved. *
* This software is published under the GPL GNU General Public License. 
* This program is free software; you can redistribute it and/or 
* modify it under the terms of the GNU General Public License 
* as published by the Free Software Foundation; either version 2 
* of the License, or (at your option) any later version. * 
* This program is distributed in the hope that it will be useful, 
* but WITHOUT ANY WARRANTY; without even the implied warranty of 
* MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the 
* GNU General Public License for more details. * * You should have received a copy of the GNU General Public License 
* along with this program; if not, write to the Free Software 
* Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA 02111-1307, USA. * 
* 
* <OSCAR TEAM>
* 
* This software was written for 
* Centre for Research on Inner City Health, St. Michael's Hospital, 
* Toronto, Ontario, Canada 
*/

package org.oscarehr.PMmodule.model.base;

import java.io.Serializable;


/**
 * This class has been automatically generated by Hibernate Synchronizer.
 * For more information or documentation, visit The Hibernate Synchronizer page
 * at http://www.binamics.com/hibernatesync or contact Joe Hudson at joe@binamics.com.
 *
 * This is an object that contains data related to the consent_interview table.
 * Do not modify this class because it will be overwritten if the configuration file
 * related to this class is modified.
 *
 * @hibernate.class
 *  table="consent_interview"
 */
public abstract class BaseConsentInterview  implements Serializable {

	public static String PROP_PRESSURE = "pressure";
	public static String PROP_EDUCATION = "education";
	public static String PROP_FORM_VERSION = "formVersion";
	public static String PROP_FOLLOWUP_OTHER = "followupOther";
	public static String PROP_FOLLOWUP = "followup";
	public static String PROP_INFORMATION = "information";
	public static String PROP_CONSENT_ID = "consentId";
	public static String PROP_REVIEW_OTHER = "reviewOther";
	public static String PROP_COMMENTS_OTHER = "commentsOther";
	public static String PROP_LANGUAGE = "language";
	public static String PROP_LANGUAGE_OTHER = "languageOther";
	public static String PROP_PROVIDER_NO = "ProviderNo";
	public static String PROP_PRESSURE_OTHER = "pressureOther";
	public static String PROP_FORM_NAME = "formName";
	public static String PROP_LANGUAGE_READ_OTHER = "languageReadOther";
	public static String PROP_REVIEW = "review";
	public static String PROP_DEMOGRAPHIC_NO = "demographicNo";
	public static String PROP_COMMENTS = "comments";
	public static String PROP_LANGUAGE_READ = "languageRead";
	public static String PROP_INFORMATION_OTHER = "informationOther";
	public static String PROP_ID = "Id";


	private int hashCode = Integer.MIN_VALUE;

	// primary key
	private java.lang.Long _id;

	// fields
	private long _consentId;
	private java.lang.Long _demographicNo;
	private java.lang.String _providerNo;
	private java.lang.String _formName;
	private java.lang.String _formVersion;
	private java.lang.String _language;
	private java.lang.String _languageOther;
	private java.lang.String _languageRead;
	private java.lang.String _languageReadOther;
	private java.lang.String _education;
	private java.lang.String _review;
	private java.lang.String _reviewOther;
	private java.lang.String _pressure;
	private java.lang.String _pressureOther;
	private java.lang.String _information;
	private java.lang.String _informationOther;
	private java.lang.String _followup;
	private java.lang.String _followupOther;
	private java.lang.String _comments;
	private java.lang.String _commentsOther;


	// constructors
	public BaseConsentInterview () {
		initialize();
	}

	/**
	 * Constructor for primary key
	 */
	public BaseConsentInterview (java.lang.Long _id) {
		this.setId(_id);
		initialize();
	}

	/**
	 * Constructor for required fields
	 */
	public BaseConsentInterview (
		java.lang.Long _id,
		long _consentId,
		java.lang.Long _demographicNo,
		java.lang.String _providerNo) {

		this.setId(_id);
		this.setConsentId(_consentId);
		this.setDemographicNo(_demographicNo);
		this.setProviderNo(_providerNo);
		initialize();
	}

	protected void initialize () {}



	/**
	 * Return the unique identifier of this class
     * @hibernate.id
     *  generator-class="native"
     *  column="id"
     */
	public java.lang.Long getId () {
		return _id;
	}

	/**
	 * Set the unique identifier of this class
	 * @param _id the new ID
	 */
	public void setId (java.lang.Long _id) {
		this._id = _id;
		this.hashCode = Integer.MIN_VALUE;
	}


	/**
	 * Return the value associated with the column: consent_id
	 */
	public long getConsentId () {
		return _consentId;
	}

	/**
	 * Set the value related to the column: consent_id
	 * @param _consentId the consent_id value
	 */
	public void setConsentId (long _consentId) {
		this._consentId = _consentId;
	}


	/**
	 * Return the value associated with the column: demographic_no
	 */
	public java.lang.Long getDemographicNo () {
		return _demographicNo;
	}

	/**
	 * Set the value related to the column: demographic_no
	 * @param _demographicNo the demographic_no value
	 */
	public void setDemographicNo (java.lang.Long _demographicNo) {
		this._demographicNo = _demographicNo;
	}


	/**
	 * Return the value associated with the column: provider_no
	 */
	public java.lang.String getProviderNo () {
		return _providerNo;
	}

	/**
	 * Set the value related to the column: provider_no
	 * @param _providerNo the provider_no value
	 */
	public void setProviderNo (java.lang.String _providerNo) {
		this._providerNo = _providerNo;
	}


	/**
	 * Return the value associated with the column: form_name
	 */
	public java.lang.String getFormName () {
		return _formName;
	}

	/**
	 * Set the value related to the column: form_name
	 * @param _formName the form_name value
	 */
	public void setFormName (java.lang.String _formName) {
		this._formName = _formName;
	}


	/**
	 * Return the value associated with the column: form_version
	 */
	public java.lang.String getFormVersion () {
		return _formVersion;
	}

	/**
	 * Set the value related to the column: form_version
	 * @param _formVersion the form_version value
	 */
	public void setFormVersion (java.lang.String _formVersion) {
		this._formVersion = _formVersion;
	}


	/**
	 * Return the value associated with the column: language
	 */
	public java.lang.String getLanguage () {
		return _language;
	}

	/**
	 * Set the value related to the column: language
	 * @param _language the language value
	 */
	public void setLanguage (java.lang.String _language) {
		this._language = _language;
	}


	/**
	 * Return the value associated with the column: language_other
	 */
	public java.lang.String getLanguageOther () {
		return _languageOther;
	}

	/**
	 * Set the value related to the column: language_other
	 * @param _languageOther the language_other value
	 */
	public void setLanguageOther (java.lang.String _languageOther) {
		this._languageOther = _languageOther;
	}


	/**
	 * Return the value associated with the column: language_read
	 */
	public java.lang.String getLanguageRead () {
		return _languageRead;
	}

	/**
	 * Set the value related to the column: language_read
	 * @param _languageRead the language_read value
	 */
	public void setLanguageRead (java.lang.String _languageRead) {
		this._languageRead = _languageRead;
	}


	/**
	 * Return the value associated with the column: language_read_other
	 */
	public java.lang.String getLanguageReadOther () {
		return _languageReadOther;
	}

	/**
	 * Set the value related to the column: language_read_other
	 * @param _languageReadOther the language_read_other value
	 */
	public void setLanguageReadOther (java.lang.String _languageReadOther) {
		this._languageReadOther = _languageReadOther;
	}


	/**
	 * Return the value associated with the column: education
	 */
	public java.lang.String getEducation () {
		return _education;
	}

	/**
	 * Set the value related to the column: education
	 * @param _education the education value
	 */
	public void setEducation (java.lang.String _education) {
		this._education = _education;
	}


	/**
	 * Return the value associated with the column: review
	 */
	public java.lang.String getReview () {
		return _review;
	}

	/**
	 * Set the value related to the column: review
	 * @param _review the review value
	 */
	public void setReview (java.lang.String _review) {
		this._review = _review;
	}


	/**
	 * Return the value associated with the column: review_other
	 */
	public java.lang.String getReviewOther () {
		return _reviewOther;
	}

	/**
	 * Set the value related to the column: review_other
	 * @param _reviewOther the review_other value
	 */
	public void setReviewOther (java.lang.String _reviewOther) {
		this._reviewOther = _reviewOther;
	}


	/**
	 * Return the value associated with the column: pressure
	 */
	public java.lang.String getPressure () {
		return _pressure;
	}

	/**
	 * Set the value related to the column: pressure
	 * @param _pressure the pressure value
	 */
	public void setPressure (java.lang.String _pressure) {
		this._pressure = _pressure;
	}


	/**
	 * Return the value associated with the column: pressure_other
	 */
	public java.lang.String getPressureOther () {
		return _pressureOther;
	}

	/**
	 * Set the value related to the column: pressure_other
	 * @param _pressureOther the pressure_other value
	 */
	public void setPressureOther (java.lang.String _pressureOther) {
		this._pressureOther = _pressureOther;
	}


	/**
	 * Return the value associated with the column: information
	 */
	public java.lang.String getInformation () {
		return _information;
	}

	/**
	 * Set the value related to the column: information
	 * @param _information the information value
	 */
	public void setInformation (java.lang.String _information) {
		this._information = _information;
	}


	/**
	 * Return the value associated with the column: information_other
	 */
	public java.lang.String getInformationOther () {
		return _informationOther;
	}

	/**
	 * Set the value related to the column: information_other
	 * @param _informationOther the information_other value
	 */
	public void setInformationOther (java.lang.String _informationOther) {
		this._informationOther = _informationOther;
	}


	/**
	 * Return the value associated with the column: followup
	 */
	public java.lang.String getFollowup () {
		return _followup;
	}

	/**
	 * Set the value related to the column: followup
	 * @param _followup the followup value
	 */
	public void setFollowup (java.lang.String _followup) {
		this._followup = _followup;
	}


	/**
	 * Return the value associated with the column: followup_other
	 */
	public java.lang.String getFollowupOther () {
		return _followupOther;
	}

	/**
	 * Set the value related to the column: followup_other
	 * @param _followupOther the followup_other value
	 */
	public void setFollowupOther (java.lang.String _followupOther) {
		this._followupOther = _followupOther;
	}


	/**
	 * Return the value associated with the column: comments
	 */
	public java.lang.String getComments () {
		return _comments;
	}

	/**
	 * Set the value related to the column: comments
	 * @param _comments the comments value
	 */
	public void setComments (java.lang.String _comments) {
		this._comments = _comments;
	}


	/**
	 * Return the value associated with the column: comments_other
	 */
	public java.lang.String getCommentsOther () {
		return _commentsOther;
	}

	/**
	 * Set the value related to the column: comments_other
	 * @param _commentsOther the comments_other value
	 */
	public void setCommentsOther (java.lang.String _commentsOther) {
		this._commentsOther = _commentsOther;
	}


	public boolean equals (Object obj) {
		if (null == obj) return false;
		if (!(obj instanceof org.oscarehr.PMmodule.model.base.BaseConsentInterview)) return false;
		else {
			org.oscarehr.PMmodule.model.base.BaseConsentInterview mObj = (org.oscarehr.PMmodule.model.base.BaseConsentInterview) obj;
			if (null == this.getId() || null == mObj.getId()) return false;
			else return (this.getId().equals(mObj.getId()));
		}
	}


	public int hashCode () {
		if (Integer.MIN_VALUE == this.hashCode) {
			if (null == this.getId()) return super.hashCode();
			else {
				String hashStr = this.getClass().getName() + ":" + this.getId().hashCode();
				this.hashCode = hashStr.hashCode();
			}
		}
		return this.hashCode;
	}


	public String toString () {
		return super.toString();
	}

}