package org.oscarehr.PMmodule.model.base;

import java.io.Serializable;


/**
 * This class has been automatically generated by Hibernate Synchronizer.
 * For more information or documentation, visit The Hibernate Synchronizer page
 * at http://www.binamics.com/hibernatesync or contact Joe Hudson at joe@binamics.com.
 *
 * This is an object that contains data related to the formintakea table.
 * Do not modify this class because it will be overwritten if the configuration file
 * related to this class is modified.
 *
 * @hibernate.class
 *  table="formintakea"
 */
public abstract class BaseFormintakea  implements Serializable {

	public static String PROP_CBOX_IDFILED = "CboxIdfiled";
	public static String PROP_CBOX_ASSISTINEDUCATION = "CboxAssistineducation";
	public static String PROP_CITZENSHIP_CARD_NUM = "CitzenshipCardNum";
	public static String PROP_RADIO_HASDOCTOR = "RadioHasdoctor";
	public static String PROP_RADIO_SEATONTOUR = "RadioSeatontour";
	public static String PROP_RADIO_SPEAKTORESEARCHER = "RadioSpeaktoresearcher";
	public static String PROP_DOCTOR_NAME = "DoctorName";
	public static String PROP_CBOX_SINCARD = "CboxSincard";
	public static String PROP_HEALTH_ISSUE_DETAILS = "HealthIssueDetails";
	public static String PROP_CBOX_ASSISTINFINANCE = "CboxAssistinfinance";
	public static String PROP_CBOX_FORTYORK = "CboxFortyork";
	public static String PROP_CBOX_ODSP = "CboxOdsp";
	public static String PROP_YEAR = "Year";
	public static String PROP_RADIO_RATEOVERALLHEALTH = "RadioRateoverallhealth";
	public static String PROP_CBOX_HEARINGIMPAIR = "CboxHearingimpair";
	public static String PROP_RADIO_SEESAMEDOCTOR = "RadioSeesamedoctor";
	public static String PROP_DOCTOR_ADDRESS = "DoctorAddress";
	public static String PROP_BIRTH_CERTIFICATE_NUM = "BirthCertificateNum";
	public static String PROP_RADIO_DIDNOTRECEIVEHEALTHCARE = "RadioDidnotreceivehealthcare";
	public static String PROP_RADIO_HASBEHAVIORPROBLEM = "RadioHasbehaviorproblem";
	public static String PROP_CBOX_BLEEDING = "CboxBleeding";
	public static String PROP_CONTACT_RELATIONSHIP = "ContactRelationship";
	public static String PROP_LAST_ISSUE_DATE = "LastIssueDate";
	public static String PROP_RADIO_ONLINECHECK = "RadioOnlinecheck";
	public static String PROP_RADIO_HASDRUGPROBLEM = "RadioHasdrugproblem";
	public static String PROP_DATES_AT_SEATON = "DatesAtSeaton";
	public static String PROP_COMPLETED_BY = "CompletedBy";
	public static String PROP_CBOX_REFUGEE = "CboxRefugee";
	public static String PROP_CBOX_VISUALIMPAIR = "CboxVisualimpair";
	public static String PROP_RADIO_HASHEALTHPROBLEM = "RadioHashealthproblem";
	public static String PROP_FORM_CREATED = "FormCreated";
	public static String PROP_CBOX_ISSTATEMENTREAD = "CboxIsstatementread";
	public static String PROP_OTHER_SPECIFY = "OtherSpecify";
	public static String PROP_CBOX_NORECORD = "CboxNorecord";
	public static String PROP_CBOX_MOBILITYIMPAIR = "CboxMobilityimpair";
	public static String PROP_CBOX_GOTOHEALTHCENTER = "CboxGotohealthcenter";
	public static String PROP_SPEAK_OTHER = "SpeakOther";
	public static String PROP_CBOX_SPEAKFRENCH = "CboxSpeakfrench";
	public static String PROP_OFFICE = "Office";
	public static String PROP_CBOX_SPEAKOTHER = "CboxSpeakother";
	public static String PROP_DATE_OF_READMISSION = "DateOfReadmission";
	public static String PROP_PROVIDER_NO = "ProviderNo";
	public static String PROP_HEALTH_CARD_VER = "HealthCardVer";
	public static String PROP_CLIENT_SURNAME = "ClientSurname";
	public static String PROP_CBOX_OTHERID = "CboxOtherid";
	public static String PROP_CBOX_ASSISTINLEGAL = "CboxAssistinlegal";
	public static String PROP_AMT_RECEIVED = "AmtReceived";
	public static String PROP_CBOX_EPILEPSY = "CboxEpilepsy";
	public static String PROP_CBOX_HOSTEL_FUSION_CARE = "CboxHostelFusionCare";
	public static String PROP_RADIO_OBJECTTOREGULARDOCTORIN4WKS = "RadioObjecttoregulardoctorin4wks";
	public static String PROP_CBOX_ONEILLHOUSE = "CboxOneillhouse";
	public static String PROP_CONTACT_ADDRESS = "ContactAddress";
	public static String PROP_CBOX_VISITHEALTHOFFICE = "CboxVisithealthoffice";
	public static String PROP_HELP_OBTAIN_MEDICATION = "HelpObtainMedication";
	public static String PROP_CBOX_ROTARYCLUB = "CboxRotaryclub";
	public static String PROP_ASSESS_COMPLETE_TIME = "AssessCompleteTime";
	public static String PROP_IMMIGRANT_NUM = "ImmigrantNum";
	public static String PROP_CBOX_ASSISTINIDENTIFICATION = "CboxAssistinidentification";
	public static String PROP_CBOX_ASSISTINEMPLOYMENT = "CboxAssistinemployment";
	public static String PROP_EFF_DATE = "EffDate";
	public static String PROP_TREAT_OTHER_REASONS = "TreatOtherReasons";
	public static String PROP_GO_TO_OTHERS = "GoToOthers";
	public static String PROP_RADIO_NEEDSEATONSERVICE = "RadioNeedseatonservice";
	public static String PROP_CBOX_ANNEXHARM = "CboxAnnexharm";
	public static String PROP_CBOX_DOWNSVIEWDELLS = "CboxDownsviewdells";
	public static String PROP_DEMOGRAPHIC_NO = "DemographicNo";
	public static String PROP_CBOX_TREATPHYSICALHEALTH = "CboxTreatphysicalhealth";
	public static String PROP_FORM_EDITED = "FormEdited";
	public static String PROP_CBOX_WSIB = "CboxWsib";
	public static String PROP_CBOX_GOTOOTHERS = "CboxGotoothers";
	public static String PROP_ENTER_SEATON_DATE = "EnterSeatonDate";
	public static String PROP_REACTION_TO_MEDICATION = "ReactionToMedication";
	public static String PROP_OTHER_IDENTIFICATION = "OtherIdentification";
	public static String PROP_CONTACT_PHONE = "ContactPhone";
	public static String PROP_CBOX_BIRTHCERTIFICATE = "CboxBirthcertificate";
	public static String PROP_CBOX_VISITEMERGENCYROOM = "CboxVisitemergencyroom";
	public static String PROP_SUMMARY = "Summary";
	public static String PROP_CBOX_HEALTHOFFICE = "CboxHealthoffice";
	public static String PROP_CBOX_OAS = "CboxOas";
	public static String PROP_CBOX_HASDIABETES = "CboxHasdiabetes";
	public static String PROP_RADIO_SEX = "RadioSex";
	public static String PROP_RADIO_HASMENTALILLNESS = "RadioHasmentalillness";
	public static String PROP_DOCTOR_PHONE = "DoctorPhone";
	public static String PROP_CBOX_OTHERINCOME = "CboxOtherincome";
	public static String PROP_HAS_WHAT_I_D = "HasWhatID";
	public static String PROP_ASSESS_START_TIME = "AssessStartTime";
	public static String PROP_SEATON_NOT_TOURED = "SeatonNotToured";
	public static String PROP_ASSESS_DATE = "AssessDate";
	public static String PROP_CBOX_VISITHEALTHCENTER = "CboxVisithealthcenter";
	public static String PROP_CBOX_CITZENSHIPCARD = "CboxCitzenshipcard";
	public static String PROP_MONTH = "Month";
	public static String PROP_CBOX_SHARING = "CboxSharing";
	public static String PROP_CBOX_HOSTEL = "CboxHostel";
	public static String PROP_CBOX_PAMPHLETISSUED = "CboxPamphletissued";
	public static String PROP_RADIO_MENTALHEALTHCONCERNS = "RadioMentalhealthconcerns";
	public static String PROP_CBOX_VISITOTHERS = "CboxVisitothers";
	public static String PROP_CBOX_DATEOFREADMISSION = "CboxDateofreadmission";
	public static String PROP_CBOX_HEALTHCARD = "CboxHealthcard";
	public static String PROP_FREQUENCY_OF_SEEING_DOCTOR = "FrequencyOfSeeingDoctor";
	public static String PROP_CBOX_TREATOTHERREASONS = "CboxTreatotherreasons";
	public static String PROP_REASON_TO_SEATON = "ReasonToSeaton";
	public static String PROP_MENTAL_HEALTH_CONCERNS = "MentalHealthConcerns";
	public static String PROP_PAMPHLET_NOT_ISSUED = "PamphletNotIssued";
	public static String PROP_CBOX_CPP = "CboxCpp";
	public static String PROP_CBOX_NOID = "CboxNoid";
	public static String PROP_CONTACT_NAME = "ContactName";
	public static String PROP_CBOX_GOTOWALKINCLINIC = "CboxGotowalkinclinic";
	public static String PROP_SIN_NUM = "SinNum";
	public static String PROP_HEALTH_CARD_NUM = "HealthCardNum";
	public static String PROP_MOBILITY_IMPAIR = "MobilityImpair";
	public static String PROP_CBOX_EMPLOYMENT = "CboxEmployment";
	public static String PROP_CBOX_ASSISTINADDICTIONS = "CboxAssistinaddictions";
	public static String PROP_CBOX_IMMIGRANT = "CboxImmigrant";
	public static String PROP_CBOX_VISITWALKINCLINIC = "CboxVisitwalkinclinic";
	public static String PROP_RADIO_ACTIVE = "RadioActive";
	public static String PROP_RADIO_PAMPHLETISSUED = "RadioPamphletissued";
	public static String PROP_CBOX_ASSISTINHEALTH = "CboxAssistinhealth";
	public static String PROP_CBOX_EI = "CboxEi";
	public static String PROP_ALLERGIC_TO_MEDICATION_NAME = "AllergicToMedicationName";
	public static String PROP_RADIO_OTHERHEALTHCONCERN = "RadioOtherhealthconcern";
	public static String PROP_DOCTOR_PHONE_EXT = "DoctorPhoneExt";
	public static String PROP_REFUGEE_NUM = "RefugeeNum";
	public static String PROP_RADIO_NEEDREGULARDOCTOR = "RadioNeedregulardoctor";
	public static String PROP_RADIO_SEEDOCTOR = "RadioSeedoctor";
	public static String PROP_CBOX_ASSISTINHOUSING = "CboxAssistinhousing";
	public static String PROP_DOCTOR_NAME2 = "DoctorName2";
	public static String PROP_CLIENT_FIRST_NAME = "ClientFirstName";
	public static String PROP_CBOX_NEWCLIENT = "CboxNewclient";
	public static String PROP_CBOX_ISSTATEMENT6READ = "CboxIsstatement6read";
	public static String PROP_CBOX_IDNONE = "CboxIdnone";
	public static String PROP_RADIO_HASDRINKINGPROBLEM = "RadioHasdrinkingproblem";
	public static String PROP_NAMES_OF_MEDICATION = "NamesOfMedication";
	public static String PROP_FREQUENCY_OF_SEEING_EMERGENCY_ROOM_DOCTOR = "FrequencyOfSeeingEmergencyRoomDoctor";
	public static String PROP_RADIO_APPMTSEEDOCTORIN3MTHS = "RadioAppmtseedoctorin3mths";
	public static String PROP_RADIO_ALLERGICTOMEDICATION = "RadioAllergictomedication";
	public static String PROP_RADIO_TAKEMEDICATION = "RadioTakemedication";
	public static String PROP_COMMENTS_ON_I_D = "CommentsOnID";
	public static String PROP_CBOX_LONGTERMPROGRAM = "CboxLongtermprogram";
	public static String PROP_CBOX_ASSISTINIMMIGRATION = "CboxAssistinimmigration";
	public static String PROP_CBOX_INSULIN = "CboxInsulin";
	public static String PROP_CBOX_OW = "CboxOw";
	public static String PROP_EVER_AT_SEATON_BEFORE = "EverAtSeatonBefore";
	public static String PROP_OTHER_HEALTH_CONERNS = "OtherHealthConerns";
	public static String PROP_CBOX_SPEAKENGLISH = "CboxSpeakenglish";
	public static String PROP_RADIO_HELPOBTAINMEDICATION = "RadioHelpobtainmedication";
	public static String PROP_CBOX_TREATINJURY = "CboxTreatinjury";
	public static String PROP_CBOX_REGULARCHECKUP = "CboxRegularcheckup";
	public static String PROP_DAY = "Day";
	public static String PROP_CBOX_BIRCHMOUNTRESIDENCE = "CboxBirchmountresidence";
	public static String PROP_CBOX_GOTOEMERGENCYROOM = "CboxGotoemergencyroom";
	public static String PROP_CBOX_TREATMENTALHEALTH = "CboxTreatmentalhealth";
	public static String PROP_ID = "Id";
	public static String PROP_WORKER_NUM = "WorkerNum";
	public static String PROP_RADIO_HEALTHISSUE = "RadioHealthissue";


	private int hashCode = Integer.MIN_VALUE;

	// primary key
	private java.lang.Long _id;

	// fields
	private java.lang.String _radioSex;
	private java.lang.String _effDate;
	private java.lang.String _cboxSharing;
	private java.lang.String _namesOfMedication;
	private java.lang.String _radioHasdoctor;
	private java.lang.String _healthIssueDetails;
	private java.lang.String _cboxOdsp;
	private java.lang.String _cboxFortyork;
	private java.lang.String _cboxIdnone;
	private java.lang.String _reactionToMedication;
	private java.lang.String _seatonNotToured;
	private java.lang.String _radioOtherhealthconcern;
	private java.lang.String _cboxOneillhouse;
	private java.lang.String _contactName;
	private java.lang.String _radioDidnotreceivehealthcare;
	private java.lang.String _cboxTreatphysicalhealth;
	private java.lang.String _cboxIdfiled;
	private java.lang.String _cboxTreatinjury;
	private java.lang.String _cboxOas;
	private java.lang.String _cboxOtherincome;
	private java.lang.String _cboxNewclient;
	private java.lang.String _radioSeedoctor;
	private java.lang.String _radioMentalhealthconcerns;
	private java.lang.String _radioObjecttoregulardoctorin4wks;
	private java.lang.String _helpObtainMedication;
	private java.lang.String _summary;
	private java.lang.String _day;
	private java.lang.String _cboxSpeakfrench;
	private java.lang.String _cboxIsstatement6read;
	private java.lang.String _hasWhatID;
	private java.lang.String _doctorPhone;
	private java.lang.String _radioHasdrinkingproblem;
	private java.lang.String _cboxDownsviewdells;
	private java.lang.String _cboxLongtermprogram;
	private java.lang.String _cboxGotoothers;
	private java.lang.String _speakOther;
	private java.lang.String _lastIssueDate;
	private java.lang.String _refugeeNum;
	private java.lang.String _radioHasbehaviorproblem;
	private java.lang.String _radioNeedregulardoctor;
	private java.lang.String _goToOthers;
	private java.lang.String _radioHelpobtainmedication;
	private java.lang.String _cboxAssistinhealth;
	private java.lang.String _cboxGotowalkinclinic;
	private java.lang.String _cboxNoid;
	private java.lang.String _cboxPamphletissued;
	private java.lang.String _cboxIsstatementread;
	private java.lang.String _cboxNorecord;
	private java.lang.String _cboxOw;
	private java.lang.String _assessCompleteTime;
	private java.lang.String _assessDate;
	private java.lang.String _cboxHearingimpair;
	private java.lang.String _cboxVisualimpair;
	private java.lang.String _cboxBirchmountresidence;
	private java.lang.String _cboxEi;
	private java.lang.String _radioHasdrugproblem;
	private java.lang.String _cboxVisithealthcenter;
	private java.lang.String _citzenshipCardNum;
	private java.lang.String _cboxRotaryclub;
	private java.lang.String _cboxHealthcard;
	private java.lang.String _clientSurname;
	private java.lang.String _treatOtherReasons;
	private java.lang.String _mobilityImpair;
	private java.lang.String _radioSeatontour;
	private java.lang.String _radioHealthissue;
	private java.lang.String _cboxAssistinhousing;
	private java.lang.String _amtReceived;
	private java.lang.String _cboxVisithealthoffice;
	private java.lang.String _completedBy;
	private java.lang.String _contactPhone;
	private java.lang.String _cboxImmigrant;
	private java.lang.String _healthCardVer;
	private java.lang.String _doctorName2;
	private java.lang.String _cboxDateofreadmission;
	private java.lang.String _cboxTreatotherreasons;
	private java.lang.String _cboxVisitothers;
	private java.lang.String _commentsOnID;
	private java.lang.String _assessStartTime;
	private java.lang.String _immigrantNum;
	private java.lang.String _cboxInsulin;
	private java.lang.String _radioSeesamedoctor;
	private java.lang.String _radioSpeaktoresearcher;
	private java.lang.String _cboxAssistinidentification;
	private java.lang.String _cboxSpeakenglish;
	private java.lang.String _contactRelationship;
	private java.lang.String _cboxTreatmentalhealth;
	private java.lang.String _datesAtSeaton;
	private java.lang.String _sinNum;
	private java.lang.String _radioRateoverallhealth;
	private java.lang.String _healthCardNum;
	private java.lang.String _office;
	private java.lang.String _radioNeedseatonservice;
	private java.lang.String _cboxBleeding;
	private java.lang.String _cboxRegularcheckup;
	private java.lang.String _workerNum;
	private java.lang.String _cboxVisitwalkinclinic;
	private java.lang.String _cboxHasdiabetes;
	private java.lang.String _birthCertificateNum;
	private java.lang.String _clientFirstName;
	private java.lang.String _month;
	private java.lang.String _radioAllergictomedication;
	private java.lang.String _cboxCpp;
	private java.lang.String _cboxHostelFusionCare;
	private java.lang.String _frequencyOfSeeingDoctor;
	private java.lang.String _cboxOtherid;
	private java.lang.String _cboxAssistineducation;
	private java.lang.String _cboxAnnexharm;
	private java.lang.String _cboxVisitemergencyroom;
	private java.lang.String _cboxMobilityimpair;
	private java.lang.String _cboxHealthoffice;
	private java.lang.String _cboxEpilepsy;
	private java.lang.String _radioPamphletissued;
	private java.util.Date _formEdited;
	private java.lang.String _otherSpecify;
	private java.lang.String _cboxCitzenshipcard;
	private java.lang.String _cboxAssistinaddictions;
	private java.lang.String _cboxAssistinfinance;
	private java.lang.String _radioActive;
	private java.lang.Long _providerNo;
	private java.lang.String _cboxEmployment;
	private java.lang.String _mentalHealthConcerns;
	private java.lang.String _radioTakemedication;
	private java.lang.String _cboxHostel;
	private java.lang.String _doctorAddress;
	private java.lang.String _doctorName;
	private java.lang.String _cboxGotohealthcenter;
	private java.lang.String _radioAppmtseedoctorin3mths;
	private java.lang.String _cboxAssistinlegal;
	private java.lang.String _everAtSeatonBefore;
	private java.lang.String _cboxSincard;
	private java.lang.String _radioHasmentalillness;
	private java.lang.String _otherIdentification;
	private java.lang.String _cboxBirthcertificate;
	private java.lang.String _cboxAssistinimmigration;
	private java.lang.String _contactAddress;
	private java.lang.String _cboxSpeakother;
	private java.lang.String _pamphletNotIssued;
	private java.lang.String _radioHashealthproblem;
	private java.lang.String _dateOfReadmission;
	private java.lang.String _radioOnlinecheck;
	private java.lang.String _allergicToMedicationName;
	private java.util.Date _formCreated;
	private java.lang.Long _demographicNo;
	private java.lang.String _cboxGotoemergencyroom;
	private java.lang.String _frequencyOfSeeingEmergencyRoomDoctor;
	private java.lang.String _cboxWsib;
	private java.lang.String _cboxRefugee;
	private java.lang.String _doctorPhoneExt;
	private java.lang.String _year;
	private java.lang.String _cboxAssistinemployment;
	private java.lang.String _otherHealthConerns;
	private java.lang.String _enterSeatonDate;
	private java.lang.String _reasonToSeaton;


	// constructors
	public BaseFormintakea () {
		initialize();
	}

	/**
	 * Constructor for primary key
	 */
	public BaseFormintakea (java.lang.Long _id) {
		this.setId(_id);
		initialize();
	}

	/**
	 * Constructor for required fields
	 */
	public BaseFormintakea (
		java.lang.Long _id,
		java.lang.Long _demographicNo) {

		this.setId(_id);
		this.setDemographicNo(_demographicNo);
		initialize();
	}

	protected void initialize () {}



	/**
	 * Return the unique identifier of this class
     * @hibernate.id
     *  generator-class="native"
     *  column="ID"
     */
	public java.lang.Long getId () {
		return _id;
	}

	/**
	 * Set the unique identifier of this class
	 * @param _id the new ID
	 */
	public void setId (java.lang.Long _id) {
		this._id = _id;
		this.hashCode = Integer.MIN_VALUE;
	}


	/**
	 * Return the value associated with the column: radio_sex
	 */
	public java.lang.String getRadioSex () {
		return _radioSex;
	}

	/**
	 * Set the value related to the column: radio_sex
	 * @param _radioSex the radio_sex value
	 */
	public void setRadioSex (java.lang.String _radioSex) {
		this._radioSex = _radioSex;
	}


	/**
	 * Return the value associated with the column: effDate
	 */
	public java.lang.String getEffDate () {
		return _effDate;
	}

	/**
	 * Set the value related to the column: effDate
	 * @param _effDate the effDate value
	 */
	public void setEffDate (java.lang.String _effDate) {
		this._effDate = _effDate;
	}


	/**
	 * Return the value associated with the column: cbox_sharing
	 */
	public java.lang.String getCboxSharing () {
		return _cboxSharing;
	}

	/**
	 * Set the value related to the column: cbox_sharing
	 * @param _cboxSharing the cbox_sharing value
	 */
	public void setCboxSharing (java.lang.String _cboxSharing) {
		this._cboxSharing = _cboxSharing;
	}


	/**
	 * Return the value associated with the column: namesOfMedication
	 */
	public java.lang.String getNamesOfMedication () {
		return _namesOfMedication;
	}

	/**
	 * Set the value related to the column: namesOfMedication
	 * @param _namesOfMedication the namesOfMedication value
	 */
	public void setNamesOfMedication (java.lang.String _namesOfMedication) {
		this._namesOfMedication = _namesOfMedication;
	}


	/**
	 * Return the value associated with the column: radio_hasDoctor
	 */
	public java.lang.String getRadioHasdoctor () {
		return _radioHasdoctor;
	}

	/**
	 * Set the value related to the column: radio_hasDoctor
	 * @param _radioHasdoctor the radio_hasDoctor value
	 */
	public void setRadioHasdoctor (java.lang.String _radioHasdoctor) {
		this._radioHasdoctor = _radioHasdoctor;
	}


	/**
	 * Return the value associated with the column: healthIssueDetails
	 */
	public java.lang.String getHealthIssueDetails () {
		return _healthIssueDetails;
	}

	/**
	 * Set the value related to the column: healthIssueDetails
	 * @param _healthIssueDetails the healthIssueDetails value
	 */
	public void setHealthIssueDetails (java.lang.String _healthIssueDetails) {
		this._healthIssueDetails = _healthIssueDetails;
	}


	/**
	 * Return the value associated with the column: cbox_ODSP
	 */
	public java.lang.String getCboxOdsp () {
		return _cboxOdsp;
	}

	/**
	 * Set the value related to the column: cbox_ODSP
	 * @param _cboxOdsp the cbox_ODSP value
	 */
	public void setCboxOdsp (java.lang.String _cboxOdsp) {
		this._cboxOdsp = _cboxOdsp;
	}


	/**
	 * Return the value associated with the column: cbox_fortYork
	 */
	public java.lang.String getCboxFortyork () {
		return _cboxFortyork;
	}

	/**
	 * Set the value related to the column: cbox_fortYork
	 * @param _cboxFortyork the cbox_fortYork value
	 */
	public void setCboxFortyork (java.lang.String _cboxFortyork) {
		this._cboxFortyork = _cboxFortyork;
	}


	/**
	 * Return the value associated with the column: cbox_idNone
	 */
	public java.lang.String getCboxIdnone () {
		return _cboxIdnone;
	}

	/**
	 * Set the value related to the column: cbox_idNone
	 * @param _cboxIdnone the cbox_idNone value
	 */
	public void setCboxIdnone (java.lang.String _cboxIdnone) {
		this._cboxIdnone = _cboxIdnone;
	}


	/**
	 * Return the value associated with the column: reactionToMedication
	 */
	public java.lang.String getReactionToMedication () {
		return _reactionToMedication;
	}

	/**
	 * Set the value related to the column: reactionToMedication
	 * @param _reactionToMedication the reactionToMedication value
	 */
	public void setReactionToMedication (java.lang.String _reactionToMedication) {
		this._reactionToMedication = _reactionToMedication;
	}


	/**
	 * Return the value associated with the column: seatonNotToured
	 */
	public java.lang.String getSeatonNotToured () {
		return _seatonNotToured;
	}

	/**
	 * Set the value related to the column: seatonNotToured
	 * @param _seatonNotToured the seatonNotToured value
	 */
	public void setSeatonNotToured (java.lang.String _seatonNotToured) {
		this._seatonNotToured = _seatonNotToured;
	}


	/**
	 * Return the value associated with the column: radio_otherHealthConcern
	 */
	public java.lang.String getRadioOtherhealthconcern () {
		return _radioOtherhealthconcern;
	}

	/**
	 * Set the value related to the column: radio_otherHealthConcern
	 * @param _radioOtherhealthconcern the radio_otherHealthConcern value
	 */
	public void setRadioOtherhealthconcern (java.lang.String _radioOtherhealthconcern) {
		this._radioOtherhealthconcern = _radioOtherhealthconcern;
	}


	/**
	 * Return the value associated with the column: cbox_oNeillHouse
	 */
	public java.lang.String getCboxOneillhouse () {
		return _cboxOneillhouse;
	}

	/**
	 * Set the value related to the column: cbox_oNeillHouse
	 * @param _cboxOneillhouse the cbox_oNeillHouse value
	 */
	public void setCboxOneillhouse (java.lang.String _cboxOneillhouse) {
		this._cboxOneillhouse = _cboxOneillhouse;
	}


	/**
	 * Return the value associated with the column: contactName
	 */
	public java.lang.String getContactName () {
		return _contactName;
	}

	/**
	 * Set the value related to the column: contactName
	 * @param _contactName the contactName value
	 */
	public void setContactName (java.lang.String _contactName) {
		this._contactName = _contactName;
	}


	/**
	 * Return the value associated with the column: radio_didNotReceiveHealthCare
	 */
	public java.lang.String getRadioDidnotreceivehealthcare () {
		return _radioDidnotreceivehealthcare;
	}

	/**
	 * Set the value related to the column: radio_didNotReceiveHealthCare
	 * @param _radioDidnotreceivehealthcare the radio_didNotReceiveHealthCare value
	 */
	public void setRadioDidnotreceivehealthcare (java.lang.String _radioDidnotreceivehealthcare) {
		this._radioDidnotreceivehealthcare = _radioDidnotreceivehealthcare;
	}


	/**
	 * Return the value associated with the column: cbox_treatPhysicalHealth
	 */
	public java.lang.String getCboxTreatphysicalhealth () {
		return _cboxTreatphysicalhealth;
	}

	/**
	 * Set the value related to the column: cbox_treatPhysicalHealth
	 * @param _cboxTreatphysicalhealth the cbox_treatPhysicalHealth value
	 */
	public void setCboxTreatphysicalhealth (java.lang.String _cboxTreatphysicalhealth) {
		this._cboxTreatphysicalhealth = _cboxTreatphysicalhealth;
	}


	/**
	 * Return the value associated with the column: cbox_idFiled
	 */
	public java.lang.String getCboxIdfiled () {
		return _cboxIdfiled;
	}

	/**
	 * Set the value related to the column: cbox_idFiled
	 * @param _cboxIdfiled the cbox_idFiled value
	 */
	public void setCboxIdfiled (java.lang.String _cboxIdfiled) {
		this._cboxIdfiled = _cboxIdfiled;
	}


	/**
	 * Return the value associated with the column: cbox_treatInjury
	 */
	public java.lang.String getCboxTreatinjury () {
		return _cboxTreatinjury;
	}

	/**
	 * Set the value related to the column: cbox_treatInjury
	 * @param _cboxTreatinjury the cbox_treatInjury value
	 */
	public void setCboxTreatinjury (java.lang.String _cboxTreatinjury) {
		this._cboxTreatinjury = _cboxTreatinjury;
	}


	/**
	 * Return the value associated with the column: cbox_OAS
	 */
	public java.lang.String getCboxOas () {
		return _cboxOas;
	}

	/**
	 * Set the value related to the column: cbox_OAS
	 * @param _cboxOas the cbox_OAS value
	 */
	public void setCboxOas (java.lang.String _cboxOas) {
		this._cboxOas = _cboxOas;
	}


	/**
	 * Return the value associated with the column: cbox_OtherIncome
	 */
	public java.lang.String getCboxOtherincome () {
		return _cboxOtherincome;
	}

	/**
	 * Set the value related to the column: cbox_OtherIncome
	 * @param _cboxOtherincome the cbox_OtherIncome value
	 */
	public void setCboxOtherincome (java.lang.String _cboxOtherincome) {
		this._cboxOtherincome = _cboxOtherincome;
	}


	/**
	 * Return the value associated with the column: cbox_newClient
	 */
	public java.lang.String getCboxNewclient () {
		return _cboxNewclient;
	}

	/**
	 * Set the value related to the column: cbox_newClient
	 * @param _cboxNewclient the cbox_newClient value
	 */
	public void setCboxNewclient (java.lang.String _cboxNewclient) {
		this._cboxNewclient = _cboxNewclient;
	}


	/**
	 * Return the value associated with the column: radio_seeDoctor
	 */
	public java.lang.String getRadioSeedoctor () {
		return _radioSeedoctor;
	}

	/**
	 * Set the value related to the column: radio_seeDoctor
	 * @param _radioSeedoctor the radio_seeDoctor value
	 */
	public void setRadioSeedoctor (java.lang.String _radioSeedoctor) {
		this._radioSeedoctor = _radioSeedoctor;
	}


	/**
	 * Return the value associated with the column: radio_mentalHealthConcerns
	 */
	public java.lang.String getRadioMentalhealthconcerns () {
		return _radioMentalhealthconcerns;
	}

	/**
	 * Set the value related to the column: radio_mentalHealthConcerns
	 * @param _radioMentalhealthconcerns the radio_mentalHealthConcerns value
	 */
	public void setRadioMentalhealthconcerns (java.lang.String _radioMentalhealthconcerns) {
		this._radioMentalhealthconcerns = _radioMentalhealthconcerns;
	}


	/**
	 * Return the value associated with the column: radio_objectToRegularDoctorIn4Wks
	 */
	public java.lang.String getRadioObjecttoregulardoctorin4wks () {
		return _radioObjecttoregulardoctorin4wks;
	}

	/**
	 * Set the value related to the column: radio_objectToRegularDoctorIn4Wks
	 * @param _radioObjecttoregulardoctorin4wks the radio_objectToRegularDoctorIn4Wks value
	 */
	public void setRadioObjecttoregulardoctorin4wks (java.lang.String _radioObjecttoregulardoctorin4wks) {
		this._radioObjecttoregulardoctorin4wks = _radioObjecttoregulardoctorin4wks;
	}


	/**
	 * Return the value associated with the column: helpObtainMedication
	 */
	public java.lang.String getHelpObtainMedication () {
		return _helpObtainMedication;
	}

	/**
	 * Set the value related to the column: helpObtainMedication
	 * @param _helpObtainMedication the helpObtainMedication value
	 */
	public void setHelpObtainMedication (java.lang.String _helpObtainMedication) {
		this._helpObtainMedication = _helpObtainMedication;
	}


	/**
	 * Return the value associated with the column: summary
	 */
	public java.lang.String getSummary () {
		return _summary;
	}

	/**
	 * Set the value related to the column: summary
	 * @param _summary the summary value
	 */
	public void setSummary (java.lang.String _summary) {
		this._summary = _summary;
	}


	/**
	 * Return the value associated with the column: day
	 */
	public java.lang.String getDay () {
		return _day;
	}

	/**
	 * Set the value related to the column: day
	 * @param _day the day value
	 */
	public void setDay (java.lang.String _day) {
		this._day = _day;
	}


	/**
	 * Return the value associated with the column: cbox_speakFrench
	 */
	public java.lang.String getCboxSpeakfrench () {
		return _cboxSpeakfrench;
	}

	/**
	 * Set the value related to the column: cbox_speakFrench
	 * @param _cboxSpeakfrench the cbox_speakFrench value
	 */
	public void setCboxSpeakfrench (java.lang.String _cboxSpeakfrench) {
		this._cboxSpeakfrench = _cboxSpeakfrench;
	}


	/**
	 * Return the value associated with the column: cbox_isStatement6Read
	 */
	public java.lang.String getCboxIsstatement6read () {
		return _cboxIsstatement6read;
	}

	/**
	 * Set the value related to the column: cbox_isStatement6Read
	 * @param _cboxIsstatement6read the cbox_isStatement6Read value
	 */
	public void setCboxIsstatement6read (java.lang.String _cboxIsstatement6read) {
		this._cboxIsstatement6read = _cboxIsstatement6read;
	}


	/**
	 * Return the value associated with the column: hasWhatID
	 */
	public java.lang.String getHasWhatID () {
		return _hasWhatID;
	}

	/**
	 * Set the value related to the column: hasWhatID
	 * @param _hasWhatID the hasWhatID value
	 */
	public void setHasWhatID (java.lang.String _hasWhatID) {
		this._hasWhatID = _hasWhatID;
	}


	/**
	 * Return the value associated with the column: doctorPhone
	 */
	public java.lang.String getDoctorPhone () {
		return _doctorPhone;
	}

	/**
	 * Set the value related to the column: doctorPhone
	 * @param _doctorPhone the doctorPhone value
	 */
	public void setDoctorPhone (java.lang.String _doctorPhone) {
		this._doctorPhone = _doctorPhone;
	}


	/**
	 * Return the value associated with the column: radio_hasDrinkingProblem
	 */
	public java.lang.String getRadioHasdrinkingproblem () {
		return _radioHasdrinkingproblem;
	}

	/**
	 * Set the value related to the column: radio_hasDrinkingProblem
	 * @param _radioHasdrinkingproblem the radio_hasDrinkingProblem value
	 */
	public void setRadioHasdrinkingproblem (java.lang.String _radioHasdrinkingproblem) {
		this._radioHasdrinkingproblem = _radioHasdrinkingproblem;
	}


	/**
	 * Return the value associated with the column: cbox_downsviewDells
	 */
	public java.lang.String getCboxDownsviewdells () {
		return _cboxDownsviewdells;
	}

	/**
	 * Set the value related to the column: cbox_downsviewDells
	 * @param _cboxDownsviewdells the cbox_downsviewDells value
	 */
	public void setCboxDownsviewdells (java.lang.String _cboxDownsviewdells) {
		this._cboxDownsviewdells = _cboxDownsviewdells;
	}


	/**
	 * Return the value associated with the column: cbox_longTermProgram
	 */
	public java.lang.String getCboxLongtermprogram () {
		return _cboxLongtermprogram;
	}

	/**
	 * Set the value related to the column: cbox_longTermProgram
	 * @param _cboxLongtermprogram the cbox_longTermProgram value
	 */
	public void setCboxLongtermprogram (java.lang.String _cboxLongtermprogram) {
		this._cboxLongtermprogram = _cboxLongtermprogram;
	}


	/**
	 * Return the value associated with the column: cbox_goToOthers
	 */
	public java.lang.String getCboxGotoothers () {
		return _cboxGotoothers;
	}

	/**
	 * Set the value related to the column: cbox_goToOthers
	 * @param _cboxGotoothers the cbox_goToOthers value
	 */
	public void setCboxGotoothers (java.lang.String _cboxGotoothers) {
		this._cboxGotoothers = _cboxGotoothers;
	}


	/**
	 * Return the value associated with the column: speakOther
	 */
	public java.lang.String getSpeakOther () {
		return _speakOther;
	}

	/**
	 * Set the value related to the column: speakOther
	 * @param _speakOther the speakOther value
	 */
	public void setSpeakOther (java.lang.String _speakOther) {
		this._speakOther = _speakOther;
	}


	/**
	 * Return the value associated with the column: lastIssueDate
	 */
	public java.lang.String getLastIssueDate () {
		return _lastIssueDate;
	}

	/**
	 * Set the value related to the column: lastIssueDate
	 * @param _lastIssueDate the lastIssueDate value
	 */
	public void setLastIssueDate (java.lang.String _lastIssueDate) {
		this._lastIssueDate = _lastIssueDate;
	}


	/**
	 * Return the value associated with the column: refugeeNum
	 */
	public java.lang.String getRefugeeNum () {
		return _refugeeNum;
	}

	/**
	 * Set the value related to the column: refugeeNum
	 * @param _refugeeNum the refugeeNum value
	 */
	public void setRefugeeNum (java.lang.String _refugeeNum) {
		this._refugeeNum = _refugeeNum;
	}


	/**
	 * Return the value associated with the column: radio_hasBehaviorProblem
	 */
	public java.lang.String getRadioHasbehaviorproblem () {
		return _radioHasbehaviorproblem;
	}

	/**
	 * Set the value related to the column: radio_hasBehaviorProblem
	 * @param _radioHasbehaviorproblem the radio_hasBehaviorProblem value
	 */
	public void setRadioHasbehaviorproblem (java.lang.String _radioHasbehaviorproblem) {
		this._radioHasbehaviorproblem = _radioHasbehaviorproblem;
	}


	/**
	 * Return the value associated with the column: radio_needRegularDoctor
	 */
	public java.lang.String getRadioNeedregulardoctor () {
		return _radioNeedregulardoctor;
	}

	/**
	 * Set the value related to the column: radio_needRegularDoctor
	 * @param _radioNeedregulardoctor the radio_needRegularDoctor value
	 */
	public void setRadioNeedregulardoctor (java.lang.String _radioNeedregulardoctor) {
		this._radioNeedregulardoctor = _radioNeedregulardoctor;
	}


	/**
	 * Return the value associated with the column: goToOthers
	 */
	public java.lang.String getGoToOthers () {
		return _goToOthers;
	}

	/**
	 * Set the value related to the column: goToOthers
	 * @param _goToOthers the goToOthers value
	 */
	public void setGoToOthers (java.lang.String _goToOthers) {
		this._goToOthers = _goToOthers;
	}


	/**
	 * Return the value associated with the column: radio_helpObtainMedication
	 */
	public java.lang.String getRadioHelpobtainmedication () {
		return _radioHelpobtainmedication;
	}

	/**
	 * Set the value related to the column: radio_helpObtainMedication
	 * @param _radioHelpobtainmedication the radio_helpObtainMedication value
	 */
	public void setRadioHelpobtainmedication (java.lang.String _radioHelpobtainmedication) {
		this._radioHelpobtainmedication = _radioHelpobtainmedication;
	}


	/**
	 * Return the value associated with the column: cbox_assistInHealth
	 */
	public java.lang.String getCboxAssistinhealth () {
		return _cboxAssistinhealth;
	}

	/**
	 * Set the value related to the column: cbox_assistInHealth
	 * @param _cboxAssistinhealth the cbox_assistInHealth value
	 */
	public void setCboxAssistinhealth (java.lang.String _cboxAssistinhealth) {
		this._cboxAssistinhealth = _cboxAssistinhealth;
	}


	/**
	 * Return the value associated with the column: cbox_goToWalkInClinic
	 */
	public java.lang.String getCboxGotowalkinclinic () {
		return _cboxGotowalkinclinic;
	}

	/**
	 * Set the value related to the column: cbox_goToWalkInClinic
	 * @param _cboxGotowalkinclinic the cbox_goToWalkInClinic value
	 */
	public void setCboxGotowalkinclinic (java.lang.String _cboxGotowalkinclinic) {
		this._cboxGotowalkinclinic = _cboxGotowalkinclinic;
	}


	/**
	 * Return the value associated with the column: cbox_noID
	 */
	public java.lang.String getCboxNoid () {
		return _cboxNoid;
	}

	/**
	 * Set the value related to the column: cbox_noID
	 * @param _cboxNoid the cbox_noID value
	 */
	public void setCboxNoid (java.lang.String _cboxNoid) {
		this._cboxNoid = _cboxNoid;
	}


	/**
	 * Return the value associated with the column: cbox_pamphletIssued
	 */
	public java.lang.String getCboxPamphletissued () {
		return _cboxPamphletissued;
	}

	/**
	 * Set the value related to the column: cbox_pamphletIssued
	 * @param _cboxPamphletissued the cbox_pamphletIssued value
	 */
	public void setCboxPamphletissued (java.lang.String _cboxPamphletissued) {
		this._cboxPamphletissued = _cboxPamphletissued;
	}


	/**
	 * Return the value associated with the column: cbox_isStatementRead
	 */
	public java.lang.String getCboxIsstatementread () {
		return _cboxIsstatementread;
	}

	/**
	 * Set the value related to the column: cbox_isStatementRead
	 * @param _cboxIsstatementread the cbox_isStatementRead value
	 */
	public void setCboxIsstatementread (java.lang.String _cboxIsstatementread) {
		this._cboxIsstatementread = _cboxIsstatementread;
	}


	/**
	 * Return the value associated with the column: cbox_noRecord
	 */
	public java.lang.String getCboxNorecord () {
		return _cboxNorecord;
	}

	/**
	 * Set the value related to the column: cbox_noRecord
	 * @param _cboxNorecord the cbox_noRecord value
	 */
	public void setCboxNorecord (java.lang.String _cboxNorecord) {
		this._cboxNorecord = _cboxNorecord;
	}


	/**
	 * Return the value associated with the column: cbox_OW
	 */
	public java.lang.String getCboxOw () {
		return _cboxOw;
	}

	/**
	 * Set the value related to the column: cbox_OW
	 * @param _cboxOw the cbox_OW value
	 */
	public void setCboxOw (java.lang.String _cboxOw) {
		this._cboxOw = _cboxOw;
	}


	/**
	 * Return the value associated with the column: assessCompleteTime
	 */
	public java.lang.String getAssessCompleteTime () {
		return _assessCompleteTime;
	}

	/**
	 * Set the value related to the column: assessCompleteTime
	 * @param _assessCompleteTime the assessCompleteTime value
	 */
	public void setAssessCompleteTime (java.lang.String _assessCompleteTime) {
		this._assessCompleteTime = _assessCompleteTime;
	}


	/**
	 * Return the value associated with the column: assessDate
	 */
	public java.lang.String getAssessDate () {
		return _assessDate;
	}

	/**
	 * Set the value related to the column: assessDate
	 * @param _assessDate the assessDate value
	 */
	public void setAssessDate (java.lang.String _assessDate) {
		this._assessDate = _assessDate;
	}


	/**
	 * Return the value associated with the column: cbox_hearingImpair
	 */
	public java.lang.String getCboxHearingimpair () {
		return _cboxHearingimpair;
	}

	/**
	 * Set the value related to the column: cbox_hearingImpair
	 * @param _cboxHearingimpair the cbox_hearingImpair value
	 */
	public void setCboxHearingimpair (java.lang.String _cboxHearingimpair) {
		this._cboxHearingimpair = _cboxHearingimpair;
	}


	/**
	 * Return the value associated with the column: cbox_visualImpair
	 */
	public java.lang.String getCboxVisualimpair () {
		return _cboxVisualimpair;
	}

	/**
	 * Set the value related to the column: cbox_visualImpair
	 * @param _cboxVisualimpair the cbox_visualImpair value
	 */
	public void setCboxVisualimpair (java.lang.String _cboxVisualimpair) {
		this._cboxVisualimpair = _cboxVisualimpair;
	}


	/**
	 * Return the value associated with the column: cbox_birchmountResidence
	 */
	public java.lang.String getCboxBirchmountresidence () {
		return _cboxBirchmountresidence;
	}

	/**
	 * Set the value related to the column: cbox_birchmountResidence
	 * @param _cboxBirchmountresidence the cbox_birchmountResidence value
	 */
	public void setCboxBirchmountresidence (java.lang.String _cboxBirchmountresidence) {
		this._cboxBirchmountresidence = _cboxBirchmountresidence;
	}


	/**
	 * Return the value associated with the column: cbox_EI
	 */
	public java.lang.String getCboxEi () {
		return _cboxEi;
	}

	/**
	 * Set the value related to the column: cbox_EI
	 * @param _cboxEi the cbox_EI value
	 */
	public void setCboxEi (java.lang.String _cboxEi) {
		this._cboxEi = _cboxEi;
	}


	/**
	 * Return the value associated with the column: radio_hasDrugProblem
	 */
	public java.lang.String getRadioHasdrugproblem () {
		return _radioHasdrugproblem;
	}

	/**
	 * Set the value related to the column: radio_hasDrugProblem
	 * @param _radioHasdrugproblem the radio_hasDrugProblem value
	 */
	public void setRadioHasdrugproblem (java.lang.String _radioHasdrugproblem) {
		this._radioHasdrugproblem = _radioHasdrugproblem;
	}


	/**
	 * Return the value associated with the column: cbox_visitHealthCenter
	 */
	public java.lang.String getCboxVisithealthcenter () {
		return _cboxVisithealthcenter;
	}

	/**
	 * Set the value related to the column: cbox_visitHealthCenter
	 * @param _cboxVisithealthcenter the cbox_visitHealthCenter value
	 */
	public void setCboxVisithealthcenter (java.lang.String _cboxVisithealthcenter) {
		this._cboxVisithealthcenter = _cboxVisithealthcenter;
	}


	/**
	 * Return the value associated with the column: citzenshipCardNum
	 */
	public java.lang.String getCitzenshipCardNum () {
		return _citzenshipCardNum;
	}

	/**
	 * Set the value related to the column: citzenshipCardNum
	 * @param _citzenshipCardNum the citzenshipCardNum value
	 */
	public void setCitzenshipCardNum (java.lang.String _citzenshipCardNum) {
		this._citzenshipCardNum = _citzenshipCardNum;
	}


	/**
	 * Return the value associated with the column: cbox_rotaryClub
	 */
	public java.lang.String getCboxRotaryclub () {
		return _cboxRotaryclub;
	}

	/**
	 * Set the value related to the column: cbox_rotaryClub
	 * @param _cboxRotaryclub the cbox_rotaryClub value
	 */
	public void setCboxRotaryclub (java.lang.String _cboxRotaryclub) {
		this._cboxRotaryclub = _cboxRotaryclub;
	}


	/**
	 * Return the value associated with the column: cbox_healthCard
	 */
	public java.lang.String getCboxHealthcard () {
		return _cboxHealthcard;
	}

	/**
	 * Set the value related to the column: cbox_healthCard
	 * @param _cboxHealthcard the cbox_healthCard value
	 */
	public void setCboxHealthcard (java.lang.String _cboxHealthcard) {
		this._cboxHealthcard = _cboxHealthcard;
	}


	/**
	 * Return the value associated with the column: clientSurname
	 */
	public java.lang.String getClientSurname () {
		return _clientSurname;
	}

	/**
	 * Set the value related to the column: clientSurname
	 * @param _clientSurname the clientSurname value
	 */
	public void setClientSurname (java.lang.String _clientSurname) {
		this._clientSurname = _clientSurname;
	}


	/**
	 * Return the value associated with the column: treatOtherReasons
	 */
	public java.lang.String getTreatOtherReasons () {
		return _treatOtherReasons;
	}

	/**
	 * Set the value related to the column: treatOtherReasons
	 * @param _treatOtherReasons the treatOtherReasons value
	 */
	public void setTreatOtherReasons (java.lang.String _treatOtherReasons) {
		this._treatOtherReasons = _treatOtherReasons;
	}


	/**
	 * Return the value associated with the column: mobilityImpair
	 */
	public java.lang.String getMobilityImpair () {
		return _mobilityImpair;
	}

	/**
	 * Set the value related to the column: mobilityImpair
	 * @param _mobilityImpair the mobilityImpair value
	 */
	public void setMobilityImpair (java.lang.String _mobilityImpair) {
		this._mobilityImpair = _mobilityImpair;
	}


	/**
	 * Return the value associated with the column: radio_seatonTour
	 */
	public java.lang.String getRadioSeatontour () {
		return _radioSeatontour;
	}

	/**
	 * Set the value related to the column: radio_seatonTour
	 * @param _radioSeatontour the radio_seatonTour value
	 */
	public void setRadioSeatontour (java.lang.String _radioSeatontour) {
		this._radioSeatontour = _radioSeatontour;
	}


	/**
	 * Return the value associated with the column: radio_healthIssue
	 */
	public java.lang.String getRadioHealthissue () {
		return _radioHealthissue;
	}

	/**
	 * Set the value related to the column: radio_healthIssue
	 * @param _radioHealthissue the radio_healthIssue value
	 */
	public void setRadioHealthissue (java.lang.String _radioHealthissue) {
		this._radioHealthissue = _radioHealthissue;
	}


	/**
	 * Return the value associated with the column: cbox_assistInHousing
	 */
	public java.lang.String getCboxAssistinhousing () {
		return _cboxAssistinhousing;
	}

	/**
	 * Set the value related to the column: cbox_assistInHousing
	 * @param _cboxAssistinhousing the cbox_assistInHousing value
	 */
	public void setCboxAssistinhousing (java.lang.String _cboxAssistinhousing) {
		this._cboxAssistinhousing = _cboxAssistinhousing;
	}


	/**
	 * Return the value associated with the column: amtReceived
	 */
	public java.lang.String getAmtReceived () {
		return _amtReceived;
	}

	/**
	 * Set the value related to the column: amtReceived
	 * @param _amtReceived the amtReceived value
	 */
	public void setAmtReceived (java.lang.String _amtReceived) {
		this._amtReceived = _amtReceived;
	}


	/**
	 * Return the value associated with the column: cbox_visitHealthOffice
	 */
	public java.lang.String getCboxVisithealthoffice () {
		return _cboxVisithealthoffice;
	}

	/**
	 * Set the value related to the column: cbox_visitHealthOffice
	 * @param _cboxVisithealthoffice the cbox_visitHealthOffice value
	 */
	public void setCboxVisithealthoffice (java.lang.String _cboxVisithealthoffice) {
		this._cboxVisithealthoffice = _cboxVisithealthoffice;
	}


	/**
	 * Return the value associated with the column: completedBy
	 */
	public java.lang.String getCompletedBy () {
		return _completedBy;
	}

	/**
	 * Set the value related to the column: completedBy
	 * @param _completedBy the completedBy value
	 */
	public void setCompletedBy (java.lang.String _completedBy) {
		this._completedBy = _completedBy;
	}


	/**
	 * Return the value associated with the column: contactPhone
	 */
	public java.lang.String getContactPhone () {
		return _contactPhone;
	}

	/**
	 * Set the value related to the column: contactPhone
	 * @param _contactPhone the contactPhone value
	 */
	public void setContactPhone (java.lang.String _contactPhone) {
		this._contactPhone = _contactPhone;
	}


	/**
	 * Return the value associated with the column: cbox_immigrant
	 */
	public java.lang.String getCboxImmigrant () {
		return _cboxImmigrant;
	}

	/**
	 * Set the value related to the column: cbox_immigrant
	 * @param _cboxImmigrant the cbox_immigrant value
	 */
	public void setCboxImmigrant (java.lang.String _cboxImmigrant) {
		this._cboxImmigrant = _cboxImmigrant;
	}


	/**
	 * Return the value associated with the column: healthCardVer
	 */
	public java.lang.String getHealthCardVer () {
		return _healthCardVer;
	}

	/**
	 * Set the value related to the column: healthCardVer
	 * @param _healthCardVer the healthCardVer value
	 */
	public void setHealthCardVer (java.lang.String _healthCardVer) {
		this._healthCardVer = _healthCardVer;
	}


	/**
	 * Return the value associated with the column: doctorName2
	 */
	public java.lang.String getDoctorName2 () {
		return _doctorName2;
	}

	/**
	 * Set the value related to the column: doctorName2
	 * @param _doctorName2 the doctorName2 value
	 */
	public void setDoctorName2 (java.lang.String _doctorName2) {
		this._doctorName2 = _doctorName2;
	}


	/**
	 * Return the value associated with the column: cbox_dateOfReadmission
	 */
	public java.lang.String getCboxDateofreadmission () {
		return _cboxDateofreadmission;
	}

	/**
	 * Set the value related to the column: cbox_dateOfReadmission
	 * @param _cboxDateofreadmission the cbox_dateOfReadmission value
	 */
	public void setCboxDateofreadmission (java.lang.String _cboxDateofreadmission) {
		this._cboxDateofreadmission = _cboxDateofreadmission;
	}


	/**
	 * Return the value associated with the column: cbox_treatOtherReasons
	 */
	public java.lang.String getCboxTreatotherreasons () {
		return _cboxTreatotherreasons;
	}

	/**
	 * Set the value related to the column: cbox_treatOtherReasons
	 * @param _cboxTreatotherreasons the cbox_treatOtherReasons value
	 */
	public void setCboxTreatotherreasons (java.lang.String _cboxTreatotherreasons) {
		this._cboxTreatotherreasons = _cboxTreatotherreasons;
	}


	/**
	 * Return the value associated with the column: cbox_visitOthers
	 */
	public java.lang.String getCboxVisitothers () {
		return _cboxVisitothers;
	}

	/**
	 * Set the value related to the column: cbox_visitOthers
	 * @param _cboxVisitothers the cbox_visitOthers value
	 */
	public void setCboxVisitothers (java.lang.String _cboxVisitothers) {
		this._cboxVisitothers = _cboxVisitothers;
	}


	/**
	 * Return the value associated with the column: commentsOnID
	 */
	public java.lang.String getCommentsOnID () {
		return _commentsOnID;
	}

	/**
	 * Set the value related to the column: commentsOnID
	 * @param _commentsOnID the commentsOnID value
	 */
	public void setCommentsOnID (java.lang.String _commentsOnID) {
		this._commentsOnID = _commentsOnID;
	}


	/**
	 * Return the value associated with the column: assessStartTime
	 */
	public java.lang.String getAssessStartTime () {
		return _assessStartTime;
	}

	/**
	 * Set the value related to the column: assessStartTime
	 * @param _assessStartTime the assessStartTime value
	 */
	public void setAssessStartTime (java.lang.String _assessStartTime) {
		this._assessStartTime = _assessStartTime;
	}


	/**
	 * Return the value associated with the column: immigrantNum
	 */
	public java.lang.String getImmigrantNum () {
		return _immigrantNum;
	}

	/**
	 * Set the value related to the column: immigrantNum
	 * @param _immigrantNum the immigrantNum value
	 */
	public void setImmigrantNum (java.lang.String _immigrantNum) {
		this._immigrantNum = _immigrantNum;
	}


	/**
	 * Return the value associated with the column: cbox_insulin
	 */
	public java.lang.String getCboxInsulin () {
		return _cboxInsulin;
	}

	/**
	 * Set the value related to the column: cbox_insulin
	 * @param _cboxInsulin the cbox_insulin value
	 */
	public void setCboxInsulin (java.lang.String _cboxInsulin) {
		this._cboxInsulin = _cboxInsulin;
	}


	/**
	 * Return the value associated with the column: radio_seeSameDoctor
	 */
	public java.lang.String getRadioSeesamedoctor () {
		return _radioSeesamedoctor;
	}

	/**
	 * Set the value related to the column: radio_seeSameDoctor
	 * @param _radioSeesamedoctor the radio_seeSameDoctor value
	 */
	public void setRadioSeesamedoctor (java.lang.String _radioSeesamedoctor) {
		this._radioSeesamedoctor = _radioSeesamedoctor;
	}


	/**
	 * Return the value associated with the column: radio_speakToResearcher
	 */
	public java.lang.String getRadioSpeaktoresearcher () {
		return _radioSpeaktoresearcher;
	}

	/**
	 * Set the value related to the column: radio_speakToResearcher
	 * @param _radioSpeaktoresearcher the radio_speakToResearcher value
	 */
	public void setRadioSpeaktoresearcher (java.lang.String _radioSpeaktoresearcher) {
		this._radioSpeaktoresearcher = _radioSpeaktoresearcher;
	}


	/**
	 * Return the value associated with the column: cbox_assistInIdentification
	 */
	public java.lang.String getCboxAssistinidentification () {
		return _cboxAssistinidentification;
	}

	/**
	 * Set the value related to the column: cbox_assistInIdentification
	 * @param _cboxAssistinidentification the cbox_assistInIdentification value
	 */
	public void setCboxAssistinidentification (java.lang.String _cboxAssistinidentification) {
		this._cboxAssistinidentification = _cboxAssistinidentification;
	}


	/**
	 * Return the value associated with the column: cbox_speakEnglish
	 */
	public java.lang.String getCboxSpeakenglish () {
		return _cboxSpeakenglish;
	}

	/**
	 * Set the value related to the column: cbox_speakEnglish
	 * @param _cboxSpeakenglish the cbox_speakEnglish value
	 */
	public void setCboxSpeakenglish (java.lang.String _cboxSpeakenglish) {
		this._cboxSpeakenglish = _cboxSpeakenglish;
	}


	/**
	 * Return the value associated with the column: contactRelationship
	 */
	public java.lang.String getContactRelationship () {
		return _contactRelationship;
	}

	/**
	 * Set the value related to the column: contactRelationship
	 * @param _contactRelationship the contactRelationship value
	 */
	public void setContactRelationship (java.lang.String _contactRelationship) {
		this._contactRelationship = _contactRelationship;
	}


	/**
	 * Return the value associated with the column: cbox_treatMentalHealth
	 */
	public java.lang.String getCboxTreatmentalhealth () {
		return _cboxTreatmentalhealth;
	}

	/**
	 * Set the value related to the column: cbox_treatMentalHealth
	 * @param _cboxTreatmentalhealth the cbox_treatMentalHealth value
	 */
	public void setCboxTreatmentalhealth (java.lang.String _cboxTreatmentalhealth) {
		this._cboxTreatmentalhealth = _cboxTreatmentalhealth;
	}


	/**
	 * Return the value associated with the column: datesAtSeaton
	 */
	public java.lang.String getDatesAtSeaton () {
		return _datesAtSeaton;
	}

	/**
	 * Set the value related to the column: datesAtSeaton
	 * @param _datesAtSeaton the datesAtSeaton value
	 */
	public void setDatesAtSeaton (java.lang.String _datesAtSeaton) {
		this._datesAtSeaton = _datesAtSeaton;
	}


	/**
	 * Return the value associated with the column: sinNum
	 */
	public java.lang.String getSinNum () {
		return _sinNum;
	}

	/**
	 * Set the value related to the column: sinNum
	 * @param _sinNum the sinNum value
	 */
	public void setSinNum (java.lang.String _sinNum) {
		this._sinNum = _sinNum;
	}


	/**
	 * Return the value associated with the column: radio_rateOverallHealth
	 */
	public java.lang.String getRadioRateoverallhealth () {
		return _radioRateoverallhealth;
	}

	/**
	 * Set the value related to the column: radio_rateOverallHealth
	 * @param _radioRateoverallhealth the radio_rateOverallHealth value
	 */
	public void setRadioRateoverallhealth (java.lang.String _radioRateoverallhealth) {
		this._radioRateoverallhealth = _radioRateoverallhealth;
	}


	/**
	 * Return the value associated with the column: healthCardNum
	 */
	public java.lang.String getHealthCardNum () {
		return _healthCardNum;
	}

	/**
	 * Set the value related to the column: healthCardNum
	 * @param _healthCardNum the healthCardNum value
	 */
	public void setHealthCardNum (java.lang.String _healthCardNum) {
		this._healthCardNum = _healthCardNum;
	}


	/**
	 * Return the value associated with the column: office
	 */
	public java.lang.String getOffice () {
		return _office;
	}

	/**
	 * Set the value related to the column: office
	 * @param _office the office value
	 */
	public void setOffice (java.lang.String _office) {
		this._office = _office;
	}


	/**
	 * Return the value associated with the column: radio_needSeatonService
	 */
	public java.lang.String getRadioNeedseatonservice () {
		return _radioNeedseatonservice;
	}

	/**
	 * Set the value related to the column: radio_needSeatonService
	 * @param _radioNeedseatonservice the radio_needSeatonService value
	 */
	public void setRadioNeedseatonservice (java.lang.String _radioNeedseatonservice) {
		this._radioNeedseatonservice = _radioNeedseatonservice;
	}


	/**
	 * Return the value associated with the column: cbox_bleeding
	 */
	public java.lang.String getCboxBleeding () {
		return _cboxBleeding;
	}

	/**
	 * Set the value related to the column: cbox_bleeding
	 * @param _cboxBleeding the cbox_bleeding value
	 */
	public void setCboxBleeding (java.lang.String _cboxBleeding) {
		this._cboxBleeding = _cboxBleeding;
	}


	/**
	 * Return the value associated with the column: cbox_regularCheckup
	 */
	public java.lang.String getCboxRegularcheckup () {
		return _cboxRegularcheckup;
	}

	/**
	 * Set the value related to the column: cbox_regularCheckup
	 * @param _cboxRegularcheckup the cbox_regularCheckup value
	 */
	public void setCboxRegularcheckup (java.lang.String _cboxRegularcheckup) {
		this._cboxRegularcheckup = _cboxRegularcheckup;
	}


	/**
	 * Return the value associated with the column: workerNum
	 */
	public java.lang.String getWorkerNum () {
		return _workerNum;
	}

	/**
	 * Set the value related to the column: workerNum
	 * @param _workerNum the workerNum value
	 */
	public void setWorkerNum (java.lang.String _workerNum) {
		this._workerNum = _workerNum;
	}


	/**
	 * Return the value associated with the column: cbox_visitWalkInClinic
	 */
	public java.lang.String getCboxVisitwalkinclinic () {
		return _cboxVisitwalkinclinic;
	}

	/**
	 * Set the value related to the column: cbox_visitWalkInClinic
	 * @param _cboxVisitwalkinclinic the cbox_visitWalkInClinic value
	 */
	public void setCboxVisitwalkinclinic (java.lang.String _cboxVisitwalkinclinic) {
		this._cboxVisitwalkinclinic = _cboxVisitwalkinclinic;
	}


	/**
	 * Return the value associated with the column: cbox_hasDiabetes
	 */
	public java.lang.String getCboxHasdiabetes () {
		return _cboxHasdiabetes;
	}

	/**
	 * Set the value related to the column: cbox_hasDiabetes
	 * @param _cboxHasdiabetes the cbox_hasDiabetes value
	 */
	public void setCboxHasdiabetes (java.lang.String _cboxHasdiabetes) {
		this._cboxHasdiabetes = _cboxHasdiabetes;
	}


	/**
	 * Return the value associated with the column: birthCertificateNum
	 */
	public java.lang.String getBirthCertificateNum () {
		return _birthCertificateNum;
	}

	/**
	 * Set the value related to the column: birthCertificateNum
	 * @param _birthCertificateNum the birthCertificateNum value
	 */
	public void setBirthCertificateNum (java.lang.String _birthCertificateNum) {
		this._birthCertificateNum = _birthCertificateNum;
	}


	/**
	 * Return the value associated with the column: clientFirstName
	 */
	public java.lang.String getClientFirstName () {
		return _clientFirstName;
	}

	/**
	 * Set the value related to the column: clientFirstName
	 * @param _clientFirstName the clientFirstName value
	 */
	public void setClientFirstName (java.lang.String _clientFirstName) {
		this._clientFirstName = _clientFirstName;
	}


	/**
	 * Return the value associated with the column: month
	 */
	public java.lang.String getMonth () {
		return _month;
	}

	/**
	 * Set the value related to the column: month
	 * @param _month the month value
	 */
	public void setMonth (java.lang.String _month) {
		this._month = _month;
	}


	/**
	 * Return the value associated with the column: radio_allergicToMedication
	 */
	public java.lang.String getRadioAllergictomedication () {
		return _radioAllergictomedication;
	}

	/**
	 * Set the value related to the column: radio_allergicToMedication
	 * @param _radioAllergictomedication the radio_allergicToMedication value
	 */
	public void setRadioAllergictomedication (java.lang.String _radioAllergictomedication) {
		this._radioAllergictomedication = _radioAllergictomedication;
	}


	/**
	 * Return the value associated with the column: cbox_CPP
	 */
	public java.lang.String getCboxCpp () {
		return _cboxCpp;
	}

	/**
	 * Set the value related to the column: cbox_CPP
	 * @param _cboxCpp the cbox_CPP value
	 */
	public void setCboxCpp (java.lang.String _cboxCpp) {
		this._cboxCpp = _cboxCpp;
	}


	/**
	 * Return the value associated with the column: cbox_hostel_fusion_care
	 */
	public java.lang.String getCboxHostelFusionCare () {
		return _cboxHostelFusionCare;
	}

	/**
	 * Set the value related to the column: cbox_hostel_fusion_care
	 * @param _cboxHostelFusionCare the cbox_hostel_fusion_care value
	 */
	public void setCboxHostelFusionCare (java.lang.String _cboxHostelFusionCare) {
		this._cboxHostelFusionCare = _cboxHostelFusionCare;
	}


	/**
	 * Return the value associated with the column: frequencyOfSeeingDoctor
	 */
	public java.lang.String getFrequencyOfSeeingDoctor () {
		return _frequencyOfSeeingDoctor;
	}

	/**
	 * Set the value related to the column: frequencyOfSeeingDoctor
	 * @param _frequencyOfSeeingDoctor the frequencyOfSeeingDoctor value
	 */
	public void setFrequencyOfSeeingDoctor (java.lang.String _frequencyOfSeeingDoctor) {
		this._frequencyOfSeeingDoctor = _frequencyOfSeeingDoctor;
	}


	/**
	 * Return the value associated with the column: cbox_otherID
	 */
	public java.lang.String getCboxOtherid () {
		return _cboxOtherid;
	}

	/**
	 * Set the value related to the column: cbox_otherID
	 * @param _cboxOtherid the cbox_otherID value
	 */
	public void setCboxOtherid (java.lang.String _cboxOtherid) {
		this._cboxOtherid = _cboxOtherid;
	}


	/**
	 * Return the value associated with the column: cbox_assistInEducation
	 */
	public java.lang.String getCboxAssistineducation () {
		return _cboxAssistineducation;
	}

	/**
	 * Set the value related to the column: cbox_assistInEducation
	 * @param _cboxAssistineducation the cbox_assistInEducation value
	 */
	public void setCboxAssistineducation (java.lang.String _cboxAssistineducation) {
		this._cboxAssistineducation = _cboxAssistineducation;
	}


	/**
	 * Return the value associated with the column: cbox_annexHarm
	 */
	public java.lang.String getCboxAnnexharm () {
		return _cboxAnnexharm;
	}

	/**
	 * Set the value related to the column: cbox_annexHarm
	 * @param _cboxAnnexharm the cbox_annexHarm value
	 */
	public void setCboxAnnexharm (java.lang.String _cboxAnnexharm) {
		this._cboxAnnexharm = _cboxAnnexharm;
	}


	/**
	 * Return the value associated with the column: cbox_visitEmergencyRoom
	 */
	public java.lang.String getCboxVisitemergencyroom () {
		return _cboxVisitemergencyroom;
	}

	/**
	 * Set the value related to the column: cbox_visitEmergencyRoom
	 * @param _cboxVisitemergencyroom the cbox_visitEmergencyRoom value
	 */
	public void setCboxVisitemergencyroom (java.lang.String _cboxVisitemergencyroom) {
		this._cboxVisitemergencyroom = _cboxVisitemergencyroom;
	}


	/**
	 * Return the value associated with the column: cbox_mobilityImpair
	 */
	public java.lang.String getCboxMobilityimpair () {
		return _cboxMobilityimpair;
	}

	/**
	 * Set the value related to the column: cbox_mobilityImpair
	 * @param _cboxMobilityimpair the cbox_mobilityImpair value
	 */
	public void setCboxMobilityimpair (java.lang.String _cboxMobilityimpair) {
		this._cboxMobilityimpair = _cboxMobilityimpair;
	}


	/**
	 * Return the value associated with the column: cbox_HealthOffice
	 */
	public java.lang.String getCboxHealthoffice () {
		return _cboxHealthoffice;
	}

	/**
	 * Set the value related to the column: cbox_HealthOffice
	 * @param _cboxHealthoffice the cbox_HealthOffice value
	 */
	public void setCboxHealthoffice (java.lang.String _cboxHealthoffice) {
		this._cboxHealthoffice = _cboxHealthoffice;
	}


	/**
	 * Return the value associated with the column: cbox_epilepsy
	 */
	public java.lang.String getCboxEpilepsy () {
		return _cboxEpilepsy;
	}

	/**
	 * Set the value related to the column: cbox_epilepsy
	 * @param _cboxEpilepsy the cbox_epilepsy value
	 */
	public void setCboxEpilepsy (java.lang.String _cboxEpilepsy) {
		this._cboxEpilepsy = _cboxEpilepsy;
	}


	/**
	 * Return the value associated with the column: radio_pamphletIssued
	 */
	public java.lang.String getRadioPamphletissued () {
		return _radioPamphletissued;
	}

	/**
	 * Set the value related to the column: radio_pamphletIssued
	 * @param _radioPamphletissued the radio_pamphletIssued value
	 */
	public void setRadioPamphletissued (java.lang.String _radioPamphletissued) {
		this._radioPamphletissued = _radioPamphletissued;
	}


	/**
	 * Return the value associated with the column: formEdited
	 */
	public java.util.Date getFormEdited () {
		return _formEdited;
	}

	/**
	 * Set the value related to the column: formEdited
	 * @param _formEdited the formEdited value
	 */
	public void setFormEdited (java.util.Date _formEdited) {
		this._formEdited = _formEdited;
	}


	/**
	 * Return the value associated with the column: otherSpecify
	 */
	public java.lang.String getOtherSpecify () {
		return _otherSpecify;
	}

	/**
	 * Set the value related to the column: otherSpecify
	 * @param _otherSpecify the otherSpecify value
	 */
	public void setOtherSpecify (java.lang.String _otherSpecify) {
		this._otherSpecify = _otherSpecify;
	}


	/**
	 * Return the value associated with the column: cbox_citzenshipCard
	 */
	public java.lang.String getCboxCitzenshipcard () {
		return _cboxCitzenshipcard;
	}

	/**
	 * Set the value related to the column: cbox_citzenshipCard
	 * @param _cboxCitzenshipcard the cbox_citzenshipCard value
	 */
	public void setCboxCitzenshipcard (java.lang.String _cboxCitzenshipcard) {
		this._cboxCitzenshipcard = _cboxCitzenshipcard;
	}


	/**
	 * Return the value associated with the column: cbox_assistInAddictions
	 */
	public java.lang.String getCboxAssistinaddictions () {
		return _cboxAssistinaddictions;
	}

	/**
	 * Set the value related to the column: cbox_assistInAddictions
	 * @param _cboxAssistinaddictions the cbox_assistInAddictions value
	 */
	public void setCboxAssistinaddictions (java.lang.String _cboxAssistinaddictions) {
		this._cboxAssistinaddictions = _cboxAssistinaddictions;
	}


	/**
	 * Return the value associated with the column: cbox_assistInFinance
	 */
	public java.lang.String getCboxAssistinfinance () {
		return _cboxAssistinfinance;
	}

	/**
	 * Set the value related to the column: cbox_assistInFinance
	 * @param _cboxAssistinfinance the cbox_assistInFinance value
	 */
	public void setCboxAssistinfinance (java.lang.String _cboxAssistinfinance) {
		this._cboxAssistinfinance = _cboxAssistinfinance;
	}


	/**
	 * Return the value associated with the column: radio_active
	 */
	public java.lang.String getRadioActive () {
		return _radioActive;
	}

	/**
	 * Set the value related to the column: radio_active
	 * @param _radioActive the radio_active value
	 */
	public void setRadioActive (java.lang.String _radioActive) {
		this._radioActive = _radioActive;
	}


	/**
	 * Return the value associated with the column: provider_no
	 */
	public java.lang.Long getProviderNo () {
		return _providerNo;
	}

	/**
	 * Set the value related to the column: provider_no
	 * @param _providerNo the provider_no value
	 */
	public void setProviderNo (java.lang.Long _providerNo) {
		this._providerNo = _providerNo;
	}


	/**
	 * Return the value associated with the column: cbox_Employment
	 */
	public java.lang.String getCboxEmployment () {
		return _cboxEmployment;
	}

	/**
	 * Set the value related to the column: cbox_Employment
	 * @param _cboxEmployment the cbox_Employment value
	 */
	public void setCboxEmployment (java.lang.String _cboxEmployment) {
		this._cboxEmployment = _cboxEmployment;
	}


	/**
	 * Return the value associated with the column: mentalHealthConcerns
	 */
	public java.lang.String getMentalHealthConcerns () {
		return _mentalHealthConcerns;
	}

	/**
	 * Set the value related to the column: mentalHealthConcerns
	 * @param _mentalHealthConcerns the mentalHealthConcerns value
	 */
	public void setMentalHealthConcerns (java.lang.String _mentalHealthConcerns) {
		this._mentalHealthConcerns = _mentalHealthConcerns;
	}


	/**
	 * Return the value associated with the column: radio_takeMedication
	 */
	public java.lang.String getRadioTakemedication () {
		return _radioTakemedication;
	}

	/**
	 * Set the value related to the column: radio_takeMedication
	 * @param _radioTakemedication the radio_takeMedication value
	 */
	public void setRadioTakemedication (java.lang.String _radioTakemedication) {
		this._radioTakemedication = _radioTakemedication;
	}


	/**
	 * Return the value associated with the column: cbox_hostel
	 */
	public java.lang.String getCboxHostel () {
		return _cboxHostel;
	}

	/**
	 * Set the value related to the column: cbox_hostel
	 * @param _cboxHostel the cbox_hostel value
	 */
	public void setCboxHostel (java.lang.String _cboxHostel) {
		this._cboxHostel = _cboxHostel;
	}


	/**
	 * Return the value associated with the column: doctorAddress
	 */
	public java.lang.String getDoctorAddress () {
		return _doctorAddress;
	}

	/**
	 * Set the value related to the column: doctorAddress
	 * @param _doctorAddress the doctorAddress value
	 */
	public void setDoctorAddress (java.lang.String _doctorAddress) {
		this._doctorAddress = _doctorAddress;
	}


	/**
	 * Return the value associated with the column: doctorName
	 */
	public java.lang.String getDoctorName () {
		return _doctorName;
	}

	/**
	 * Set the value related to the column: doctorName
	 * @param _doctorName the doctorName value
	 */
	public void setDoctorName (java.lang.String _doctorName) {
		this._doctorName = _doctorName;
	}


	/**
	 * Return the value associated with the column: cbox_goToHealthCenter
	 */
	public java.lang.String getCboxGotohealthcenter () {
		return _cboxGotohealthcenter;
	}

	/**
	 * Set the value related to the column: cbox_goToHealthCenter
	 * @param _cboxGotohealthcenter the cbox_goToHealthCenter value
	 */
	public void setCboxGotohealthcenter (java.lang.String _cboxGotohealthcenter) {
		this._cboxGotohealthcenter = _cboxGotohealthcenter;
	}


	/**
	 * Return the value associated with the column: radio_appmtSeeDoctorIn3Mths
	 */
	public java.lang.String getRadioAppmtseedoctorin3mths () {
		return _radioAppmtseedoctorin3mths;
	}

	/**
	 * Set the value related to the column: radio_appmtSeeDoctorIn3Mths
	 * @param _radioAppmtseedoctorin3mths the radio_appmtSeeDoctorIn3Mths value
	 */
	public void setRadioAppmtseedoctorin3mths (java.lang.String _radioAppmtseedoctorin3mths) {
		this._radioAppmtseedoctorin3mths = _radioAppmtseedoctorin3mths;
	}


	/**
	 * Return the value associated with the column: cbox_assistInLegal
	 */
	public java.lang.String getCboxAssistinlegal () {
		return _cboxAssistinlegal;
	}

	/**
	 * Set the value related to the column: cbox_assistInLegal
	 * @param _cboxAssistinlegal the cbox_assistInLegal value
	 */
	public void setCboxAssistinlegal (java.lang.String _cboxAssistinlegal) {
		this._cboxAssistinlegal = _cboxAssistinlegal;
	}


	/**
	 * Return the value associated with the column: everAtSeatonBefore
	 */
	public java.lang.String getEverAtSeatonBefore () {
		return _everAtSeatonBefore;
	}

	/**
	 * Set the value related to the column: everAtSeatonBefore
	 * @param _everAtSeatonBefore the everAtSeatonBefore value
	 */
	public void setEverAtSeatonBefore (java.lang.String _everAtSeatonBefore) {
		this._everAtSeatonBefore = _everAtSeatonBefore;
	}


	/**
	 * Return the value associated with the column: cbox_sinCard
	 */
	public java.lang.String getCboxSincard () {
		return _cboxSincard;
	}

	/**
	 * Set the value related to the column: cbox_sinCard
	 * @param _cboxSincard the cbox_sinCard value
	 */
	public void setCboxSincard (java.lang.String _cboxSincard) {
		this._cboxSincard = _cboxSincard;
	}


	/**
	 * Return the value associated with the column: radio_hasMentalIllness
	 */
	public java.lang.String getRadioHasmentalillness () {
		return _radioHasmentalillness;
	}

	/**
	 * Set the value related to the column: radio_hasMentalIllness
	 * @param _radioHasmentalillness the radio_hasMentalIllness value
	 */
	public void setRadioHasmentalillness (java.lang.String _radioHasmentalillness) {
		this._radioHasmentalillness = _radioHasmentalillness;
	}


	/**
	 * Return the value associated with the column: otherIdentification
	 */
	public java.lang.String getOtherIdentification () {
		return _otherIdentification;
	}

	/**
	 * Set the value related to the column: otherIdentification
	 * @param _otherIdentification the otherIdentification value
	 */
	public void setOtherIdentification (java.lang.String _otherIdentification) {
		this._otherIdentification = _otherIdentification;
	}


	/**
	 * Return the value associated with the column: cbox_birthCertificate
	 */
	public java.lang.String getCboxBirthcertificate () {
		return _cboxBirthcertificate;
	}

	/**
	 * Set the value related to the column: cbox_birthCertificate
	 * @param _cboxBirthcertificate the cbox_birthCertificate value
	 */
	public void setCboxBirthcertificate (java.lang.String _cboxBirthcertificate) {
		this._cboxBirthcertificate = _cboxBirthcertificate;
	}


	/**
	 * Return the value associated with the column: cbox_assistInImmigration
	 */
	public java.lang.String getCboxAssistinimmigration () {
		return _cboxAssistinimmigration;
	}

	/**
	 * Set the value related to the column: cbox_assistInImmigration
	 * @param _cboxAssistinimmigration the cbox_assistInImmigration value
	 */
	public void setCboxAssistinimmigration (java.lang.String _cboxAssistinimmigration) {
		this._cboxAssistinimmigration = _cboxAssistinimmigration;
	}


	/**
	 * Return the value associated with the column: contactAddress
	 */
	public java.lang.String getContactAddress () {
		return _contactAddress;
	}

	/**
	 * Set the value related to the column: contactAddress
	 * @param _contactAddress the contactAddress value
	 */
	public void setContactAddress (java.lang.String _contactAddress) {
		this._contactAddress = _contactAddress;
	}


	/**
	 * Return the value associated with the column: cbox_speakOther
	 */
	public java.lang.String getCboxSpeakother () {
		return _cboxSpeakother;
	}

	/**
	 * Set the value related to the column: cbox_speakOther
	 * @param _cboxSpeakother the cbox_speakOther value
	 */
	public void setCboxSpeakother (java.lang.String _cboxSpeakother) {
		this._cboxSpeakother = _cboxSpeakother;
	}


	/**
	 * Return the value associated with the column: pamphletNotIssued
	 */
	public java.lang.String getPamphletNotIssued () {
		return _pamphletNotIssued;
	}

	/**
	 * Set the value related to the column: pamphletNotIssued
	 * @param _pamphletNotIssued the pamphletNotIssued value
	 */
	public void setPamphletNotIssued (java.lang.String _pamphletNotIssued) {
		this._pamphletNotIssued = _pamphletNotIssued;
	}


	/**
	 * Return the value associated with the column: radio_hasHealthProblem
	 */
	public java.lang.String getRadioHashealthproblem () {
		return _radioHashealthproblem;
	}

	/**
	 * Set the value related to the column: radio_hasHealthProblem
	 * @param _radioHashealthproblem the radio_hasHealthProblem value
	 */
	public void setRadioHashealthproblem (java.lang.String _radioHashealthproblem) {
		this._radioHashealthproblem = _radioHashealthproblem;
	}


	/**
	 * Return the value associated with the column: dateOfReadmission
	 */
	public java.lang.String getDateOfReadmission () {
		return _dateOfReadmission;
	}

	/**
	 * Set the value related to the column: dateOfReadmission
	 * @param _dateOfReadmission the dateOfReadmission value
	 */
	public void setDateOfReadmission (java.lang.String _dateOfReadmission) {
		this._dateOfReadmission = _dateOfReadmission;
	}


	/**
	 * Return the value associated with the column: radio_onlineCheck
	 */
	public java.lang.String getRadioOnlinecheck () {
		return _radioOnlinecheck;
	}

	/**
	 * Set the value related to the column: radio_onlineCheck
	 * @param _radioOnlinecheck the radio_onlineCheck value
	 */
	public void setRadioOnlinecheck (java.lang.String _radioOnlinecheck) {
		this._radioOnlinecheck = _radioOnlinecheck;
	}


	/**
	 * Return the value associated with the column: allergicToMedicationName
	 */
	public java.lang.String getAllergicToMedicationName () {
		return _allergicToMedicationName;
	}

	/**
	 * Set the value related to the column: allergicToMedicationName
	 * @param _allergicToMedicationName the allergicToMedicationName value
	 */
	public void setAllergicToMedicationName (java.lang.String _allergicToMedicationName) {
		this._allergicToMedicationName = _allergicToMedicationName;
	}


	/**
	 * Return the value associated with the column: formCreated
	 */
	public java.util.Date getFormCreated () {
		return _formCreated;
	}

	/**
	 * Set the value related to the column: formCreated
	 * @param _formCreated the formCreated value
	 */
	public void setFormCreated (java.util.Date _formCreated) {
		this._formCreated = _formCreated;
	}


	/**
	 * Return the value associated with the column: demographic_no
	 */
	public java.lang.Long getDemographicNo () {
		return _demographicNo;
	}

	/**
	 * Set the value related to the column: demographic_no
	 * @param _demographicNo the demographic_no value
	 */
	public void setDemographicNo (java.lang.Long _demographicNo) {
		this._demographicNo = _demographicNo;
	}


	/**
	 * Return the value associated with the column: cbox_goToEmergencyRoom
	 */
	public java.lang.String getCboxGotoemergencyroom () {
		return _cboxGotoemergencyroom;
	}

	/**
	 * Set the value related to the column: cbox_goToEmergencyRoom
	 * @param _cboxGotoemergencyroom the cbox_goToEmergencyRoom value
	 */
	public void setCboxGotoemergencyroom (java.lang.String _cboxGotoemergencyroom) {
		this._cboxGotoemergencyroom = _cboxGotoemergencyroom;
	}


	/**
	 * Return the value associated with the column: frequencyOfSeeingEmergencyRoomDoctor
	 */
	public java.lang.String getFrequencyOfSeeingEmergencyRoomDoctor () {
		return _frequencyOfSeeingEmergencyRoomDoctor;
	}

	/**
	 * Set the value related to the column: frequencyOfSeeingEmergencyRoomDoctor
	 * @param _frequencyOfSeeingEmergencyRoomDoctor the frequencyOfSeeingEmergencyRoomDoctor value
	 */
	public void setFrequencyOfSeeingEmergencyRoomDoctor (java.lang.String _frequencyOfSeeingEmergencyRoomDoctor) {
		this._frequencyOfSeeingEmergencyRoomDoctor = _frequencyOfSeeingEmergencyRoomDoctor;
	}


	/**
	 * Return the value associated with the column: cbox_WSIB
	 */
	public java.lang.String getCboxWsib () {
		return _cboxWsib;
	}

	/**
	 * Set the value related to the column: cbox_WSIB
	 * @param _cboxWsib the cbox_WSIB value
	 */
	public void setCboxWsib (java.lang.String _cboxWsib) {
		this._cboxWsib = _cboxWsib;
	}


	/**
	 * Return the value associated with the column: cbox_refugee
	 */
	public java.lang.String getCboxRefugee () {
		return _cboxRefugee;
	}

	/**
	 * Set the value related to the column: cbox_refugee
	 * @param _cboxRefugee the cbox_refugee value
	 */
	public void setCboxRefugee (java.lang.String _cboxRefugee) {
		this._cboxRefugee = _cboxRefugee;
	}


	/**
	 * Return the value associated with the column: doctorPhoneExt
	 */
	public java.lang.String getDoctorPhoneExt () {
		return _doctorPhoneExt;
	}

	/**
	 * Set the value related to the column: doctorPhoneExt
	 * @param _doctorPhoneExt the doctorPhoneExt value
	 */
	public void setDoctorPhoneExt (java.lang.String _doctorPhoneExt) {
		this._doctorPhoneExt = _doctorPhoneExt;
	}


	/**
	 * Return the value associated with the column: year
	 */
	public java.lang.String getYear () {
		return _year;
	}

	/**
	 * Set the value related to the column: year
	 * @param _year the year value
	 */
	public void setYear (java.lang.String _year) {
		this._year = _year;
	}


	/**
	 * Return the value associated with the column: cbox_assistInEmployment
	 */
	public java.lang.String getCboxAssistinemployment () {
		return _cboxAssistinemployment;
	}

	/**
	 * Set the value related to the column: cbox_assistInEmployment
	 * @param _cboxAssistinemployment the cbox_assistInEmployment value
	 */
	public void setCboxAssistinemployment (java.lang.String _cboxAssistinemployment) {
		this._cboxAssistinemployment = _cboxAssistinemployment;
	}


	/**
	 * Return the value associated with the column: otherHealthConerns
	 */
	public java.lang.String getOtherHealthConerns () {
		return _otherHealthConerns;
	}

	/**
	 * Set the value related to the column: otherHealthConerns
	 * @param _otherHealthConerns the otherHealthConerns value
	 */
	public void setOtherHealthConerns (java.lang.String _otherHealthConerns) {
		this._otherHealthConerns = _otherHealthConerns;
	}


	/**
	 * Return the value associated with the column: enterSeatonDate
	 */
	public java.lang.String getEnterSeatonDate () {
		return _enterSeatonDate;
	}

	/**
	 * Set the value related to the column: enterSeatonDate
	 * @param _enterSeatonDate the enterSeatonDate value
	 */
	public void setEnterSeatonDate (java.lang.String _enterSeatonDate) {
		this._enterSeatonDate = _enterSeatonDate;
	}


	/**
	 * Return the value associated with the column: reasonToSeaton
	 */
	public java.lang.String getReasonToSeaton () {
		return _reasonToSeaton;
	}

	/**
	 * Set the value related to the column: reasonToSeaton
	 * @param _reasonToSeaton the reasonToSeaton value
	 */
	public void setReasonToSeaton (java.lang.String _reasonToSeaton) {
		this._reasonToSeaton = _reasonToSeaton;
	}


	public boolean equals (Object obj) {
		if (null == obj) return false;
		if (!(obj instanceof org.oscarehr.PMmodule.model.base.BaseFormintakea)) return false;
		else {
			org.oscarehr.PMmodule.model.base.BaseFormintakea mObj = (org.oscarehr.PMmodule.model.base.BaseFormintakea) obj;
			if (null == this.getId() || null == mObj.getId()) return false;
			else return (this.getId().equals(mObj.getId()));
		}
	}


	public int hashCode () {
		if (Integer.MIN_VALUE == this.hashCode) {
			if (null == this.getId()) return super.hashCode();
			else {
				String hashStr = this.getClass().getName() + ":" + this.getId().hashCode();
				this.hashCode = hashStr.hashCode();
			}
		}
		return this.hashCode;
	}


	public String toString () {
		return super.toString();
	}

}