package org.oscarehr.PMmodule.model.base;

import java.io.Serializable;


/**
 * This class has been automatically generated by Hibernate Synchronizer.
 * For more information or documentation, visit The Hibernate Synchronizer page
 * at http://www.binamics.com/hibernatesync or contact Joe Hudson at joe@binamics.com.
 *
 * This is an object that contains data related to the consent table.
 * Do not modify this class because it will be overwritten if the configuration file
 * related to this class is modified.
 *
 * @hibernate.class
 *  table="consent"
 */
public abstract class BaseConsent  implements Serializable {

	public static String PROP_STATUS = "status";
	public static String PROP_ANSWER1 = "answer1";
	public static String PROP_DATE_SIGNED = "dateSigned";
	public static String PROP_FORM_VERSION = "formVersion";
	public static String PROP_SIGNATURE_DECLARATION = "signatureDeclaration";
	public static String PROP_PROVIDER_NAME = "ProviderName";
	public static String PROP_REFUSED_TO_SIGN = "refusedToSign";
	public static String PROP_ANSWER2 = "answer2";
	public static String PROP_EXCLUSION_STRING = "exclusionString";
	public static String PROP_PROVIDER_NO = "ProviderNo";
	public static String PROP_FORM_NAME = "formName";
	public static String PROP_ANSWER3 = "answer3";
	public static String PROP_DEMOGRAPHIC_NO = "demographicNo";
	public static String PROP_ID = "Id";
	public static String PROP_LOCATION = "location";
	public static String PROP_HARDCOPY = "hardcopy";


	private int hashCode = Integer.MIN_VALUE;

	// primary key
	private java.lang.Long _id;

	// fields
	private java.lang.Long _demographicNo;
	private java.lang.String _providerNo;
	private java.lang.String _providerName;
	private java.util.Date _dateSigned;
	private java.lang.Integer _answer1;
	private java.lang.Integer _answer2;
	private java.lang.Integer _answer3;
	private java.lang.String _status;
	private boolean _hardcopy;
	private java.lang.String _location;
	private java.lang.String _formName;
	private java.lang.String _formVersion;
	private boolean _signatureDeclaration;
	private java.lang.String _exclusionString;
	private boolean _refusedToSign;


	// constructors
	public BaseConsent () {
		initialize();
	}

	/**
	 * Constructor for primary key
	 */
	public BaseConsent (java.lang.Long _id) {
		this.setId(_id);
		initialize();
	}

	/**
	 * Constructor for required fields
	 */
	public BaseConsent (
		java.lang.Long _id,
		java.lang.Long _demographicNo,
		java.lang.String _providerNo) {

		this.setId(_id);
		this.setDemographicNo(_demographicNo);
		this.setProviderNo(_providerNo);
		initialize();
	}

	protected void initialize () {}



	/**
	 * Return the unique identifier of this class
     * @hibernate.id
     *  generator-class="native"
     *  column="id"
     */
	public java.lang.Long getId () {
		return _id;
	}

	/**
	 * Set the unique identifier of this class
	 * @param _id the new ID
	 */
	public void setId (java.lang.Long _id) {
		this._id = _id;
		this.hashCode = Integer.MIN_VALUE;
	}


	/**
	 * Return the value associated with the column: demographic_no
	 */
	public java.lang.Long getDemographicNo () {
		return _demographicNo;
	}

	/**
	 * Set the value related to the column: demographic_no
	 * @param _demographicNo the demographic_no value
	 */
	public void setDemographicNo (java.lang.Long _demographicNo) {
		this._demographicNo = _demographicNo;
	}


	/**
	 * Return the value associated with the column: provider_no
	 */
	public java.lang.String getProviderNo () {
		return _providerNo;
	}

	/**
	 * Set the value related to the column: provider_no
	 * @param _providerNo the provider_no value
	 */
	public void setProviderNo (java.lang.String _providerNo) {
		this._providerNo = _providerNo;
	}


	/**
	 * Return the value associated with the column: provider_name
	 */
	public java.lang.String getProviderName () {
		return _providerName;
	}

	/**
	 * Set the value related to the column: provider_name
	 * @param _providerName the provider_name value
	 */
	public void setProviderName (java.lang.String _providerName) {
		this._providerName = _providerName;
	}


	/**
	 * Return the value associated with the column: date_signed
	 */
	public java.util.Date getDateSigned () {
		return _dateSigned;
	}

	/**
	 * Set the value related to the column: date_signed
	 * @param _dateSigned the date_signed value
	 */
	public void setDateSigned (java.util.Date _dateSigned) {
		this._dateSigned = _dateSigned;
	}


	/**
	 * Return the value associated with the column: answer_1
	 */
	public java.lang.Integer getAnswer1 () {
		return _answer1;
	}

	/**
	 * Set the value related to the column: answer_1
	 * @param _answer1 the answer_1 value
	 */
	public void setAnswer1 (java.lang.Integer _answer1) {
		this._answer1 = _answer1;
	}


	/**
	 * Return the value associated with the column: answer_2
	 */
	public java.lang.Integer getAnswer2 () {
		return _answer2;
	}

	/**
	 * Set the value related to the column: answer_2
	 * @param _answer2 the answer_2 value
	 */
	public void setAnswer2 (java.lang.Integer _answer2) {
		this._answer2 = _answer2;
	}


	/**
	 * Return the value associated with the column: answer_3
	 */
	public java.lang.Integer getAnswer3 () {
		return _answer3;
	}

	/**
	 * Set the value related to the column: answer_3
	 * @param _answer3 the answer_3 value
	 */
	public void setAnswer3 (java.lang.Integer _answer3) {
		this._answer3 = _answer3;
	}


	/**
	 * Return the value associated with the column: status
	 */
	public java.lang.String getStatus () {
		return _status;
	}

	/**
	 * Set the value related to the column: status
	 * @param _status the status value
	 */
	public void setStatus (java.lang.String _status) {
		this._status = _status;
	}


	/**
	 * Return the value associated with the column: hardcopy
	 */
	public boolean isHardcopy () {
		return _hardcopy;
	}

	/**
	 * Set the value related to the column: hardcopy
	 * @param _hardcopy the hardcopy value
	 */
	public void setHardcopy (boolean _hardcopy) {
		this._hardcopy = _hardcopy;
	}


	/**
	 * Return the value associated with the column: location
	 */
	public java.lang.String getLocation () {
		return _location;
	}

	/**
	 * Set the value related to the column: location
	 * @param _location the location value
	 */
	public void setLocation (java.lang.String _location) {
		this._location = _location;
	}


	/**
	 * Return the value associated with the column: form_name
	 */
	public java.lang.String getFormName () {
		return _formName;
	}

	/**
	 * Set the value related to the column: form_name
	 * @param _formName the form_name value
	 */
	public void setFormName (java.lang.String _formName) {
		this._formName = _formName;
	}


	/**
	 * Return the value associated with the column: form_version
	 */
	public java.lang.String getFormVersion () {
		return _formVersion;
	}

	/**
	 * Set the value related to the column: form_version
	 * @param _formVersion the form_version value
	 */
	public void setFormVersion (java.lang.String _formVersion) {
		this._formVersion = _formVersion;
	}


	/**
	 * Return the value associated with the column: signature_declaration
	 */
	public boolean isSignatureDeclaration () {
		return _signatureDeclaration;
	}

	/**
	 * Set the value related to the column: signature_declaration
	 * @param _signatureDeclaration the signature_declaration value
	 */
	public void setSignatureDeclaration (boolean _signatureDeclaration) {
		this._signatureDeclaration = _signatureDeclaration;
	}


	/**
	 * Return the value associated with the column: exclusions
	 */
	public java.lang.String getExclusionString () {
		return _exclusionString;
	}

	/**
	 * Set the value related to the column: exclusions
	 * @param _exclusionString the exclusions value
	 */
	public void setExclusionString (java.lang.String _exclusionString) {
		this._exclusionString = _exclusionString;
	}


	/**
	 * Return the value associated with the column: refused
	 */
	public boolean isRefusedToSign () {
		return _refusedToSign;
	}

	/**
	 * Set the value related to the column: refused
	 * @param _refusedToSign the refused value
	 */
	public void setRefusedToSign (boolean _refusedToSign) {
		this._refusedToSign = _refusedToSign;
	}


	public boolean equals (Object obj) {
		if (null == obj) return false;
		if (!(obj instanceof org.oscarehr.PMmodule.model.base.BaseConsent)) return false;
		else {
			org.oscarehr.PMmodule.model.base.BaseConsent mObj = (org.oscarehr.PMmodule.model.base.BaseConsent) obj;
			if (null == this.getId() || null == mObj.getId()) return false;
			else return (this.getId().equals(mObj.getId()));
		}
	}


	public int hashCode () {
		if (Integer.MIN_VALUE == this.hashCode) {
			if (null == this.getId()) return super.hashCode();
			else {
				String hashStr = this.getClass().getName() + ":" + this.getId().hashCode();
				this.hashCode = hashStr.hashCode();
			}
		}
		return this.hashCode;
	}


	public String toString () {
		return super.toString();
	}

}