//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-793 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.05.24 at 10:52:14 PM EDT 
//


package oscar.ocan.domain.staff;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}CCanadian_citizen"/>
 *         &lt;element ref="{}CPermanent_resident"/>
 *         &lt;element ref="{}CTemporary_resident"/>
 *         &lt;element ref="{}CRefugee"/>
 *         &lt;element ref="{}CUnknown"/>
 *         &lt;element ref="{}CClient_declined_to_answer"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "cCanadianCitizen",
    "cPermanentResident",
    "cTemporaryResident",
    "cRefugee",
    "cUnknown",
    "cClientDeclinedToAnswer"
})
@XmlRootElement(name = "CCitizenship_Status__select_one_")
public class CCitizenshipStatusSelectOne {

    @XmlElement(name = "CCanadian_citizen", required = true)
    protected String cCanadianCitizen;
    @XmlElement(name = "CPermanent_resident", required = true)
    protected String cPermanentResident;
    @XmlElement(name = "CTemporary_resident", required = true)
    protected String cTemporaryResident;
    @XmlElement(name = "CRefugee", required = true)
    protected String cRefugee;
    @XmlElement(name = "CUnknown", required = true)
    protected String cUnknown;
    @XmlElement(name = "CClient_declined_to_answer", required = true)
    protected String cClientDeclinedToAnswer;

    /**
     * Gets the value of the cCanadianCitizen property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCCanadianCitizen() {
        return cCanadianCitizen;
    }

    /**
     * Sets the value of the cCanadianCitizen property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCCanadianCitizen(String value) {
        this.cCanadianCitizen = value;
    }

    /**
     * Gets the value of the cPermanentResident property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCPermanentResident() {
        return cPermanentResident;
    }

    /**
     * Sets the value of the cPermanentResident property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCPermanentResident(String value) {
        this.cPermanentResident = value;
    }

    /**
     * Gets the value of the cTemporaryResident property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCTemporaryResident() {
        return cTemporaryResident;
    }

    /**
     * Sets the value of the cTemporaryResident property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCTemporaryResident(String value) {
        this.cTemporaryResident = value;
    }

    /**
     * Gets the value of the cRefugee property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCRefugee() {
        return cRefugee;
    }

    /**
     * Sets the value of the cRefugee property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCRefugee(String value) {
        this.cRefugee = value;
    }

    /**
     * Gets the value of the cUnknown property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCUnknown() {
        return cUnknown;
    }

    /**
     * Sets the value of the cUnknown property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCUnknown(String value) {
        this.cUnknown = value;
    }

    /**
     * Gets the value of the cClientDeclinedToAnswer property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCClientDeclinedToAnswer() {
        return cClientDeclinedToAnswer;
    }

    /**
     * Sets the value of the cClientDeclinedToAnswer property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCClientDeclinedToAnswer(String value) {
        this.cClientDeclinedToAnswer = value;
    }

}
