package org.caisi.casemgmt.model.base;

import java.io.Serializable;


/**
 * This class has been automatically generated by Hibernate Synchronizer.
 * For more information or documentation, visit The Hibernate Synchronizer page
 * at http://www.binamics.com/hibernatesync or contact Joe Hudson at joe@binamics.com.
 *
 * This is an object that contains data related to the default_role_access table.
 * Do not modify this class because it will be overwritten if the configuration file
 * related to this class is modified.
 *
 * @hibernate.class
 *  table="default_role_access"
 */
public abstract class BaseDefaultRoleAccess  implements Serializable {

	public static String PROP_ACCESS_TYPE = "access_type";
	public static String PROP_CAISI_ROLE = "caisi_role";
	public static String PROP_ID = "id";


	private int hashCode = Integer.MIN_VALUE;

	// primary key
	private java.lang.Long _id;

	// many to one
	private org.caisi.model.Role _caisi_role;
	private org.caisi.PMmodule.model.AccessType _access_type;


	// constructors
	public BaseDefaultRoleAccess () {
		initialize();
	}

	/**
	 * Constructor for primary key
	 */
	public BaseDefaultRoleAccess (java.lang.Long _id) {
		this.setId(_id);
		initialize();
	}

	protected void initialize () {}



	/**
	 * Return the unique identifier of this class
     * @hibernate.id
     *  generator-class="native"
     *  column="id"
     */
	public java.lang.Long getId () {
		return _id;
	}

	/**
	 * Set the unique identifier of this class
	 * @param _id the new ID
	 */
	public void setId (java.lang.Long _id) {
		this._id = _id;
		this.hashCode = Integer.MIN_VALUE;
	}


	/**
     * @hibernate.property
     *  column=role_id
	 */
	public org.caisi.model.Role getCaisi_role () {
		return this._caisi_role;
	}

	/**
	 * Set the value related to the column: role_id
	 * @param _caisi_role the role_id value
	 */
	public void setCaisi_role (org.caisi.model.Role _caisi_role) {
		this._caisi_role = _caisi_role;
	}


	/**
     * @hibernate.property
     *  column=access_id
	 */
	public org.caisi.PMmodule.model.AccessType getAccess_type () {
		return this._access_type;
	}

	/**
	 * Set the value related to the column: access_id
	 * @param _access_type the access_id value
	 */
	public void setAccess_type (org.caisi.PMmodule.model.AccessType _access_type) {
		this._access_type = _access_type;
	}


	public boolean equals (Object obj) {
		if (null == obj) return false;
		if (!(obj instanceof org.caisi.casemgmt.model.base.BaseDefaultRoleAccess)) return false;
		else {
			org.caisi.casemgmt.model.base.BaseDefaultRoleAccess mObj = (org.caisi.casemgmt.model.base.BaseDefaultRoleAccess) obj;
			if (null == this.getId() || null == mObj.getId()) return false;
			else return (this.getId().equals(mObj.getId()));
		}
	}


	public int hashCode () {
		if (Integer.MIN_VALUE == this.hashCode) {
			if (null == this.getId()) return super.hashCode();
			else {
				String hashStr = this.getClass().getName() + ":" + this.getId().hashCode();
				this.hashCode = hashStr.hashCode();
			}
		}
		return this.hashCode;
	}


	public String toString () {
		return super.toString();
	}

}