create table complaint (
	id int primary key auto_increment,
	source varchar(100),
	method varchar(20),
	firstName varchar(30),
	lastName varchar(30),
	standardsRelated boolean,
	standards varchar(100),
	description text,
	satisfiedWithOutcome varchar(50),
	standardsBreached varchar(1),
	outstandingIssues text,
	status varchar(1),
	completedDate date,
	createdDate date,
	duration varchar(10),
	person1 varchar(60),
	title1 varchar(20),
	date1 date,
	person2 varchar(60),
	title2 varchar(20),
	date2 date,
	person3 varchar(60),
	title3 varchar(20),
	date3 date,
	person4 varchar(60),
	title4 varchar(20),
	date4 date,
	clientId int(10),
	programId int(10),
	lastUpdateUser varchar(6),
	lastUpdateDate date
);


create table incident (
	id int primary key auto_increment,
	createdDate date,
	providerNo varchar(6),
	incidentDate date,
	incidentTime varchar(8),
	clients text,
	staff text,
	witnesses text,
	otherInvolved varchar(100),
	nature varchar(100),
	location varchar(200),
	clientIssues varchar(100),
	description text,
	disposition varchar(100),
	restriction text,
	chargesLaid varchar(2),
	policeReportNo varchar(20),
	badgeNo varchar(20),
	investigationRcmd text,
	investigationConductedBy text,
	investigationDate date,
	followupInfo text,
	followupCompletedBy varchar(200),
	followupDate date,
	reportCompleted varchar(1),
	programId int(10)
);
