insert into encounterForm values("Discharge Summary","../form/formDischargeSummary.jsp?demographic_no=","formDischargeSummary",1);

DROP TABLE IF EXISTS `formDischargeSummary`;
CREATE TABLE `formDischargeSummary` (
  `id` bigint(11) NOT NULL auto_increment,
  `demographic_no` bigint(11) NOT NULL default '0',  
  `formCreated` date default NULL,
  `formEdited` timestamp NOT NULL default CURRENT_TIMESTAMP on update CURRENT_TIMESTAMP,
  `clientName` varchar(60) default NULL,
  `birthDate` date default NULL,
  `ohip` varchar(25) default NULL,
  `admitDate` date default NULL,
  `dischargeDate` date default NULL,
  `programName` varchar(70) default NULL,
  `allergies` text default NULL,
  `admissionNotes` text default NULL,
  `currentIssues` text default NULL,
  `briefSummary` text default NULL,
  `dischargePlan` text default NULL,
  `followUpAppointment` char(1) default NULL,
  `doctor1` varchar(30) default NULL,
  `phoneNumber1` varchar(30) default NULL,
  `date1` varchar(20) default NULL,
  `location1` varchar(100) default NULL,
  `doctor2` varchar(30) default NULL,
  `phoneNumber2` varchar(30) default NULL,
  `date2` varchar(20) default NULL,
  `location2` varchar(100) default NULL,
  `doctor3` varchar(30) default NULL,
  `phoneNumber3` varchar(30) default NULL,
  `date3` varchar(20) default NULL,
  `location3` varchar(100) default NULL,
  `prescriptionSummary` text default NULL,
  `prescriptionProvided` char(1) default NULL,  
  `coveredByODB` char(1) default NULL,  
  `ODBFormReqired` char(1) default NULL,
-- `counsellorName` varchar(30) default NULL,
--  `followUpRequired` char(1) default NULL,  
--  `followUpRequiredDetail` varchar(255) default NULL,
  `changeMedications` varchar(255) default NULL,
--  `referrals` text default NULL,
  `referralProgram1` varchar(255) default NULL,
  `referralMade1` varchar(255) default NULL,
  `referralOutcome1` varchar(255) default NULL, 
  `referralProgram2` varchar(255) default NULL,
  `referralMade2` varchar(255) default NULL,
  `referralOutcome2` varchar(255) default NULL, 
  `referralProgram3` varchar(255) default NULL,
  `referralMade3` varchar(255) default NULL,
  `referralOutcome3` varchar(255) default NULL, 
  `referralProgram4` varchar(255) default NULL,
  `referralMade4` varchar(255) default NULL,
  `referralOutcome4` varchar(255) default NULL, 
  `referralProgram5` varchar(255) default NULL,
  `referralMade5` varchar(255) default NULL,
  `referralOutcome5` varchar(255) default NULL,  
  `provider_no` bigint(11) NOT NULL default '0',
  `providerName` varchar(60) default NULL,
  `signature` varchar(60) default NULL,
  `signatureDate` varchar(20) default NULL,
  PRIMARY KEY  (`id`)  
);


