<?xml version="1.0"?>

<!--
3 month recommendations / 6 month warnings
REBG
A1C
DMED
BP
BMED
WT
DIET
EXE
SMK
VMED

Annually
LDL
TCHD
LMED
FGLC
EYEE
ACR
EGFR
FOTE
FEET
SEXF
DMME
FLUS
Once
PNEU

should colour be in drools file or some other way
-->
<rule-set name="DiabetesFlowSheet"
          xmlns="http://drools.org/rules"
          xmlns:java="http://drools.org/semantics/java">

    <rule name="BP 1">
        <parameter identifier="m">
            <class>oscar.oscarEncounter.oscarMeasurements.MeasurementInfo</class>
        </parameter>
        <java:condition>m.getLastDateRecordedInMonths("BP") &gt;= 3</java:condition>
        <java:condition>m.getLastDateRecordedInMonths("BP") &lt; 6</java:condition>
        <java:consequence>              
              System.out.println("BP 1 getting called");
              m.addRecommendation("BP","BP hasn't been recorded in the last "+m.getLastDateRecordedInMonths("BP")+" months");
        </java:consequence>
    </rule>

    <rule name="BP 2">
        <parameter identifier="m">
            <class>oscar.oscarEncounter.oscarMeasurements.MeasurementInfo</class>
        </parameter>
        <java:condition>m.getLastDateRecordedInMonths("BP") &gt;= 6</java:condition>        
        <java:consequence>              
              System.out.println("BP 2 getting called");
              m.addWarning("BP","BP hasn't been recorded in the last "+m.getLastDateRecordedInMonths("BP")+" months");
        </java:consequence>
    </rule>

    <rule name="BP 3">
        <parameter identifier="m">
            <class>oscar.oscarEncounter.oscarMeasurements.MeasurementInfo</class>
        </parameter>
        <java:condition>m.getLastDateRecordedInMonths("BP") ==  -1</java:condition>
        <java:consequence>              
              System.out.println("BP 3 getting called");
              m.addRecommendation("BP","no BP has been recorded");
        </java:consequence>
    </rule>

</rule-set>


