<?xml version="1.0"?>

<rule-set name="SocialLegalFlowsheet"
          xmlns="http://drools.org/rules"
          xmlns:java="http://drools.org/semantics/java"
          xmlns:xs="http://www.w3.org/2001/XMLSchema-instance"
          xs:schemaLocation="http://drools.org/rules rules.xsd
                             http://drools.org/semantics/java java.xsd">

    <rule name="Lwil 1">
        <parameter identifier="m">
            <class>oscar.oscarEncounter.oscarMeasurements.MeasurementInfo</class>
        </parameter>
        <java:condition>m.getLastDateRecordedInMonths("Lwil") &gt;= 12</java:condition>
        <java:consequence>
              m.addWarning("Lwil","Question not answered in "+m.getLastDateRecordedInMonths("Lwil")+" months");
        </java:consequence>
    </rule>

    <rule name="Lwil 2">
        <parameter identifier="m">
            <class>oscar.oscarEncounter.oscarMeasurements.MeasurementInfo</class>
        </parameter>
        <java:condition>m.getLastDateRecordedInMonths("Lwil") == -1</java:condition>
        <java:consequence>
              m.addWarning("Lwil","Question not answered");
        </java:consequence>
    </rule>


</rule-set>


