<?xml version="1.0"?>


<rule-set name="RhFlowSheet"
          xmlns="http://drools.org/rules"
          xmlns:java="http://drools.org/semantics/java">
<!--
States
0 NO EDD  doesn't matter the state
  No Appt made
1    - regular before 24 weeks
2    - orange after 24 weeks
3    - red after 27 weeks
  Appt Booked
4    - regular before 28 weeks
5    - red after 28 Weeks
  Injection 28
6    - red after EDD
  Requires Another Injection
7    - orange
  Missed Appt
8     - red
  Follow up Appt Booked
      - yellow
  Closed

"1","No Appt made"
"2","Appt Booked"
"3","Injection 28"
"4","Requires Another Injection"
"5","Missed Appt"
"C","Closed"


#ccccff - normal
orange - needs attention
red imediate attention
-->      
   <rule name="No EDD 0">
        <parameter identifier="w">
            <class>oscar.oscarWorkflow.WorkFlowInfo</class>
        </parameter>
        <java:condition>w.getGestationAge() == -1</java:condition>
        <java:consequence>                 
              w.setColour("red");
        </java:consequence>
    </rule>


    <rule name="No Appt 1">
        <parameter identifier="w">
            <class>oscar.oscarWorkflow.WorkFlowInfo</class>
        </parameter>
        <java:condition>w.isCurrentState("1")</java:condition>
        <java:condition>w.getGestationAge() &lt; 24</java:condition>
        <java:consequence>                 
              w.setColour("#ccccff");
        </java:consequence>
    </rule>


    <rule name="No Appt 2">
        <parameter identifier="w">
            <class>oscar.oscarWorkflow.WorkFlowInfo</class>
        </parameter>
        <java:condition>w.isCurrentState("1")</java:condition>
        <java:condition>w.getGestationAge() &gt;= 24</java:condition>
        <java:consequence>                 
              w.setColour("orange");
        </java:consequence>
    </rule>

    <rule name="No Appt 3">
        <parameter identifier="w">
            <class>oscar.oscarWorkflow.WorkFlowInfo</class>
        </parameter>
        <java:condition>w.isCurrentState("1")</java:condition>
        <java:condition>w.getGestationAge() &gt;= 27</java:condition>
        <java:consequence>                 
              w.setColour("red");
        </java:consequence>
    </rule>


    <rule name="Appt Booked 4">
        <parameter identifier="w">
            <class>oscar.oscarWorkflow.WorkFlowInfo</class>
        </parameter>
        <java:condition>w.isCurrentState("2")</java:condition>
        <java:condition>w.getGestationAge() &lt;= 28</java:condition>
        <java:consequence>      
              w.setColour("#ccccff");
        </java:consequence>
    </rule>
    
    
    <rule name="Appt Booked 5">
        <parameter identifier="w">
            <class>oscar.oscarWorkflow.WorkFlowInfo</class>
        </parameter>
        <java:condition>w.isCurrentState("2")</java:condition>
        <java:condition>w.getGestationAge() &gt; 28</java:condition>
        <java:consequence>              
              w.setColour("red");  
        </java:consequence>
    </rule>
    

    <rule name="Injection 28 6">
        <parameter identifier="w">
            <class>oscar.oscarWorkflow.WorkFlowInfo</class>
        </parameter>
        <java:condition>w.isCurrentState("3")</java:condition>
        <java:condition>w.getGestationAge() &gt; 42</java:condition>
        <java:consequence>                 
              w.setColour("red");
        </java:consequence>
    </rule>
  

    <rule name="Requires Another Injection 7">
        <parameter identifier="w">
            <class>oscar.oscarWorkflow.WorkFlowInfo</class>
        </parameter>
        <java:condition>w.isCurrentState("4")</java:condition>
        <java:consequence>            
              w.setColour("orange");
        </java:consequence>
    </rule>
  

    <rule name="Missed Appt 8">
        <parameter identifier="w">
            <class>oscar.oscarWorkflow.WorkFlowInfo</class>
        </parameter>
        <java:condition>w.isCurrentState("5")</java:condition>
        <java:consequence>             
              w.setColour("orange");
        </java:consequence>
    </rule>

    <rule name="Follow up Appt Booked 9">
        <parameter identifier="w">
            <class>oscar.oscarWorkflow.WorkFlowInfo</class>
        </parameter>
        <java:condition>w.isCurrentState("6")</java:condition>
        <java:consequence>              
              w.setColour("yellow");
        </java:consequence>
    </rule>
    

  

</rule-set>


