//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-793 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.05.21 at 12:06:38 PM EDT 
//


package oscar.ocan.domain.submission;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}serviceOrg"/>
 *         &lt;element ref="{}program"/>
 *         &lt;element ref="{}MISFunction"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "serviceOrg",
    "program",
    "misFunction"
})
@XmlRootElement(name = "organizationRecord")
public class OrganizationRecord {

    @XmlElement(required = true)
    protected ServiceOrg serviceOrg;
    @XmlElement(required = true)
    protected Program program;
    @XmlElement(name = "MISFunction", required = true)
    protected MISFunction misFunction;

    /**
     * Gets the value of the serviceOrg property.
     * 
     * @return
     *     possible object is
     *     {@link ServiceOrg }
     *     
     */
    public ServiceOrg getServiceOrg() {
        return serviceOrg;
    }

    /**
     * Sets the value of the serviceOrg property.
     * 
     * @param value
     *     allowed object is
     *     {@link ServiceOrg }
     *     
     */
    public void setServiceOrg(ServiceOrg value) {
        this.serviceOrg = value;
    }

    /**
     * Gets the value of the program property.
     * 
     * @return
     *     possible object is
     *     {@link Program }
     *     
     */
    public Program getProgram() {
        return program;
    }

    /**
     * Sets the value of the program property.
     * 
     * @param value
     *     allowed object is
     *     {@link Program }
     *     
     */
    public void setProgram(Program value) {
        this.program = value;
    }

    /**
     * Gets the value of the misFunction property.
     * 
     * @return
     *     possible object is
     *     {@link MISFunction }
     *     
     */
    public MISFunction getMISFunction() {
        return misFunction;
    }

    /**
     * Sets the value of the misFunction property.
     * 
     * @param value
     *     allowed object is
     *     {@link MISFunction }
     *     
     */
    public void setMISFunction(MISFunction value) {
        this.misFunction = value;
    }

}
