//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-793 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.05.21 at 12:06:38 PM EDT 
//


package oscar.ocan.domain.submission;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}safetyToSelfRisk" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="otherSafetyToSelfRisk" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "safetyToSelfRisk"
})
@XmlRootElement(name = "safetyToSelfRiskList")
public class SafetyToSelfRiskList {

    protected List<String> safetyToSelfRisk;
    @XmlAttribute
    protected String otherSafetyToSelfRisk;

    /**
     * Gets the value of the safetyToSelfRisk property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the safetyToSelfRisk property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSafetyToSelfRisk().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getSafetyToSelfRisk() {
        if (safetyToSelfRisk == null) {
            safetyToSelfRisk = new ArrayList<String>();
        }
        return this.safetyToSelfRisk;
    }

    /**
     * Gets the value of the otherSafetyToSelfRisk property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOtherSafetyToSelfRisk() {
        return otherSafetyToSelfRisk;
    }

    /**
     * Sets the value of the otherSafetyToSelfRisk property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOtherSafetyToSelfRisk(String value) {
        this.otherSafetyToSelfRisk = value;
    }

}
