

CREATE TABLE  formcounsellorassessment (     

ID int(10) NOT NULL auto_increment, 
demographic_no int(10) NOT NULL default '0',  
provider_no int(10) default NULL,   
formCreated date default NULL,      
formEdited timestamp(14) NOT NULL,  

dateAssessment    varchar(24) default NULL,
assessStartTime    varchar(24) default NULL,
dateEnteredSeaton    varchar(24) default NULL,
dateExitedSeaton    varchar(24) default NULL,
clientSurname    varchar(50) default NULL,
clientFirstName    varchar(50) default NULL,
month    varchar(2) default NULL,
day    varchar(2) default NULL,
year    varchar(4) default NULL,
cbox_speakEnglish    char(1) default NULL,
cbox_speakFrench    char(1) default NULL,
cbox_speakSpanish    char(1) default NULL,
cbox_speakOther    char(1) default NULL,
speakOther    varchar(50) default NULL,
howHearAboutSeaton    varchar(255) default NULL,
whereBeforeSeaton    varchar(255) default NULL,
radio_hasIDInFile    varchar(24) default NULL,
cbox_assistWithSINCard    char(1) default NULL,
cbox_assistWithImmigrant    char(1) default NULL,
cbox_assistWithHealthCard    char(1) default NULL,
cbox_assistWithRefugee    char(1) default NULL,
cbox_assistWithBirthCert    char(1) default NULL,
cbox_assistWithNone    char(1) default NULL,
cbox_assistWithCitizenCard    char(1) default NULL,
cbox_assistWithOther    char(1) default NULL,
commentsOnID    varchar(255) default NULL,
radio_haveHealthCoverage    varchar(24) default NULL,
cbox_haveOHIP    char(1) default NULL,
cbox_haveODSP    char(1) default NULL,
cbox_haveODB    char(1) default NULL,
cbox_haveOther1    char(1) default NULL,
haveOther    varchar(70) default NULL,
radio_haveMentalProblem    varchar(24) default NULL,
cbox_haveSchizophrenia    char(1) default NULL,
radio_caredForSchizophrenia    varchar(24) default NULL,
cbox_haveManic    char(1) default NULL,
radio_caredForManic    varchar(24) default NULL,
cbox_haveDepression    char(1) default NULL,
radio_caredForDepression    varchar(24) default NULL,
cbox_haveAnxiety    char(1) default NULL,
radio_caredForAnxiety    varchar(24) default NULL,
cbox_haveOther2    char(1) default NULL,
radio_caredForOther    varchar(24) default NULL,
doctor1NameAddr    varchar(255) default NULL,
doctor1Phone    varchar(24) default NULL,
dateLastDoctor1Contact    varchar(24) default NULL,
doctor2NameAddr    varchar(255) default NULL,
doctor2Phone    varchar(24) default NULL,
dateLastDoctor2Contact    varchar(24) default NULL,
radio_needAssistWithMedication    varchar(24) default NULL,
cbox_rememberToTakeMedication    char(1) default NULL,
cbox_getMoreMedication    char(1) default NULL,
cbox_storeMedication    char(1) default NULL,
cbox_needHelpInOther    char(1) default NULL,
cbox_takePrescribedMedication    char(1) default NULL,
commentsOnNeedHelp    varchar(255) default NULL,
radio_doYouDrink    varchar(24) default NULL,
drinksPerDay    varchar(3) default NULL,
drinksPerWeek    varchar(4) default NULL,
drinksPerMonth    varchar(5) default NULL,
radio_howMuchDrink    varchar(24) default NULL,
radio_drinkThese    varchar(24) default NULL,
radio_seenDoctorRegAlcohol    varchar(24) default NULL,
radio_wantHelpQuit    varchar(24) default NULL,
commentsOnAlcohol    varchar(255) default NULL,
radio_useDrugs    varchar(24) default NULL,
radio_drugUseFrequency    varchar(24) default NULL,
radio_wantHelpQuitDrug    varchar(24) default NULL,
commentsOnStreetDrugs    varchar(255) default NULL,
housingInterested    varchar(70) default NULL,
radio_wantAppmt    varchar(24) default NULL,
clientLastAddress    varchar(255) default NULL,
clientLastAddressPayRent    varchar(255) default NULL,
dateLivedThere    varchar(24) default NULL,
livedWithWhom    varchar(120) default NULL,
radio_livedInSubsidized    varchar(24) default NULL,
radio_owedRent    varchar(24) default NULL,
whereOweRent    varchar(255) default NULL,
amtOwing    varchar(16) default NULL,
commentsOnHousing    varchar(255) default NULL,
yearsOfEducation    varchar(4) default NULL,
cbox_haveHighSchool    char(1) default NULL,
cbox_haveCollege    char(1) default NULL,
cbox_haveUniversity    char(1) default NULL,
cbox_haveOther3    char(1) default NULL,
radio_interestBackToSchool    varchar(24) default NULL,
radio_requireReferralToESL    varchar(24) default NULL,
commentsOnEducation    varchar(255) default NULL,
radio_currentlyEmployed    varchar(24) default NULL,
howLongEmployed    varchar(3) default NULL,
howLongUnemployed    varchar(3) default NULL,
usualOccupation    varchar(70) default NULL,
radio_interestedInTraining    varchar(24) default NULL,
commentsOnEmployment    varchar(255) default NULL,
mainSourceOfIncome    varchar(70) default NULL,
cbox_OW    char(1) default NULL,
cbox_ODSP    char(1) default NULL,
cbox_employment    char(1) default NULL,
cbox_UI    char(1) default NULL,
cbox_OAS    char(1) default NULL,
cbox_CPP    char(1) default NULL,
cbox_other    char(1) default NULL,
howMuchYouReceive    varchar(12) default NULL,
radio_havePublicTrustee    varchar(24) default NULL,
publicTrusteeInfo    varchar(255) default NULL,
radio_entitledToOtherIncome    varchar(24) default NULL,
typeOfIncome    varchar(120) default NULL,
radio_everMadeAppforOtherIncome    varchar(24) default NULL,
everMadeAppforOtherIncome    varchar(120) default NULL,
whenMadeAppforOtherIncome    varchar(24) default NULL,
commentsOnFinance    varchar(255) default NULL,
radio_everBeenJailed    varchar(24) default NULL,
radio_needAssistInLegal    varchar(24) default NULL,
needAssistInLegal    varchar(255) default NULL,
commentsOnLegalIssues    varchar(255) default NULL,
radio_citizen    varchar(24) default NULL,
radio_yourCanadianStatus    varchar(24) default NULL,
radio_sponsorshipBreakdown    varchar(24) default NULL,
whySponsorshipBreakdown    varchar(255) default NULL,
sponsorName    varchar(50) default NULL,
needHelpWithImmigration    varchar(50) default NULL,
CommentsOnImmigration    varchar(255) default NULL,
radio_involvedOtherAgencies    varchar(24) default NULL,
agency1Name    varchar(70) default NULL,
contact1Name    varchar(50) default NULL,
contact1Phone    varchar(24) default NULL,
assistProvided1    varchar(120) default NULL,
dateLastContact1    varchar(24) default NULL,
agency2Name    varchar(70) default NULL,
contact2Name    varchar(50) default NULL,
contact2Phone    varchar(24) default NULL,
assistProvided2    varchar(120) default NULL,
dateLastContact2    varchar(24) default NULL,
agency3Name    varchar(70) default NULL,
contact3Name    varchar(50) default NULL,
contact3Phone    varchar(24) default NULL,
assistProvided3    varchar(120) default NULL,
dateLastContact3    varchar(24) default NULL,
agency4Name    varchar(70) default NULL,
contact4Name    varchar(50) default NULL,
contact4Phone    varchar(24) default NULL,
assistProvided4    varchar(120) default NULL,
dateLastContact4    varchar(24) default NULL,
radio_mentalIllness    varchar(24) default NULL,
radio_drinking    varchar(24) default NULL,
radio_drugUse    varchar(24) default NULL,
radio_healthProblem    varchar(24) default NULL,
radio_behaviorProblem    varchar(24) default NULL,
radio_need60DaysSeatonServices    varchar(24) default NULL,
completedBy1    varchar(50) default NULL,
completedBy2    varchar(50) default NULL,
assessCompleteTime    varchar(50) default NULL,
followupAppmts    varchar(120) default NULL,
cbox_pamphletIssued    char(1) default NULL,
cbox_hostel    char(1) default NULL,
cbox_rotaryClub    char(1) default NULL,
cbox_annexHarm    char(1) default NULL,
cbox_longTermProgram    char(1) default NULL,
cbox_birchmountResidence    char(1) default NULL,
cbox_oNeillHouse    char(1) default NULL,
cbox_fortYork    char(1) default NULL,
cbox_downsviewDells    char(1) default NULL,
  

PRIMARY KEY  (ID)  
) TYPE=MyISAM;



CREATE TABLE  formreceptionassessment (     

ID int(10) NOT NULL auto_increment, 
demographic_no int(10) NOT NULL default '0',  
provider_no int(10) default NULL,   
formCreated date default NULL,      
formEdited timestamp(14) NOT NULL,  

assessDate      varchar(24) default NULL,
assessStartTime      varchar(24) default NULL,
enterSeatonDate      varchar(24) default NULL,
cbox_newClient      char(1) default NULL,
cbox_dateOfReadmission      char(1) default NULL,
dateOfReadmission      varchar(24) default NULL,
clientSurname      varchar(50) default NULL,
clientFirstName      varchar(50) default NULL,
month      varchar(2) default NULL,
day      varchar(2) default NULL,
year      varchar(4) default NULL,
cbox_speakEnglish      char(1) default NULL,
cbox_speakFrench      char(1) default NULL,
cbox_speakOther      char(1) default NULL,
speakOther      varchar(36) default NULL,
reasonToSeaton      varchar(255) default NULL,
datesAtSeaton      varchar(70) default NULL,
cbox_assistInHealth      char(1) default NULL,
cbox_assistInIdentification      char(1) default NULL,
cbox_assistInAddictions      char(1) default NULL,
cbox_assistInHousing      char(1) default NULL,
cbox_assistInEducation      char(1) default NULL,
cbox_assistInEmployment      char(1) default NULL,
cbox_assistInFinance      char(1) default NULL,
cbox_assistInLegal      char(1) default NULL,
cbox_assistInImmigration      char(1) default NULL,
cbox_noID      char(1) default NULL,
cbox_sinCard      char(1) default NULL,
cbox_healthCard      char(1) default NULL,
healthCardNum      varchar(24) default NULL,
cbox_birthCertificate      char(1) default NULL,
cbox_citzenshipCard      char(1) default NULL,
cbox_immigrant      char(1) default NULL,
cbox_refugee      char(1) default NULL,
cbox_otherID      char(1) default NULL,
otherIdentification      varchar(70) default NULL,
cbox_idFiled      char(1) default NULL,
cbox_idNone      char(1) default NULL,
commentsOnID      varchar(255) default NULL,
cbox_OW      char(1) default NULL,
cbox_ODSP      char(1) default NULL,
cbox_WSIB      char(1) default NULL,
cbox_Employment      char(1) default NULL,
cbox_EI      char(1) default NULL,
cbox_OAS      char(1) default NULL,
cbox_CPP      char(1) default NULL,
cbox_OtherIncome      char(1) default NULL,
radio_onlineCheck      varchar(36) default NULL,
radio_active      varchar(36) default NULL,
cbox_noRecord      char(1) default NULL,
lastIssueDate      varchar(24) default NULL,
office      varchar(50) default NULL,
workerNum      varchar(36) default NULL,
amtReceived      varchar(9) default NULL,
radio_hasDoctor      varchar(36) default NULL,
doctorName      varchar(50) default NULL,
doctorPhone      varchar(24) default NULL,
doctorPhoneExt      varchar(8) default NULL,
doctorAddress      varchar(120) default NULL,
radio_seeDoctor      varchar(36) default NULL,
radio_healthIssue      varchar(36) default NULL,
healthIssueDetails      varchar(255) default NULL,
cbox_hasDiabetes      char(1) default NULL,
cbox_insulin      char(1) default NULL,
cbox_epilepsy      char(1) default NULL,
cbox_bleeding      char(1) default NULL,
cbox_hearingImpair      char(1) default NULL,
cbox_visualImpair      char(1) default NULL,
cbox_mobilityImpair      char(1) default NULL,
mobilityImpair      varchar(255) default NULL,
radio_otherHealthConcern      varchar(36) default NULL,
otherHealthConerns      varchar(255) default NULL,
radio_takeMedication      varchar(36) default NULL,
namesOfMedication      varchar(120) default NULL,
radio_helpObtainMedication      varchar(36) default NULL,
helpObtainMedication      varchar(255) default NULL,
radio_allergicToMedication      varchar(36) default NULL,
allergicToMedicationName      varchar(255) default NULL,
reactionToMedication      varchar(255) default NULL,
radio_mentalHealthConcerns      varchar(36) default NULL,
mentalHealthConcerns      varchar(255) default NULL,
frequencyOfSeeingDoctor      varchar(8) default NULL,
cbox_visitWalkInClinic      char(1) default NULL,
cbox_visitHealthCenter      char(1) default NULL,
cbox_visitEmergencyRoom      char(1) default NULL,
cbox_visitOthers      char(1) default NULL,
cbox_visitHealthOffice      char(1) default NULL,
radio_seeSameDoctor      varchar(36) default NULL,
frequencyOfSeeingEmergencyRoomDoctor      varchar(8) default NULL,
radio_didNotReceiveHealthCare      varchar(36) default NULL,
cbox_treatPhysicalHealth      char(1) default NULL,
cbox_treatMentalHealth      char(1) default NULL,
cbox_regularCheckup      char(1) default NULL,
cbox_treatOtherReasons      char(1) default NULL,
treatOtherReasons      varchar(255) default NULL,
cbox_treatInjury      char(1) default NULL,
cbox_goToWalkInClinic      char(1) default NULL,
cbox_goToHealthCenter      char(1) default NULL,
cbox_goToEmergencyRoom      char(1) default NULL,
cbox_goToOthers      char(1) default NULL,
goToOthers      varchar(255) default NULL,
cbox_HealthOffice      char(1) default NULL,
radio_appmtSeeDoctorIn3Mths      varchar(36) default NULL,
radio_needRegularDoctor      varchar(36) default NULL,
radio_objectToRegularDoctorIn4Wks      varchar(36) default NULL,
radio_rateOverallHealth      varchar(36) default NULL,
radio_speakToResearcher      varchar(36) default NULL,
contactName      varchar(70) default NULL,
contactPhone      varchar(24) default NULL,
contactAddress      varchar(255) default NULL,
contactRelationship      varchar(120) default NULL,
radio_hasMentalIllness      varchar(36) default NULL,
radio_hasDrinkingProblem      varchar(36) default NULL,
radio_hasDrugProblem      varchar(36) default NULL,
radio_hasHealthProblem      varchar(36) default NULL,
radio_hasBehaviorProblem      varchar(36) default NULL,
radio_needSeatonService      varchar(36) default NULL,
radio_seatonTour      varchar(36) default NULL,
seatonNotToured      varchar(255) default NULL,
radio_pamphletIssued      varchar(36) default NULL,
pamphletNotIssued      varchar(255) default NULL,
summary      varchar(255) default NULL,
completedBy      varchar(120) default NULL,
assessCompleteTime      varchar(36) default NULL,
cbox_pamphletIssued      char(1) default NULL,
cbox_hostel      char(1) default NULL,
cbox_rotaryClub      char(1) default NULL,
cbox_annexHarm      char(1) default NULL,
cbox_longTermProgram      char(1) default NULL,
cbox_birchmountResidence      char(1) default NULL,
cbox_oNeillHouse      char(1) default NULL,
cbox_fortYork      char(1) default NULL,
cbox_downsviewDells      char(1) default NULL,


PRIMARY KEY  (ID)  
) TYPE=MyISAM;



insert  into  encounterForm  values 
(
'ReceptionAssessment',
'../form/formreceptionassessment.jsp?demographic_no=',
'formreceptionassessment',
'1'

);

insert  into  encounterForm  values 
(
'CounsellorAssessment',
'../form/formcounsellorassessment.jsp?demographic_no=',
'formcounsellorassessment',
'1'

);

