#insert into encounterform values("Discharge Summary","../form/formDischargeSummary.jsp?demographic_no=","formDischargeSummary",1);

DROP TABLE IF EXISTS `formDischargeSummary`;
CREATE TABLE `formDischargeSummary` (
  `id` bigint(11) NOT NULL auto_increment,
  `demographic_no` bigint(11) NOT NULL default '0',  
  `formCreated` date default NULL,
  `formEdited` timestamp NOT NULL default CURRENT_TIMESTAMP on update CURRENT_TIMESTAMP,
  `clientName` varchar(60) default NULL,
  `birthDate` date default NULL,
  `ohip` varchar(25) default NULL,
  `admitDate` date default NULL,
  `dischargeDate` date default NULL,
  `programName` varchar(70) default NULL,
  `allergies` varchar(255) default NULL,
  `admissionNotes` varchar(255) default NULL,
  `currentIssues` varchar(255) default NULL,
  `briefSummary` varchar(255) default NULL,
  `dischargePlan` varchar(255) default NULL,
  `followUpAppointment` char(1) default NULL,
  `doctor1` varchar(30) default NULL,
  `phoneNumber1` varchar(30) default NULL,
  `date1` varchar(20) default NULL,
  `location1` varchar(100) default NULL,
  `doctor2` varchar(30) default NULL,
  `phoneNumber2` varchar(30) default NULL,
  `date2` varchar(20) default NULL,
  `location2` varchar(100) default NULL,
  `doctor3` varchar(30) default NULL,
  `phoneNumber3` varchar(30) default NULL,
  `date3` varchar(20) default NULL,
  `location3` varchar(100) default NULL,
  `prescriptionSummary` varchar(255) default NULL,
  `prescriptionProvided` char(1) default NULL,  
  `coveredByODB` char(1) default NULL,  
  `ODBFormReqired` char(1) default NULL,
  `counsellorName` varchar(30) default NULL,
  `followUpRequired` char(1) default NULL,  
  `followUpRequiredDetail` varchar(255) default NULL,
  `changeMedications` varchar(255) default NULL,
  `referrals` varchar(255) default NULL,
  `program` varchar(255) default NULL,
  `referralMade` varchar(255) default NULL,
  `outcome` varchar(255) default NULL,  
  `provider_no` bigint(11) NOT NULL default '0',
  `providerName` varchar(60) default NULL,
  `signature` varchar(25) default NULL,
  `signatureDate` varchar(20) default NULL,
  PRIMARY KEY  (`id`)  
);

