INSERT INTO `program` (facilityId,name,description,type,maxAllowed,holdingTank,allowBatchAdmission,allowBatchDischarge,hic,programStatus,userDefined, enableEncounterTime, enableEncounterTransportationTime) VALUES (1,'Correctional/Probational Facility','Correctional/Probational Facility','community',99999,0,0,0,0,'active',1,0,0);
INSERT INTO `program` (facilityId,name,description,type,maxAllowed,holdingTank,allowBatchAdmission,allowBatchDischarge,hic,programStatus,userDefined, enableEncounterTime, enableEncounterTransportationTime) VALUES (1,'Domiciliary Hospital','Domiciliary Hospital','community',99999,0,0,0,0,'active',1,0,0);
INSERT INTO `program` (facilityId,name,description,type,maxAllowed,holdingTank,allowBatchAdmission,allowBatchDischarge,hic,programStatus,userDefined, enableEncounterTime, enableEncounterTransportationTime) VALUES (1,'General Hospital','General Hospital','community',99999,0,0,0,0,'active',1,0,0);
INSERT INTO `program` (facilityId,name,description,type,maxAllowed,holdingTank,allowBatchAdmission,allowBatchDischarge,hic,programStatus,userDefined, enableEncounterTime, enableEncounterTransportationTime) VALUES (1,'Psychiatric Hospital','Psychiatric Hospital','community',99999,0,0,0,0,'active',1,0,0);
INSERT INTO `program` (facilityId,name,description,type,maxAllowed,holdingTank,allowBatchAdmission,allowBatchDischarge,hic,programStatus,userDefined, enableEncounterTime, enableEncounterTransportationTime) VALUES (1,'Other Specialty Hospital','Other Specialty Hospital','community',99999,0,0,0,0,'active',1,0,0);
INSERT INTO `program` (facilityId,name,description,type,maxAllowed,holdingTank,allowBatchAdmission,allowBatchDischarge,hic,programStatus,userDefined, enableEncounterTime, enableEncounterTransportationTime) VALUES (1,'No fixed address','No fixed address','community',99999,0,0,0,0,'active',1,0,0);
INSERT INTO `program` (facilityId,name,description,type,maxAllowed,holdingTank,allowBatchAdmission,allowBatchDischarge,hic,programStatus,userDefined, enableEncounterTime, enableEncounterTransportationTime) VALUES (1,'Hostel/Shelter','Hostel/Shelter','community',99999,0,0,0,0,'active',1,0,0);
INSERT INTO `program` (facilityId,name,description,type,maxAllowed,holdingTank,allowBatchAdmission,allowBatchDischarge,hic,programStatus,userDefined, enableEncounterTime, enableEncounterTransportationTime) VALUES (1,'Long-Term Care Facility/Nursing Home','Long-Term Care Facility/Nursing Home','community',99999,0,0,0,0,'active',1,0,0);
INSERT INTO `program` (facilityId,name,description,type,maxAllowed,holdingTank,allowBatchAdmission,allowBatchDischarge,hic,programStatus,userDefined, enableEncounterTime, enableEncounterTransportationTime) VALUES (1,'Municipal Non-Profit Housing','Municipal Non-Profit Housing','community',99999,0,0,0,0,'active',1,0,0);
INSERT INTO `program` (facilityId,name,description,type,maxAllowed,holdingTank,allowBatchAdmission,allowBatchDischarge,hic,programStatus,userDefined, enableEncounterTime, enableEncounterTransportationTime) VALUES (1,'Private House/Apt.- Client Owned/Market','Private House/Apt.- Client Owned/Market','community',99999,0,0,0,0,'active',1,0,0);
INSERT INTO `program` (facilityId,name,description,type,maxAllowed,holdingTank,allowBatchAdmission,allowBatchDischarge,hic,programStatus,userDefined, enableEncounterTime, enableEncounterTransportationTime) VALUES (1,'Rent','Rent','community',99999,0,0,0,0,'active',1,0,0);
INSERT INTO `program` (facilityId,name,description,type,maxAllowed,holdingTank,allowBatchAdmission,allowBatchDischarge,hic,programStatus,userDefined, enableEncounterTime, enableEncounterTransportationTime) VALUES (1,'Private House/Apt.- Other/Subsidized','Private House/Apt.- Other/Subsidized','community',99999,0,0,0,0,'active',1,0,0);
INSERT INTO `program` (facilityId,name,description,type,maxAllowed,holdingTank,allowBatchAdmission,allowBatchDischarge,hic,programStatus,userDefined, enableEncounterTime, enableEncounterTransportationTime) VALUES (1,'Retirement Home/Seniors\' Residence','Retirement Home/Seniors\' Residence','community',99999,0,0,0,0,'active',1,0,0);
INSERT INTO `program` (facilityId,name,description,type,maxAllowed,holdingTank,allowBatchAdmission,allowBatchDischarge,hic,programStatus,exclusiveView,defaultServiceRestrictionDays,userDefined, enableEncounterTime, enableEncounterTransportationTime) VALUES (1,'Rooming/Boarding House','Rooming/Boarding House','community',99999,0,0,0,0,'active','no',30,1,0,0);
INSERT INTO `program` (facilityId,name,description,type,maxAllowed,holdingTank,allowBatchAdmission,allowBatchDischarge,hic,programStatus,userDefined, enableEncounterTime, enableEncounterTransportationTime) VALUES (10030,1,'Supportive Housing - Congregate Living','Supportive Housing - Congregate Living','community',99999,0,0,0,0,'active',1,0,0);
INSERT INTO `program` (facilityId,name,description,type,maxAllowed,holdingTank,allowBatchAdmission,allowBatchDischarge,hic,programStatus,userDefined, enableEncounterTime, enableEncounterTransportationTime) VALUES (1,'Supportive Housing - Assisted Living (RTF 24 Hr Home and Group Homes)','Supportive Housing - Assisted Living (RTF 24 Hr Home and Group Homes)','community',99999,0,0,0,0,'active',1,0,0);
INSERT INTO `program` (facilityId,name,description,type,maxAllowed,holdingTank,allowBatchAdmission,allowBatchDischarge,hic,programStatus,userDefined, enableEncounterTime, enableEncounterTransportationTime) VALUES (1,'Private Non-Profit Housing','Private Non-Profit Housing','community',99999,0,0,0,0,'active',1,0,0);
INSERT INTO `program` (facilityId,name,description,type,maxAllowed,holdingTank,allowBatchAdmission,allowBatchDischarge,hic,programStatus,userDefined, enableEncounterTime, enableEncounterTransportationTime) VALUES (1,'Approved Homes & Homes for Special Care','Approved Homes & Homes for Special Care','community',99999,0,0,0,0,'active',1,0,0);

