#Added a form table for the RhImmuneGlobulin form
#This  update is not needed except for Rh negative clinics


CREATE TABLE `formRhImmuneGlobulin` (
  `ID` int(10) NOT NULL auto_increment,
  `demographic_no` int(10) NOT NULL default '0',
  `provider_no` int(10) default NULL,
  `formCreated` date default NULL,
  `formEdited` timestamp NOT NULL default CURRENT_TIMESTAMP on update CURRENT_TIMESTAMP,
  `workflowId` int(10) default NULL,
  `state` char(1) default NULL,
  `dateOfReferral` datetime default NULL,
  `edd` datetime default NULL,
  `motherSurname` varchar(30) default NULL,
  `motherFirstname` varchar(30) default NULL,
  `dob` date default NULL,
  `motherHIN` varchar(20) default NULL,
  `motherVC` varchar(30) default NULL,
  `motherAddress` varchar(60) default NULL,
  `motherCity` varchar(60) default NULL,
  `motherProvince` varchar(60) default NULL,
  `motherPostalCode` varchar(10) default NULL,
  `motherABO` char(3) default NULL,
  `motherRHtype` varchar(4) default NULL,
  `hospitalForDelivery` varchar(255) default NULL,
  `refPhySurname` varchar(30) default NULL,
  `refPhyFirstname` varchar(30) default NULL,
  `refPhyAddress` varchar(60) default NULL,
  `refPhyCity` varchar(60) default NULL,
  `refPhyProvince` varchar(60) default NULL,
  `refPhyPostalCode` varchar(10) default NULL,
  `refPhyPhone` varchar(20) default NULL,
  `refPhyFax` varchar(20) default NULL,
  `comments` text,
  `obsHisG` varchar(10) default NULL,
  `obsHisP` varchar(10) default NULL,
  `obsHisT` varchar(10) default NULL,
  `obsHisA` varchar(10) default NULL,
  `obsHisL` varchar(10) default NULL,
  `obsHisTubMolPregYes` tinyint(1) default NULL,
  `obsHisTubMolPregNo` tinyint(1) default NULL,
  `obsHisMisAbortionYes` tinyint(1) default NULL,
  `obsHisMisAbortionNo` tinyint(1) default NULL,
  `obsHisReceiveAntiDYes` tinyint(1) default NULL,
  `obsHisReceiveAntiDNo` tinyint(1) default NULL,
  `motherAntibodies` varchar(4) default NULL,
  `fatherABO` char(3) default NULL,
  `fatherRHtype` varchar(4) default NULL,
  `pmHisBlClDisordersYes` tinyint(1) default NULL,
  `pmHisBlClDisordersNo` tinyint(1) default NULL,
  `pmHisBlClDisordersComment` text,
  `pmHisBlPlTransfusYes` tinyint(1) default NULL,
  `pmHisBlPlTransfusNo` tinyint(1) default NULL,
  `pmHisBlPlTransfusComment` text,
  `allReactionsYes` tinyint(1) default NULL,
  `allReactionsNo` tinyint(1) default NULL,
  `allReactionsComment` text,
  `curPregDueDateChangeYes` tinyint(1) default NULL,
  `curPregDueDateChangeNo` tinyint(1) default NULL,
  `curPregProceduresYes` tinyint(1) default NULL,
  `curPregProceduresNo` tinyint(1) default NULL,
  `curPregProceduresComment` text,
  `curPregBleedingYes` tinyint(1) default NULL,
  `curPregBleedingNo` tinyint(1) default NULL,
  `curPregBleedingComment` text,
  `curPregBleedingContYes` tinyint(1) default NULL,
  `curPregBleedingContNo` tinyint(1) default NULL,
  `curPregTraumaYes` tinyint(1) default NULL,
  `curPregTraumaNo` tinyint(1) default NULL,
  `curPregAntiDYes` tinyint(1) default NULL,
  `curPregAntiDNo` tinyint(1) default NULL,
  `curPregAntiDComment` text,
  `curPregAntiDReactionYes` tinyint(1) default NULL,
  `curPregAntiDReactionNo` tinyint(1) default NULL,
  `curPregBloodDrawnYes` tinyint(1) default NULL,
  `curPregBloodDrawnNo` tinyint(1) default NULL,
  `curPregDueDateChangeComment` text,
  `famPhySurname` varchar(30) default NULL,
  `famPhyFirstname` varchar(30) default NULL,
  `famPhyAddress` varchar(60) default NULL,
  `famPhyCity` varchar(60) default NULL,
  `famPhyProvince` varchar(60) default NULL,
  `famPhyPostalCode` varchar(10) default NULL,
  `famPhyPhone` varchar(20) default NULL,
  `famPhyFax` varchar(20) default NULL,
  PRIMARY KEY  (`ID`)
);
