alter table drugs add column eTreatmentType varchar(20);

alter table formRourke2009
change p1_breastFeeding1wNo p1_breastFeeding1wOkConcerns tinyint(1),
add p1_breastFeeding1wNo tinyint(1),
add p1_breastFeeding1wNotDiscussed tinyint(1),
change  p1_formulaFeeding1wNo p1_formulaFeeding1wOkConcerns tinyint(1),
add p1_formulaFeeding1wNo tinyint(1),
add p1_formulaFeeding1wNotDiscussed tinyint(1),
change p1_stoolUrine1wNo p1_stoolUrine1wOkConcerns tinyint(1),
add p1_stoolUrine1wNotDiscussed tinyint(1),
change p1_breastFeeding2wNo p1_breastFeeding2wOkConcerns tinyint(1),
add p1_breastFeeding2wNo tinyint(1),
add p1_breastFeeding2wNotDiscussed tinyint(1),
change p1_formulaFeeding2wNo p1_formulaFeeding2wOkConcerns tinyint(1),
add p1_formulaFeeding2wNo tinyint(1),
add p1_formulaFeeding2wNotDiscussed tinyint(1),
change p1_stoolUrine2wNo p1_stoolUrine2wOkConcerns tinyint(1),
add p1_stoolUrine2wNotDiscussed tinyint(1),
change p1_breastFeeding1mNo p1_breastFeeding1mOkConcerns tinyint(1),
add p1_breastFeeding1mNo tinyint(1),
add p1_breastFeeding1mNotDiscussed tinyint(1),
change p1_formulaFeeding1mNo p1_formulaFeeding1mOkConcerns tinyint(1),
add p1_formulaFeeding1mNo tinyint(1),
add p1_formulaFeeding1mNotDiscussed tinyint(1),
change p1_stoolUrine1mNo p1_stoolUrine1mOkConcerns tinyint(1),
add p1_stoolUrine1mNotDiscussed tinyint(1),
change p1_carSeatNo p1_carSeatOkConcerns tinyint(1),
add p1_carSeatNotDiscussed tinyint(1),
change p1_sleepPosNo p1_sleepPosOkConcerns tinyint(1),
add p1_sleepPosNotDiscussed tinyint(1),
change p1_cribSafetyNo p1_cribSafetyOkConcerns tinyint(1),
add p1_cribSafetyNotDiscussed tinyint(1),
change p1_firearmSafetyNo p1_firearmSafetyOkConcerns tinyint(1),
add p1_firearmSafetyNotDiscussed tinyint(1),
change p1_smokeSafetyNo p1_smokeSafetyOkConcerns tinyint(1),
add p1_smokeSafetyNotDiscussed tinyint(1),
change p1_hotWaterNo p1_hotWaterOkConcerns tinyint(1),
add p1_hotWaterNotDiscussed tinyint(1),
change p1_safeToysNo p1_safeToysOkConcerns tinyint(1),
add p1_safeToysNotDiscussed tinyint(1),
change p1_sleepCryNo p1_sleepCryOkConcerns tinyint(1),
add p1_sleepCryNotDiscussed tinyint(1),
change p1_soothabilityNo p1_soothabilityOkConcerns tinyint(1),
add p1_soothabilityNotDiscussed tinyint(1),
change p1_bondingNo p1_bondingOkConcerns tinyint(1),
add p1_bondingNotDiscussed tinyint(1),
change p1_pFatigueNo p1_pFatigueOkConcerns tinyint(1),
add p1_pFatigueNotDiscussed tinyint(1),
change p1_famConflictNo p1_famConflictOkConcerns tinyint(1),
add p1_famConflictNotDiscussed tinyint(1),
change p1_siblingsNo p1_siblingsOkConcerns tinyint(1),
add p1_siblingsNotDiscussed tinyint(1),
change p1_homeVisitNo p1_homeVisitOkConcerns tinyint(1),
add p1_homeVisitNotDiscussed tinyint(1),
change p1_2ndSmokeNo p1_2ndSmokeOkConcerns tinyint(1),
add p1_2ndSmokeNotDiscussed tinyint(1),
change p1_altMedNo p1_altMedOkConcerns tinyint(1),
add p1_altMedNotDiscussed tinyint(1),
change p1_pacifierNo p1_pacifierOkConcerns tinyint(1),
add p1_pacifierNotDiscussed tinyint(1),
change p1_feverNo p1_feverOkConcerns tinyint(1),
add p1_feverNotDiscussed tinyint(1),
change p1_tmpControlNo p1_tmpControlOkConcerns tinyint(1),
add p1_tmpControlNotDiscussed tinyint(1),
change p1_sunExposureNo p1_sunExposureOkConcerns tinyint(1),
add p1_sunExposureNotDiscussed tinyint(1),
change p1_noCoughMedNo p1_noCoughMedOkConcerns tinyint(1),
add p1_noCoughMedNotDiscussed tinyint(1),
add p1_sucks2wNotDiscussed tinyint(1),
add p1_noParentsConcerns2wNotDiscussed tinyint(1),
add p1_focusGaze1mNotDiscussed tinyint(1),
add p1_startles1mNotDiscussed tinyint(1),
add p1_calms1mNotDiscussed tinyint(1),
add p1_sucks1mNotDiscussed tinyint(1),
add p1_noParentsConcerns1mNotDiscussed tinyint(1),
add p1_skin1wNotDiscussed tinyint(1),
add p1_fontanelles1wNotDiscussed tinyint(1),
add p1_eyes1wNotDiscussed tinyint(1),
add p1_ears1wNotDiscussed tinyint(1),
add p1_heartLungs1wNotDiscussed tinyint(1),
add p1_umbilicus1wNotDiscussed tinyint(1),
add p1_femoralPulses1wNotDiscussed tinyint(1),
add p1_hips1wNotDiscussed tinyint(1),
add p1_muscleTone1wNotDiscussed tinyint(1),
add p1_testicles1wNotDiscussed tinyint(1),
add p1_maleUrinary1wNotDiscussed tinyint(1),
add p1_skin2wNotDiscussed tinyint(1),
add p1_fontanelles2wNotDiscussed tinyint(1),
add p1_eyes2wNotDiscussed tinyint(1),
add p1_ears2wNotDiscussed tinyint(1),
add p1_heartLungs2wNotDiscussed tinyint(1),
add p1_umbilicus2wNotDiscussed tinyint(1),
add p1_femoralPulses2wNotDiscussed tinyint(1),
add p1_hips2wNotDiscussed tinyint(1),
add p1_muscleTone2wNotDiscussed tinyint(1),
add p1_testicles2wNotDiscussed tinyint(1),
add p1_maleUrinary2wNotDiscussed tinyint(1),
add p1_skin1mNotDiscussed tinyint(1),
add p1_fontanelles1mNotDiscussed tinyint(1),
add p1_eyes1mNotDiscussed tinyint(1),
add p1_corneal1mNotDiscussed tinyint(1),
add p1_hearing1mNotDiscussed tinyint(1),
add p1_heart1mNotDiscussed tinyint(1),
add p1_hips1mNotDiscussed tinyint(1),
add p1_muscleTone1mNotDiscussed tinyint(1),
change p1_pkuThyroid1w p1_pkuThyroid1wOkConcerns tinyint(1),
add p1_pkuThyroid1wOk tinyint(1),
add p1_pkuThyroid1wNotDiscussed tinyint(1),
change p1_hemoScreen1w p1_hemoScreen1wOkConcerns tinyint(1),
add p1_hemoScreen1wOk tinyint(1),
add p1_hemoScreen1wNotDiscussed tinyint(1),
change p1_hepatitisVaccine1w p1_hepatitisVaccine1wOk tinyint(1),
add p1_hepatitisVaccine1wNo tinyint(1),
change p1_hepatitisVaccine1m p1_hepatitisVaccine1mOk tinyint(1),
add p1_hepatitisVaccine1mNo tinyint(1),
change p2_breastFeeding2mNo p2_breastFeeding2mOkConcerns tinyint(1),
add p2_breastFeeding2mNo tinyint(1),
add p2_breastFeeding2mNotDiscussed tinyint(1),
change p2_formulaFeeding2mNo p2_formulaFeeding2mOkConcerns tinyint(1),
add p2_formulaFeeding2mNo tinyint(1),
add p2_formulaFeeding2mNotDiscussed tinyint(1),
change p2_breastFeeding4mNo p2_breastFeeding4mOkConcerns tinyint(1),
add p2_breastFeeding4mNo tinyint(1),
add p2_breastFeeding4mNotDiscussed tinyint(1),
change p2_formulaFeeding4mNo p2_formulaFeeding4mOkConcerns tinyint(1),
add p2_formulaFeeding4mNo tinyint(1),
add p2_formulaFeeding4mNotDiscussed tinyint(1),
change p2_breastFeeding6mNo p2_breastFeeding6mOkConcerns tinyint(1),
add p2_breastFeeding6mNo tinyint(1),
add p2_breastFeeding6mNotDiscussed tinyint(1),
change p2_formulaFeeding6mNo p2_formulaFeeding6mOkConcerns tinyint(1),
add p2_formulaFeeding6mNo tinyint(1),
add p2_formulaFeeding6mNotDiscussed tinyint(1),
change p2_bottle6mNo p2_bottle6mOkConcerns tinyint(1),
add p2_bottle6mNotDiscussed tinyint(1),
change p2_liquids6mNo p2_liquids6mOkConcerns tinyint(1),
add p2_liquids6mNo tinyint(1),
add p2_liquids6mNotDiscussed tinyint(1),
change p2_iron6mNo p2_iron6mOkConcerns tinyint(1),
add p2_iron6mNotDiscussed tinyint(1),
change p2_vegFruit6mNo p2_vegFruit6mOkConcerns tinyint(1),
add p2_vegFruit6mNotDiscussed tinyint(1),
change p2_egg6mNo p2_egg6mOkConcerns tinyint(1),
add p2_egg6mNotDiscussed tinyint(1),
change p2_choking6mNo p2_choking6mOkConcerns tinyint(1),
add p2_choking6mNotDiscussed tinyint(1),
change p2_carSeatNo p2_carSeatOkConcerns tinyint(1),
add p2_carSeatNotDiscussed tinyint(1),
change p2_sleepPosNo p2_sleepPosOkConcerns tinyint(1),
add p2_sleepPosNotDiscussed tinyint(1),
change p2_poisonsNo p2_poisonsOkConcerns tinyint(1),
add p2_poisonsNotDiscussed tinyint(1),
change p2_firearmSafetyNo p2_firearmSafetyOkConcerns tinyint(1),
add p2_firearmSafetyNotDiscussed tinyint(1),
change p2_electricNo p2_electricOkConcerns tinyint(1),
add p2_electricNotDiscussed tinyint(1),
change p2_smokeSafetyNo p2_smokeSafetyOkConcerns tinyint(1),
add p2_smokeSafetyNotDiscussed tinyint(1),
change p2_hotWaterNo p2_hotWaterOkConcerns tinyint(1),
add p2_hotWaterNotDiscussed tinyint(1),
change p2_fallsNo p2_fallsp2_sleepCryOkConcernsOkConcerns tinyint(1),
add p2_fallsNotDiscussed tinyint(1),
change p2_safeToysNo p2_safeToysOkConcerns tinyint(1),
add p2_safeToysNotDiscussed tinyint(1),
change p2_sleepCryNo p2_sleepCryOkConcerns tinyint(1),
add p2_sleepCryNotDiscussed tinyint(1),
change p2_soothabilityNo p2_soothabilityOkConcerns tinyint(1),
add p2_soothabilityNotDiscussed tinyint(1),
change p2_homeVisitNo p2_homeVisitOkConcerns tinyint(1),
add p2_homeVisitNotDiscussed tinyint(1),
change p2_bondingNo p2_bondingOkConcerns tinyint(1),
add p2_bondingNotDiscussed tinyint(1),
change p2_pFatigueNo p2_pFatigueOkConcerns tinyint(1),
add p2_pFatigueNotDiscussed tinyint(1),
change p2_famConflictNo p2_famConflictOkConcerns tinyint(1),
add p2_famConflictNotDiscussed tinyint(1),
change p2_siblingsNo p2_siblingsOkConcerns tinyint(1),
add p2_siblingsNotDiscussed tinyint(1),
change p2_childCareNo p2_childCareOkConcerns tinyint(1),
add p2_childCareNotDiscussed tinyint(1),
change p2_2ndSmokeNo p2_2ndSmokeOkConcerns tinyint(1),
add p2_2ndSmokeNotDiscussed tinyint(1),
change p2_teethingNo p2_teethingOkConcerns tinyint(1),
add p2_teethingNotDiscussed tinyint(1),
change p2_altMedNo p2_altMedOkConcerns tinyint(1),
add p2_altMedNotDiscussed tinyint(1),
change p2_pacifierNo p2_pacifierOkConcerns tinyint(1),
add p2_pacifierNotDiscussed tinyint(1),
change p2_tmpControlNo p2_tmpControlOkConcerns tinyint(1),
add p2_tmpControlNotDiscussed tinyint(1),
change p2_feverNo p2_feverOkConcerns tinyint(1),
add p2_feverNotDiscussed tinyint(1),
change p2_sunExposureNo p2_sunExposureOkConcerns tinyint(1),
add p2_sunExposureNotDiscussed tinyint(1),
change p2_pesticidesNo p2_pesticidesOkConcerns tinyint(1),
add p2_pesticidesNotDiscussed tinyint(1),
change p2_readingNo p2_readingOkConcerns tinyint(1),
add p2_readingNotDiscussed tinyint(1),
change p2_noCoughMedNo p2_noCoughMedOkConcerns tinyint(1),
add p2_noCoughMedNotDiscussed tinyint(1),
change p2_eyesNo p2_eyesOkConcerns tinyint(1),
add p2_eyesNotDiscussed tinyint(1),
change p2_coosNo p2_coosOkConcerns tinyint(1),
add p2_coosNotDiscussed tinyint(1),
change p2_headUpTummyNo p2_headUpTummyOkConcerns tinyint(1),
add p2_headUpTummyNotDiscussed tinyint(1),
change p2_cuddledNo p2_cuddledOkConcerns tinyint(1),
add p2_cuddledNotDiscussed tinyint(1),
change p2_2sucksNo p2_2sucksOkConcerns tinyint(1),
add p2_2sucksNotDiscussed tinyint(1),
change p2_smilesNo p2_smilesOkConcerns tinyint(1),
add p2_smilesNotDiscussed tinyint(1),
change p2_noParentsConcerns2mNo p2_noParentsConcerns2mOkConcerns tinyint(1),
add p2_noParentsConcerns2mNotDiscussed tinyint(1),
change p2_movingObjNo p2_movingObjOkConcerns tinyint(1),
add p2_movingObjNotDiscussed tinyint(1),
change p2_respondsNo p2_respondsOkConcerns tinyint(1),
add p2_respondsNotDiscussed tinyint(1),
change p2_headSteadyNo p2_headSteadyOkConcerns tinyint(1),
add p2_headSteadyNotDiscussed tinyint(1),
change p2_holdsObjNo p2_holdsObjOkConcerns tinyint(1),
add p2_holdsObjNotDiscussed tinyint(1),
change p2_laughsNo p2_laughsOkConcerns tinyint(1),
add p2_laughsNotDiscussed tinyint(1),
change p2_noParentsConcerns4mNo p2_noParentsConcerns4mOkConcerns tinyint(1),
add p2_noParentsConcerns4mNotDiscussed tinyint(1),
change p2_turnsHeadNo p2_turnsHeadOkConcerns tinyint(1),
add p2_turnsHeadNotDiscussed tinyint(1),
change p2_makesSoundNo p2_makesSoundOkConcerns tinyint(1),
add p2_makesSoundNotDiscussed tinyint(1),
change p2_vocalizesNo p2_vocalizesOkConcerns tinyint(1),
add p2_vocalizesNotDiscussed tinyint(1),
change p2_rollsNo p2_rollsOkConcerns tinyint(1),
add p2_rollsNotDiscussed tinyint(1),
change p2_sitsNo p2_sitsOkConcerns tinyint(1),
add p2_sitsNotDiscussed tinyint(1),
change p2_reachesGraspsNo p2_reachesGraspsOkConcerns tinyint(1),
add p2_reachesGraspsNotDiscussed tinyint(1),
change p2_noParentsConcerns6mNo p2_noParentsConcerns6mOkConcerns tinyint(1),
add p2_noParentsConcerns6mNotDiscussed tinyint(1),
change p2_fontanelles2mNo p2_fontanelles2mOkConcerns tinyint(1),
add p2_fontanelles2mNotDiscussed tinyint(1),
change p2_eyes2mNo p2_eyes2mOkConcerns tinyint(1),
add p2_eyes2mNotDiscussed tinyint(1),
change p2_corneal2mNo p2_corneal2mOkConcerns tinyint(1),
add p2_corneal2mNotDiscussed tinyint(1),
change p2_hearing2mNo p2_hearing2mOkConcerns tinyint(1),
add p2_hearing2mNotDiscussed tinyint(1),
change p2_heart2mNo p2_heart2mOkConcerns tinyint(1),
add p2_heart2mNotDiscussed tinyint(1),
change p2_hips2mNo p2_hips2mOkConcerns tinyint(1),
add p2_hips2mNotDiscussed tinyint(1),
change p2_muscleTone2mNo p2_muscleTone2mOkConcerns tinyint(1),
add p2_muscleTone2mNotDiscussed tinyint(1),
change p2_fontanelles4mNo p2_fontanelles4mOkConcerns tinyint(1),
add p2_fontanelles4mNotDiscussed tinyint(1),
change p2_eyes4mNo p2_eyes4mOkConcerns tinyint(1),
add p2_eyes4mNotDiscussed tinyint(1),
change p2_corneal4mNo p2_corneal4mOkConcerns tinyint(1),
add p2_corneal4mNotDiscussed tinyint(1),
change p2_hearing4mNo p2_hearing4mOkConcerns tinyint(1),
add p2_hearing4mNotDiscussed tinyint(1),
change p2_hips4mNo p2_hips4mOkConcerns tinyint(1),
add p2_hips4mNotDiscussed tinyint(1),
change p2_muscleTone4mNo p2_muscleTone4mOkConcerns tinyint(1),
add p2_muscleTone4mNotDiscussed tinyint(1),
change p2_fontanelles6mNo p2_fontanelles6mOkConcerns tinyint(1),
add p2_fontanelles6mNotDiscussed tinyint(1),
change p2_eyes6mNo p2_eyes6mOkConcerns tinyint(1),
add p2_eyes6mNotDiscussed tinyint(1),
change p2_corneal6mNo p2_corneal6mOkConcerns tinyint(1),
add p2_corneal6mNotDiscussed tinyint(1),
change p2_hearing6mNo p2_hearing6mOkConcerns tinyint(1),
add p2_hearing6mNotDiscussed tinyint(1),
change p2_hips6mNo p2_hips6mOkConcerns tinyint(1),
add p2_hips6mNotDiscussed tinyint(1),
change p2_muscleTone6mNo p2_muscleTone6mOkConcerns tinyint(1),
add p2_muscleTone6mNotDiscussed tinyint(1),
change p2_hepatitisVaccine6m p2_hepatitisVaccine6mOk tinyint(1),
add p2_hepatitisVaccine6mNo tinyint(1),
change p2_tb6m p2_tb6mOkConcerns tinyint(1),
add p2_tb6mOk tinyint(1),
add p2_tb6mNotDiscussed tinyint(1),
change p3_breastFeeding9mNo p3_breastFeeding9mOkConcerns tinyint(1),
add p3_breastFeeding9mNo tinyint(1),
add p3_breastFeeding9mNotDiscussed tinyint(1),
change p3_formulaFeeding9mNo p3_formulaFeeding9mOkConcerns tinyint(1),
add p3_formulaFeeding9mNo tinyint(1),
add p3_formulaFeeding9mNotDiscussed tinyint(1),
change p3_bottle9mNo p3_bottle9mOkConcerns tinyint(1),
add p3_bottle9mNotDiscussed tinyint(1),
change p3_liquids9mNo p3_liquids9mOkConcerns tinyint(1),
add p3_liquids9mNotDiscussed tinyint(1),
change p3_cereal9mNo p3_cereal9mOkConcerns tinyint(1),
add p3_cereal9mNotDiscussed tinyint(1),
change p3_introCowMilk9mNo p3_introCowMilk9mOkConcerns tinyint(1),
add p3_introCowMilk9mNotDiscussed tinyint(1),
change p3_egg9mNo p3_egg9mOkConcerns tinyint(1),
add p3_egg9mNotDiscussed tinyint(1),
change p3_choking9mNo p3_choking9mOkConcerns tinyint(1),
add p3_choking9mNotDiscussed tinyint(1),
change p3_breastFeeding12mNo p3_breastFeeding12mOkConcerns tinyint(1),
add p3_breastFeeding12mNo tinyint(1),
add p3_breastFeeding12mNotDiscussed tinyint(1),
change p3_homoMilk12mNo p3_homoMilk12mOkConcerns tinyint(1),
add p3_homoMilk12mNo tinyint(1),
add p3_homoMilk12mNotDiscussed tinyint(1),
change p3_cup12mNo p3_cup12mOkConcerns tinyint(1),
add p3_cup12mNotDiscussed tinyint(1),
change p3_appetite12mNo p3_appetite12mOkConcerns tinyint(1),
add p3_appetite12mNotDiscussed tinyint(1),
change p3_choking12mNo p3_choking12mOkConcerns tinyint(1),
add p3_choking12mNotDiscussed tinyint(1),
change p3_breastFeeding15mNo p3_breastFeeding15mOkConcerns tinyint(1),
add p3_breastFeeding15mNo tinyint(1),
add p3_breastFeeding15mNotDiscussed tinyint(1),
change p3_homoMilk15mNo p3_homoMilk15mOkConcerns tinyint(1),
add p3_homoMilk15mNo tinyint(1),
add p3_homoMilk15mNotDiscussed tinyint(1),
change p3_choking15mNo p3_choking15mOkConcerns tinyint(1),
add p3_choking15mNotDiscussed tinyint(1),
change p3_cup15mNo p3_cup15mOkConcerns tinyint(1),
add p3_cup15mNotDiscussed tinyint(1),
change p3_poisonsNo p3_poisonsOkConcerns tinyint(1),
add p3_poisonsNotDiscussed tinyint(1),
change p3_carSeatNo p3_carSeatOkConcerns tinyint(1),
add p3_carSeatNotDiscussed tinyint(1),
change p3_firearmSafetyNo p3_firearmSafetyOkConcerns tinyint(1),
add p3_firearmSafetyNotDiscussed tinyint(1),
change p3_smokeSafetyNo p3_smokeSafetyOkConcerns tinyint(1),
add p3_smokeSafetyNotDiscussed tinyint(1),
change p3_hotWaterNo p3_hotWaterOkConcerns tinyint(1),
add p3_hotWaterNotDiscussed tinyint(1),
change p3_electricNo p3_electricOkConcerns tinyint(1),
add p3_electricNotDiscussed tinyint(1),
change p3_fallsNo p3_fallsOkConcerns tinyint(1),
add p3_fallsNotDiscussed tinyint(1),
change p3_safeToysNo p3_safeToysOkConcerns tinyint(1),
add p3_safeToysNotDiscussed tinyint(1),
change p3_sleepCryNo p3_sleepCryOkConcerns tinyint(1),
add p3_sleepCryNotDiscussed tinyint(1),
change p3_soothabilityNo p3_soothabilityOkConcerns tinyint(1),
add p3_soothabilityNotDiscussed tinyint(1),
change p3_homeVisitNo p3_homeVisitOkConcerns tinyint(1),
add p3_homeVisitNotDiscussed tinyint(1),
change p3_parentingNo p3_parentingOkConcerns tinyint(1),
add p3_parentingNotDiscussed tinyint(1),
change p3_pFatigueNo p3_pFatigueOkConcerns tinyint(1),
add p3_pFatigueNotDiscussed tinyint(1),
change p3_famConflictNo p3_famConflictOkConcerns tinyint(1),
add p3_famConflictNotDiscussed tinyint(1),
change p3_siblingsNo p3_siblingsOkConcerns tinyint(1),
add p3_siblingsNotDiscussed tinyint(1),
change p3_childCareNo p3_childCareOkConcerns tinyint(1),
add p3_childCareNotDiscussed tinyint(1),
change p3_2ndSmokeNo p3_2ndSmokeOkConcerns tinyint(1),
add p3_2ndSmokeNotDiscussed tinyint(1),
change p3_teethingNo p3_teethingOkConcerns tinyint(1),
add p3_teethingNotDiscussed tinyint(1),
change p3_altMedNo p3_altMedOkConcerns tinyint(1),
add p3_altMedNotDiscussed tinyint(1),
change p3_pacifierNo p3_pacifierOkConcerns tinyint(1),
add p3_pacifierNotDiscussed tinyint(1),
change p3_feverNo p3_feverOkConcerns tinyint(1),
add p3_feverNotDiscussed tinyint(1),
change p3_activeNo p3_activeOkConcerns tinyint(1),
add p3_activeNotDiscussed tinyint(1),
change p3_readingNo p3_readingOkConcerns tinyint(1),
add p3_readingNotDiscussed tinyint(1),
change p3_footwearNo p3_footwearOkConcerns tinyint(1),
add p3_footwearNotDiscussed tinyint(1),
change p3_coughMedNo p3_coughMedOkConcerns tinyint(1),
add p3_coughMedNotDiscussed tinyint(1),
change p3_sunExposureNo p3_sunExposureOkConcerns tinyint(1),
add p3_sunExposureNotDiscussed tinyint(1),
change p3_checkSerumNo p3_checkSerumOkConcerns tinyint(1),
add p3_checkSerumNotDiscussed tinyint(1),
change p3_pesticidesNo p3_pesticidesOkConcerns tinyint(1),
add p3_pesticidesNotDiscussed tinyint(1),
change p3_hiddenToyNo p3_hiddenToyOkConcerns tinyint(1),
add p3_hiddenToyNotDiscussed tinyint(1),
change p3_soundsNo p3_soundsOkConcerns tinyint(1),
add p3_soundsNotDiscussed tinyint(1),
change p3_responds2peopleNo p3_responds2peopleOkConcerns tinyint(1),
add p3_responds2peopleNotDiscussed tinyint(1),
change p3_makeSoundsNo p3_makeSoundsOkConcerns tinyint(1),
add p3_makeSoundsNotDiscussed tinyint(1),
change p3_sitsNo p3_sitsOkConcerns tinyint(1),
add p3_sitsNotDiscussed tinyint(1),
change p3_standsNo p3_standsOkConcerns tinyint(1),
add p3_standsNotDiscussed tinyint(1),
change p3_thumbNo p3_thumbOkConcerns tinyint(1),
add p3_thumbNotDiscussed tinyint(1),
change p3_playGamesNo p3_playGamesOkConcerns tinyint(1),
add p3_playGamesNotDiscussed tinyint(1),
change p3_attention9mNo p3_attention9mOkConcerns tinyint(1),
add p3_attention9mNotDiscussed tinyint(1),
change p3_noParentsConcerns9mNo p3_noParentsConcerns9mOkConcerns tinyint(1),
add p3_noParentsConcerns9mNotDiscussed tinyint(1),
change p3_respondsNo p3_respondsOkConcerns tinyint(1),
add p3_respondsNotDiscussed tinyint(1),
change p3_simpleRequestsNo p3_simpleRequestsOkConcerns tinyint(1),
add p3_simpleRequestsNotDiscussed tinyint(1),
change p3_consonantNo p3_consonantOkConcerns tinyint(1),
add p3_consonantNotDiscussed tinyint(1),
change p3_says3wordsNo p3_says3wordsOkConcerns tinyint(1),
add p3_says3wordsNotDiscussed tinyint(1),
change p3_shufflesNo p3_shufflesOkConcerns tinyint(1),
add p3_shufflesNotDiscussed tinyint(1),
change p3_pull2standNo p3_pull2standOkConcerns tinyint(1),
change p3_showDistressNo p3_showDistressOkConcerns tinyint(1),
add p3_showDistressNotDiscussed tinyint(1),
add p3_pull2standNotDiscussed tinyint(1),
change p3_followGazeNo p3_followGazeOkConcerns tinyint(1),
add p3_followGazeNotDiscussed tinyint(1),
change p3_noParentsConcerns12mNo p3_noParentsConcerns12mOkConcerns tinyint(1),
add p3_noParentsConcerns12mNotDiscussed tinyint(1),
change p3_says5wordsNo p3_says5wordsOkConcerns tinyint(1),
add p3_says5wordsNotDiscussed tinyint(1),
change p3_fingerFoodsNo p3_fingerFoodsOkConcerns tinyint(1),
add p3_fingerFoodsNotDiscussed tinyint(1),
change p3_walksSidewaysNo p3_walksSidewaysOkConcerns tinyint(1),
add p3_walksSidewaysNotDiscussed tinyint(1),
change p3_showsFearStrangersNo p3_showsFearStrangersOkConcerns tinyint(1),
add p3_showsFearStrangersNotDiscussed tinyint(1),
change p3_crawlsStairsNo p3_crawlsStairsOkConcerns tinyint(1),
add p3_crawlsStairsNotDiscussed tinyint(1),
change p3_squatsNo p3_squatsOkConcerns tinyint(1),
add p3_squatsNotDiscussed tinyint(1),
change p3_noParentsConcerns15mNo p3_noParentsConcerns15mOkConcerns tinyint(1),
add p3_noParentsConcerns15mNotDiscussed tinyint(1),
change p3_fontanelles9mNo p3_fontanelles9mOkConcerns tinyint(1),
add p3_fontanelles9mNotDiscussed tinyint(1),
change p3_eyes9mNo p3_eyes9mOkConcerns tinyint(1),
add p3_eyes9mNotDiscussed tinyint(1),
change p3_corneal9mNo p3_corneal9mOkConcerns tinyint(1),
add p3_corneal9mNotDiscussed tinyint(1),
change p3_hearing9mNo p3_hearing9mOkConcerns tinyint(1),
add p3_hearing9mNotDiscussed tinyint(1),
change p3_hips9mNo p3_hips9mOkConcerns tinyint(1),
add p3_hips9mNotDiscussed tinyint(1),
change p3_fontanelles12mNo p3_fontanelles12mOkConcerns tinyint(1),
add p3_fontanelles12mNotDiscussed tinyint(1),
change p3_eyes12mNo p3_eyes12mOkConcerns tinyint(1),
add p3_eyes12mNotDiscussed tinyint(1),
change p3_corneal12mNo p3_corneal12mOkConcerns tinyint(1),
add p3_corneal12mNotDiscussed tinyint(1),
change p3_hearing12mNo p3_hearing12mOkConcerns tinyint(1),
add p3_hearing12mNotDiscussed tinyint(1),
change p3_tonsil12mNo p3_tonsil12mOkConcerns tinyint(1),
add p3_tonsil12mNotDiscussed tinyint(1),
change p3_hips12mNo p3_hips12mOkConcerns tinyint(1),
add p3_hips12mNotDiscussed tinyint(1),
change p3_fontanelles15mNo p3_fontanelles15mOkConcerns tinyint(1),
add p3_fontanelles15mNotDiscussed tinyint(1),
change p3_eyes15mNo p3_eyes15mOkConcerns tinyint(1),
add p3_eyes15mNotDiscussed tinyint(1),
change p3_corneal15mNo p3_corneal15mOkConcerns tinyint(1),
add p3_corneal15mNotDiscussed tinyint(1),
change p3_hearing15mNo p3_hearing15mOkConcerns tinyint(1),
add p3_hearing15mNotDiscussed tinyint(1),
change p3_tonsil15mNo p3_tonsil15mOkConcerns tinyint(1),
add p3_tonsil15mNotDiscussed tinyint(1),
change p3_hips15mNo p3_hips15mOkConcerns tinyint(1),
add p3_hips15mNotDiscussed tinyint(1),
change p3_antiHB9m p3_antiHB9mOkConcerns tinyint(1),
add p3_antiHB9mNotDiscussed tinyint(1),
add p3_antiHB9mOk tinyint(1),
change p3_hemoglobin9m p3_hemoglobin9mOkConcerns tinyint(1),
add p3_hemoglobin9mOk tinyint(1),
add p3_hemoglobin9mNotDiscussed tinyint(1),
change p3_hemoglobin12m p3_hemoglobin12mOkConcerns tinyint(1),
add p3_hemoglobin12mOk tinyint(1),
add p3_hemoglobin12mNotDiscussed tinyint(1),
change p4_breastFeeding18mNo p4_breastFeeding18mOkConcerns tinyint(1),
add p4_breastFeeding18mNo tinyint(1),
add p4_breastFeeding18mNotDiscussed tinyint(1),
change p4_homoMilk18mNo p4_homoMilk18mOkConcerns tinyint(1),
add p4_homoMilk18mNo tinyint(1),
add p4_homoMilk18mNotDiscussed tinyint(1),
change p4_bottle18mNo p4_bottle18mOkConcerns tinyint(1),
add p4_bottle18mNotDiscussed tinyint(1),
change p4_homo2percent24mNo p4_homo2percent24mOkConcerns tinyint(1),
add p4_homo2percent24mNo tinyint(1),
add p4_homo2percent24mNotDiscussed tinyint(1),
change p4_lowerfatdiet24mNo p4_lowerfatdiet24mOkConcerns tinyint(1),
add p4_lowerfatdiet24mNotDiscussed tinyint(1),
add p4_foodguide24mNotDiscussed tinyint(1),
change p4_2pMilk48mNo p4_2pMilk48mOkConcerns tinyint(1),
add p4_2pMilk48mNo tinyint(1),
add p4_2pMilk48mNotDiscussed tinyint(1),
add p4_foodguide48mNotDiscussed tinyint(1),
change p4_carSeat18mNo p4_carSeat18mOkConcerns tinyint(1),
add p4_carSeat18mNotDiscussed tinyint(1),
change  p4_bathSafetyNo p4_bathSafetyOkConcerns tinyint(1),
add p4_bathSafetyNotDiscussed tinyint(1),
change p4_safeToysNo p4_safeToysOkConcerns tinyint(1),
add p4_safeToysNotDiscussed tinyint(1),
change p4_parentChild18mNo p4_parentChild18mOkConcerns tinyint(1),
add p4_parentChild18mNotDiscussed tinyint(1),
change p4_discipline18mNo p4_discipline18mOkConcerns tinyint(1),
add p4_discipline18mNotDiscussed tinyint(1),
change p4_pFatigue18mNo p4_pFatigue18mOkConcerns tinyint(1),
add p4_pFatigue18mNotDiscussed tinyint(1),
change p4_highRisk18mNo p4_highRisk18mOkConcerns tinyint(1),
add p4_highRisk18mNotDiscussed tinyint(1),
change p4_socializing18mNo p4_socializing18mOkConcerns tinyint(1),
add p4_socializing18mNotDiscussed tinyint(1),
change p4_weanPacifier18mNo p4_weanPacifier18mOkConcerns tinyint(1),
add p4_weanPacifier18mNotDiscussed tinyint(1),
change p4_dentalCareNo p4_dentalCareOkConcerns tinyint(1),
add p4_dentalCareNotDiscussed tinyint(1),
change p4_toiletLearning18mNo p4_toiletLearning18mOkConcerns tinyint(1),
add p4_toiletLearning18mNotDiscussed tinyint(1),
change p4_encourageReading18mNo p4_encourageReading18mOkConcerns tinyint(1),
add p4_encourageReading18mNotDiscussed tinyint(1),
change p4_carSeat24mNo p4_carSeat24mOkConcerns tinyint(1),
add p4_carSeat24mNotDiscussed tinyint(1),
change p4_bikeHelmetsNo p4_bikeHelmetsOkConcerns tinyint(1),
add p4_bikeHelmetsNotDiscussed tinyint(1),
change p4_firearmSafetyNo p4_firearmSafetyOkConcerns tinyint(1),
add p4_firearmSafetyNotDiscussed tinyint(1),
change p4_smokeSafetyNo p4_smokeSafetyOkConcerns tinyint(1),
add p4_smokeSafetyNotDiscussed tinyint(1),
change p4_matchesNo p4_matchesOkConcerns tinyint(1),
add p4_matchesNotDiscussed tinyint(1),
change p4_waterSafetyNo p4_waterSafetyOkConcerns tinyint(1),
add p4_waterSafetyNotDiscussed tinyint(1),
change p4_parentChild24mNo p4_parentChild24mOkConcerns tinyint(1),
add p4_parentChild24mNotDiscussed tinyint(1),
change p4_discipline24mNo p4_discipline24mOkConcerns tinyint(1),
add p4_discipline24mNotDiscussed tinyint(1),
change p4_highRisk24mNo p4_highRisk24mOkConcerns tinyint(1),
add p4_highRisk24mNotDiscussed tinyint(1),
change p4_pFatigue24mNo p4_pFatigue24mOkConcerns tinyint(1),
add p4_pFatigue24mNotDiscussed tinyint(1),
change p4_famConflictNo p4_famConflictOkConcerns tinyint(1),
add p4_famConflictNotDiscussed tinyint(1),
change p4_siblingsNo p4_siblingsOkConcerns tinyint(1),
add p4_siblingsNotDiscussed tinyint(1),
change p4_2ndSmokeNo p4_2ndSmokeOkConcerns tinyint(1),
add p4_2ndSmokeNotDiscussed tinyint(1),
change p4_dentalCleaningNo p4_dentalCleaningOkConcerns tinyint(1),
add p4_dentalCleaningNotDiscussed tinyint(1),
change p4_noPacifier24mNo p4_noPacifier24mOkConcerns tinyint(1),
add p4_noPacifier24mNotDiscussed tinyint(1),
change p4_altMedNo p4_altMedOkConcerns tinyint(1),
add p4_altMedNotDiscussed tinyint(1),
change p4_toiletLearning24mNo p4_toiletLearning24mOkConcerns tinyint(1),
add p4_toiletLearning24mNotDiscussed tinyint(1),
change p4_noCough24mNo p4_noCough24mOkConcerns tinyint(1),
add p4_noCough24mNotDiscussed tinyint(1),
change p4_activeNo p4_activeOkConcerns tinyint(1),
add p4_activeNotDiscussed tinyint(1),
change p4_socializing24mNo p4_socializing24mOkConcerns tinyint(1),
add p4_socializing24mNotDiscussed tinyint(1),
change p4_readingNo p4_readingOkConcerns tinyint(1),
add p4_readingNotDiscussed tinyint(1),
change p4_dayCareNo p4_dayCareOkConcerns tinyint(1),
add p4_dayCareNotDiscussed tinyint(1),
change p4_sunExposureNo p4_sunExposureOkConcerns tinyint(1),
add p4_sunExposureNotDiscussed tinyint(1),
change p4_pesticidesNo p4_pesticidesOkConcerns tinyint(1),
add p4_pesticidesNotDiscussed tinyint(1),
change p4_checkSerumNo p4_checkSerumOkConcerns tinyint(1),
add p4_checkSerumNotDiscussed tinyint(1),
change p4_manageableNo p4_manageableOkConcerns tinyint(1),
add p4_manageableNotDiscussed tinyint(1),
change p4_otherChildrenNo p4_otherChildrenOkConcerns tinyint(1),
add p4_otherChildrenNotDiscussed tinyint(1),
change p4_soothabilityNo p4_soothabilityOkConcerns tinyint(1),
add p4_soothabilityNotDiscussed tinyint(1),
change p4_comfortNo p4_comfortOkConcerns tinyint(1),
add p4_comfortNotDiscussed tinyint(1),
change p4_pointsNo p4_pointsOkConcerns tinyint(1),
add p4_pointsNotDiscussed tinyint(1),
change p4_getAttnNo p4_getAttnOkConcerns tinyint(1),
add p4_getAttnNotDiscussed tinyint(1),
change p4_recsNameNo p4_recsNameOkConcerns tinyint(1),
add p4_recsNameNotDiscussed tinyint(1),
change p4_points2wantNo p4_points2wantOkConcerns tinyint(1),
add p4_points2wantNotDiscussed tinyint(1),
change p4_looks4toyNo p4_looks4toyOkConcerns tinyint(1),
add p4_looks4toyNotDiscussed tinyint(1),
change p4_initSpeechNo p4_initSpeechOkConcerns tinyint(1),
add p4_initSpeechNotDiscussed tinyint(1),
change p4_says20wordsNo p4_says20wordsOkConcerns tinyint(1),
add p4_says20wordsNotDiscussed tinyint(1),
change p4_4consonantsNo p4_4consonantsOkConcerns tinyint(1),
add p4_4consonantsNotDiscussed tinyint(1),
change p4_walksbackNo p4_walksbackOkConcerns tinyint(1),
add p4_walksbackNotDiscussed tinyint(1),
change p4_feedsSelfNo p4_feedsSelfOkConcerns tinyint(1),
add p4_feedsSelfNotDiscussed tinyint(1),
change p4_removesHatNo p4_removesHatOkConcerns tinyint(1),
add p4_removesHatNotDiscussed tinyint(1),
change p4_noParentsConcerns18mNo p4_noParentsConcerns18mOkConcerns tinyint(1),
add p4_noParentsConcerns18mNotDiscussed tinyint(1),
change p4_2wSentenceNo p4_2wSentenceOkConcerns tinyint(1),
add p4_2wSentenceNotDiscussed tinyint(1),
change p4_one2stepdirectionsNo p4_one2stepdirectionsOkConcerns tinyint(1),
add p4_one2stepdirectionsNotDiscussed tinyint(1),
change p4_walksbackwardNo p4_walksbackwardOkConcerns tinyint(1),
add p4_walksbackwardNotDiscussed tinyint(1),
change p4_runsNo p4_runsOkConcerns tinyint(1),
add p4_runsNotDiscussed tinyint(1),
change p4_smallContainerNo p4_smallContainerOkConcerns tinyint(1),
add p4_smallContainerNotDiscussed tinyint(1),
change p4_pretendsPlayNo p4_pretendsPlayOkConcerns tinyint(1),
add p4_pretendsPlayNotDiscussed tinyint(1),
change p4_newSkillsNo p4_newSkillsOkConcerns tinyint(1),
add p4_newSkillsNotDiscussed tinyint(1),
change p4_noParentsConcerns24mNo p4_noParentsConcerns24mOkConcerns tinyint(1),
add p4_noParentsConcerns24mNotDiscussed tinyint(1),
change p4_3directionsNo p4_3directionsOkConcerns tinyint(1),
add p4_3directionsNotDiscussed tinyint(1),
change p4_asksQuestionsNo p4_asksQuestionsOkConcerns tinyint(1),
add p4_asksQuestionsNotDiscussed tinyint(1),
change p4_upDownStairsNo p4_upDownStairsOkConcerns tinyint(1),
add p4_upDownStairsNotDiscussed tinyint(1),
change p4_undoesZippersNo p4_undoesZippersOkConcerns tinyint(1),
add p4_undoesZippersNotDiscussed tinyint(1),
change p4_tries2comfortNo p4_tries2comfortOkConcerns tinyint(1),
add p4_tries2comfortNotDiscussed tinyint(1),
change p4_noParentsConcerns48mNo p4_noParentsConcerns48mOkConcerns tinyint(1),
add p4_noParentsConcerns48mNotDiscussed tinyint(1),
change p4_2directionsNo p4_2directionsOkConcerns tinyint(1),
add p4_2directionsNotDiscussed tinyint(1),
change p4_5ormoreWordsNo p4_5ormoreWordsOkConcerns tinyint(1),
add p4_5ormoreWordsNotDiscussed tinyint(1),
change p4_walksUpStairsNo p4_walksUpStairsOkConcerns tinyint(1),
add p4_walksUpStairsNotDiscussed tinyint(1),
change p4_twistslidsNo p4_twistslidsOkConcerns tinyint(1),
add p4_twistslidsNotDiscussed tinyint(1),
change p4_sharesSometimeNo p4_sharesSometimeOkConcerns tinyint(1),
add p4_sharesSometimeNotDiscussed tinyint(1),
change p4_playMakeBelieveNo p4_playMakeBelieveOkConcerns tinyint(1),
add p4_playMakeBelieveNotDiscussed tinyint(1),
change p4_turnsPagesNo p4_turnsPagesOkConcerns tinyint(1),
add p4_turnsPagesNotDiscussed tinyint(1),
change p4_listenMusikNo p4_listenMusikOkConcerns tinyint(1),
add p4_listenMusikNotDiscussed tinyint(1),
change p4_noParentsConcerns36mNo p4_noParentsConcerns36mOkConcerns tinyint(1),
add p4_noParentsConcerns36mNotDiscussed tinyint(1),
change p4_countsOutloudNo p4_countsOutloudOkConcerns tinyint(1),
add p4_countsOutloudNotDiscussed tinyint(1),
change p4_speaksClearlyNo p4_speaksClearlyOkConcerns tinyint(1),
add p4_speaksClearlyNotDiscussed tinyint(1),
change p4_throwsCatchesNo p4_throwsCatchesOkConcerns tinyint(1),
add p4_throwsCatchesNotDiscussed tinyint(1),
change p4_hops1footNo p4_hops1footOkConcerns tinyint(1),
add p4_hops1footNotDiscussed tinyint(1),
change p4_dressesUndressesNo p4_dressesUndressesOkConcerns tinyint(1),
add p4_dressesUndressesNotDiscussed tinyint(1),
change p4_obeysAdultNo p4_obeysAdultOkConcerns tinyint(1),
add p4_obeysAdultNotDiscussed tinyint(1),
change p4_retellsStoryNo p4_retellsStoryOkConcerns tinyint(1),
add p4_retellsStoryNotDiscussed tinyint(1),
change p4_separatesNo p4_separatesOkConcerns tinyint(1),
add p4_separatesNotDiscussed tinyint(1),
change p4_noParentsConcerns60mNo p4_noParentsConcerns60mOkConcerns tinyint(1),
add p4_noParentsConcerns60mNotDiscussed tinyint(1),
change p4_fontanellesClosedNo p4_fontanellesClosedOkConcerns tinyint(1),
add p4_fontanellesClosedNotDiscussed tinyint(1),
change p4_eyes18mNo p4_eyes18mOkConcerns tinyint(1),
add p4_eyes18mNotDiscussed tinyint(1),
change p4_corneal18mNo p4_corneal18mOkConcerns tinyint(1),
add p4_corneal18mNotDiscussed tinyint(1),
change p4_hearing18mNo p4_hearing18mOkConcerns tinyint(1),
add p4_hearing18mNotDiscussed tinyint(1),
change p4_tonsil18mNo p4_tonsil18mOkConcerns tinyint(1),
add p4_tonsil18mNotDiscussed tinyint(1),
change p4_bloodpressure24mNo p4_bloodpressure24mOkConcerns tinyint(1),
add p4_bloodpressure24mNotDiscussed tinyint(1),
change p4_eyes24mNo p4_eyes24mOkConcerns tinyint(1),
add p4_eyes24mNotDiscussed tinyint(1),
change p4_corneal24mNo p4_corneal24mOkConcerns tinyint(1),
add p4_corneal24mNotDiscussed tinyint(1),
change p4_hearing24mNo p4_hearing24mOkConcerns tinyint(1),
add p4_hearing24mNotDiscussed tinyint(1),
change p4_tonsil24mNo p4_tonsil24mOkConcerns tinyint(1),
add p4_tonsil24mNotDiscussed tinyint(1),
change p4_bloodpressure48mNo p4_bloodpressure48mOkConcerns tinyint(1),
add p4_bloodpressure48mNotDiscussed tinyint(1),
change p4_eyes48mNo p4_eyes48mOkConcerns tinyint(1),
add p4_eyes48mNotDiscussed tinyint(1),
change p4_corneal48mNo p4_corneal48mOkConcerns tinyint(1),
add p4_corneal48mNotDiscussed tinyint(1),
change p4_hearing48mNo p4_hearing48mOkConcerns tinyint(1),
add p4_hearing48mNotDiscussed tinyint(1),
change p4_tonsil48mNo p4_tonsil48mOkConcerns tinyint(1),
add p4_tonsil48mNotDiscussed tinyint(1),
add p1_pNutrition1w text,
add p1_pNutrition2w text,
add p1_pNutrition1m text,
add p1_pEducation text,
add p1_pPhysical1w text,
add p1_pPhysical2w text,
add p1_pPhysical1m text,
add p1_immunization1w text,
add p1_immunization2w text,
add p1_immunization1m text,
add p2_nutrition6m text,
add p2_education text,
add p2_physical2m text,
add p2_physical4m text,
add p2_physical6m text,
add p2_immunization6m text,
add p3_nutrition9m text,
add p3_education text,
add p3_physical9m text,
add p3_physical12m text,
add p3_physical15m text,
add p4_nutrition18m text,
add p4_nutrition24m text,
add p4_nutrition48m text,
add p4_education18m text,
add p4_education48m text,
add p4_development18m text,
add p4_development24m text,
add p4_development48m text,
add p4_development36m text,
add p4_development60m text,
add p4_physical18m text,
add p4_physical24m text,
add p4_physical48m text,
add p4_nippisingattained text;
