insert into LookupList values (\N,'phu','Public Health Units','Public Health Units - needed for DHIR submissions',NULL,1,'oscar',now());
SET @lid = LAST_INSERT_ID();
insert into LookupListItem values (\N,@lid,'6','Grey Bruce Health Unit',1,1,'oscar',now());
insert into LookupListItem values (\N,@lid,'9','Huron County Health Unit',2,1,'oscar',now());
insert into LookupListItem values (\N,@lid,'11','Oxford County Public Health',3,1,'oscar',now());
insert into LookupListItem values (\N,@lid,'12','Simcoe Muskoka District Health Unit',4,1,'oscar',now());
insert into LookupListItem values (\N,@lid,'13','Hastings and Prince Edward Counties Health Unit',5,1,'oscar',now());
insert into LookupListItem values (\N,@lid,'14','Peel Public Health',6,1,'oscar',now());
insert into LookupListItem values (\N,@lid,'15','Brant County Health Unit',7,1,'oscar',now());
insert into LookupListItem values (\N,@lid,'16','Leeds, Grenville and Lanark District Health Unit',8,1,'oscar',now());
insert into LookupListItem values (\N,@lid,'17','Chatham-Kent Public Health Unit',9,1,'oscar',now());
insert into LookupListItem values (\N,@lid,'18','Eastern Ontario Health Unit',10,1,'oscar',now());
insert into LookupListItem values (\N,@lid,'19','Wellington-Dufferin-Guelph Public Health',11,1,'oscar',now());
insert into LookupListItem values (\N,@lid,'20','Hamilton Public Health services',12,1,'oscar',now());
insert into LookupListItem values (\N,@lid,'21','Northwestern Health Unit',13,1,'oscar',now());
insert into LookupListItem values (\N,@lid,'22','Kingston, Frontenac and Lennox & Addington Public Health',14,1,'oscar',now());
insert into LookupListItem values (\N,@lid,'23','Middlesex-London Health Unit',15,1,'oscar',now());
insert into LookupListItem values (\N,@lid,'24','Timiskaming Health Unit',16,1,'oscar',now());
insert into LookupListItem values (\N,@lid,'25','York Region Public Health services',17,1,'oscar',now());
insert into LookupListItem values (\N,@lid,'26','North Bay Parry Sound District Health Unit',18,1,'oscar',now());
insert into LookupListItem values (\N,@lid,'27','Halton Region Health Department',19,1,'oscar',now());
insert into LookupListItem values (\N,@lid,'28','Ottawa Public Health',20,1,'oscar',now());
insert into LookupListItem values (\N,@lid,'29','Renfrew County and District Health Unit',21,1,'oscar',now());
insert into LookupListItem values (\N,@lid,'30','Peterborough Country-City Health Unit',22,1,'oscar',now());
insert into LookupListItem values (\N,@lid,'31','Lambton Public Health',23,1,'oscar',now());
insert into LookupListItem values (\N,@lid,'32','Haliburton, Kawartha, Pine Ridge District Health Unit',24,1,'oscar',now());
insert into LookupListItem values (\N,@lid,'33','Algoma Public Health Unit',25,1,'oscar',now());
insert into LookupListItem values (\N,@lid,'34','Haldimand-Norfolk Health Unit',26,1,'oscar',now());
insert into LookupListItem values (\N,@lid,'35','Elgin-St. Thomas Health Unit',27,1,'oscar',now());
insert into LookupListItem values (\N,@lid,'36','Perth District Health Unit',28,1,'oscar',now());
insert into LookupListItem values (\N,@lid,'40','Sudbury and District Health Unit',29,1,'oscar',now());
insert into LookupListItem values (\N,@lid,'41','Niagara Region Public Health Unit',30,1,'oscar',now());
insert into LookupListItem values (\N,@lid,'46','Thunder Bay District Health Unit',31,1,'oscar',now());
insert into LookupListItem values (\N,@lid,'54','Porcupine Health Unit',32,1,'oscar',now());
insert into LookupListItem values (\N,@lid,'55','Toronto Public Health',33,1,'oscar',now());
insert into LookupListItem values (\N,@lid,'56','Region of Waterloo, Public Health',34,1,'oscar',now());
insert into LookupListItem values (\N,@lid,'57','Durham Region Health Department',35,1,'oscar',now());
insert into LookupListItem values (\N,@lid,'58','Windsor-Essex County Health Unit',36,1,'oscar',now());

