alter table document add docClass varchar(60);
alter table document add docSubClass varchar(60);

create table ctl_doc_class (
  id integer auto_increment primary key,
  reportclass varchar(60) not null,
subclass varchar(60) not null);

insert into ctl_doc_class (reportclass,subclass) values ("Diagnostic Imaging Report","Abdomen X-Ray");
insert into ctl_doc_class (reportclass,subclass) values ("Diagnostic Imaging Report","Barium Enema");
insert into ctl_doc_class (reportclass,subclass) values ("Diagnostic Imaging Report","Bone Densitometry");
insert into ctl_doc_class (reportclass,subclass) values ("Diagnostic Imaging Report","Bone Scan");
insert into ctl_doc_class (reportclass,subclass) values ("Diagnostic Imaging Report","Brain Scan");
insert into ctl_doc_class (reportclass,subclass) values ("Diagnostic Imaging Report","Carotid Angiography");
insert into ctl_doc_class (reportclass,subclass) values ("Diagnostic Imaging Report","Carotid Doppler Ultrasound");
insert into ctl_doc_class (reportclass,subclass) values ("Diagnostic Imaging Report","Cervical Spine X-Ray");
insert into ctl_doc_class (reportclass,subclass) values ("Diagnostic Imaging Report","Chest X-Ray");
insert into ctl_doc_class (reportclass,subclass) values ("Diagnostic Imaging Report","Coronary Angiography");
insert into ctl_doc_class (reportclass,subclass) values ("Diagnostic Imaging Report","CT Scan Body");
insert into ctl_doc_class (reportclass,subclass) values ("Diagnostic Imaging Report","CT Scan Head");
insert into ctl_doc_class (reportclass,subclass) values ("Diagnostic Imaging Report","Echocardiogram");
insert into ctl_doc_class (reportclass,subclass) values ("Diagnostic Imaging Report","ERCP X-Ray");
insert into ctl_doc_class (reportclass,subclass) values ("Diagnostic Imaging Report","Hysterosalpingogram");
insert into ctl_doc_class (reportclass,subclass) values ("Diagnostic Imaging Report","IVP");
insert into ctl_doc_class (reportclass,subclass) values ("Diagnostic Imaging Report","Liver-Spleen Scan");
insert into ctl_doc_class (reportclass,subclass) values ("Diagnostic Imaging Report","Lumbar Spine X-Ray");
insert into ctl_doc_class (reportclass,subclass) values ("Diagnostic Imaging Report","Lung Scan");
insert into ctl_doc_class (reportclass,subclass) values ("Diagnostic Imaging Report","Mammogram");
insert into ctl_doc_class (reportclass,subclass) values ("Diagnostic Imaging Report","Misc. CT Scan");
insert into ctl_doc_class (reportclass,subclass) values ("Diagnostic Imaging Report","Misc. MRI Scan");
insert into ctl_doc_class (reportclass,subclass) values ("Diagnostic Imaging Report","Misc. Nuclear Scan");
insert into ctl_doc_class (reportclass,subclass) values ("Diagnostic Imaging Report","Misc. Ultrasound");
insert into ctl_doc_class (reportclass,subclass) values ("Diagnostic Imaging Report","Misc. X-Ray");
insert into ctl_doc_class (reportclass,subclass) values ("Diagnostic Imaging Report","MRI Scan Body");
insert into ctl_doc_class (reportclass,subclass) values ("Diagnostic Imaging Report","MRI Scan Head");
insert into ctl_doc_class (reportclass,subclass) values ("Diagnostic Imaging Report","Myelogram");
insert into ctl_doc_class (reportclass,subclass) values ("Diagnostic Imaging Report","Myoview)");
insert into ctl_doc_class (reportclass,subclass) values ("Diagnostic Imaging Report","Other Angiography");
insert into ctl_doc_class (reportclass,subclass) values ("Diagnostic Imaging Report","Retinal Angiography");
insert into ctl_doc_class (reportclass,subclass) values ("Diagnostic Imaging Report","Retinal Tomograph");
insert into ctl_doc_class (reportclass,subclass) values ("Diagnostic Imaging Report","Sestamibi");
insert into ctl_doc_class (reportclass,subclass) values ("Diagnostic Imaging Report","Sonohistogram");
insert into ctl_doc_class (reportclass,subclass) values ("Diagnostic Imaging Report","Stress Heart Scan (Thallium");
insert into ctl_doc_class (reportclass,subclass) values ("Diagnostic Imaging Report","UGI with Small Bowel");
insert into ctl_doc_class (reportclass,subclass) values ("Diagnostic Imaging Report","Ultrasound Abdomen");
insert into ctl_doc_class (reportclass,subclass) values ("Diagnostic Imaging Report","Ultrasound Breast");
insert into ctl_doc_class (reportclass,subclass) values ("Diagnostic Imaging Report","Ultrasound Obstetrical");
insert into ctl_doc_class (reportclass,subclass) values ("Diagnostic Imaging Report","Ultrasound Pelvis");
insert into ctl_doc_class (reportclass,subclass) values ("Diagnostic Imaging Report","Ultrasound Thyroid");
insert into ctl_doc_class (reportclass,subclass) values ("Diagnostic Imaging Report","Upper GI Series");
insert into ctl_doc_class (reportclass,subclass) values ("Diagnostic Imaging Report","Venous Doppler Ultrasound");

insert into ctl_doc_class (reportclass,subclass) values ("Diagnostic Test Reports","Ambulatory BP Monitoring");
insert into ctl_doc_class (reportclass,subclass) values ("Diagnostic Test Reports","Arterial Segmental Pressures (ABI)");
insert into ctl_doc_class (reportclass,subclass) values ("Diagnostic Test Reports","Audiogram");
insert into ctl_doc_class (reportclass,subclass) values ("Diagnostic Test Reports","Bronchoscopy");
insert into ctl_doc_class (reportclass,subclass) values ("Diagnostic Test Reports","Colonoscopy");
insert into ctl_doc_class (reportclass,subclass) values ("Diagnostic Test Reports","Colposcopy");
insert into ctl_doc_class (reportclass,subclass) values ("Diagnostic Test Reports","Cystoscopy");
insert into ctl_doc_class (reportclass,subclass) values ("Diagnostic Test Reports","Dobutamine)");
insert into ctl_doc_class (reportclass,subclass) values ("Diagnostic Test Reports","ECG");
insert into ctl_doc_class (reportclass,subclass) values ("Diagnostic Test Reports","EEG");
insert into ctl_doc_class (reportclass,subclass) values ("Diagnostic Test Reports","EGD-oscopy");
insert into ctl_doc_class (reportclass,subclass) values ("Diagnostic Test Reports","EMG");
insert into ctl_doc_class (reportclass,subclass) values ("Diagnostic Test Reports","Holter Monitor");
insert into ctl_doc_class (reportclass,subclass) values ("Diagnostic Test Reports","Loop Recorder");
insert into ctl_doc_class (reportclass,subclass) values ("Diagnostic Test Reports","Mantoux Test");
insert into ctl_doc_class (reportclass,subclass) values ("Diagnostic Test Reports","Misc. Diagnostic Test");
insert into ctl_doc_class (reportclass,subclass) values ("Diagnostic Test Reports","Pap Test Report");
insert into ctl_doc_class (reportclass,subclass) values ("Diagnostic Test Reports","Persantine");
insert into ctl_doc_class (reportclass,subclass) values ("Diagnostic Test Reports","Pulmonary Function Testing");
insert into ctl_doc_class (reportclass,subclass) values ("Diagnostic Test Reports","Sigmoidoscopy");
insert into ctl_doc_class (reportclass,subclass) values ("Diagnostic Test Reports","Sleep Study");
insert into ctl_doc_class (reportclass,subclass) values ("Diagnostic Test Reports","Stress Test (Exercise");
insert into ctl_doc_class (reportclass,subclass) values ("Diagnostic Test Reports","Urodynamic Testing");

insert into ctl_doc_class (reportclass,subclass) values ("Cardio Respiratory Report","Echocardiography Bubble Study");
insert into ctl_doc_class (reportclass,subclass) values ("Cardio Respiratory Report","Pericardiocentesis");
insert into ctl_doc_class (reportclass,subclass) values ("Cardio Respiratory Report","Echocardiography Esophageal");

insert into ctl_doc_class (reportclass,subclass) values ("Other Letters","Authorization from Patient");
insert into ctl_doc_class (reportclass,subclass) values ("Other Letters","Consent from Patient");
insert into ctl_doc_class (reportclass,subclass) values ("Other Letters","Disability Report");
insert into ctl_doc_class (reportclass,subclass) values ("Other Letters","Letter from Insurance Company");
insert into ctl_doc_class (reportclass,subclass) values ("Other Letters","Letter from Lawyer");
insert into ctl_doc_class (reportclass,subclass) values ("Other Letters","Letter from Patient");
insert into ctl_doc_class (reportclass,subclass) values ("Other Letters","Letter from WSIB");
insert into ctl_doc_class (reportclass,subclass) values ("Other Letters","Living Will");
insert into ctl_doc_class (reportclass,subclass) values ("Other Letters","Miscellaneous Letter");
insert into ctl_doc_class (reportclass,subclass) values ("Other Letters","Power of Attorney for Health Care");

insert into ctl_doc_class (reportclass,subclass) values ("ConsultA","Allergy & Immunology");
insert into ctl_doc_class (reportclass,subclass) values ("ConsultA","Anaesthesiology");
insert into ctl_doc_class (reportclass,subclass) values ("ConsultA","Audiology");
insert into ctl_doc_class (reportclass,subclass) values ("ConsultA","Cardiology");
insert into ctl_doc_class (reportclass,subclass) values ("ConsultA","Cardiovascular Surgery");
insert into ctl_doc_class (reportclass,subclass) values ("ConsultA","Chiropody / Podiatry");
insert into ctl_doc_class (reportclass,subclass) values ("ConsultA","Chiropractic");
insert into ctl_doc_class (reportclass,subclass) values ("ConsultA","Clinical Biochemistry");
insert into ctl_doc_class (reportclass,subclass) values ("ConsultA","Dentistry");
insert into ctl_doc_class (reportclass,subclass) values ("ConsultA","Dermatology");
insert into ctl_doc_class (reportclass,subclass) values ("ConsultA","Diagnostic Radiology");
insert into ctl_doc_class (reportclass,subclass) values ("ConsultA","Dietitian");
insert into ctl_doc_class (reportclass,subclass) values ("ConsultA","Emergency Medicine");
insert into ctl_doc_class (reportclass,subclass) values ("ConsultA","Emergency Physician");
insert into ctl_doc_class (reportclass,subclass) values ("ConsultA","Endocrinology");
insert into ctl_doc_class (reportclass,subclass) values ("ConsultA","Family Practice");
insert into ctl_doc_class (reportclass,subclass) values ("ConsultA","Gastroenterology");
insert into ctl_doc_class (reportclass,subclass) values ("ConsultA","General Surgery");
insert into ctl_doc_class (reportclass,subclass) values ("ConsultA","Genetics");
insert into ctl_doc_class (reportclass,subclass) values ("ConsultA","Geriatrics");
insert into ctl_doc_class (reportclass,subclass) values ("ConsultA","Hematology");
insert into ctl_doc_class (reportclass,subclass) values ("ConsultA","Hospitalis");
insert into ctl_doc_class (reportclass,subclass) values ("ConsultA","Infectious Disease");
insert into ctl_doc_class (reportclass,subclass) values ("ConsultA","Internal Medicine");
insert into ctl_doc_class (reportclass,subclass) values ("ConsultA","Kinesiology");
insert into ctl_doc_class (reportclass,subclass) values ("ConsultA","Microbiology");
insert into ctl_doc_class (reportclass,subclass) values ("ConsultA","Midwifery");
insert into ctl_doc_class (reportclass,subclass) values ("ConsultA","Naturopathy");
insert into ctl_doc_class (reportclass,subclass) values ("ConsultA","Neonatology");
insert into ctl_doc_class (reportclass,subclass) values ("ConsultA","Nephrology");
insert into ctl_doc_class (reportclass,subclass) values ("ConsultA","Neurology");
insert into ctl_doc_class (reportclass,subclass) values ("ConsultA","Neurosurgery");
insert into ctl_doc_class (reportclass,subclass) values ("ConsultA","Nuclear Medicine");
insert into ctl_doc_class (reportclass,subclass) values ("ConsultA","Nurse Practitioner");
insert into ctl_doc_class (reportclass,subclass) values ("ConsultA","Nursing");
insert into ctl_doc_class (reportclass,subclass) values ("ConsultA","Obstetrics & Gynecology");
insert into ctl_doc_class (reportclass,subclass) values ("ConsultA","Occupational Therapy");
insert into ctl_doc_class (reportclass,subclass) values ("ConsultA","On-Call Nurse");
insert into ctl_doc_class (reportclass,subclass) values ("ConsultA","On-Call Physician");
insert into ctl_doc_class (reportclass,subclass) values ("ConsultA","Oncology / Chemotherapy");
insert into ctl_doc_class (reportclass,subclass) values ("ConsultA","Ophthalmology");
insert into ctl_doc_class (reportclass,subclass) values ("ConsultA","Optometry");
insert into ctl_doc_class (reportclass,subclass) values ("ConsultA","Oral Surgery");
insert into ctl_doc_class (reportclass,subclass) values ("ConsultA","Orthopedic Surgery");
insert into ctl_doc_class (reportclass,subclass) values ("ConsultA","Osteopathy");
insert into ctl_doc_class (reportclass,subclass) values ("ConsultA","Other Consultant");
insert into ctl_doc_class (reportclass,subclass) values ("ConsultA","Other Therapy");
insert into ctl_doc_class (reportclass,subclass) values ("ConsultA","Otolaryngology (ENT)");
insert into ctl_doc_class (reportclass,subclass) values ("ConsultA","Paediatrics");
insert into ctl_doc_class (reportclass,subclass) values ("ConsultA","Palliative Care");
insert into ctl_doc_class (reportclass,subclass) values ("ConsultA","Pathology");
insert into ctl_doc_class (reportclass,subclass) values ("ConsultA","Pharmacology");
insert into ctl_doc_class (reportclass,subclass) values ("ConsultA","Physical Medicine");
insert into ctl_doc_class (reportclass,subclass) values ("ConsultA","Physiotherapy");
insert into ctl_doc_class (reportclass,subclass) values ("ConsultA","Plastic Surgery");
insert into ctl_doc_class (reportclass,subclass) values ("ConsultA","Psychiatry");
insert into ctl_doc_class (reportclass,subclass) values ("ConsultA","Psychology");
insert into ctl_doc_class (reportclass,subclass) values ("ConsultA","Respiratory Technology");
insert into ctl_doc_class (reportclass,subclass) values ("ConsultA","Respirology");
insert into ctl_doc_class (reportclass,subclass) values ("ConsultA","Rheumatology");
insert into ctl_doc_class (reportclass,subclass) values ("ConsultA","Social Work");
insert into ctl_doc_class (reportclass,subclass) values ("ConsultA","Speech Therapy");
insert into ctl_doc_class (reportclass,subclass) values ("ConsultA","Sports Medicine");
insert into ctl_doc_class (reportclass,subclass) values ("ConsultA","Therapeutic Radiology");
insert into ctl_doc_class (reportclass,subclass) values ("ConsultA","Thoracic Surgery");
insert into ctl_doc_class (reportclass,subclass) values ("ConsultA","Urgent Care/Walk-In Clinic Physician");
insert into ctl_doc_class (reportclass,subclass) values ("ConsultA","Uro-Gynecology");
insert into ctl_doc_class (reportclass,subclass) values ("ConsultA","Urology");
insert into ctl_doc_class (reportclass,subclass) values ("ConsultA","Vascular Surgery");

insert into ctl_doc_class (reportclass,subclass) values ("ConsultB","Admission History");
insert into ctl_doc_class (reportclass,subclass) values ("ConsultB","Consultation");
insert into ctl_doc_class (reportclass,subclass) values ("ConsultB","Discharge Summary");
insert into ctl_doc_class (reportclass,subclass) values ("ConsultB","Encounter Report");
insert into ctl_doc_class (reportclass,subclass) values ("ConsultB","Operative Report");
insert into ctl_doc_class (reportclass,subclass) values ("ConsultB","Progress Report");

alter table allergies add position int(10) not null;

insert into `secRole` (role_name, description) values('Counselling Intern', 'Counselling Intern');

insert into `secObjPrivilege` values('Counselling Intern','_appointment','x',0,'999998');
insert into `secObjPrivilege` values('Counselling Intern','_casemgmt.issues','x',0,'999998');
insert into `secObjPrivilege` values('Counselling Intern','_casemgmt.notes','x',0,'999998');
insert into `secObjPrivilege` values('Counselling Intern','_demographic','x',0,'999998');
insert into `secObjPrivilege` values('Counselling Intern','_eChart','x',0,'999998');
insert into `secObjPrivilege` values('Counselling Intern','_eChart.verifyButton','x',0,'999998');
insert into `secObjPrivilege` values('Counselling Intern','_flowsheet','x',0,'999998');
insert into `secObjPrivilege` values('Counselling Intern','_masterLink','x',0,'999998');
insert into `secObjPrivilege` values('Counselling Intern','_pmm.agencyInformation','x',0,'999998');
insert into `secObjPrivilege` values('Counselling Intern','_pmm.caseManagement','x',0,'999998');
insert into `secObjPrivilege` values('Counselling Intern','_pmm.clientSearch','x',0,'999998');
insert into `secObjPrivilege` values('Counselling Intern','_pmm.mergeRecords','x',0,'999998');
insert into `secObjPrivilege` values('Counselling Intern','_pmm.newClient','x',0,'999998');
insert into `secObjPrivilege` values('Counselling Intern','_tasks','x',0,'999998');

insert into access_type (name, type) values("read ticklers assigned to a Counselling Intern","access");
insert into access_type (name, type) values("write Counselling Intern issues","access");
insert into access_type (name, type) values("read Counselling Intern issues","access");
insert into access_type (name, type) values("read Counselling Intern notes","access");

insert into default_role_access (role_id,access_id) values ((select role_no from secRole where role_name='Counselling Intern'),(select access_id from access_type where name='read ticklers assigned to a Counselling Intern'));
insert into default_role_access (role_id,access_id) values ((select role_no from secRole where role_name='Counselling Intern'),(select access_id from access_type where name='read Counselling Intern issues'));
insert into default_role_access (role_id,access_id) values ((select role_no from secRole where role_name='Counselling Intern'),(select access_id from access_type where name='write Counselling Intern issues'));
insert into default_role_access (role_id,access_id) values ((select role_no from secRole where role_name='Counselling Intern'),(select access_id from access_type where name='read Counselling Intern notes'));

insert into default_role_access (role_id,access_id) values ((select role_no from secRole where role_name ='Counselling Intern'),(select access_id from access_type where name='read ticklers assigned to a Counselling Intern'));
insert into default_role_access (role_id,access_id) values ((select role_no from secRole where role_name ='Counselling Intern'),(select access_id from access_type where name='read Counselling Intern issues'));
insert into default_role_access (role_id,access_id) values ((select role_no from secRole where role_name ='Counselling Intern'),(select access_id from access_type where name='write Counselling Intern issues'));
insert into default_role_access (role_id,access_id) values ((select role_no from secRole where role_name ='Counselling Intern'),(select access_id from access_type where name='read Counselling Intern notes'));

insert into default_role_access (role_id,access_id) values ((select role_no from secRole where role_name ='Counselling Intern'),(select access_id from access_type where name='read ticklers assigned to a Clinical Assistant'));
insert into default_role_access (role_id,access_id) values ((select role_no from secRole where role_name ='Counselling Intern'),(select access_id from access_type where name='read Clinical Assistant issues'));
insert into default_role_access (role_id,access_id) values ((select role_no from secRole where role_name ='Counselling Intern'),(select access_id from access_type where name='write Clinical Assistant issues'));
insert into default_role_access (role_id,access_id) values ((select role_no from secRole where role_name ='Counselling Intern'),(select access_id from access_type where name='read Clinical Assistant notes'));

insert into default_role_access (role_id,access_id) values ((select role_no from secRole where role_name ='Counselling Intern'),(select access_id from access_type where name='read ticklers assigned to a Medical Secretary'));
insert into default_role_access (role_id,access_id) values ((select role_no from secRole where role_name ='Counselling Intern'),(select access_id from access_type where name='read Medical Secretary issues'));
insert into default_role_access (role_id,access_id) values ((select role_no from secRole where role_name ='Counselling Intern'),(select access_id from access_type where name='write Medical Secretary issues'));
insert into default_role_access (role_id,access_id) values ((select role_no from secRole where role_name ='Counselling Intern'),(select access_id from access_type where name='read Medical Secretary notes'));

insert into default_role_access (role_id,access_id) values ((select role_no from secRole where role_name ='Counselling Intern'),(select access_id from access_type where name='read ticklers assigned to a secretary'));
insert into default_role_access (role_id,access_id) values ((select role_no from secRole where role_name ='Counselling Intern'),(select access_id from access_type where name='read secretary issues'));
insert into default_role_access (role_id,access_id) values ((select role_no from secRole where role_name ='Counselling Intern'),(select access_id from access_type where name='write secretary issues'));
insert into default_role_access (role_id,access_id) values ((select role_no from secRole where role_name ='Counselling Intern'),(select access_id from access_type where name='read secretary notes'));

insert into default_role_access (role_id,access_id) values ((select role_no from secRole where role_name ='Counselling Intern'),(select access_id from access_type where name='Write Ticklers'));
insert into default_role_access (role_id,access_id) values ((select role_no from secRole where role_name ='Counselling Intern'),(select access_id from access_type where name='oscarcomm'));
insert into default_role_access (role_id,access_id) values ((select role_no from secRole where role_name ='Counselling Intern'),(select access_id from access_type where name='medical form'));
insert into default_role_access (role_id,access_id) values ((select role_no from secRole where role_name ='Counselling Intern'),(select access_id from access_type where name='measurements'));
insert into default_role_access (role_id,access_id) values ((select role_no from secRole where role_name ='Counselling Intern'),(select access_id from access_type where name='eform'));
insert into default_role_access (role_id,access_id) values ((select role_no from secRole where role_name ='Counselling Intern'),(select access_id from access_type where name='master file'));
insert into default_role_access (role_id,access_id) values ((select role_no from secRole where role_name ='Counselling Intern'),(select access_id from access_type where name='read ticklers'));
insert into default_role_access (role_id,access_id) values ((select role_no from secRole where role_name ='Counselling Intern'),(select access_id from access_type where name='Perform program registration intake'));
insert into default_role_access (role_id,access_id) values ((select role_no from secRole where role_name ='Counselling Intern'),(select access_id from access_type where name='perform registration intake'));
insert into default_role_access (role_id,access_id) values ((select role_no from secRole where role_name ='Counselling Intern'),(select access_id from access_type where name='perform admissions'));
insert into default_role_access (role_id,access_id) values ((select role_no from secRole where role_name ='Counselling Intern'),(select access_id from access_type where name='perform discharges'));
insert into default_role_access (role_id,access_id) values ((select role_no from secRole where role_name ='Counselling Intern'),(select access_id from access_type where name='perform bed assignments'));
insert into default_role_access (role_id,access_id) values ((select role_no from secRole where role_name ='Counselling Intern'),(select access_id from access_type where name='print bed rosters and reports'));


insert into default_role_access (role_id,access_id) values ((select role_no from secRole where role_name ='Case Manager'),(select access_id from access_type where name='read Counselling Intern notes'));
insert into default_role_access (role_id,access_id) values ((select role_no from secRole where role_name ='counsellor'),(select access_id from access_type where name='read Counselling Intern notes'));
