ALTER TABLE EyeformConsultationReport add column contactId varchar(100);
ALTER TABLE EyeformConsultationReport add column contact_type INT(10);
ALTER TABLE EyeformConsultationReport add column otherReferralId INT(11);
ALTER TABLE EyeformConsultationReport add column siteId INT(11);
ALTER TABLE `EyeformSpecsHistory` ADD COLUMN `note` VARCHAR(254) AFTER `appointmentNo`;
ALTER TABLE EyeformFollowUp MODIFY COLUMN timespan VARCHAR(6);


-- transfer eyeform v2 data to v3

UPDATE measurements SET `type` = 'v_rs' WHERE `type` = 'od_ar_sph';
UPDATE measurements SET `type` = 'v_rc' WHERE `type` = 'od_ar_cyl';
UPDATE measurements SET `type` = 'v_rx' WHERE `type` = 'od_ar_axis';
UPDATE measurements SET `type` = 'v_ls' WHERE `type` = 'os_ar_sph';
UPDATE measurements SET `type` = 'v_lc' WHERE `type` = 'os_ar_cyl';
UPDATE measurements SET `type` = 'v_lx' WHERE `type` = 'os_ar_axis';
UPDATE measurements SET `type` = 'v_rk1' WHERE `type` = 'od_k1';
UPDATE measurements SET `type` = 'v_rk2' WHERE `type` = 'od_k2';
UPDATE measurements SET `type` = 'v_rkx' WHERE `type` = 'od_k2_axis';
UPDATE measurements SET `type` = 'v_lk1' WHERE `type` = 'os_k1';
UPDATE measurements SET `type` = 'v_lk2' WHERE `type` = 'os_k2';
UPDATE measurements SET `type` = 'v_lkx' WHERE `type` = 'os_k2_axis';
UPDATE measurements SET `type` = 'v_rdsc' WHERE `type` = 'od_sc_distance';
UPDATE measurements SET `type` = 'v_rdcc' WHERE `type` = 'od_cc_distance';
UPDATE measurements SET `type` = 'v_rph' WHERE `type` = 'od_ph_distance';
UPDATE measurements SET `type` = 'v_ldsc' WHERE `type` = 'os_sc_distance';
UPDATE measurements SET `type` = 'v_ldcc' WHERE `type` = 'os_cc_distance';
UPDATE measurements SET `type` = 'v_lph' WHERE `type` = 'os_ph_distance';
UPDATE measurements SET `type` = 'v_rnsc' WHERE `type` = 'od_sc_near';
UPDATE measurements SET `type` = 'v_rncc' WHERE `type` = 'od_cc_near';
UPDATE measurements SET `type` = 'v_lnsc' WHERE `type` = 'os_sc_near';
UPDATE measurements SET `type` = 'v_lncc' WHERE `type` = 'os_cc_near';
UPDATE measurements SET `type` = 'v_rds' WHERE `type` = 'od_manifest_refraction_sph';
UPDATE measurements SET `type` = 'v_rdc' WHERE `type` = 'od_manifest_refraction_cyl';
UPDATE measurements SET `type` = 'v_rdx' WHERE `type` = 'od_manifest_refraction_axis';
UPDATE measurements SET `type` = 'v_rdv' WHERE `type` = 'od_manifest_distance';
UPDATE measurements SET `type` = 'v_lds' WHERE `type` = 'os_manifest_refraction_sph';
UPDATE measurements SET `type` = 'v_ldc' WHERE `type` = 'os_manifest_refraction_cyl';
UPDATE measurements SET `type` = 'v_ldx' WHERE `type` = 'os_manifest_refraction_axis';
UPDATE measurements SET `type` = 'v_ldv' WHERE `type` = 'os_manifest_distance';
UPDATE measurements SET `type` = 'v_rcs' WHERE `type` = 'od_cycloplegic_refraction_sph';
UPDATE measurements SET `type` = 'v_rcc' WHERE `type` = 'od_cycloplegic_refraction_cyl';
UPDATE measurements SET `type` = 'v_rcx' WHERE `type` = 'od_cycloplegic_refraction_axis';
UPDATE measurements SET `type` = 'v_rcv' WHERE `type` = 'od_cycloplegic_distance';
UPDATE measurements SET `type` = 'v_lcs' WHERE `type` = 'os_cycloplegic_refraction_sph';
UPDATE measurements SET `type` = 'v_lcc' WHERE `type` = 'os_cycloplegic_refraction_cyl';
UPDATE measurements SET `type` = 'v_lcx' WHERE `type` = 'os_cycloplegic_refraction_axis';
UPDATE measurements SET `type` = 'v_lcv' WHERE `type` = 'os_cycloplegic_distance';
UPDATE measurements SET `type` = 'iop_rn' WHERE `type` = 'od_iop_nct';
UPDATE measurements SET `type` = 'iop_ln' WHERE `type` = 'os_iop_nct';
UPDATE measurements SET `type` = 'iop_ra' WHERE `type` = 'od_iop_applanation';
UPDATE measurements SET `type` = 'iop_la' WHERE `type` = 'os_iop_applanation';
UPDATE measurements SET `type` = 'cct_r' WHERE `type` = 'od_cct';
UPDATE measurements SET `type` = 'cct_l' WHERE `type` = 'os_cct';
UPDATE measurements SET `type` = 'o_rcolour' WHERE `type` = 'od_color_vision';
UPDATE measurements SET `type` = 'o_rpupil' WHERE `type` = 'od_pupil';
UPDATE measurements SET `type` = 'o_ramsler' WHERE `type` = 'od_amsler_grid';
UPDATE measurements SET `type` = 'o_rpam' WHERE `type` = 'od_pam';
UPDATE measurements SET `type` = 'o_rconf' WHERE `type` = 'od_confrontation';
UPDATE measurements SET `type` = 'o_lcolour' WHERE `type` = 'os_color_vision';
UPDATE measurements SET `type` = 'o_lpupil' WHERE `type` = 'os_pupil';
UPDATE measurements SET `type` = 'o_lamsler' WHERE `type` = 'os_amsler_grid';
UPDATE measurements SET `type` = 'o_lpam' WHERE `type` = 'os_pam';
UPDATE measurements SET `type` = 'o_lconf' WHERE `type` = 'os_confrontation';
UPDATE measurements SET `type` = 'v_stereo' WHERE `type` = 'EOM';
UPDATE measurements SET `type` = 'a_rk' WHERE `type` = 'od_cornea';
UPDATE measurements SET `type` = 'a_rconj' WHERE `type` = 'od_conjuctiva_sclera';
UPDATE measurements SET `type` = 'a_rac' WHERE `type` = 'od_anterior_chamber';
UPDATE measurements SET `type` = 'a_rangle_1' WHERE `type` = 'od_angle_up';
UPDATE measurements SET `type` = 'a_rangle_2' WHERE `type` = 'od_angle_middle0';
UPDATE measurements SET `type` = 'a_rangle_3' WHERE `type` = 'od_angle_middle1';
UPDATE measurements SET `type` = 'a_rangle_4' WHERE `type` = 'od_angle_middle2';
UPDATE measurements SET `type` = 'a_rangle_5' WHERE `type` = 'od_angle_down';
UPDATE measurements SET `type` = 'a_riris' WHERE `type` = 'od_iris';
UPDATE measurements SET `type` = 'a_rlens' WHERE `type` = 'od_lens';
UPDATE measurements SET `type` = 'a_lk' WHERE `type` = 'os_cornea';
UPDATE measurements SET `type` = 'a_lconj' WHERE `type` = 'os_conjuctiva_sclera';
UPDATE measurements SET `type` = 'a_lac' WHERE `type` = 'os_anterior_chamber';
UPDATE measurements SET `type` = 'a_langle_1' WHERE `type` = 'os_angle_up';
UPDATE measurements SET `type` = 'a_langle_2' WHERE `type` = 'os_angle_middle0';
UPDATE measurements SET `type` = 'a_langle_3' WHERE `type` = 'os_angle_middle1';
UPDATE measurements SET `type` = 'a_langle_4' WHERE `type` = 'os_angle_middle2';
UPDATE measurements SET `type` = 'a_langle_5' WHERE `type` = 'os_angle_down';
UPDATE measurements SET `type` = 'a_liris' WHERE `type` = 'os_iris';
UPDATE measurements SET `type` = 'a_llens' WHERE `type` = 'os_lens';
UPDATE measurements SET `type` = 'p_rdisc' WHERE `type` = 'od_disc';
UPDATE measurements SET `type` = 'p_rcd' WHERE `type` = 'od_cd_ratio_horizontal';
UPDATE measurements SET `type` = 'p_rmac' WHERE `type` = 'od_macula';
UPDATE measurements SET `type` = 'p_rret' WHERE `type` = 'od_retina';
UPDATE measurements SET `type` = 'p_rvit' WHERE `type` = 'od_vitreous';
UPDATE measurements SET `type` = 'p_ldisc' WHERE `type` = 'os_disc';
UPDATE measurements SET `type` = 'p_lcd' WHERE `type` = 'os_cd_ratio_horizontal';
UPDATE measurements SET `type` = 'p_lmac' WHERE `type` = 'os_macula';
UPDATE measurements SET `type` = 'p_lret' WHERE `type` = 'os_retina';
UPDATE measurements SET `type` = 'p_lvit' WHERE `type` = 'os_vitreous';
UPDATE measurements SET `type` = 'ext_rface' WHERE `type` = 'od_face';
UPDATE measurements SET `type` = 'ext_rul' WHERE `type` = 'od_upper_lid';
UPDATE measurements SET `type` = 'ext_rll' WHERE `type` = 'od_lower_lid';
UPDATE measurements SET `type` = 'ext_rpunc' WHERE `type` = 'od_punctum';
UPDATE measurements SET `type` = 'ext_rlake' WHERE `type` = 'od_lacrimal_lake';
UPDATE measurements SET `type` = 'ext_lface' WHERE `type` = 'os_face';
UPDATE measurements SET `type` = 'ext_lul' WHERE `type` = 'os_upper_lid';
UPDATE measurements SET `type` = 'ext_lll' WHERE `type` = 'os_lower_lid';
UPDATE measurements SET `type` = 'ext_lpunc' WHERE `type` = 'os_punctum';
UPDATE measurements SET `type` = 'ext_llake' WHERE `type` = 'os_lacrimal_lake';
UPDATE measurements SET `type` = 'ext_rirrig' WHERE `type` = 'od_lacrimal_irrigation';
UPDATE measurements SET `type` = 'ext_rnld' WHERE `type` = 'od_nld';
UPDATE measurements SET `type` = 'ext_rdye' WHERE `type` = 'od_dye_disappearance';
UPDATE measurements SET `type` = 'ext_lirrig' WHERE `type` = 'os_lacrimal_irrigation';
UPDATE measurements SET `type` = 'ext_lnld' WHERE `type` = 'os_nld';
UPDATE measurements SET `type` = 'ext_ldye' WHERE `type` = 'os_dye_disappearance';
UPDATE measurements SET `type` = 'lid_rmrd' WHERE `type` = 'od_mrd';
UPDATE measurements SET `type` = 'lid_rlev' WHERE `type` = 'od_levator_function';
UPDATE measurements SET `type` = 'lid_riss' WHERE `type` = 'od_inferior_scleral_show';
UPDATE measurements SET `type` = 'lid_rcn7' WHERE `type` = 'od_cn_vii';
UPDATE measurements SET `type` = 'lid_rblink' WHERE `type` = 'od_blink';
UPDATE measurements SET `type` = 'lid_rbell' WHERE `type` = 'od_bells';
UPDATE measurements SET `type` = 'lid_rlag' WHERE `type` = 'od_lagophthalmos';
UPDATE measurements SET `type` = 'lid_lmrd' WHERE `type` = 'os_mrd';
UPDATE measurements SET `type` = 'lid_llev' WHERE `type` = 'os_levator_function';
UPDATE measurements SET `type` = 'lid_liss' WHERE `type` = 'os_inferior_scleral_show';
UPDATE measurements SET `type` = 'lid_lcn7' WHERE `type` = 'os_cn_vii';
UPDATE measurements SET `type` = 'lid_lblink' WHERE `type` = 'os_blink';
UPDATE measurements SET `type` = 'lid_lbell' WHERE `type` = 'os_bells';
UPDATE measurements SET `type` = 'lid_llag' WHERE `type` = 'os_lagophthalmos';
UPDATE measurements SET `type` = 'ext_rhertel' WHERE `type` = 'od_hertel';
UPDATE measurements SET `type` = 'ext_rretro' WHERE `type` = 'od_retropulsion';
UPDATE measurements SET `type` = 'ext_lhertel' WHERE `type` = 'os_hertel';
UPDATE measurements SET `type` = 'ext_lretro' WHERE `type` = 'os_retropulsion';



