//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-558 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.06.03 at 01:48:51 AM EDT 
//


package org.oscarehr.hospitalReportManager.xsd;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{cds}PatientRecord"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "patientRecord"
})
@XmlRootElement(name = "OmdCds", namespace = "cds")
public class OmdCds {

    @XmlElement(name = "PatientRecord", namespace = "cds", required = true)
    protected PatientRecord patientRecord;

    /**
     * Gets the value of the patientRecord property.
     * 
     * @return
     *     possible object is
     *     {@link PatientRecord }
     *     
     */
    public PatientRecord getPatientRecord() {
        return patientRecord;
    }

    /**
     * Sets the value of the patientRecord property.
     * 
     * @param value
     *     allowed object is
     *     {@link PatientRecord }
     *     
     */
    public void setPatientRecord(PatientRecord value) {
        this.patientRecord = value;
    }

}
