<?xml version="1.0"?>



<rule-set name="DiabetesACR"
          xmlns="http://drools.org/rules"
          xmlns:java="http://drools.org/semantics/java"
          xmlns:xs="http://www.w3.org/2001/XMLSchema-instance"
          xs:schemaLocation="http://drools.org/rules rules.xsd
                             http://drools.org/semantics/java java.xsd">

    <rule name="ACR 1">
        <parameter identifier="m">
            <class>oscar.oscarEncounter.oscarMeasurements.util.MeasurementDSHelper</class>
        </parameter>
        <java:condition>m.isMale() == true </java:condition>       
        <java:condition>m.getDataAsDouble() &gt;= 2.0</java:condition> 
        <java:consequence>     
              m.log("ACR RULES IS GETTING RUN");
              m.setIndicationColor("HIGH");
        </java:consequence>
    </rule>

    <rule name="ACR 2">
        <parameter identifier="m">
            <class>oscar.oscarEncounter.oscarMeasurements.util.MeasurementDSHelper</class>
        </parameter>
        <java:condition>m.isFemale() == true </java:condition>       
        <java:condition>m.getDataAsDouble() &gt;= 2.0</java:condition> 
        <java:consequence>     
              m.log("ACR RULES IS GETTING RUN");
              m.setIndicationColor("HIGH");
        </java:consequence>
    </rule>

    
</rule-set>


