<?xml version="1.0"?>



<rule-set name="DiabetesHCHDL"
          xmlns="http://drools.org/rules"
          xmlns:java="http://drools.org/semantics/java"
          xmlns:xs="http://www.w3.org/2001/XMLSchema-instance"
          xs:schemaLocation="http://drools.org/rules rules.xsd
                             http://drools.org/semantics/java java.xsd">

    <rule name="HCHDL 1">
        <parameter identifier="m">
            <class>oscar.oscarEncounter.oscarMeasurements.util.MeasurementDSHelper</class>
        </parameter>
        <java:condition>m.getDataAsDouble() &gt;= 4.0</java:condition>       
        <java:condition>m.getDataAsDouble() &lt; 5.0</java:condition> 
        <java:consequence>     
              m.log("HCHDL 1 RULES IS GETTING RUN");
              m.setIndicationColor("HIGH");
        </java:consequence>
    </rule>

    <rule name="HCHDL 2">
        <parameter identifier="m">
            <class>oscar.oscarEncounter.oscarMeasurements.util.MeasurementDSHelper</class>
        </parameter>      
        <java:condition>m.getDataAsDouble() &gt;= 5.0</java:condition> 
        <java:consequence>     
              m.log("HCHDL 2 RULES IS GETTING RUN");
              m.setIndicationColor("HIGH 1");
        </java:consequence>
    </rule>

   

</rule-set>


