<?xml version="1.0"?>



<rule-set name="DiabetesA1C"
          xmlns="http://drools.org/rules"
          xmlns:java="http://drools.org/semantics/java"
          xmlns:xs="http://www.w3.org/2001/XMLSchema-instance"
          xs:schemaLocation="http://drools.org/rules rules.xsd
                             http://drools.org/semantics/java java.xsd">

    <rule name="A1C">
        <parameter identifier="m">
            <class>oscar.oscarEncounter.oscarMeasurements.util.MeasurementDSHelper</class>
        </parameter>
        <java:condition>m.getDataAsDouble() &gt;= 7</java:condition>       
        <java:consequence>     
              m.log("A1C RULES IS GETTING RUN");
              m.setIndicationColor("HIGH");
        </java:consequence>
    </rule>

    <rule name="A1C2">
        <parameter identifier="m">
            <class>oscar.oscarEncounter.oscarMeasurements.util.MeasurementDSHelper</class>
        </parameter>
        <java:condition>m.getDataAsDouble() &lt;= 2</java:condition>   
        <java:condition>m.getDataAsDouble() &gt;= 0.07</java:condition>    
        <java:consequence>     
              m.log("A1C RULES IS GETTING RUN");
              m.setIndicationColor("HIGH");
        </java:consequence>
    </rule>

</rule-set>


