<?xml version="1.0"?>



<rule-set name="ReportA1C"
          xmlns="http://drools.org/rules"
          xmlns:java="http://drools.org/semantics/java"
          xmlns:xs="http://www.w3.org/2001/XMLSchema-instance"
          xs:schemaLocation="http://drools.org/rules rules.xsd
                             http://drools.org/semantics/java java.xsd">

    <rule name="LDL">
        <parameter identifier="m">
            <class>oscar.oscarEncounter.oscarMeasurements.util.MeasurementDSHelper</class>
        </parameter>
        <java:condition>m.setMeasurement("LDL") == true</java:condition>       
        <java:condition>m.getDataAsDouble() &lt; 2.0</java:condition>       
        <java:consequence>     
              m.log("LDL RULES IS GETTING RUN"+m.getDataAsDouble());
              m.setInRange(true);
        </java:consequence>
    </rule>

</rule-set>


