<?xml version="1.0"?>



<rule-set name="DiabetesTG"
          xmlns="http://drools.org/rules"
          xmlns:java="http://drools.org/semantics/java">

    <rule name="TG 1">
        <parameter identifier="m">
            <class>oscar.oscarEncounter.oscarMeasurements.util.MeasurementDSHelper</class>
        </parameter>       
        <java:condition>m.getDataAsDouble() &gt;= 2.0</java:condition> 
        <java:consequence>     
              System.out.println("TG RULES IS GETTING RUN");           
              m.setIndicationColor("HIGH");
        </java:consequence>
    </rule>
    
</rule-set>


