<?xml version="1.0"?>



<rule-set name="DiabetesEFGR"
          xmlns="http://drools.org/rules"
          xmlns:java="http://drools.org/semantics/java"
          xmlns:xs="http://www.w3.org/2001/XMLSchema-instance"
          xs:schemaLocation="http://drools.org/rules rules.xsd
                             http://drools.org/semantics/java java.xsd">

    <rule name="EFGR">
        <parameter identifier="m">
            <class>oscar.oscarEncounter.oscarMeasurements.util.MeasurementDSHelper</class>
        </parameter>      
        <java:condition>m.getDataAsDouble() &lt;= 60</java:condition> 
        <java:consequence>     
              m.log("ACR RULES IS GETTING RUN");
              m.setIndicationColor("LOW");
        </java:consequence>
    </rule>
    
</rule-set>


