<?xml version="1.0"?>



<rule-set name="ReportA1C"
          xmlns="http://drools.org/rules"
          xmlns:java="http://drools.org/semantics/java">

    <rule name="LDL">
        <parameter identifier="m">
            <class>oscar.oscarEncounter.oscarMeasurements.util.MeasurementDSHelper</class>
        </parameter>
        <java:condition>m.setMeasurement("LDL") == true</java:condition>       
        <java:condition>m.getDataAsDouble() &lt; 2.6</java:condition>       
        <java:consequence>     
              System.out.println("LDL RULES IS GETTING RUN"+m.getDataAsDouble());           
              m.setInRange(true);
        </java:consequence>
    </rule>

</rule-set>


