#!/bin/sh
# postrm
# a script file for OSCAR that uninstalls and tweaks the necessary files
#=================================================================
# Copyright Peter Hutten-Czapski 2012-14 released under the GPL v2
#=================================================================

# Source debconf library.
. /usr/share/debconf/confmodule

# PROGRAM matches the war and properties name
PROGRAM=oscar
PACKAGE=oscar-emr
db_name=oscar_14
VERSION=14
PREVIOUS=12_1
REVISION=0.2
TOMCAT="tomcat7"
C_HOME=/usr/share/${TOMCAT}/
C_BASE=/var/lib/${TOMCAT}/
SRC=/usr/share/${PACKAGE}/
db_password=liyi
DOCS=OscarDocument

LOG_FILE=${SRC}Oscar${VERSION}install.log
LOG_ERR=${SRC}Oscar.err

# --- log the running of the script appending as necessary
echo "#########" `date` "#########" 1>> $LOG_FILE
echo PostRemoval script triggered with $1>>$LOG_FILE
echo VERSION=${VERSION}-${REVISION}>>$LOG_FILE
echo "#########" `date` "#########" 1>> $LOG_ERR
echo PostRemoval script triggered with $1>>$LOG_ERR
echo VERSION=${VERSION}-${REVISION}>>$LOG_ERR

case "$1" in
    purge)
        # ignore errors and remove patient data in doing purge
        set +e
	# remove property files but extract the password first
	if [ -f "${C_HOME}${PROGRAM}.properties" ]; then
		#first grep the password
		echo "grep the password from the properties file" 2>>$LOG_ERR
		db_password=$(sed '/^\#/d' ${C_HOME}${PROGRAM}.properties | grep 'db_password'  | tail -n 1 | cut -d "=" -f2- | sed 's/^[[:space:]]*//;s/[[:space:]]*$//') 1>>$LOG_FILE
		echo "Deleting ${PROGRAM}.properties"
		rm -f ${C_HOME}${PROGRAM}.properties 2>>$LOG_ERR
	fi

	# remove drugref explicitly
	if [ -f "${C_BASE}webapps/drugref.war" ]; then
		echo "Purging drugref.war"
		rm -f ${C_BASE}webapps/drugref.war 2>>$LOG_ERR
	fi
	echo "Dropping drugref"
	mysql -u root -p${db_password} --execute="drop database if exists drugref;"  2>>$LOG_ERR

	# remove oscar web app regardless
	if [ -f "${C_BASE}webapps/${PROGRAM}.war" ]; then
		echo "Purging ${PROGRAM}.war"
		rm -f ${C_BASE}webapps/${PROGRAM}.war 2>>$LOG_ERR
	fi

	#...and its database WHICH CONTAINS PATIENT DATA
	echo "Dropping ${db_name}"
	mysql -u root -p${db_password} --execute="drop database if exists ${db_name};"  2>>$LOG_ERR
      
	# remove OscarDocument.war as that will have Tomcat delete its directory WHICH CONTAINS PATIENT DATA
	if [ -f "${C_BASE}webapps/OscarDocument.war" ]; then
		echo "Purging OscarDocument.war"
		rm -f ${C_BASE}webapps/OscarDocument.war 2>>$LOG_ERR
	else
		# if no OscarDocument war there still may be a directory WHICH CONTAINS PATIENT DATA
		if [ -d "${C_BASE}webapps/OscarDocument/" ]; then
			echo "Deleting OscarDocument directory"
			rm -f -R ${C_BASE}webapps/OscarDocument/ 2>>$LOG_ERR
		fi
	fi
	
	#remove the shared directory and its contents
	echo "Deleting ${SRC}"
	rm -f -R ${SRC}

    ;;

    remove|upgrade|failed-upgrade|abort-install|abort-upgrade|disappear)
        # Nothing to do here
    ;;

    *)
        echo "$0 called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

exit 0
