
--
-- Table structure for table `measurementMap`
--

DROP TABLE IF EXISTS `measurementMap`;
CREATE TABLE `measurementMap` (
  `id` int(10) NOT NULL auto_increment,
  `loinc_code` varchar(20) default NULL,
  `ident_code` varchar(20) NOT NULL,
  `name` varchar(255) NOT NULL,
  `lab_type` varchar(10) NOT NULL,
  PRIMARY KEY  (`id`),
  KEY `ident_code` (`ident_code`)
) ;

--
-- Dumping data for table `measurementMap`
--

LOCK TABLES `measurementMap` WRITE;
/*!40000 ALTER TABLE `measurementMap` DISABLE KEYS */;

insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('14646-4','14646-4','HDL Cholesterol','PATHL7');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('1963-8','1963-8','Bicarbonate','PATHL7');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('2075-0','2075-0','Chloride ','PATHL7');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('1988-5','1988-5','CRP','PATHL7');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('14647-2','14647-2','Cholesterol ','PATHL7');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('14771-0','14771-0','Glucose Fasting','PATHL7');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('X438','X438','Result','PATHL7');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('X504','X504','Result ','PATHL7');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('X503','X503','Result','PATHL7');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('5193-8','5193-8','Hep B Surface Antibody (HBsAb)','PATHL7');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('17871-5','17871-5','HB H Bodies','PATHL7');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('X502','X502','Result ','PATHL7');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('2857-1','2857-1','PSA  ','PATHL7');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('X433','X433','Organism 1  ','PATHL7');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('X805','X805','Comment','PATHL7');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('13965-9','13965-9','Homocysteine','PATHL7');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('2532-0','2532-0','LD ','PATHL7');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('1920-8','1920-8','AST ','PATHL7');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('14913-8','14913-8','Testosterone','PATHL7');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('X10025','X10025','Comment','PATHL7');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('1742-6','1742-6','ALT  ','PATHL7');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('X10019','X10019','Organism 2','PATHL7');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('6768-6','6768-6','Alkaline Phosphatase ','PATHL7');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('363-2','363-2','Nitrofurantoin','PATHL7');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('14631-6','14631-6','Total Bilirubin','PATHL7');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('496-0','496-0','Tetracycline ','PATHL7');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('14933-6','14933-6','Uric Acid  ','PATHL7');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('267-5','267-5','Gentamicin','PATHL7');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('33914-3','33914-3','Estimated GFR','PATHL7');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('516-5','516-5','Trimethoprim-Sulfa ','PATHL7');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('14682-9','14682-9','Creatinine','PATHL7');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('X10042','X10042','Cephalothin/Cephalexin','PATHL7');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('2276-4','2276-4','Ferritin ','PATHL7');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('704-7','704-7','Basophils','PATHL7');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('28-1','28-1','Ampicillin ','PATHL7');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('711-2','711-2','Eosinophils','PATHL7');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('5774-5','5774-5','Calcium Oxalate','PATHL7');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('742-7','742-7','Monocytes ','PATHL7');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('731-0','731-0','Lymphocytes','PATHL7');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('13945-1','13945-1','RBC  ','PATHL7');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('751-8','751-8','Neutrophils','PATHL7');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('14920-3','14920-3','Free T4     ','PATHL7');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('777-3','777-3','Platelet Count','PATHL7');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('788-0','788-0','RDW ','PATHL7');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('14565-6','14565-6','Occult Blood 3 ','PATHL7');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('786-4','786-4','MCHC','PATHL7');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('14564-9','14564-9','Occult Blood 2      ','PATHL7');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('14563-1','14563-1','Occult Blood 1     ','PATHL7');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('785-6','785-6','MCH','PATHL7');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('787-2','787-2','MCV  ','PATHL7');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('4544-3','4544-3','Hematocrit','PATHL7');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('X633','X633','Specific Allergen IgE','PATHL7');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('718-7','718-7','Hemoglobin ','PATHL7');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('789-8','789-8','RBC ','PATHL7');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('12227-5','6690-2','WBC','PATHL7');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('6248-9','6248-9','Soybean','PATHL7');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('6206-7','6206-7','Peanut','PATHL7');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('6276-0','6276-0','Wheat   ','PATHL7');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('6082-2','6082-2','Codfish ','PATHL7');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('6174-7','6174-7','Milk   ','PATHL7');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('6106-9','6106-9','Egg White','PATHL7');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('7426-0','7426-0','House Dust H-S ','PATHL7');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('6100-2','6100-2','Duck Feathers ','PATHL7');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('X10059','X10059','Seafood Mix (Cod, Shrimp, Crab, Tuna, Salmon)    ','PATHL7');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('6167-1','6167-1','Mango','PATHL7');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('6071-5','6071-5','Chicken   ','PATHL7');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('6125-9','6125-9','Gluten ','PATHL7');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('6219-0','6219-0','Pork  ','PATHL7');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('6230-7','6230-7','Rice  ','PATHL7');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('6095-4','6095-4','Derm.farinae ','PATHL7');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('6096-2','6096-2','Derm.pteronyssinus','PATHL7');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('22748-8','22748-8','LDL Cholesterol','PATHL7');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('X10045','X10045','Partner Name','PATHL7');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('9322-9','9322-9','Chol/HDL (Risk Ratio) ','PATHL7');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('16601-7','16601-7','Chlamydia trachomatis Nucleic Acid Amplification','PATHL7');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('xBCB 0101','xBCB 0101','Collection Date','PATHL7');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('14927-8','14927-8','Triglycerides  ','PATHL7');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('11288-8','11288-8','Received Time','PATHL7');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('14756-1','14756-1','Glucose 1h ','PATHL7');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('16600-9','16600-9','Chlamydia trachomatis Nucleic Acid Amplification  ','PATHL7');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('X10056','X10056','Complete Sample?','PATHL7');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('X041','X041','Collection to Testing Interval ','PATHL7');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('664-3','664-3','Gram Stain','PATHL7');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('10580-9','10580-9','Liquefaction ','PATHL7');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('14759-5','14759-5','Glucose 2h','PATHL7');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('X800','X800','Gram Stain','PATHL7');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('9631-3','9631-3','Viscosity','PATHL7');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('21613-5','21613-5','Chlamydia trachomatis Nucleic Acid Amplification','PATHL7');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('3160-9','3160-9','Volume','PATHL7');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('14765-2','14765-2','Glucose 3h','PATHL7');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('10331-7','-RH','Rh','MDS');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('8061-4','-AB','ANTIBODY SCREEN:','MDS');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('14663-9','14663-9','Colour','PATHL7');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('X801','X801','Gram Stain','PATHL7');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('5196-1','5196-1','Hep B Surface Antigen (HBsAg)','PATHL7');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('13628-3','13628-3','Motility','PATHL7');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('3255-7','3255-7','Fibrinogen','PATHL7');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('9780-8','9780-8','Concentration','PATHL7');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('10622-9','10622-9','Normal Forms','PATHL7');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('X10011','X10011','Pathologist Comments','PATHL7');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('14688-6','14688-6','DHEA Sulphate','PATHL7');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('X008','X008','Appearance','PATHL7');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('X047','X047','Kinetics','PATHL7');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('5778-6','5778-6','Colour','PATHL7');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('10595-7','10595-7','Total Sperm Count','PATHL7');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('14914-6','14914-6','Free Testosterone ','PATHL7');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('15376-7','15376-7','Abnormal Forms','PATHL7');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('5767-9','5767-9','Appearance/Clarity','PATHL7');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('10576-7','10576-7','Immature Forms','PATHL7');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('2756-5','2756-5','pH','PATHL7');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('14679-5','14679-5','AM Cortisol','PATHL7');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('5811-5','5811-5','Specific Gravity','PATHL7');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('X044','X044','Pathologist Comments (Semen)','PATHL7');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('5804-0','5804-0','Protein','PATHL7');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('14685-2','14685-2','Vitamin B12','PATHL7');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('14732-2','14732-2','Folate  ','PATHL7');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('2349-9','2349-9','Glucose','PATHL7');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('14754-6','14754-6','Glucose 1h (Gestational)','PATHL7');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('2514-8','2514-8','Ketones','PATHL7');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('14678-7','14678-7','PM Cortisol','PATHL7');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('5794-3','5794-3','Hemoglobin','PATHL7');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('5770-3','5770-3','Bilirubin','PATHL7');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('5818-0','5818-0','Urobilinogen','PATHL7');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('2157-6','2157-6','CK','PATHL7');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('5802-4','5802-4','Nitrite ','PATHL7');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('12227-5','12227-5','WBC ','PATHL7');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('5799-2','5799-2','Leukocytes  ','PATHL7');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('19261-7','19261-7','Amphetamines','PATHL7');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('4548-4','4548-4','Hemoglobin A1c','PATHL7');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('19270-8','19270-8','Barbiturates','PATHL7');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('6301-6','6301-6','INR','PATHL7');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('14316-4','14316-4','Benzodiazepines ','PATHL7');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('3393-6','3393-6','Cocaine','PATHL7');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('14798-3','14798-3','Iron','PATHL7');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('19295-5','19295-5','Opiates','PATHL7');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('14800-7','14800-7','TIBC ','PATHL7');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('3529-5','3529-5','Cannabinoid','PATHL7');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('14801-5','14801-5','Iron Saturation','PATHL7');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('xBCB 0017','xBCB 0017','Time Since Eating','PATHL7');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('5821-4','5821-4','WBC ','PATHL7');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('19151-0','19151-0','Collection Time','PATHL7');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('6742-1','6742-1','RBC Morphology','PATHL7');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('19088-4','19088-4','Collection Date ','PATHL7');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('X501','X501','Comment','PATHL7');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('5214-2','5214-2','Mono Test','PATHL7');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('14684-5','14684-5','Urine Creatinine','PATHL7');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('3016-3','3016-3','TSH','PATHL7');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('19153-6','19153-6','Urine Volume','PATHL7');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('2286-3','2286-3','FSH ','PATHL7');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('2579-1','2579-1','LH','PATHL7');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('13362-9','13362-9','Collection Interval','PATHL7');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('14935-1','14935-1','Urine Uric Acid  ','PATHL7');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('2842-3','2842-3','Prolactin ','PATHL7');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('14637-3','14637-3','Urine Calcium','PATHL7');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('14715-7','14715-7','Estradiol','PATHL7');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('14650-6','14650-6','Urine Citrate','PATHL7');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('X10002','X10002','Helicobacter Pylori','PATHL7');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('14862-7','14862-7','Urine Oxalate','PATHL7');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('21198-7','21198-7','HCG Serum','PATHL7');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('2885-2','2885-2','Total Protein ','PATHL7');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('14629-0','14629-0','Direct Bilirubin','PATHL7');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('2458-8','2458-8','IgA  ','PATHL7');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('2324-2','2324-2','Gamma GT','PATHL7');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('2951-2','2951-2','Sodium  ','PATHL7');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('31017-7','31017-7','Tissue Transglutaminase Antibody IgA','PATHL7');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('14749-6','14749-6','Glucose Random','PATHL7');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('2823-3','2823-3','Potassium ','PATHL7');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('197-4','197-4','Cloxacillin','PATHL7');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('14937-7','14937-7','Urea ','PATHL7');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('233-7','233-7','Erythromycin','PATHL7');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('14334-7','14334-7','Lithium','PATHL7');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('5803-2','5803-2','pH ','PATHL7');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('X10005','X10005','Time Since Med','PATHL7');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('5787-7','5787-7','Epithelial Cells','PATHL7');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('14869-2','14869-2','Pathologist Comments','PATHL7');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('19803-6','19803-6','Specimen Site','PATHL7');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('3034-6','3034-6','Transferrin ','PATHL7');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('6463-4','6463-4','Culture','PATHL7');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('2000-8','2000-8','Calcium','PATHL7');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('X1019','X1019','Free Testosterone Calculated ','PATHL7');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('14879-1','14879-1','Phosphorus ','PATHL7');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('X1020','X1020','Bioavailable Testosterone','PATHL7');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('1751-7','1751-7','Albumin','PATHL7');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('13967-5','13967-5','Sex Hormone Binding Globulin','PATHL7');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('14683-7','14683-7','Urine Creatinine','PATHL7');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('9318-7','9318-7','Urine ACR (Albumin/Creatinine Ratio)','PATHL7');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('2064-4','2064-4','Ceruloplasmin','PATHL7');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('11277-1','11277-1','Squamous Cells','PATHL7');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('5383-5','5383-5','Microsomal Ab','PATHL7');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('8247-9','8247-9','Mucus','PATHL7');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('15210-8','15210-8','Thyroglobulin Ab','PATHL7');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('X10020','X10020','Organism 3  ','PATHL7');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('X645','X645','CA 125','PATHL7');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('6875-9','6875-9','CA 15-3','PATHL7');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('X456','X456','C. difficile Toxin Assay','PATHL7');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('X450','X450','Culture','PATHL7');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('4537-7','4537-7','ESR','PATHL7');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('185-9','185-9','Ciprofloxacin','PATHL7');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('X10023','X10023','ANA Screen','PATHL7');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('15205-8','15205-8','RA Factor','PATHL7');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('X802','X802','Gram Stain ','PATHL7');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('11029-6','11029-6','Stool Macroscopic','PATHL7');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('10895-1','10895-1','C. difficile Toxin Assay ','PATHL7');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('xBCB 0004','xBCB 0004','Collection Date','PATHL7');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('9785-7','9785-7','Ova and Parasite Stool ','PATHL7');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('2465-3','2465-3','IgG ','PATHL7');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('2472-9','2472-9','IgM ','PATHL7');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('4485-9','4485-9','Complement C3','PATHL7');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('4498-2','4498-2','Complement C4','PATHL7');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('4551-8','4551-8','HB A2  ','PATHL7');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('X514','X514','HB HPLC ','PATHL7');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('5817-2','5817-2','Urate Crystals','PATHL7');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('14890-8','14890-8','Progesterone','PATHL7');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('X575','X575','Serum Pregnancy Test','PATHL7');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('14928-6','14928-6','Free T3','PATHL7');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('6092-1','6092-1','Crab  ','PATHL7');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('6165-5','6165-5','Lobster','PATHL7');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('6246-3','6246-3','Shrimp ','PATHL7');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('18309-5','18309-5','Nucleated RBC   ','PATHL7');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('14698-5','14698-5','Digoxin ','PATHL7');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('14866-8','14866-8','Parathyroid Hormone Intact','PATHL7');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('5356-1','5356-1','Sm','PATHL7');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('5301-7','5301-7','RNP','PATHL7');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('14630-8','14630-8','Neonatal Unconjugated Bilirubin','PATHL7');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('5351-2','5351-2','SSA ','PATHL7');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('2112-1','2112-1','Urine Pregnancy Test','PATHL7');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('5353-8','5353-8','SSB','PATHL7');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('11060-1','11060-1','Fecal Reducing Substances','PATHL7');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('5348-8','5348-8','Scl70 ','PATHL7');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('2755-7','2755-7','Fecal pH ','PATHL7');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('5234-0','5234-0','Jo-1','PATHL7');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('X464','X464','Transferrin Saturation','PATHL7');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('18482-0','18482-0','Yeast Culture   ','PATHL7');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('5796-8','5796-8','Hyaline Casts','PATHL7');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('149-5','149-5','Cephalexin','PATHL7');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('14753-8','14753-8','Glucose 1h ','PATHL7');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('4269-7','4269-7','Glucose Load','PATHL7');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('14764-5','14764-5','Glucose 3h','PATHL7');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('X10033','X10033','WBC ','PATHL7');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('14757-9','14757-9','Glucose 2h','PATHL7');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('X10010','X10010','Viability ','PATHL7');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('14731-4','14731-4','RBC Folate','PATHL7');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('2601-3','2601-3','Magnesium ','PATHL7');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('1995-0','1995-0','Calcium Ionized','PATHL7');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('30522-7','30522-7','CRP','PATHL7');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('1798-8','1798-8','Amylase','PATHL7');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('1869-7','1869-7','Apo A-1','PATHL7');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('6771-0','6771-0','A 1 Antitrypsin ','PATHL7');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('1871-3','1871-3','Apo B-100','PATHL7');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('20396-8','20396-8','Levofloxacin','PATHL7');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('X803','X803','Gram Stain','PATHL7');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('X446','X446','Result','PATHL7');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('335-0','335-0','Minocycline','PATHL7');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('5048-4','5048-4','ANA Titre and Pattern','PATHL7');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('14807-2','14807-2','Blood Lead','PATHL7');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('X441','X441','Result','PATHL7');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('14725-6','14725-6','Fluid Type','PATHL7');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('2532-0','14805-6','LD ','PATHL7');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('X40006','X40006','Fluid Appearance','PATHL7');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('3176-5','3176-5','Antithrombin','PATHL7');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('6743-9','6743-9','Fluid WBC','PATHL7');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('4671-4','4671-4','Protein C Activity ','PATHL7');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('9306-2','9306-2','Fluid Neutrophils ','PATHL7');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('5893-3','5893-3','Protein S Activity','PATHL7');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('9305-4','9305-4','Fluid Mononuclear Cells','PATHL7');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('X045','X045','Interpretation','PATHL7');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('21025-2','21025-2','Pathologist Comments (Fluid)','PATHL7');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('3181-5','3181-5','IgG (ACL)','PATHL7');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('3182-3','3182-3','IgM (ACL)','PATHL7');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('21667-1','21667-1','Factor V Leiden','PATHL7');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('6825-4','6825-4','Fluid Crystals','PATHL7');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('XBCB0226','XBCB0226','Prothrombin G20210A','PATHL7');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('2862-1','2862-1','Albumin','PATHL7');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('19139-5','19139-5','Pathologist Comments (Fluid)   ','PATHL7');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('14722-3','14722-3','ENA','PATHL7');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('2865-4','2865-4','Alpha 1 Globulin','PATHL7');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('2868-8','2868-8','Alpha 2 Globulin ','PATHL7');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('2871-2','2871-2','Beta Globulin ','PATHL7');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('24108-3','24108-3','CA 19-9 ','PATHL7');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('2874-6','2874-6','Gamma Globulin','PATHL7');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('5793-5','5793-5','Granular Casts','PATHL7');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('12851-2','12851-2','Pattern','PATHL7');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('X440','X440','Comment','PATHL7');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('16935-9','16935-9','Hep B surface Antibody (HBsAb)    ','PATHL7');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('145-3','145-3','Cefuroxime','PATHL7');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('189-1','189-1','Clarithromycin','PATHL7');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('76-0','76-0','Cefazolin','PATHL7');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('3281-3','3281-3','Lupus Anticoagulant','PATHL7');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('3040-3','3040-3','Lipase','PATHL7');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('X107','X107','Direct Antiglobulin Test','PATHL7');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('X488','X488','HLA B27','PATHL7');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('13445-2','13445-2','Corrected Creatinine Clearance 24h','PATHL7');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('367-3','367-3','Norfloxacin','PATHL7');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('5775-2','5775-2','Calcium Phosphate','PATHL7');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('748-4','748-4','Myelocytes','PATHL7');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('8099-4','8099-4','Anti-Thyroid Peroxidase','PATHL7');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('30240-6','30240-6','D-Dimer','PATHL7');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('9317-9','9317-9','Platelet Estimate','PATHL7');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('8677-7','8677-7','Dexamethasone ','PATHL7');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('682-5','682-5','Test Comments','PATHL7');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('14566-4','14566-4','1 25-(OH)2 Vitamin D','PATHL7');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('21419-7','21419-7','Immunofluorescence','PATHL7');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('10835-7','10835-7','Lipoprotein (a) ','PATHL7');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('2955-3','2955-3','Urine Sodium','PATHL7');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('6969-0','6969-0','MPO-ANCA','PATHL7');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('2828-2','2828-2','Urine Potassium','PATHL7');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('6968-2','6968-2','PR3-ANCA','PATHL7');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('2004-0','2004-0','Urine Calcium','PATHL7');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('X647','X647','25 (OH) Vitamin D ','PATHL7');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('3167-4','3167-4','Urine Volume','PATHL7');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('11140-1','11140-1','Urine Metanephrine 24h','PATHL7');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('15083-9','15083-9','Urine Normetanephrine 24h','PATHL7');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('14712-4','14712-4','Urine Epinephrine 24h','PATHL7');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('14854-4','14854-4','Urine Norepinephrine 24h','PATHL7');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('15059-9','15059-9','Urine Dopamine 24h','PATHL7');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('108-1','108-1','Cefotaxime','PATHL7');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('2889-4','2889-4','Urine Protein','PATHL7');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('408-5','408-5','Piperacillin','PATHL7');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('6565-6','6565-6','Trichomonas','PATHL7');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('2462-0','2462-0','IgE ','PATHL7');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('14603-5','14603-5','Androstenedione','PATHL7');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('12710-0','12710-0','HB HPLC ','PATHL7');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('X505','X505','Result','PATHL7');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('X506','X506','Result','PATHL7');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('13950-1','13950-1','Hep A Antibody IgM ','PATHL7');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('X507','X507','Result','PATHL7');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('13955-0','13955-0','Hepatitis C','PATHL7');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('X508','X508','Result','PATHL7');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('17284-1','17284-1','Mitochondrial Ab ','PATHL7');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('14877-5','14877-5','Phenytoin','PATHL7');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('5358-7','5358-7','Smooth Muscle Ab Titre  ','PATHL7');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('3173-2','3173-2','Activated PTT ','PATHL7');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('5117-7','5117-7','Cryglobulin','PATHL7');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('19177-5','19177-5','AFP ','PATHL7');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('14639-9','14639-9','Carbamazepine','PATHL7');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('2888-6','2888-6','Urine Protein','PATHL7');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('2890-2','2890-2','Urine Protein/Creatinine Ratio','PATHL7');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('4542-7','4542-7','Haptoglobin ','PATHL7');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('14252-1','14252-1','Smooth Muscle Ab','PATHL7');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('14241-4','14241-4','Parietal Cell Ab','PATHL7');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('13952-7','13952-7','Hep B Core Antibody (HBcAb)','PATHL7');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('3013-0','3013-0','Thyroglobulin','PATHL7');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('X30003','X30003','Comment','PATHL7');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('10839-9','10839-9','Troponin I','PATHL7');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('5130-0','5130-0','Anti-DNA ','PATHL7');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('23803-0','23803-0','Grass Mix (June, Rye, M.Fescue, Orchard, Timothy)','PATHL7');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('X995','X995','Mould Mix ','PATHL7');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('739-3','739-3','Metamyelocytes','PATHL7');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('17783-2','17783-2','Urine Hemosiderin','PATHL7');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('13954-3','13954-3','Hep Be Antigen','PATHL7');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('14770-2','14770-2','Glucose By Meter Fasting','PATHL7');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('X467','X467','D-PYR Crosslinks Urine Random','PATHL7');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('8061-4','8061-4','ANA Screen','PATHL7');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('xBCB 0033','xBCB 0033','Stool Eosinophils (one)  ','PATHL7');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('16933-4','16933-4','Hep B Core Antibody (HBcAb)','PATHL7');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('80-2','80-2','Cefixime','PATHL7');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('13655-6','13655-6','Fecal Leukocytes','PATHL7');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('23798-2','23798-2','Cat Hair Dander','PATHL7');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('X901','X901','Serum Osmolality','PATHL7');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('883-9','883-9','Blood Group ','PATHL7');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('10331-7','10331-7','Rh(D) Type','PATHL7');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('X902','X902','Urine Osmolality','PATHL7');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('X905','X905','Urine/Serum Osmolality Ratio','PATHL7');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('X994','X994','Mite Mix','PATHL7');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('X907','X907','C282Y Mutation','PATHL7');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('15284-3','15284-3','Gray Alder','PATHL7');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('X908','X908','H63D Mutation','PATHL7');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('15283-5','15283-5','Birch','PATHL7');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('5195-3','5195-3','Hep B Surface Antigen (HBsAg) ','PATHL7');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('xBCB 0010','xBCB 0010','Collection Time #1','PATHL7');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('X447','X447','Dermatophyte Culture','PATHL7');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('20-8','20-8','Amoxicillin-Clavulanate','PATHL7');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('580-1','580-1','Culture','PATHL7');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('6932-8','6932-8','Penicillin','PATHL7');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('21026-0','21026-0','Pathologist Blood Film Review','PATHL7');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('193-3','193-3','Clindamycin','PATHL7');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('X10009','X10009','HCG Serum ','PATHL7');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('524-9','524-9','Vancomycin','PATHL7');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('14196-0','14196-0','Reticulocytes','PATHL7');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('2555-8','2555-8','Zinc','PATHL7');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('14946-8','14946-8','Valproic Acid','PATHL7');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('20472-7','20472-7','Eosinophils ','PATHL7');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('20473-5','20473-5','Polymorphs','PATHL7');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('133-9','133-9','Ceftazidime','PATHL7');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('11279-7','11279-7','Test Comments (Urine)','PATHL7');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('15218-1','15218-1','Seafood Mix (Cod, Shrimp, Mussel, Tuna, Salmon)','PATHL7');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('6303-2','6303-2','DRVVT   ','PATHL7');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('X500','X500','Referred Test','PATHL7');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('667-6','667-6','KOH Preparation','PATHL7');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('X445','X445','Comment','PATHL7');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('14656-3','14656-3','Clozapine ','PATHL7');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('14851-0','14851-0','Norclozapine','PATHL7');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('45359-7','45359-7','Time Since Med  ','PATHL7');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('6844-5','6844-5','Honey Bee','PATHL7');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('6288-5','6288-5','Yellow Hornet','PATHL7');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('6740-5','6740-5','Yellow Jacket  ','PATHL7');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('6198-6','6198-6','Paper Wasp','PATHL7');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('6280-2','6280-2','White Faced Hornet ','PATHL7');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('7918-6','7918-6','HIV-1 HIV-2','PATHL7');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('20507-0','20507-0','Syphilis','PATHL7');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('1857-2','1857-2','ACE ','PATHL7');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('X50028','X50028','Hep A Ab IgM   ','PATHL7');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('X50060','X50060','Hep C Ab','PATHL7');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('X50045','X50045','HIV Serology ','PATHL7');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('14665-4','14665-4','Copper','PATHL7');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('X10021','X10021','Organism 4','PATHL7');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('4576-5','4576-5','HB F ','PATHL7');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('X900','X900','Urine Mercury 24h ','PATHL7');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('2335-8','2335-8','Occult Blood 1','PATHL7');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('36-4','36-4','Azithromycin','PATHL7');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('2963-7','2963-7','Growth Hormone','PATHL7');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('33358-3','33358-3','Protein Band 1 ','PATHL7');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('14895-7','14895-7','Immunofixation ','PATHL7');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('X062','X062','Urine Electrophoresis','PATHL7');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('X094','X094','Misc Hematology ','PATHL7');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('14896-5','14896-5','Urine Immunofixation','PATHL7');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('X090','X090','Sperm Spun Specimen','PATHL7');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('X472','X472','Aldosterone','PATHL7');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('X470','X470','Renin ','PATHL7');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('X1030','X1030','Insulin Random','PATHL7');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('X10083','X10083','Test Comment','PATHL7');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('X50000','X50000','Referred Test    ','PATHL7');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('16986-2','16986-2','Breath Hydrogen 60min','PATHL7');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('16988-8','16988-8','Breath Hydrogen 120min  ','PATHL7');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('19145-2','19145-2','Test Name','PATHL7');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('X10003','X10003','Methadone Metabolite  ','PATHL7');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('2110-5','2110-5','Serum Pregnancy Test','PATHL7');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('6037-6','6037-6','Barley ','PATHL7');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('6190-3','6190-3','Oat ','PATHL7');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('6107-7','6107-7','Egg Yolk','PATHL7');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('7674-5','7674-5','Rye ','PATHL7');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('X10024','X10024','Microalbumin','PATHL7');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('X30020','X30020','Glucose by Meter','PATHL7');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('13705-9','13705-9','Microalbumin/Creatinine Ratio','PATHL7');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('6064-0','6064-0','Cat Epithelium','PATHL7');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('30183-8','30183-8','Mold Mix (P.notatum, C.herbarum, A,fumigatus, A,alternata, H.halodes)','PATHL7');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('2744-1','2744-1','Arterial pH','PATHL7');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('2019-8','2019-8','Arterial pCO2','PATHL7');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('2703-7','2703-7','Arterial pO2','PATHL7');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('1960-4','1960-4','Arterial HCO3','PATHL7');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('2026-3','2026-3','Arterial tCO2','PATHL7');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('1925-7','1925-7','Arterial Base Excess','PATHL7');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('2708-6','2708-6','Arterial O2SAT','PATHL7');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('13657-2','13657-2','Amorphous Urates','PATHL7');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('13656-4','13656-4','Amorphous Phosphates','PATHL7');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('5814-9','5814-9','Triple Phosphates','PATHL7');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('9842-6','9842-6','Casts','PATHL7');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('X30025','X30025','Gestational Tolerance','PATHL7');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('X30011','X30011','Organism','PATHL7');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('X30029','X30029','Other','PATHL7');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('X30030','X30030','Other','PATHL7');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('X30031','X30031','Other','PATHL7');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('8462-4','8462-4','Systolic','PATHL7');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('8480-6','8480-6','Diastolic','PATHL7');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('12-5','12-5','Amikacin','PATHL7');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('781-5','781-5','Promyelocytes','PATHL7');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('708-8','708-8','Blasts','PATHL7');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('729-4','729-4','Other Cells','PATHL7');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('11067-6','11067-6','Bleeding Time','PATHL7');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('X574','X574','Anion Gap','PATHL7');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('2598-1','2598-1','Urine Magnesium','PATHL7');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('13539-2','13539-2','Urine Phosphorus','PATHL7');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('1799-6','1799-6','Urine Amylase','PATHL7');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('X30018','X30018','Synovial Fluid Analysis','PATHL7');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('X1008','X1008','Result','PATHL7');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('X30024','X30024','Glucose by Meter','PATHL7');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('512-4','512-4','Trimethoprim-Sulfa','PATHL7');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('508-2','508-2','Tobramycin','PATHL7');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('15076-3','15076-3','Urine Glucose','PATHL7');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('14938-5','14938-5','Urine Urea','PATHL7');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('14934-4','14934-4','Urine Uric Acid','PATHL7');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('2078-4','2078-4','Urine Chloride','PATHL7');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('26880-5','26880-5','Sm/RNP','PATHL7');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('X557','X557','Malaria','PATHL7');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('X30028','X30028','Glucose Tolerance','PATHL7');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('X31002','X31002','Protein Electrophoresis','PATHL7');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('14915-3','14915-3','Theophylline','PATHL7');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('14881-7','14881-7','Urine Phosphate','PATHL7');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('2956-1','2956-1','Urine Sodium 24h','PATHL7');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('2829-0','2829-0','Urine Potassium 24h','PATHL7');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('161-0','161-0','Cephalothin','PATHL7');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('112-3','112-3','Cefotetan','PATHL7');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('116-4','116-4','Cefoxitin','PATHL7');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('141-2','141-2','Ceftriaxone','PATHL7');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('500-9','500-9','Ticarcillin','PATHL7');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('412-7','412-7','Piperacillin-Tazobactam','PATHL7');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('279-0','279-0','Imipenen','PATHL7');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('6652-2','6652-2','Meropenem','PATHL7');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('262-6','262-6','Fusidic Acid','PATHL7');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('428-3','428-3','Rifampin','PATHL7');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('173-5','173-5','Chloramphenicol','PATHL7');

insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('5793-5','-CASTG','       GRANULAR CASTS','MDS');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('5796-8','-CASTH','       HYALINE CASTS','MDS');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('2555-8','-ZINC','ZINE','MDS');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('524-9','-VANCO','VANCOMYCIN','MDS');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('4485-9','-C3','COMPLEMENT C3','MDS');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('4498-2','-C4','COMPLEMENT C4','MDS');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('6932-8','-PEN','PENICILLIN','MDS');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('80-2','-CEFIXIME','CEFIXIME','MDS');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('4542-7','-HAPTO','HAPTOGLOBIN','MDS');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('3393-6','-COCAINE','COCAINE','MDS');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('108-1','-CEFOTAXI','CEFOTAXIME ','MDS');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('X472','-ALDOST','ALDOSTERONE','MDS');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('2828-2','-UR K','POTASSIUM','MDS');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('19088-4','-CDATE','COLLECTION DATE','MDS');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('4548-4','-HBAIC','HbA1C','MDS');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('14771-0','-GLU-F','GLUCOSE-FASTING','MDS');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('12227-5','-WBC','WHITE BLOOD CELL COUNT','MDS');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('789-8','-RBC','RED BLOOD CELL COUNT','MDS');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('731-0','-LYMPH-A','     (A)       LYMPH','MDS');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('742-7','-MONO-A','     (A)       MONO','MDS');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('711-2','-EOS-A','     (A)       EOS','MDS');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('704-7','-BASO-A','     (A)       BASO','MDS');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('777-3','-PLAT','PLATELET COUNT','MDS');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('1751-7','-ALB','ALBUMIN','MDS');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('751-8','-NEUT-A','ABSOLUTE:      NEUTS','MDS');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('13705-9','-ALBCRE','MICROALBUMIN/CREATININE-U','MDS');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('X10024','-ALB-U','MICROALBUMIN (RANDOM)','MDS');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('718-7','-HGB','HEMOGLOBIN','MDS');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('4537-7','-ESR','SEDIMENTATION RATE (ESR)','MDS');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('30229-9','-BAND A','     (A)       BAND','MDS');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('4544-3','-HCT','HEMATOCRIT','MDS');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('787-2','-MCV','MCV ','MDS');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('785-6','-MCH','MCH','MDS');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('786-4','-MCHC','MCHC','MDS');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('788-0','-RDW','RDW','MDS');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('14682-9','-CREAT','Creatinine','MDS');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('2951-2','-NA','SODIUM','MDS');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('2823-3','-K','POTASSIUM','MDS');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('14685-2','-VITB12','VITAMIN B12','MDS');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('14731-4','-RBC-F','RBC FOLATE','MDS');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('2075-0','-CL','CHLORIDE','MDS');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('6768-6','-ALK','ALKALINE PHOSPHATASE','MDS');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('14647-2','-CHOL','CHOLESTEROL','MDS');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('14646-4','-HDL','HDL CHOLESTEROL','MDS');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('14927-8','-TRIG','TRIGLYCERIDES','MDS');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('19151-0','-CTIME','COLLECTION TIME','MDS');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('14631-6','-BILI-T','TOTAL BILIRUBIN','MDS');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('1798-8','-AMY','AMYLASE','MDS');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('14937-7','-UREA','UREA','MDS');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('19261-7','-AMPHET','AMPHETAMINES','MDS');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('2756-5','-PH','pH','MDS');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('883-9','-GROUP','BLOOD GROUP','MDS');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('X50045','-HIV S','HIV SEROLOGY','MDS');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('2276-4','-FERRIT','FERRITIN','MDS');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('X433','-ORG 1','ORGANISM 1','MDS');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('2842-3','-PROL','PROLACTIN','MDS');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('X1020','-BIOAVAIL','BIOAVAILABLE TESTOSTERONE','MDS');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('2000-8','-CA','CALCIUM','MDS');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('267-5','-GENT','GENTAMICIN','MDS');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('76-0','-CEFAZOL','CEFAZOLIN','MDS');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('185-9','-CIPROFL','CIPROFLOXACIN','MDS');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('28-1','-AMPIC','AMPICILLIN','MDS');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('363-2','-NITROFU','NITROFURANTOIN','MDS');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('408-5','-PIPER','PIPERACILLIN','MDS');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('3040-3','-LIPASE','LIPASE','MDS');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('X10002','-HPY','HELICOBACTER PYLORI','MDS');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('19270-8','-BARB','BARBITURATES','MDS');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('19295-5','-OPIATE','OPIATES','MDS');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('14316-4','-BENZ','BENZODIAZEPINES','MDS');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('14334-7','-LI','LITHIUM','MDS');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('14890-8','-PROG','PROGESTERONE','MDS');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('1742-6','-ALT','ALANINE TRANSAMINASE (ALT)','MDS');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('19261-7','-AMPHET','AMPHETAMINE','MDS');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('13362-9','-COLL INT','COLLECTION INTERVAL','MDS');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('496-0','-TETRAC','TETRACYCLINE','MDS');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('667-6','-KOH PREP','KOH PREPARATION','MDS');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('X10019','-ORG 2','ORGANISM 2','MDS');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('233-7','-ERYTHRO','ERYTHROMYCIN','MDS');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('193-3','-CLINCIN','CLINDAMYCIN','MDS');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('14913-8','-TESTOS','TESTOSTERONE','MDS');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('197-4','-CLOX/MET','CLOXACILLIN','MDS');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('3013-0','-THYRO','THYROGLOBULIN','MDS');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('5778-6','-COLOR','       COLOUR','MDS');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('5767-9','-APP U','       APPEARANCE','MDS');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('14698-5','-DIG','DIGOXIN','MDS');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('2601-3','-MAG','MAGNESIUM','MDS');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('2885-2','-PROT-T','TOTAL PROTEIN','MDS');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('2458-8','-IGA','IGA','MDS');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('2465-3','-IGG','IGG','MDS');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('2472-9','-IGM','IGM','MDS');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('14798-3','-IRON','IRON','MDS');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('14603-5','-ANDROS','ANDROSTENEDIONE','MDS');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('X645','-CA125','CA 125','MDS');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('X107','-DAHG','DIRECT ANTIGLOBULIN TEST','MDS');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('2963-7','-GROW','GROWTH HORMONE','MDS');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('2955-3','-UR NA','SODIUM','MDS');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('X1030','-INS-R','INSULIN:RANDOM','MDS');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('3034-6','-TRANS','TRANSFERRIN','MDS');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('14196-0','-RETIC C','RETICULOCYTE COUNT','MDS');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('748-4','-MYELO-A','     (A)       MYELO','MDS');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('739-3','-META-A','     (A)       META','MDS');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('781-5','-PROMY-A','     (A)       PROMYELO','MDS');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('708-8','-BLAST-A','     (A)       BLASTS','MDS');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('43743-4','-ATY LY-A','     (A)       ATYP LYMPHS','MDS');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('729-4','-OTHER-A','     (A)       OTHER','MDS');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('133-9','-CEFTAZ','CEFTAZIDIME','MDS');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('33358-3','-PROT 1','    PROTEIN BAND 1','MDS');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('2064-4','-CERULO','CERULOPLASMIN','MDS');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('6742-1','-RBCM','RBC','MDS');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('9317-9','-PLATM','PLATELETS','MDS');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('9317-9','2111','PLATELETS','CML');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('4551-8','-HGBAZ','HEMOGLOBIN A2','MDS');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('4576-5','-HGBF','HEMOGLOBIN F','MDS');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('4563-3','-HGB C','HEMOGLOBIN C','MDS');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('4575-5','-HGB E','HEMOGLOBIN E','MDS');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('4625-0','-HGB S','HEMOGLOBIN S','MDS');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('X100111','-HGBABN','ABNORMAL HEMOGLOBIN','MDS');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('X100333','-DELAY','DELAY OF TEST NOTICE:','MDS');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('6301-6','-INR','INR','MDS');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('3173-2','-APTT','APTT (AUTOMATED)','MDS');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('31418-7','-HETAB','INF MONO HETERO ANTIBODIES','MDS');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('14800-7','-TIBC','IRON BINDING CAPACITY(TIBC)','MDS');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('14801-5','-SAT','SATURATION','MDS');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('14801-5','1390','SATURATION','GDML');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('2349-9','-GLUU','       GLUCOSE','MDS');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('2514-8','-KET','       KETONE','MDS');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('5811-5','-SG','       SPECIFIC GRAVITY','MDS');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('X100222','253&25','BLOOD','GDML');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('X100222','-BLD-U','       BLOOD','MDS');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('5804-0','-PROTU','       PROTEIN','MDS');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('5804-0','253&27','PROTEIN','GDML');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('5802-4','-NITRI','       NITRITE','MDS');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('5799-2','-LEU EST','       LEUCOCYTE ESTERASE','MDS');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('13945-1','-RBC-U','       RBC','MDS');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('13945-1','253A&01','R.B.C.','GDML');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('5821-4','253A&03','W.B.C.','GDML');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('5821-4','-WBC-U','       WBC','MDS');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('5787-7','-EPIU','       EPITHELIAL CELLS','MDS');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('5769-5','-BACT-U','       BACTERIA','MDS');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('5817-2','-CRYST','       CRYSTALS','MDS');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('25155-3','-CRYS CY','       CYSTINE CRYSTALS','MDS');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('33021-7','-CRYS TYR','       TYROSINE CRYSTALS','MDS');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('25163-7','-CRYS LEU','       LEUCINE CRYSTALS','MDS');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('25153-8','-CRYS CH','       CHOLESTEROL CRYSTALS','MDS');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('25146-2','-CRYS B','       BILIRUBIN CRYSTALS','MDS');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('9842-6','-CASTS','       CASTS','MDS');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('5820-6','-CASTW','       WBC CASTS','MDS');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('5807-3','-CASTR','       RBC CASTS','MDS');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('38995-7','-CAST CE','       CELLULAR CASTS','MDS');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('5819-8','-CASTWA','       WAXY CASTS','MDS');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('5789-3','-CASTF','       FATTY CASTS','MDS');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('X100444','-OTH','       OTHER','MDS');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('22748-8','-LDL','LDL CHOLESTEROL(CALCULATED)','MDS');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('9322-9','-HDLRAT','CHOLESTEROL/HDL RATIO','MDS');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('14934-4','252M','URATE','GDML');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('14934-4','-URATE','URATE','MDS');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('14629-0','-BILI-D','DIRECT BILIRUBIN:CONJUGATED','MDS');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('1920-8','-AST','ASPARTATE TRANSAMINASE(AST)','MDS');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('2324-2','-GGT','GAMMA-GLUTAMYLTRANSFERASE','MDS');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('25514-1','-RUB-G','RUBELLA-IGG','MDS');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('2532-0','-LD','LACTATE DEHYDROGENASE (LD)','MDS');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('11156-7','-WBCM','WBC','MDS');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('14895-7','-IMMUNO','IMMUNOFIXATION - SERUM','MDS');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('3016-3','-TSH','THYROTROPIN (SENSITIVE TSH)','MDS');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('14563-1','-OB','OCCULT BLOOD-FECES #1','MDS');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('14564-9','-OB2','OCCULT BLOOD-FECES #2','MDS');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('14565-6','-OB3','OCCULT BLOOD-FECES #3','MDS');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('2756-5','5803-2','PH','PATHL7');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('1988-5','-CRP','C-REACTIVE PROTEIN','MDS');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('X100666','-VDRL','VDRL','MDS');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('X100555','-LIPID','LIPID TARGET VALUES','MDS');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('5193-8','-HBSAB','SURFACE ANTIBODY (ANTI-HBs)','MDS');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('5196-1','-HBSAG','SURFACE ANTIGEN (HBsAg)','MDS');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('14914-6','-F-TEST','TESTOSTERONE-FREE','MDS');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('2112-1','-PREG-U','PREGNANCY TEST-URINE','MDS');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('33914-3','-GFR','eGFR','MDS');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('14683-7','-CREAT-U','CREATININE (U)','MDS');

insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('14631-6','030M','BILIRUBIN TOTAL','GDML');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('2075-0','053M','Chloride','GDML');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('14647-2','055M','Cholesterol','GDML');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('1963-8','061M','BICARBONATE','GDML');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('2157-6','066M','CK','GDML');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('14682-9','067A','Creatinine','GDML');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('4548-4','093D','Hemoglobin A1c','GDML');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('14646-4','117M','HDL Cholesterol ','GDML');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('14798-3','139M','Iron','GDML');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('14800-7','139N','TIBC','GDML');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('19295-5','-OPIATE','OPIATES','MDS');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('2823-3','204M','Potassium','GDML');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('2885-2','208M','PROTEIN','GDML');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('1920-8','222M','AST','GDML');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('1742-6','223M','ALT','GDML');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('2951-2','226M','Sodium','GDML');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('14927-8','243M','TRIGLYCERIDES','GDML');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('14937-7','151M','UREA','GDML');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('2349-9','253&21','GLUCOSE','GDML');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('2514-8','253&23','KETONES','GDML');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('5802-4','253&29','NITRITE','GDML');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('5799-2','253&30','LEUKOCYTE','GDML');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('14913-8','340','TESTOSTERONE','GDML');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('14685-2','345','VITAMIN B12','GDML');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('751-8','372&15','NEUTROPHILS','GDML');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('731-0','372&16','LYMPHOCYTES','GDML');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('742-7','372&17','MONOCYTES','GDML');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('711-2','372&18','EOSINOPHILS ','GDML');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('704-7','372&19','BASOPHILS ','GDML');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('785-6','397H','MCH','GDML');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('3255-7','402D','FIBRINOGEN, QUANTITATIVE','GDML');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('4544-3','417','HEMATOCRIT','GDML');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('786-4','417C','MCHC','GDML');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('13965-9','HCSD','HOMOCYSTEINE','GDML');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('9322-9','R/RM','RATIO AND RISK FACTOR','GDML');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('13705-9','05DR&02','MICROALB/CREAT RATIO','GDML');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('X10024','05DR&01','MICROALBUMIN (RDM U)','GDML');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('30522-7','HSCR','HIGH SENSITIVITY CRP','GDML');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('14920-3','339D','T4 FREE','GDML');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('787-2','397V','RBC INDICES:  MCV','GDML');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('1751-7','005M','ALBUMIN','GDML');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('6768-6','191M','ALKALINE PHOSPHATASE','GDML');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('2324-2','107M','GGT','GDML');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('3016-3','341','sTSH','GDML');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('777-3','396','PLATELETS','GDML');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('12227-5','399','WBC','GDML');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('789-8','397','RBC','GDML');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('788-0','RDW','RDW','GDML');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('718-7','418','HEMOGLOBIN','GDML');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('2532-0','146M','LD','GDML');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('22748-8','LDLM','LDL CHOLESTEROL CALC.','GDML');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('14771-0','111G','GLUCOSE SERUM FASTING','GDML');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('2756-5','253&26','pH','GDML');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('5811-5','253&24','S.G.','GDML');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('5770-3','253&22','BILIRUBIN','GDML');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('5787-7','253A&02','EPITHELIAL','GDML');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('5769-5','253A&04','BACTERIA','GDML');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('33914-3','067A&01','eGFR','GDML');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('2885-2','208M','PROTEIN','GDML');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('6301-6','445','INR','GDML');

insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('14771-0','3007','GLUCOSE FASTING-SER','CML');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('14682-9','3180','Creatinine','CML');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('2951-2','3210','Sodium','CML');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('2823-3','3220','Potassium','CML');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('2075-0','3230','Chloride','CML');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('1920-8','3370','AST','CML');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('14647-2','3120','CHOLESTEROL','CML');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('14927-8','3140','TRIGLYCERIDES','CML');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('14646-4','3923','HDL Cholesterol ','CML');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('22748-8','3933','LDL CHOLESTEROL','CML');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('4548-4','3767','HEMOGLOBIN A1C','CML');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('4544-3','2013','Hematocrit','CML');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('787-2','2022','MCV','CML');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('785-6','2025','MCH','CML');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('786-4','2028','MCHC','CML');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('788-0','2029','RDW','CML');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('777-3','2030','PLATELET COUNT ','CML');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('6742-1','2107','RBC MORPHOLOGY','CML');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('14685-2','4035','VITAMIN B12','CML');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('3016-3','4025','TSH','CML');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('14946-8','4089','VALPROIC ACID','CML');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('1742-6','3380','ALT','CML');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('6768-6','3360','ALK PHOS','CML');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('9322-9','3939','CHOL/HDL RATIO','CML');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('718-7','2010','HEMOGLOBIN','CML');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('12227-5','2016','WBC COUNT','CML');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('789-8','2019','RBC COUNT','CML');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('751-8','2191','ABSOLUTE:  NEUTROS','CML');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('731-0','2193','(A)   LYMPH','CML');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('742-7','2196','(A)   MONO','CML');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('711-2','2197','(A)   EOS','CML');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('704-7','2198','(A)   BASO','CML');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('6301-6','2165','I.N.R.','CML');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('33914-3','3190','eGFR','CML');

insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('33914-3','GFRM','EGFR','ICL');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('33914-3','GFRF','EGFR','ICL');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('14927-8','TRI','LIPIDS TG','ICL');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('14646-4','HDL','HDL','ICL');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('X100666','VDR','VDRL','ICL');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('14914-6','FTS','Free Testost','ICL');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('14685-2','B12','Vit B12','ICL');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('22748-8','LDL','LIPIDS LDL','ICL');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('9322-9','TCHOL','LIPIDS TC/HDL','ICL');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('4548-4','A1C','A1C','ICL');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('9318-7','UMALB','Alb creat ratio','ICL');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('X50060','HCV','Hep C Ab','ICL');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('5196-1','HSG','Hep BS Ag','ICL');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('5193-8','HAS','Hep BS Ab','ICL');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('1742-6','ALT','ALT','ICL');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('14647-2','CHO','Total Cholestorol','ICL');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('6301-6','PT','INR','ICL');


insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('6301-6','INR','INR','FLOWSHEET');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('3142-7', 'WT', 'Weight', 'FLOWSHEET');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('3138-5', 'HT', 'Height', 'FLOWSHEET');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('14682-9', 'SCR', 'Creatinine', 'FLOWSHEET');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('8280-0', 'WC', 'Waist Circumference', 'FLOWSHEET');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('X100666','VDRL','VDRL','FLOWSHEET');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('14914-6','FTST','Free Testost','FLOWSHEET');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('14685-2','VB12','Vit B12','FLOWSHEET');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('22748-8','LDL','LIPIDS LDL','FLOWSHEET');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('9322-9','TCHD','LIPIDS TC/HDL','FLOWSHEET');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('4548-4','A1C','A1C','FLOWSHEET');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('9318-7','ACR','Alb creat ratio','FLOWSHEET');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('14646-4','HDL','HDL','FLOWSHEET');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('X50060','HpCA','Hep C Ab','FLOWSHEET');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('5196-1','HpBS','Hep BS Ag','FLOWSHEET');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('5193-8','HpBA','Hep BS Ab','FLOWSHEET');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('14647-2','TCHL','Total Cholestorol','FLOWSHEET');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('14927-8','TG','LIPIDS TG','FLOWSHEET');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('33914-3','EGFR','EGFR','FLOWSHEET');
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('1742-6','ALT','ALT','FLOWSHEET');

insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('6301-6','INR','INR','MUHC'); 
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('4548-4','HA1C','Hb A1c','MUHC'); 
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('33914-3','NGFR','eGFR','MUHC'); 
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('14646-4','HDL','HDL','MUHC'); 
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('X100666','VDRL','VDRL','MUHC'); 
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('14685-2','B12','Vitamin B12','MUHC'); 
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('22748-8','LDL','LDL','MUHC'); 
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('22748-8','LDL','LDL','MUHC'); 
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('14682-9','CR','Creatinine','MUHC'); 
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('1751-7','ALB','Albumin','MUHC'); 
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('14879-1','PO4','Phosphate','MUHC'); 
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('2000-8','CA','Calcium','MUHC'); 
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('1742-6','ALT','ALT','MUHC'); 
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('14927-8','TRIG','Triglycerides','MUHC'); 
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('9322-9','CHHD','Total Cholesterol/HDL Cholesterol Ratio','MUHC'); 
insert into measurementMap (loinc_code, ident_code, name, lab_type) VALUES ('9318-7','UMIC',' U Microalb/Creat Ratio','MUHC'); 


/*!40000 ALTER TABLE `measurementMap` ENABLE KEYS */;
UNLOCK TABLES;

