CREATE TABLE billingreferral (
  billingreferral_no int(10) NOT NULL auto_increment,
  referral_no varchar(6) NOT NULL default '000000',
  last_name varchar(30) default NULL,
  first_name varchar(30) default NULL,
  specialty varchar(30) default NULL,
  address1 varchar(50) default NULL,
  address2 varchar(50) default NULL,
  city varchar(30) default NULL,
  province varchar(30) default NULL,
  country varchar(30) default NULL,
  postal varchar(10) default NULL,
  phone varchar(16) default NULL,
  fax varchar(16) default NULL,
  PRIMARY KEY  (billingreferral_no),
  KEY referral_no (referral_no),
  UNIQUE (referral_no) 
) TYPE=MyISAM;

CREATE TABLE billingperclimit (
  service_code varchar(10) NOT NULL ,
  min varchar(8) default '0',
  max varchar(8) default '0',
  PRIMARY KEY  (service_code)
) TYPE=MyISAM;

CREATE TABLE formGrowthChart(
  ID int(10) NOT NULL  auto_increment,
  demographic_no int(10) NOT NULL default '0' ,
  provider_no int(10)  default NULL ,
  formCreated date  default NULL ,
  formEdited timestamp   ,
  patientName varchar(80),
  recordNo varchar(10),
  motherStature varchar(80),
  fatherStature varchar(80),
  date_1 date,
  age_1 varchar(5),
  stature_1 varchar(6),
  weight_1 varchar(6),
  comment_1 varchar(25),
  bmi_1 varchar(5),
  date_2 date,
  age_2 varchar(5),
  stature_2 varchar(6),
  weight_2 varchar(6),
  comment_2 varchar(25),
  bmi_2 varchar(5),
  date_3 date,
  age_3 varchar(5),
  stature_3 varchar(6),
  weight_3 varchar(6),
  comment_3 varchar(25),
  bmi_3 varchar(5),
  date_4 date,
  age_4 varchar(5),
  stature_4 varchar(6),
  weight_4 varchar(6),
  comment_4 varchar(25),
  bmi_4 varchar(5),
  date_5 date,
  age_5 varchar(5),
  stature_5 varchar(6),
  weight_5 varchar(6),
  comment_5 varchar(25),
  bmi_5 varchar(5),
  date_6 date,
  age_6 varchar(5),
  stature_6 varchar(6),
  weight_6 varchar(6),
  comment_6 varchar(25),
  bmi_6 varchar(5),
  date_7 date,
  age_7 varchar(5),
  stature_7 varchar(6),
  weight_7 varchar(6),
  comment_7 varchar(25),
  bmi_7 varchar(5),
  PRIMARY KEY (ID)
) TYPE=MyISAM;

