CREATE TABLE billingreferral (
  billingreferral_no int(10) NOT NULL auto_increment,
  referral_no varchar(6) NOT NULL default '000000',
  last_name varchar(30) default NULL,
  first_name varchar(30) default NULL,
  specialty varchar(30) default NULL,
  address1 varchar(50) default NULL,
  address2 varchar(50) default NULL,
  city varchar(30) default NULL,
  province varchar(30) default NULL,
  country varchar(30) default NULL,
  postal varchar(10) default NULL,
  phone varchar(16) default NULL,
  fax varchar(16) default NULL,
  PRIMARY KEY  (billingreferral_no),
  KEY referral_no (referral_no),
  UNIQUE (referral_no) 
) ;

CREATE TABLE billingperclimit (
  service_code varchar(10) NOT NULL ,
  min varchar(8) default '0',
  max varchar(8) default '0',
  effective_date date default '1970-01-01',
  id int auto_increment,
  PRIMARY KEY  (id)
) ;



create table labReportInformation(
  id  int(10) NOT NULL auto_increment primary key,
  location_id  varchar(255),
  print_date varchar(10),
  print_time varchar(10),
  total_BType varchar(5),
  total_CType varchar(5),
  total_DType  varchar(5)
);

create table labPatientPhysicianInfo(
  id int(10) NOT NULL auto_increment primary key,
  labReportInfo_id int(10),
  accession_num varchar(64),
  physician_account_num varchar(30),
  service_date varchar(10),
  patient_first_name varchar(100),
  patient_last_name varchar(100),
  patient_sex char(1),
  patient_health_num varchar(20),
  patient_dob varchar(15),
  lab_status char(1),
  doc_num varchar(50),
  doc_name varchar(100),
  doc_addr1 varchar(100),
  doc_addr2 varchar(100),
  doc_addr3 varchar(100),
  doc_postal varchar(15),
  doc_route varchar(50),
  comment1 text,
  comment2 text,
  patient_phone varchar(20),
  doc_phone varchar(20),
  collection_date varchar(12)
);

create table labTestResults(
  id int(10) NOT NULL auto_increment primary key,
  labPatientPhysicianInfo_id int(10),
  line_type char (1),
  title varchar(255),
  notUsed1 varchar(255),
  notUsed2 varchar(255),
  test_name varchar(255),
  abn char(1),
  minimum varchar(65),
  maximum varchar(65),
  units varchar(65),
  result varchar(65),
  description text,
  location_id  varchar(255),
  last char(1)
);

CREATE TABLE formONAR(
  ID int(10) NOT NULL  auto_increment,
  demographic_no int(10) NOT NULL default '0',
  provider_no int(10)  default NULL,
  formCreated date  default NULL,
  formEdited timestamp,
  c_lastName varchar(80),
  c_firstName varchar(80),
  c_address varchar(80),
  c_apt varchar(20),
  c_city varchar(80),
  c_province varchar(80),
  c_postal varchar(10),
  c_partnerLastName varchar(80),
  c_partnerFirstName varchar(80),
  pg1_homePhone varchar(20),
  pg1_workPhone varchar(20),
  pg1_language varchar(25),
  pg1_partnerOccupation varchar(25),
  pg1_partnerEduLevel varchar(25),
  pg1_partnerAge varchar(5),
  pg1_dateOfBirth date,
  pg1_age varchar(10),
  pg1_occupation varchar(25),
  pg1_eduLevel varchar(25),
  pg1_ethnicBg varchar(200),
  c_hin varchar(20),
  c_fileNo varchar(20),
  pg1_msSingle tinyint(1) default NULL,
  pg1_msCommonLaw tinyint(1) default NULL,
  pg1_msMarried tinyint(1) default NULL,
  pg1_baObs tinyint(1) default NULL,
  pg1_baFP tinyint(1) default NULL,
  pg1_baMidwife tinyint(1) default NULL,
  c_ba varchar(25) default NULL,
  pg1_ncPed tinyint(1) default NULL,
  pg1_ncFP tinyint(1) default NULL,
  pg1_ncMidwife tinyint(1) default NULL,
  c_nc varchar(25) default NULL,
  c_famPhys varchar(80) default NULL,
  c_allergies text,
  c_meds text,
  pg1_menLMP date,
  pg1_psCertY tinyint(1),
  pg1_psCertN tinyint(1),
  pg1_menCycle varchar(7),
  pg1_menReg tinyint(1),
  pg1_menRegN tinyint(1),
  pg1_contracep varchar(25),
  pg1_lastUsed date,
  pg1_menEDB date,
  c_finalEDB date,
  pg1_edbByDate tinyint(1),
  pg1_edbByT1 tinyint(1),
  pg1_edbByT2 tinyint(1),
  pg1_edbByART tinyint(1),
  c_gravida varchar(3) default NULL,
  c_term varchar(3) default NULL,
  c_prem varchar(3) default NULL,
  c_abort varchar(3) default NULL,
  c_living varchar(3) default NULL,

  pg1_year1 varchar(10) default NULL,
  pg1_sex1 char(1) default NULL,
  pg1_oh_gest1 varchar(5) default NULL,
  pg1_weight1 varchar(6) default NULL,
  pg1_length1 varchar(6) default NULL,
  pg1_place1 varchar(20) default NULL,
  pg1_svb1 tinyint(1) default NULL,
  pg1_cs1 tinyint(1) default NULL,
  pg1_ass1 tinyint(1) default NULL,
  pg1_oh_comments1 varchar(80) default NULL,
  pg1_year2 varchar(10) default NULL,
  pg1_sex2 char(1) default NULL,
  pg1_oh_gest2 varchar(5) default NULL,
  pg1_weight2 varchar(6) default NULL,
  pg1_length2 varchar(6) default NULL,
  pg1_place2 varchar(20) default NULL,
  pg1_svb2 tinyint(1) default NULL,
  pg1_cs2 tinyint(1) default NULL,
  pg1_ass2 tinyint(1) default NULL,
  pg1_oh_comments2 varchar(80) default NULL,
  pg1_year3 varchar(10) default NULL,
  pg1_sex3 char(1) default NULL,
  pg1_oh_gest3 varchar(5) default NULL,
  pg1_weight3 varchar(6) default NULL,
  pg1_length3 varchar(6) default NULL,
  pg1_place3 varchar(20) default NULL,
  pg1_svb3 tinyint(1) default NULL,
  pg1_cs3 tinyint(1) default NULL,
  pg1_ass3 tinyint(1) default NULL,
  pg1_oh_comments3 varchar(80) default NULL,
  pg1_year4 varchar(10) default NULL,
  pg1_sex4 char(1) default NULL,
  pg1_oh_gest4 varchar(5) default NULL,
  pg1_weight4 varchar(6) default NULL,
  pg1_length4 varchar(6) default NULL,
  pg1_place4 varchar(20) default NULL,
  pg1_svb4 tinyint(1) default NULL,
  pg1_cs4 tinyint(1) default NULL,
  pg1_ass4 tinyint(1) default NULL,
  pg1_oh_comments4 varchar(80) default NULL,
  pg1_year5 varchar(10) default NULL,
  pg1_sex5 char(1) default NULL,
  pg1_oh_gest5 varchar(5) default NULL,
  pg1_weight5 varchar(6) default NULL,
  pg1_length5 varchar(6) default NULL,
  pg1_place5 varchar(20) default NULL,
  pg1_svb5 tinyint(1) default NULL,
  pg1_cs5 tinyint(1) default NULL,
  pg1_ass5 tinyint(1) default NULL,
  pg1_oh_comments5 varchar(80) default NULL,
  pg1_year6 varchar(10) default NULL,
  pg1_sex6 char(1) default NULL,
  pg1_oh_gest6 varchar(5) default NULL,
  pg1_weight6 varchar(6) default NULL,
  pg1_length6 varchar(6) default NULL,
  pg1_place6 varchar(20) default NULL,
  pg1_svb6 tinyint(1) default NULL,
  pg1_cs6 tinyint(1) default NULL,
  pg1_ass6 tinyint(1) default NULL,
  pg1_oh_comments6 varchar(80) default NULL,
  pg1_cp1 tinyint(1) default NULL,
  pg1_cp1N tinyint(1) default NULL,
  pg1_cp2 tinyint(1) default NULL,
  pg1_cp2N tinyint(1) default NULL,
  pg1_box3 varchar(3) default NULL,
  pg1_cp3 tinyint(1) default NULL,
  pg1_cp3N tinyint(1) default NULL,
  pg1_cp4 tinyint(1) default NULL,
  pg1_cp4N tinyint(1) default NULL,
  pg1_cp8 tinyint(1) default NULL,
  pg1_cp8N tinyint(1) default NULL,
  pg1_naDietRes tinyint(1) default NULL,
  pg1_naDietBal tinyint(1) default NULL,
  pg1_naMilk tinyint(1) default NULL,
  pg1_naMilkN tinyint(1) default NULL,
  pg1_naFolic tinyint(1) default NULL,
  pg1_naFolicN tinyint(1) default NULL,
  pg1_yes9 tinyint(1) default NULL,
  pg1_no9 tinyint(1) default NULL,
  pg1_yes10 tinyint(1) default NULL,
  pg1_no10 tinyint(1) default NULL,
  pg1_yes12 tinyint(1) default NULL,
  pg1_no12 tinyint(1) default NULL,
  pg1_yes13 tinyint(1) default NULL,
  pg1_no13 tinyint(1) default NULL,
  pg1_yes14 tinyint(1) default NULL,
  pg1_no14 tinyint(1) default NULL,
  pg1_yes17 tinyint(1) default NULL,
  pg1_no17 tinyint(1) default NULL,
  pg1_yes22 tinyint(1) default NULL,
  pg1_no22 tinyint(1) default NULL,
  pg1_yes20 tinyint(1) default NULL,
  pg1_no20 tinyint(1) default NULL,
  pg1_bloodTranY tinyint(1) default NULL,
  pg1_bloodTranN tinyint(1) default NULL,
  pg1_yes21 tinyint(1) default NULL,
  pg1_no21 tinyint(1) default NULL,
  pg1_yes24 tinyint(1) default NULL,
  pg1_no24 tinyint(1) default NULL,
  pg1_yes15 tinyint(1) default NULL,
  pg1_no15 tinyint(1) default NULL,
  pg1_box25  varchar(25) default NULL,
  pg1_yes25 tinyint(1) default NULL,
  pg1_no25 tinyint(1) default NULL,
  pg1_yes27 tinyint(1) default NULL,
  pg1_no27 tinyint(1) default NULL,
  pg1_yes31 tinyint(1) default NULL,
  pg1_no31 tinyint(1) default NULL,
  pg1_yes32 tinyint(1) default NULL,
  pg1_no32 tinyint(1) default NULL,
  pg1_yes34 tinyint(1) default NULL,
  pg1_no34 tinyint(1) default NULL,
  pg1_yes35 tinyint(1) default NULL,
  pg1_no35 tinyint(1) default NULL,
  pg1_idt40 tinyint(1) default NULL,
  pg1_idt40N tinyint(1) default NULL,
  pg1_idt38 tinyint(1) default NULL,
  pg1_idt38N tinyint(1) default NULL,
  pg1_idt42 tinyint(1) default NULL,
  pg1_idt42N tinyint(1) default NULL,
  pg1_infectDisOther varchar(20) default NULL,
  pg1_infectDisOtherY tinyint(1) default NULL,
  pg1_infectDisOtherN tinyint(1) default NULL,
  pg1_pdt43 tinyint(1) default NULL,
  pg1_pdt43N tinyint(1) default NULL,
  pg1_pdt44 tinyint(1) default NULL,
  pg1_pdt44N tinyint(1) default NULL,
  pg1_pdt45 tinyint(1) default NULL,
  pg1_pdt45N tinyint(1) default NULL,
  pg1_pdt46 tinyint(1) default NULL,
  pg1_pdt46N tinyint(1) default NULL,
  pg1_pdt47 tinyint(1) default NULL,
  pg1_pdt47N tinyint(1) default NULL,
  pg1_pdt48 tinyint(1) default NULL,
  pg1_pdt48N tinyint(1) default NULL,
  pg1_reliCultY tinyint(1) default NULL,
  pg1_reliCultN tinyint(1) default NULL,
  pg1_fhRiskY tinyint(1) default NULL,
  pg1_fhRiskN tinyint(1) default NULL,
  pg1_ht varchar(6) default NULL,
  pg1_wt varchar(6) default NULL,
  c_bmi varchar(6) default NULL,
  pg1_BP varchar(10) default NULL,
  pg1_thyroid tinyint(1) default NULL,
  pg1_thyroidA tinyint(1) default NULL,
  pg1_chest tinyint(1) default NULL,
  pg1_chestA tinyint(1) default NULL,
  pg1_breasts tinyint(1) default NULL,
  pg1_breastsA tinyint(1) default NULL,
  pg1_cardio tinyint(1) default NULL,
  pg1_cardioA tinyint(1) default NULL,
  pg1_abdomen tinyint(1) default NULL,
  pg1_abdomenA tinyint(1) default NULL,
  pg1_vari tinyint(1) default NULL,
  pg1_variA tinyint(1) default NULL,
  pg1_extGen tinyint(1) default NULL,
  pg1_extGenA tinyint(1) default NULL,
  pg1_cervix tinyint(1) default NULL,
  pg1_cervixA tinyint(1) default NULL,
  pg1_uterus tinyint(1) default NULL,
  pg1_uterusA tinyint(1) default NULL,
  pg1_uterusBox varchar(3) default NULL,
  pg1_adnexa tinyint(1) default NULL,
  pg1_adnexaA tinyint(1) default NULL,
  pg1_pExOther varchar(20) default NULL,
  pg1_pExOtherN tinyint(1) default NULL,
  pg1_pExOtherA tinyint(1) default NULL,

  pg1_labHb varchar(20) default NULL,
  pg1_labHIV varchar(20) default NULL,
  pg1_labMCV varchar(20) default NULL,
  pg1_labHIVCounsel tinyint(1) default NULL,
  pg1_labABO varchar(20) default NULL,
  pg1_labLastPapDate varchar(10) default NULL,
  pg1_labLastPap varchar(20) default NULL,

  pg1_labRh varchar(20) default NULL,
  pg1_labAntiScr varchar(20) default NULL,
  pg1_labGC varchar(20) default NULL,
  pg1_labRubella varchar(20) default NULL,
  pg1_labUrine varchar(20) default NULL,
  pg1_labHBsAg varchar(20) default NULL,
  pg1_labVDRL varchar(20) default NULL,
  pg1_labSickle varchar(20) default NULL,
  pg1_geneticA varchar(20) default NULL,
  pg1_geneticB varchar(20) default NULL,
  pg1_geneticC varchar(20) default NULL,
  pg1_geneticD tinyint(1) default NULL,
  pg1_commentsAR1 text,
  pg1_signature varchar(50) default NULL,
  pg1_formDate date default NULL,
  pg1_signature2 varchar(50) default NULL,
  pg1_formDate2 date default NULL,

  c_riskFactors1 varchar(50) default NULL,
  c_planManage1 varchar(100) default NULL,
  c_riskFactors2 varchar(50) default NULL,
  c_planManage2 varchar(100) default NULL,
  c_riskFactors3 varchar(50) default NULL,
  c_planManage3 varchar(100) default NULL,
  c_riskFactors4 varchar(50) default NULL,
  c_planManage4 varchar(100) default NULL,
  c_riskFactors5 varchar(50) default NULL,
  c_planManage5 varchar(100) default NULL,
  c_riskFactors6 varchar(50) default NULL,
  c_planManage6 varchar(100) default NULL,
  c_riskFactors7 varchar(50) default NULL,
  c_planManage7 varchar(100) default NULL,
  ar2_rhNeg tinyint(1) default NULL,
  ar2_rhIG varchar(10) default NULL,
  ar2_rubella tinyint(1) default NULL,
  ar2_hepBIG tinyint(1) default NULL,
  ar2_hepBVac tinyint(1) default NULL,
  pg2_date1 date default NULL,
  pg2_gest1 varchar(6) default NULL,
  pg2_wt1 varchar(6) default NULL,
  pg2_BP1 varchar(8) default NULL,
  pg2_urinePr1 char(3) default NULL,
  pg2_urineGl1 char(3) default NULL,
  pg2_ht1 varchar(6) default NULL,
  pg2_presn1 varchar(6) default NULL,
  pg2_FHR1 varchar(6) default NULL,
  pg2_comments1 varchar(255) default NULL,
  pg2_date2 date default NULL,
  pg2_gest2 varchar(6) default NULL,
  pg2_ht2 varchar(6) default NULL,
  pg2_wt2 varchar(6) default NULL,
  pg2_presn2 varchar(6) default NULL,
  pg2_FHR2 varchar(6) default NULL,
  pg2_urinePr2 char(3) default NULL,
  pg2_urineGl2 char(3) default NULL,
  pg2_BP2 varchar(8) default NULL,
  pg2_comments2 varchar(255) default NULL,
  pg2_date3 date default NULL,
  pg2_gest3 varchar(6) default NULL,
  pg2_ht3 varchar(6) default NULL,
  pg2_wt3 varchar(6) default NULL,
  pg2_presn3 varchar(6) default NULL,
  pg2_FHR3 varchar(6) default NULL,
  pg2_urinePr3 char(3) default NULL,
  pg2_urineGl3 char(3) default NULL,
  pg2_BP3 varchar(8) default NULL,
  pg2_comments3 varchar(255) default NULL,
  pg2_date4 date default NULL,
  pg2_gest4 varchar(6) default NULL,
  pg2_ht4 varchar(6) default NULL,
  pg2_wt4 varchar(6) default NULL,
  pg2_presn4 varchar(6) default NULL,
  pg2_FHR4 varchar(6) default NULL,
  pg2_urinePr4 char(3) default NULL,
  pg2_urineGl4 char(3) default NULL,
  pg2_BP4 varchar(8) default NULL,
  pg2_comments4 varchar(255) default NULL,
  pg2_date5 date default NULL,
  pg2_gest5 varchar(6) default NULL,
  pg2_ht5 varchar(6) default NULL,
  pg2_wt5 varchar(6) default NULL,
  pg2_presn5 varchar(6) default NULL,
  pg2_FHR5 varchar(6) default NULL,
  pg2_urinePr5 char(3) default NULL,
  pg2_urineGl5 char(3) default NULL,
  pg2_BP5 varchar(8) default NULL,
  pg2_comments5 varchar(255) default NULL,
  pg2_date6 date default NULL,
  pg2_gest6 varchar(6) default NULL,
  pg2_ht6 varchar(6) default NULL,
  pg2_wt6 varchar(6) default NULL,
  pg2_presn6 varchar(6) default NULL,
  pg2_FHR6 varchar(6) default NULL,
  pg2_urinePr6 char(3) default NULL,
  pg2_urineGl6 char(3) default NULL,
  pg2_BP6 varchar(8) default NULL,
  pg2_comments6 varchar(255) default NULL,
  pg2_date7 date default NULL,
  pg2_gest7 varchar(6) default NULL,
  pg2_ht7 varchar(6) default NULL,
  pg2_wt7 varchar(6) default NULL,
  pg2_presn7 varchar(6) default NULL,
  pg2_FHR7 varchar(6) default NULL,
  pg2_urinePr7 char(3) default NULL,
  pg2_urineGl7 char(3) default NULL,
  pg2_BP7 varchar(8) default NULL,
  pg2_comments7 varchar(255) default NULL,
  pg2_date8 date default NULL,
  pg2_gest8 varchar(6) default NULL,
  pg2_ht8 varchar(6) default NULL,
  pg2_wt8 varchar(6) default NULL,
  pg2_presn8 varchar(6) default NULL,
  pg2_FHR8 varchar(6) default NULL,
  pg2_urinePr8 char(3) default NULL,
  pg2_urineGl8 char(3) default NULL,
  pg2_BP8 varchar(8) default NULL,
  pg2_comments8 varchar(255) default NULL,
  pg2_date9 date default NULL,
  pg2_gest9 varchar(6) default NULL,
  pg2_ht9 varchar(6) default NULL,
  pg2_wt9 varchar(6) default NULL,
  pg2_presn9 varchar(6) default NULL,
  pg2_FHR9 varchar(6) default NULL,
  pg2_urinePr9 char(3) default NULL,
  pg2_urineGl9 char(3) default NULL,
  pg2_BP9 varchar(8) default NULL,
  pg2_comments9 varchar(255) default NULL,
  pg2_date10 date default NULL,
  pg2_gest10 varchar(6) default NULL,
  pg2_ht10 varchar(6) default NULL,
  pg2_wt10 varchar(6) default NULL,
  pg2_presn10 varchar(6) default NULL,
  pg2_FHR10 varchar(6) default NULL,
  pg2_urinePr10 char(3) default NULL,
  pg2_urineGl10 char(3) default NULL,
  pg2_BP10 varchar(8) default NULL,
  pg2_comments10 varchar(255) default NULL,
  pg2_date11 date default NULL,
  pg2_gest11 varchar(6) default NULL,
  pg2_ht11 varchar(6) default NULL,
  pg2_wt11 varchar(6) default NULL,
  pg2_presn11 varchar(6) default NULL,
  pg2_FHR11 varchar(6) default NULL,
  pg2_urinePr11 char(3) default NULL,
  pg2_urineGl11 char(3) default NULL,
  pg2_BP11 varchar(8) default NULL,
  pg2_comments11 varchar(255) default NULL,
  pg2_date12 date default NULL,
  pg2_gest12 varchar(6) default NULL,
  pg2_ht12 varchar(6) default NULL,
  pg2_wt12 varchar(6) default NULL,
  pg2_presn12 varchar(6) default NULL,
  pg2_FHR12 varchar(6) default NULL,
  pg2_urinePr12 char(3) default NULL,
  pg2_urineGl12 char(3) default NULL,
  pg2_BP12 varchar(8) default NULL,
  pg2_comments12 varchar(255) default NULL,
  pg2_date13 date default NULL,
  pg2_gest13 varchar(6) default NULL,
  pg2_ht13 varchar(6) default NULL,
  pg2_wt13 varchar(6) default NULL,
  pg2_presn13 varchar(6) default NULL,
  pg2_FHR13 varchar(6) default NULL,
  pg2_urinePr13 char(3) default NULL,
  pg2_urineGl13 char(3) default NULL,
  pg2_BP13 varchar(8) default NULL,
  pg2_comments13 varchar(255) default NULL,
  pg2_date14 date default NULL,
  pg2_gest14 varchar(6) default NULL,
  pg2_ht14 varchar(6) default NULL,
  pg2_wt14 varchar(6) default NULL,
  pg2_presn14 varchar(6) default NULL,
  pg2_FHR14 varchar(6) default NULL,
  pg2_urinePr14 char(3) default NULL,
  pg2_urineGl14 char(3) default NULL,
  pg2_BP14 varchar(8) default NULL,
  pg2_comments14 varchar(255) default NULL,
  pg2_date15 date default NULL,
  pg2_gest15 varchar(6) default NULL,
  pg2_ht15 varchar(6) default NULL,
  pg2_wt15 varchar(6) default NULL,
  pg2_presn15 varchar(6) default NULL,
  pg2_FHR15 varchar(6) default NULL,
  pg2_urinePr15 char(3) default NULL,
  pg2_urineGl15 char(3) default NULL,
  pg2_BP15 varchar(8) default NULL,
  pg2_comments15 varchar(255) default NULL,
  pg2_date16 date default NULL,
  pg2_gest16 varchar(6) default NULL,
  pg2_ht16 varchar(6) default NULL,
  pg2_wt16 varchar(6) default NULL,
  pg2_presn16 varchar(6) default NULL,
  pg2_FHR16 varchar(6) default NULL,
  pg2_urinePr16 char(3) default NULL,
  pg2_urineGl16 char(3) default NULL,
  pg2_BP16 varchar(8) default NULL,
  pg2_comments16 varchar(255) default NULL,
  pg2_date17 date default NULL,
  pg2_gest17 varchar(6) default NULL,
  pg2_ht17 varchar(6) default NULL,
  pg2_wt17 varchar(6) default NULL,
  pg2_presn17 varchar(6) default NULL,
  pg2_FHR17 varchar(6) default NULL,
  pg2_urinePr17 char(3) default NULL,
  pg2_urineGl17 char(3) default NULL,
  pg2_BP17 varchar(8) default NULL,
  pg2_comments17 varchar(255) default NULL,
  pg2_date18 date default NULL,
  pg2_gest18 varchar(6) default NULL,
  pg2_ht18 varchar(6) default NULL,
  pg2_wt18 varchar(6) default NULL,
  pg2_presn18 varchar(6) default NULL,
  pg2_FHR18 varchar(6) default NULL,
  pg2_urinePr18 char(3) default NULL,
  pg2_urineGl18 char(3) default NULL,
  pg2_BP18 varchar(8) default NULL,
  pg2_comments18 varchar(255) default NULL,
  pg3_date19 date default NULL,
  pg3_gest19 varchar(6) default NULL,
  pg3_ht19 varchar(6) default NULL,
  pg3_wt19 varchar(6) default NULL,
  pg3_presn19 varchar(6) default NULL,
  pg3_FHR19 varchar(6) default NULL,
  pg3_urinePr19 char(3) default NULL,
  pg3_urineGl19 char(3) default NULL,
  pg3_BP19 varchar(8) default NULL,
  pg3_comments19 varchar(255) default NULL,
  pg3_date20 date default NULL,
  pg3_gest20 varchar(6) default NULL,
  pg3_ht20 varchar(6) default NULL,
  pg3_wt20 varchar(6) default NULL,
  pg3_presn20 varchar(6) default NULL,
  pg3_FHR20 varchar(6) default NULL,
  pg3_urinePr20 char(3) default NULL,
  pg3_urineGl20 char(3) default NULL,
  pg3_BP20 varchar(8) default NULL,
  pg3_comments20 varchar(255) default NULL,
  pg3_date21 date default NULL,
  pg3_gest21 varchar(6) default NULL,
  pg3_ht21 varchar(6) default NULL,
  pg3_wt21 varchar(6) default NULL,
  pg3_presn21 varchar(6) default NULL,
  pg3_FHR21 varchar(6) default NULL,
  pg3_urinePr21 char(3) default NULL,
  pg3_urineGl21 char(3) default NULL,
  pg3_BP21 varchar(8) default NULL,
  pg3_comments21 varchar(255) default NULL,
  pg3_date22 date default NULL,
  pg3_gest22 varchar(6) default NULL,
  pg3_ht22 varchar(6) default NULL,
  pg3_wt22 varchar(6) default NULL,
  pg3_presn22 varchar(6) default NULL,
  pg3_FHR22 varchar(6) default NULL,
  pg3_urinePr22 char(3) default NULL,
  pg3_urineGl22 char(3) default NULL,
  pg3_BP22 varchar(8) default NULL,
  pg3_comments22 varchar(255) default NULL,
  pg3_date23 date default NULL,
  pg3_gest23 varchar(6) default NULL,
  pg3_ht23 varchar(6) default NULL,
  pg3_wt23 varchar(6) default NULL,
  pg3_presn23 varchar(6) default NULL,
  pg3_FHR23 varchar(6) default NULL,
  pg3_urinePr23 char(3) default NULL,
  pg3_urineGl23 char(3) default NULL,
  pg3_BP23 varchar(8) default NULL,
  pg3_comments23 varchar(255) default NULL,
  pg3_date24 date default NULL,
  pg3_gest24 varchar(6) default NULL,
  pg3_ht24 varchar(6) default NULL,
  pg3_wt24 varchar(6) default NULL,
  pg3_presn24 varchar(6) default NULL,
  pg3_FHR24 varchar(6) default NULL,
  pg3_urinePr24 char(3) default NULL,
  pg3_urineGl24 char(3) default NULL,
  pg3_BP24 varchar(8) default NULL,
  pg3_comments24 varchar(255) default NULL,
  pg3_date25 date default NULL,
  pg3_gest25 varchar(6) default NULL,
  pg3_ht25 varchar(6) default NULL,
  pg3_wt25 varchar(6) default NULL,
  pg3_presn25 varchar(6) default NULL,
  pg3_FHR25 varchar(6) default NULL,
  pg3_urinePr25 char(3) default NULL,
  pg3_urineGl25 char(3) default NULL,
  pg3_BP25 varchar(8) default NULL,
  pg3_comments25 varchar(255) default NULL,
  pg3_date26 date default NULL,
  pg3_gest26 varchar(6) default NULL,
  pg3_ht26 varchar(6) default NULL,
  pg3_wt26 varchar(6) default NULL,
  pg3_presn26 varchar(6) default NULL,
  pg3_FHR26 varchar(6) default NULL,
  pg3_urinePr26 char(3) default NULL,
  pg3_urineGl26 char(3) default NULL,
  pg3_BP26 varchar(8) default NULL,
  pg3_comments26 varchar(255) default NULL,
  pg3_date27 date default NULL,
  pg3_gest27 varchar(6) default NULL,
  pg3_ht27 varchar(6) default NULL,
  pg3_wt27 varchar(6) default NULL,
  pg3_presn27 varchar(6) default NULL,
  pg3_FHR27 varchar(6) default NULL,
  pg3_urinePr27 char(3) default NULL,
  pg3_urineGl27 char(3) default NULL,
  pg3_BP27 varchar(8) default NULL,
  pg3_comments27 varchar(255) default NULL,
  pg3_date28 date default NULL,
  pg3_gest28 varchar(6) default NULL,
  pg3_ht28 varchar(6) default NULL,
  pg3_wt28 varchar(6) default NULL,
  pg3_presn28 varchar(6) default NULL,
  pg3_FHR28 varchar(6) default NULL,
  pg3_urinePr28 char(3) default NULL,
  pg3_urineGl28 char(3) default NULL,
  pg3_BP28 varchar(8) default NULL,
  pg3_comments28 varchar(255) default NULL,
  pg3_date29 date default NULL,
  pg3_gest29 varchar(6) default NULL,
  pg3_ht29 varchar(6) default NULL,
  pg3_wt29 varchar(6) default NULL,
  pg3_presn29 varchar(6) default NULL,
  pg3_FHR29 varchar(6) default NULL,
  pg3_urinePr29 char(3) default NULL,
  pg3_urineGl29 char(3) default NULL,
  pg3_BP29 varchar(8) default NULL,
  pg3_comments29 varchar(255) default NULL,
  pg3_date30 date default NULL,
  pg3_gest30 varchar(6) default NULL,
  pg3_ht30 varchar(6) default NULL,
  pg3_wt30 varchar(6) default NULL,
  pg3_presn30 varchar(6) default NULL,
  pg3_FHR30 varchar(6) default NULL,
  pg3_urinePr30 char(3) default NULL,
  pg3_urineGl30 char(3) default NULL,
  pg3_BP30 varchar(8) default NULL,
  pg3_comments30 varchar(255) default NULL,
  pg3_date31 date default NULL,
  pg3_gest31 varchar(6) default NULL,
  pg3_ht31 varchar(6) default NULL,
  pg3_wt31 varchar(6) default NULL,
  pg3_presn31 varchar(6) default NULL,
  pg3_FHR31 varchar(6) default NULL,
  pg3_urinePr31 char(3) default NULL,
  pg3_urineGl31 char(3) default NULL,
  pg3_BP31 varchar(8) default NULL,
  pg3_comments31 varchar(255) default NULL,
  pg3_date32 date default NULL,
  pg3_gest32 varchar(6) default NULL,
  pg3_ht32 varchar(6) default NULL,
  pg3_wt32 varchar(6) default NULL,
  pg3_presn32 varchar(6) default NULL,
  pg3_FHR32 varchar(6) default NULL,
  pg3_urinePr32 char(3) default NULL,
  pg3_urineGl32 char(3) default NULL,
  pg3_BP32 varchar(8) default NULL,
  pg3_comments32 varchar(255) default NULL,
  pg3_date33 date default NULL,
  pg3_gest33 varchar(6) default NULL,
  pg3_ht33 varchar(6) default NULL,
  pg3_wt33 varchar(6) default NULL,
  pg3_presn33 varchar(6) default NULL,
  pg3_FHR33 varchar(6) default NULL,
  pg3_urinePr33 char(3) default NULL,
  pg3_urineGl33 char(3) default NULL,
  pg3_BP33 varchar(8) default NULL,
  pg3_comments33 varchar(255) default NULL,
  pg3_date34 date default NULL,
  pg3_gest34 varchar(6) default NULL,
  pg3_ht34 varchar(6) default NULL,
  pg3_wt34 varchar(6) default NULL,
  pg3_presn34 varchar(6) default NULL,
  pg3_FHR34 varchar(6) default NULL,
  pg3_urinePr34 char(3) default NULL,
  pg3_urineGl34 char(3) default NULL,
  pg3_BP34 varchar(8) default NULL,
  pg3_comments34 varchar(255) default NULL,
  pg3_date35 date default NULL,
  pg3_gest35 varchar(6) default NULL,
  pg3_ht35 varchar(6) default NULL,
  pg3_wt35 varchar(6) default NULL,
  pg3_presn35 varchar(6) default NULL,
  pg3_FHR35 varchar(6) default NULL,
  pg3_urinePr35 char(3) default NULL,
  pg3_urineGl35 char(3) default NULL,
  pg3_BP35 varchar(8) default NULL,
  pg3_comments35 varchar(255) default NULL,
  pg3_date36 date default NULL,
  pg3_gest36 varchar(6) default NULL,
  pg3_ht36 varchar(6) default NULL,
  pg3_wt36 varchar(6) default NULL,
  pg3_presn36 varchar(6) default NULL,
  pg3_FHR36 varchar(6) default NULL,
  pg3_urinePr36 char(3) default NULL,
  pg3_urineGl36 char(3) default NULL,
  pg3_BP36 varchar(8) default NULL,
  pg3_comments36 varchar(255) default NULL,
  pg4_date37 date default NULL,
  pg4_gest37 varchar(6) default NULL,
  pg4_ht37 varchar(6) default NULL,
  pg4_wt37 varchar(6) default NULL,
  pg4_presn37 varchar(6) default NULL,
  pg4_FHR37 varchar(6) default NULL,
  pg4_urinePr37 char(3) default NULL,
  pg4_urineGl37 char(3) default NULL,
  pg4_BP37 varchar(8) default NULL,
  pg4_comments37 varchar(255) default NULL,
  pg4_date38 date default NULL,
  pg4_gest38 varchar(6) default NULL,
  pg4_ht38 varchar(6) default NULL,
  pg4_wt38 varchar(6) default NULL,
  pg4_presn38 varchar(6) default NULL,
  pg4_FHR38 varchar(6) default NULL,
  pg4_urinePr38 char(3) default NULL,
  pg4_urineGl38 char(3) default NULL,
  pg4_BP38 varchar(8) default NULL,
  pg4_comments38 varchar(255) default NULL,
  pg4_date39 date default NULL,
  pg4_gest39 varchar(6) default NULL,
  pg4_ht39 varchar(6) default NULL,
  pg4_wt39 varchar(6) default NULL,
  pg4_presn39 varchar(6) default NULL,
  pg4_FHR39 varchar(6) default NULL,
  pg4_urinePr39 char(3) default NULL,
  pg4_urineGl39 char(3) default NULL,
  pg4_BP39 varchar(8) default NULL,
  pg4_comments39 varchar(255) default NULL,
  pg4_date40 date default NULL,
  pg4_gest40 varchar(6) default NULL,
  pg4_ht40 varchar(6) default NULL,
  pg4_wt40 varchar(6) default NULL,
  pg4_presn40 varchar(6) default NULL,
  pg4_FHR40 varchar(6) default NULL,
  pg4_urinePr40 char(3) default NULL,
  pg4_urineGl40 char(3) default NULL,
  pg4_BP40 varchar(8) default NULL,
  pg4_comments40 varchar(255) default NULL,
  pg4_date41 date default NULL,
  pg4_gest41 varchar(6) default NULL,
  pg4_ht41 varchar(6) default NULL,
  pg4_wt41 varchar(6) default NULL,
  pg4_presn41 varchar(6) default NULL,
  pg4_FHR41 varchar(6) default NULL,
  pg4_urinePr41 char(3) default NULL,
  pg4_urineGl41 char(3) default NULL,
  pg4_BP41 varchar(8) default NULL,
  pg4_comments41 varchar(255) default NULL,
  pg4_date42 date default NULL,
  pg4_gest42 varchar(6) default NULL,
  pg4_ht42 varchar(6) default NULL,
  pg4_wt42 varchar(6) default NULL,
  pg4_presn42 varchar(6) default NULL,
  pg4_FHR42 varchar(6) default NULL,
  pg4_urinePr42 char(3) default NULL,
  pg4_urineGl42 char(3) default NULL,
  pg4_BP42 varchar(8) default NULL,
  pg4_comments42 varchar(255) default NULL,
  pg4_date43 date default NULL,
  pg4_gest43 varchar(6) default NULL,
  pg4_ht43 varchar(6) default NULL,
  pg4_wt43 varchar(6) default NULL,
  pg4_presn43 varchar(6) default NULL,
  pg4_FHR43 varchar(6) default NULL,
  pg4_urinePr43 char(3) default NULL,
  pg4_urineGl43 char(3) default NULL,
  pg4_BP43 varchar(8) default NULL,
  pg4_comments43 varchar(255) default NULL,
  pg4_date44 date default NULL,
  pg4_gest44 varchar(6) default NULL,
  pg4_ht44 varchar(6) default NULL,
  pg4_wt44 varchar(6) default NULL,
  pg4_presn44 varchar(6) default NULL,
  pg4_FHR44 varchar(6) default NULL,
  pg4_urinePr44 char(3) default NULL,
  pg4_urineGl44 char(3) default NULL,
  pg4_BP44 varchar(8) default NULL,
  pg4_comments44 varchar(255) default NULL,
  pg4_date45 date default NULL,
  pg4_gest45 varchar(6) default NULL,
  pg4_ht45 varchar(6) default NULL,
  pg4_wt45 varchar(6) default NULL,
  pg4_presn45 varchar(6) default NULL,
  pg4_FHR45 varchar(6) default NULL,
  pg4_urinePr45 char(3) default NULL,
  pg4_urineGl45 char(3) default NULL,
  pg4_BP45 varchar(8) default NULL,
  pg4_comments45 varchar(255) default NULL,
  pg4_date46 date default NULL,
  pg4_gest46 varchar(6) default NULL,
  pg4_ht46 varchar(6) default NULL,
  pg4_wt46 varchar(6) default NULL,
  pg4_presn46 varchar(6) default NULL,
  pg4_FHR46 varchar(6) default NULL,
  pg4_urinePr46 char(3) default NULL,
  pg4_urineGl46 char(3) default NULL,
  pg4_BP46 varchar(8) default NULL,
  pg4_comments46 varchar(255) default NULL,
  pg4_date47 date default NULL,
  pg4_gest47 varchar(6) default NULL,
  pg4_ht47 varchar(6) default NULL,
  pg4_wt47 varchar(6) default NULL,
  pg4_presn47 varchar(6) default NULL,
  pg4_FHR47 varchar(6) default NULL,
  pg4_urinePr47 char(3) default NULL,
  pg4_urineGl47 char(3) default NULL,
  pg4_BP47 varchar(8) default NULL,
  pg4_comments47 varchar(255) default NULL,
  pg4_date48 date default NULL,
  pg4_gest48 varchar(6) default NULL,
  pg4_ht48 varchar(6) default NULL,
  pg4_wt48 varchar(6) default NULL,
  pg4_presn48 varchar(6) default NULL,
  pg4_FHR48 varchar(6) default NULL,
  pg4_urinePr48 char(3) default NULL,
  pg4_urineGl48 char(3) default NULL,
  pg4_BP48 varchar(8) default NULL,
  pg4_comments48 varchar(255) default NULL,
  pg4_date49 date default NULL,
  pg4_gest49 varchar(6) default NULL,
  pg4_ht49 varchar(6) default NULL,
  pg4_wt49 varchar(6) default NULL,
  pg4_presn49 varchar(6) default NULL,
  pg4_FHR49 varchar(6) default NULL,
  pg4_urinePr49 char(3) default NULL,
  pg4_urineGl49 char(3) default NULL,
  pg4_BP49 varchar(8) default NULL,
  pg4_comments49 varchar(255) default NULL,
  pg4_date50 date default NULL,
  pg4_gest50 varchar(6) default NULL,
  pg4_ht50 varchar(6) default NULL,
  pg4_wt50 varchar(6) default NULL,
  pg4_presn50 varchar(6) default NULL,
  pg4_FHR50 varchar(6) default NULL,
  pg4_urinePr50 char(3) default NULL,
  pg4_urineGl50 char(3) default NULL,
  pg4_BP50 varchar(8) default NULL,
  pg4_comments50 varchar(255) default NULL,
  pg4_date51 date default NULL,
  pg4_gest51 varchar(6) default NULL,
  pg4_ht51 varchar(6) default NULL,
  pg4_wt51 varchar(6) default NULL,
  pg4_presn51 varchar(6) default NULL,
  pg4_FHR51 varchar(6) default NULL,
  pg4_urinePr51 char(3) default NULL,
  pg4_urineGl51 char(3) default NULL,
  pg4_BP51 varchar(8) default NULL,
  pg4_comments51 varchar(255) default NULL,
  pg4_date52 date default NULL,
  pg4_gest52 varchar(6) default NULL,
  pg4_ht52 varchar(6) default NULL,
  pg4_wt52 varchar(6) default NULL,
  pg4_presn52 varchar(6) default NULL,
  pg4_FHR52 varchar(6) default NULL,
  pg4_urinePr52 char(3) default NULL,
  pg4_urineGl52 char(3) default NULL,
  pg4_BP52 varchar(8) default NULL,
  pg4_comments52 varchar(255) default NULL,
  pg4_date53 date default NULL,
  pg4_gest53 varchar(6) default NULL,
  pg4_ht53 varchar(6) default NULL,
  pg4_wt53 varchar(6) default NULL,
  pg4_presn53 varchar(6) default NULL,
  pg4_FHR53 varchar(6) default NULL,
  pg4_urinePr53 char(3) default NULL,
  pg4_urineGl53 char(3) default NULL,
  pg4_BP53 varchar(8) default NULL,
  pg4_comments53 varchar(255) default NULL,
  pg4_date54 date default NULL,
  pg4_gest54 varchar(6) default NULL,
  pg4_ht54 varchar(6) default NULL,
  pg4_wt54 varchar(6) default NULL,
  pg4_presn54 varchar(6) default NULL,
  pg4_FHR54 varchar(6) default NULL,
  pg4_urinePr54 char(3) default NULL,
  pg4_urineGl54 char(3) default NULL,
  pg4_BP54 varchar(8) default NULL,
  pg4_comments54 varchar(255) default NULL,
  ar2_uDate1 date,
  ar2_uGA1 varchar(10) default NULL,
  ar2_uResults1 varchar(50) default NULL,
  ar2_uDate2 date,
  ar2_uGA2 varchar(10) default NULL,
  ar2_uResults2 varchar(50) default NULL,
  ar2_uDate3 date,
  ar2_uGA3 varchar(10) default NULL,
  ar2_uResults3 varchar(50) default NULL,
  ar2_uDate4 date,
  ar2_uGA4 varchar(10) default NULL,
  ar2_uResults4 varchar(50) default NULL,
  ar2_hb varchar(10) default NULL,
  ar2_bloodGroup varchar(6) default NULL,
  ar2_rh varchar(6) default NULL,
  ar2_labABS varchar(10) default NULL,
  ar2_lab1GCT varchar(10) default NULL,
  ar2_lab2GTT varchar(10) default NULL,
  ar2_strep varchar(10) default NULL,
  ar2_exercise tinyint(1) default NULL,
  ar2_workPlan tinyint(1) default NULL,
  ar2_intercourse tinyint(1) default NULL,
  ar2_travel tinyint(1) default NULL,
  ar2_prenatal tinyint(1) default NULL,
  ar2_birth tinyint(1) default NULL,
  ar2_onCall tinyint(1) default NULL,
  ar2_preterm tinyint(1) default NULL,
  ar2_prom tinyint(1) default NULL,
  ar2_aph tinyint(1) default NULL,
  ar2_fetal tinyint(1) default NULL,
  ar2_admission tinyint(1) default NULL,
  ar2_pain tinyint(1) default NULL,
  ar2_labour tinyint(1) default NULL,
  ar2_breast tinyint(1) default NULL,
  ar2_circumcision tinyint(1) default NULL,
  ar2_dischargePlan tinyint(1) default NULL,
  ar2_car tinyint(1) default NULL,
  ar2_depression tinyint(1) default NULL,
  ar2_contraception tinyint(1) default NULL,
  ar2_postpartumCare tinyint(1) default NULL,
  pg2_signature varchar(50) default NULL,
  pg2_formDate date default NULL,
  pg2_signature2 varchar(50) default NULL,
  pg2_formDate2 date default NULL,
  pg3_signature varchar(50) default NULL,
  pg3_formDate date default NULL,
  pg3_signature2 varchar(50) default NULL,
  pg3_formDate2 date default NULL,
  pg4_signature varchar(50) default NULL,
  pg4_formDate date default NULL,
  pg4_signature2 varchar(50) default NULL,
  pg4_formDate2 date default NULL,
  PRIMARY KEY (ID)
) ;

CREATE TABLE `formovulation` (
  `ID` bigint(11) NOT NULL auto_increment,
  `demographic_no` bigint(11) NOT NULL default '0',
  `provider_no` bigint(11) default '0',
  `formCreated` date default '0000-00-00',
  `formEdited` timestamp NOT NULL default CURRENT_TIMESTAMP on update CURRENT_TIMESTAMP,
  `clientFirstName` varchar(30) default '',
  `clientLastName` varchar(30) default '',
  `dob` varchar(16) default '',
  `healthNum` varchar(24) default '',
  `workPhone` varchar(18) default '',
  `homePhone` varchar(18) default '',
  `otherPhone` varchar(18) default '',
  `diag` varchar(24) default '',
  `femara` varchar(24) default '',
  `tamoxi` varchar(24) default '',
  `ccNol` varchar(24) default '',
  `gonad` varchar(24) default '',
  `metForMin` varchar(24) default '',
  `parlodEl` varchar(24) default '',
  `folicAcid` varchar(24) default '',
  `ovul` varchar(24) default '',
  `postOv` varchar(24) default '',
  `iui` varchar(24) default '',
  `tdi` varchar(24) default '',
  `semenVolume` varchar(24) default '',
  `semenPMotility` varchar(24) default '',
  `semenTMotility` varchar(24) default '',
  `semenMorphology` varchar(24) default '',
  `semenConcentration` varchar(24) default '',
  `semenSperm` varchar(24) default '',
  `semenSpermPh` varchar(24) default '',
  `diagnosis` varchar(255) default '',
  `sideEffects` varchar(255) default '',
  `abnormalResult` varchar(255) default '',
  `previousCycles` varchar(255) default '',
  `fsh` varchar(24) default '',
  `collectionDate` varchar(24) default '',
  `abstinenceDays` varchar(24) default '',
  `collectionTime` varchar(24) default '',
  `collectionAmPm` varchar(24) default '',
  `collectionMethod` varchar(24) default '',
  `bmiAge` char(3) default '',
  `bmiPpWt` varchar(5) default '',
  `bmiPpHt` varchar(5) default '',
  `bmi` varchar(5) default '',
  `preColor` varchar(24) default '',
  `preViscosity` varchar(24) default '',
  `preLiquefaction` varchar(24) default '',
  `prePh` varchar(24) default '',
  `preRoundCells` varchar(24) default '',
  `preProgression` varchar(24) default '',
  `preVolume` varchar(24) default '',
  `preDensity` varchar(24) default '',
  `preMotility` varchar(24) default '',
  `preTmc` varchar(24) default '',
  `preMorphology` varchar(24) default '',
  `preAgglutination` varchar(24) default '',
  `preDebris` varchar(24) default '',
  `postProgression` varchar(24) default '',
  `postVolume` varchar(24) default '',
  `postDensity` varchar(24) default '',
  `postMotility` varchar(24) default '',
  `postTmc` varchar(24) default '',
  `date1` varchar(16) default '',
  `date2` varchar(16) default '',
  `date3` varchar(16) default '',
  `date4` varchar(16) default '',
  `date5` varchar(16) default '',
  `date6` varchar(16) default '',
  `date7` varchar(16) default '',
  `date8` varchar(16) default '',
  `date9` varchar(16) default '',
  `date10` varchar(16) default '',
  `date11` varchar(16) default '',
  `date12` varchar(16) default '',
  `day1` varchar(8) default '',
  `day2` varchar(8) default '',
  `day3` varchar(8) default '',
  `day4` varchar(8) default '',
  `day5` varchar(8) default '',
  `day6` varchar(8) default '',
  `day7` varchar(8) default '',
  `day8` varchar(8) default '',
  `day9` varchar(8) default '',
  `day10` varchar(8) default '',
  `day11` varchar(8) default '',
  `day12` varchar(8) default '',
  `e2Lh1a` varchar(12) default '',
  `e2Lh1b` varchar(12) default '',
  `e2Lh2a` varchar(12) default '',
  `e2Lh2b` varchar(12) default '',
  `e2Lh3a` varchar(12) default '',
  `e2Lh3b` varchar(12) default '',
  `e2Lh4a` varchar(12) default '',
  `e2Lh4b` varchar(12) default '',
  `e2Lh5a` varchar(12) default '',
  `e2Lh5b` varchar(12) default '',
  `e2Lh6a` varchar(12) default '',
  `e2Lh6b` varchar(12) default '',
  `e2Lh7a` varchar(12) default '',
  `e2Lh7b` varchar(12) default '',
  `e2Lh8a` varchar(12) default '',
  `e2Lh8b` varchar(12) default '',
  `e2Lh9a` varchar(12) default '',
  `e2Lh9b` varchar(12) default '',
  `e2Lh10a` varchar(12) default '',
  `e2Lh10b` varchar(12) default '',
  `e2Lh11a` varchar(12) default '',
  `e2Lh11b` varchar(12) default '',
  `e2Lh12a` varchar(12) default '',
  `e2Lh12b` varchar(12) default '',
  `tshPrl1a` varchar(12) default '',
  `tshPrl1b` varchar(12) default '',
  `tshPrl2a` varchar(12) default '',
  `tshPrl2b` varchar(12) default '',
  `tshPrl3a` varchar(12) default '',
  `tshPrl3b` varchar(12) default '',
  `tshPrl4a` varchar(12) default '',
  `tshPrl4b` varchar(12) default '',
  `tshPrl5a` varchar(12) default '',
  `tshPrl5b` varchar(12) default '',
  `tshPrl6a` varchar(12) default '',
  `tshPrl6b` varchar(12) default '',
  `tshPrl7a` varchar(12) default '',
  `tshPrl7b` varchar(12) default '',
  `tshPrl8a` varchar(12) default '',
  `tshPrl8b` varchar(12) default '',
  `tshPrl9a` varchar(12) default '',
  `tshPrl9b` varchar(12) default '',
  `tshPrl10a` varchar(12) default '',
  `tshPrl10b` varchar(12) default '',
  `tshPrl11a` varchar(12) default '',
  `tshPrl11b` varchar(12) default '',
  `tshPrl12a` varchar(12) default '',
  `tshPrl12b` varchar(12) default '',
  `progBhog1a` varchar(12) default '',
  `progBhog1b` varchar(12) default '',
  `progBhog2a` varchar(12) default '',
  `progBhog2b` varchar(12) default '',
  `progBhog3a` varchar(12) default '',
  `progBhog3b` varchar(12) default '',
  `progBhog4a` varchar(12) default '',
  `progBhog4b` varchar(12) default '',
  `progBhog5a` varchar(12) default '',
  `progBhog5b` varchar(12) default '',
  `progBhog6a` varchar(12) default '',
  `progBhog6b` varchar(12) default '',
  `progBhog7a` varchar(12) default '',
  `progBhog7b` varchar(12) default '',
  `progBhog8a` varchar(12) default '',
  `progBhog8b` varchar(12) default '',
  `progBhog9a` varchar(12) default '',
  `progBhog9b` varchar(12) default '',
  `progBhog10a` varchar(12) default '',
  `progBhog10b` varchar(12) default '',
  `progBhog11a` varchar(12) default '',
  `progBhog11b` varchar(12) default '',
  `progBhog12a` varchar(12) default '',
  `progBhog12b` varchar(12) default '',
  `flag_e2Lh1a` varchar(8) default '',
  `flag_e2Lh1b` varchar(8) default '',
  `flag_e2Lh2a` varchar(8) default '',
  `flag_e2Lh2b` varchar(8) default '',
  `flag_e2Lh3a` varchar(8) default '',
  `flag_e2Lh3b` varchar(8) default '',
  `flag_e2Lh4a` varchar(8) default '',
  `flag_e2Lh4b` varchar(8) default '',
  `flag_e2Lh5a` varchar(8) default '',
  `flag_e2Lh5b` varchar(8) default '',
  `flag_e2Lh6a` varchar(8) default '',
  `flag_e2Lh6b` varchar(8) default '',
  `flag_e2Lh7a` varchar(8) default '',
  `flag_e2Lh7b` varchar(8) default '',
  `flag_e2Lh8a` varchar(8) default '',
  `flag_e2Lh8b` varchar(8) default '',
  `flag_e2Lh9a` varchar(8) default '',
  `flag_e2Lh9b` varchar(8) default '',
  `flag_e2Lh10a` varchar(8) default '',
  `flag_e2Lh10b` varchar(8) default '',
  `flag_e2Lh11a` varchar(8) default '',
  `flag_e2Lh11b` varchar(8) default '',
  `flag_e2Lh12a` varchar(8) default '',
  `flag_e2Lh12b` varchar(8) default '',
  `flag_tshPrl1a` varchar(8) default '',
  `flag_tshPrl1b` varchar(8) default '',
  `flag_tshPrl2a` varchar(8) default '',
  `flag_tshPrl2b` varchar(8) default '',
  `flag_tshPrl3a` varchar(8) default '',
  `flag_tshPrl3b` varchar(8) default '',
  `flag_tshPrl4a` varchar(8) default '',
  `flag_tshPrl4b` varchar(8) default '',
  `flag_tshPrl5a` varchar(8) default '',
  `flag_tshPrl5b` varchar(8) default '',
  `flag_tshPrl6a` varchar(8) default '',
  `flag_tshPrl6b` varchar(8) default '',
  `flag_tshPrl7a` varchar(8) default '',
  `flag_tshPrl7b` varchar(8) default '',
  `flag_tshPrl8a` varchar(8) default '',
  `flag_tshPrl8b` varchar(8) default '',
  `flag_tshPrl9a` varchar(8) default '',
  `flag_tshPrl9b` varchar(8) default '',
  `flag_tshPrl10a` varchar(8) default '',
  `flag_tshPrl10b` varchar(8) default '',
  `flag_tshPrl11a` varchar(8) default '',
  `flag_tshPrl11b` varchar(8) default '',
  `flag_tshPrl12a` varchar(8) default '',
  `flag_tshPrl12b` varchar(8) default '',
  `flag_progBhog1a` varchar(8) default '',
  `flag_progBhog1b` varchar(8) default '',
  `flag_progBhog2a` varchar(8) default '',
  `flag_progBhog2b` varchar(8) default '',
  `flag_progBhog3a` varchar(8) default '',
  `flag_progBhog3b` varchar(8) default '',
  `flag_progBhog4a` varchar(8) default '',
  `flag_progBhog4b` varchar(8) default '',
  `flag_progBhog5a` varchar(8) default '',
  `flag_progBhog5b` varchar(8) default '',
  `flag_progBhog6a` varchar(8) default '',
  `flag_progBhog6b` varchar(8) default '',
  `flag_progBhog7a` varchar(8) default '',
  `flag_progBhog7b` varchar(8) default '',
  `flag_progBhog8a` varchar(8) default '',
  `flag_progBhog8b` varchar(8) default '',
  `flag_progBhog9a` varchar(8) default '',
  `flag_progBhog9b` varchar(8) default '',
  `flag_progBhog10a` varchar(8) default '',
  `flag_progBhog10b` varchar(8) default '',
  `flag_progBhog11a` varchar(8) default '',
  `flag_progBhog11b` varchar(8) default '',
  `flag_progBhog12a` varchar(8) default '',
  `flag_progBhog12b` varchar(8) default '',
  `rightCyst1a` varchar(24) default '',
  `rightCyst1b` varchar(24) default '',
  `rightCyst2a` varchar(24) default '',
  `rightCyst2b` varchar(24) default '',
  `rightCyst3a` varchar(24) default '',
  `rightCyst3b` varchar(24) default '',
  `rightCyst4a` varchar(24) default '',
  `rightCyst4b` varchar(24) default '',
  `rightCyst5a` varchar(24) default '',
  `rightCyst5b` varchar(24) default '',
  `rightCyst6a` varchar(24) default '',
  `rightCyst6b` varchar(24) default '',
  `rightCyst7a` varchar(24) default '',
  `rightCyst7b` varchar(24) default '',
  `rightCyst8a` varchar(24) default '',
  `rightCyst8b` varchar(24) default '',
  `rightCyst9a` varchar(24) default '',
  `rightCyst9b` varchar(24) default '',
  `rightCyst10a` varchar(24) default '',
  `rightCyst10b` varchar(24) default '',
  `rightCyst11a` varchar(24) default '',
  `rightCyst11b` varchar(24) default '',
  `rightCyst12a` varchar(24) default '',
  `rightCyst12b` varchar(24) default '',
  `leftCyst1a` varchar(24) default '',
  `leftCyst1b` varchar(24) default '',
  `leftCyst2a` varchar(24) default '',
  `leftCyst2b` varchar(24) default '',
  `leftCyst3a` varchar(24) default '',
  `leftCyst3b` varchar(24) default '',
  `leftCyst4a` varchar(24) default '',
  `leftCyst4b` varchar(24) default '',
  `leftCyst5a` varchar(24) default '',
  `leftCyst5b` varchar(24) default '',
  `leftCyst6a` varchar(24) default '',
  `leftCyst6b` varchar(24) default '',
  `leftCyst7a` varchar(24) default '',
  `leftCyst7b` varchar(24) default '',
  `leftCyst8a` varchar(24) default '',
  `leftCyst8b` varchar(24) default '',
  `leftCyst9a` varchar(24) default '',
  `leftCyst9b` varchar(24) default '',
  `leftCyst10a` varchar(24) default '',
  `leftCyst10b` varchar(24) default '',
  `leftCyst11a` varchar(24) default '',
  `leftCyst11b` varchar(24) default '',
  `leftCyst12a` varchar(24) default '',
  `leftCyst12b` varchar(24) default '',
  `etTEX1a` varchar(24) default '',
  `etTEX1b` varchar(24) default '',
  `etTEX2a` varchar(24) default '',
  `etTEX2b` varchar(24) default '',
  `etTEX3a` varchar(24) default '',
  `etTEX3b` varchar(24) default '',
  `etTEX4a` varchar(24) default '',
  `etTEX4b` varchar(24) default '',
  `etTEX5a` varchar(24) default '',
  `etTEX5b` varchar(24) default '',
  `etTEX6a` varchar(24) default '',
  `etTEX6b` varchar(24) default '',
  `etTEX7a` varchar(24) default '',
  `etTEX7b` varchar(24) default '',
  `etTEX8a` varchar(24) default '',
  `etTEX8b` varchar(24) default '',
  `etTEX9a` varchar(24) default '',
  `etTEX9b` varchar(24) default '',
  `etTEX10a` varchar(24) default '',
  `etTEX10b` varchar(24) default '',
  `etTEX11a` varchar(24) default '',
  `etTEX11b` varchar(24) default '',
  `etTEX12a` varchar(24) default '',
  `etTEX12b` varchar(24) default '',
  `ff1` varchar(12) default '',
  `ff2` varchar(12) default '',
  `ff3` varchar(12) default '',
  `ff4` varchar(12) default '',
  `ff5` varchar(12) default '',
  `ff6` varchar(12) default '',
  `ff7` varchar(12) default '',
  `ff8` varchar(12) default '',
  `ff9` varchar(12) default '',
  `ff10` varchar(12) default '',
  `ff11` varchar(12) default '',
  `ff12` varchar(12) default '',
  `rightLo1` varchar(255) default '',
  `rightLo2` varchar(255) default '',
  `rightLo3` varchar(255) default '',
  `rightLo4` varchar(255) default '',
  `rightLo5` varchar(255) default '',
  `rightLo6` varchar(255) default '',
  `rightLo7` varchar(255) default '',
  `rightLo8` varchar(255) default '',
  `rightLo9` varchar(255) default '',
  `rightLo10` varchar(255) default '',
  `rightLo11` varchar(255) default '',
  `rightLo12` varchar(255) default '',
  `leftLo1` varchar(255) default '',
  `leftLo2` varchar(255) default '',
  `leftLo3` varchar(255) default '',
  `leftLo4` varchar(255) default '',
  `leftLo5` varchar(255) default '',
  `leftLo6` varchar(255) default '',
  `leftLo7` varchar(255) default '',
  `leftLo8` varchar(255) default '',
  `leftLo9` varchar(255) default '',
  `leftLo10` varchar(255) default '',
  `leftLo11` varchar(255) default '',
  `leftLo12` varchar(255) default '',
  `meds1` varchar(255) default '',
  `meds2` varchar(255) default '',
  `meds3` varchar(255) default '',
  `meds4` varchar(255) default '',
  `meds5` varchar(255) default '',
  `meds6` varchar(255) default '',
  `meds7` varchar(255) default '',
  `meds8` varchar(255) default '',
  `meds9` varchar(255) default '',
  `meds10` varchar(255) default '',
  `meds11` varchar(255) default '',
  `meds12` varchar(255) default '',
  `comment1` varchar(255) default '',
  `comment2` varchar(255) default '',
  `comment3` varchar(255) default '',
  `comment4` varchar(255) default '',
  `comment5` varchar(255) default '',
  `comment6` varchar(255) default '',
  `comment7` varchar(255) default '',
  `comment8` varchar(255) default '',
  `comment9` varchar(255) default '',
  `comment10` varchar(255) default '',
  `comment11` varchar(255) default '',
  `comment12` varchar(255) default '',
  `postComment` varchar(255) default '',
  PRIMARY KEY  (`ID`)
);

CREATE TABLE billing_on_diskname (
  id int(11) NOT NULL auto_increment,
  monthCode char(1) default '',
  batchcount int(3),
  ohipfilename varchar(50),
  groupno varchar(6) default NULL,
  creator char(6) default NULL,
  claimrecord varchar(10) default null,
  createdatetime datetime,
  status char(1) default NULL,
  total varchar(20) default null,
  timestamp timestamp,
  PRIMARY KEY  (id)
) ;

CREATE TABLE billing_on_filename (
  id int(11) NOT NULL auto_increment,
  disk_id int(11) NOT NULL,
  htmlfilename varchar(50),
  providerohipno varchar(6) default NULL,
  providerno char(6) NOT NULL,
  claimrecord varchar(10) default null,
  status char(1) default NULL,
  total varchar(20) default null,
  timestamp timestamp,
  PRIMARY KEY  (id)
) ;

CREATE TABLE billing_on_repo (
  id int(11) NOT NULL auto_increment,
  h_id int(11) NOT NULL,
  category varchar(60),
  content text,
  createdatetime datetime,
  PRIMARY KEY  (id)
) ;

CREATE TABLE billing_on_proc (
  id int(11) NOT NULL auto_increment,
  creator varchar(6),
  action varchar(60)  default '',
  comment varchar(200)  default '',
  object varchar(60) default '',
  createdatetime datetime,
  PRIMARY KEY  (id)
) ;

CREATE TABLE billing_on_header (
  id int(11) NOT NULL auto_increment,
  disk_id int(11) NOT NULL,
  transc_id char(2) default 'HE',
  rec_id char(1) default 'B',
  spec_id char(3) default 'V03',
  moh_office char(1) default '',
  batch_id varchar(12) default '',
  operator varchar(6) default '',
  group_num char(4) default '0000',
  provider_reg_num varchar(6) default '',
  specialty char(2) default '00',
  h_count varchar(4) default '0000',
  r_count varchar(4) default '0000',
  t_count varchar(5) default '00000',
  batch_date date,

  createdatetime datetime,
  updatedatetime datetime,
  creator varchar(6) default '',
  action varchar(60)  default '',
  comment varchar(200)  default '',
  PRIMARY KEY  (id)
) ;

CREATE TABLE billing_on_cheader1 (
  id int(12) NOT NULL auto_increment,
  header_id int(11) NOT NULL,
  transc_id char(2) default 'HE',
  rec_id char(1) default 'H',
  hin char(10) default NULL,
  ver char(2) default '  ',
  dob char(8) default NULL,
  ##acc_num char(8) default NULL,
  pay_program char(3) default 'HCP',
  payee char(1) default 'P',
  ref_num varchar(6) default NULL,
  facilty_num varchar(4) default NULL,
  admission_date varchar(10) default NULL,
  ref_lab_num varchar(4) default NULL,
  man_review char(1) default NULL,
  location varchar(4) default NULL,

  demographic_no int(10) NOT NULL default '0',
  provider_no varchar(6) NOT NULL default '',
  appointment_no int(12) default NULL,
  demographic_name varchar(20) default NULL,
  sex char(1) default '1',
  province char(2) default 'ON',
  billing_date date default NULL,
  billing_time time default NULL,
  total varchar(7) default NULL,
  paid varchar(7) default NULL,
  status char(1) default NULL,
  comment1 varchar(255) default NULL,
  visittype char(2) default NULL,
  provider_ohip_no varchar(20) default NULL,
  provider_rma_no varchar(20) default NULL,
  apptProvider_no varchar(6) default NULL,
  asstProvider_no varchar(6) default NULL,
  creator varchar(6) default NULL,
  timestamp1 timestamp,
  clinic varchar(30) default NULL,

  PRIMARY KEY  (id),
  KEY appointment_no (appointment_no,demographic_no),
  KEY demographic_no (demographic_no),
  KEY billing_date (billing_date),
  KEY provider_no (provider_no),
  KEY provider_ohip_no (provider_ohip_no),
  KEY apptProvider_no (apptProvider_no),
  KEY creator (creator),
  KEY clinic (clinic),
  KEY status (status)
) ;

CREATE TABLE billing_on_cheader2 (
  id int(12) NOT NULL auto_increment,
  ch1_id int(12) NOT NULL ,
  transc_id char(2) default 'HE',
  rec_id char(1) default 'R',
  hin char(12) default NULL,
  last_name char(9) default '  ',
  first_name char(5) default NULL,
  sex char(1) default '1',
  province char(2) default 'AB',
  timestamp timestamp,
  PRIMARY KEY  (id),
  KEY ch1_id (ch1_id)
) ;

CREATE TABLE billing_on_item (
  id int(12) NOT NULL auto_increment,
  ch1_id int(12) NOT NULL ,
  transc_id char(2) default 'HE',
  rec_id char(1) default 'T',
  service_code char(20) default NULL,
  fee varchar(7) default '',
  ser_num char(2) default '01',
  service_date date,
  dx char(4) default '',
  dx1 char(4) default '',
  dx2 char(4) default '',

  status char(1) default NULL,
  timestamp timestamp,
  PRIMARY KEY  (id),
  KEY ch1_id (ch1_id)
) ;

CREATE TABLE billing_on_favourite (
  id int(12) NOT NULL auto_increment,
  name varchar(60) default '',
  service_dx varchar(255) default '',
  provider_no varchar(6) default null,
  timestamp timestamp,
  deleted boolean NOT NULL default false,
  PRIMARY KEY  (id)
) ;

CREATE TABLE billing_private_service (
  id int(6) NOT NULL auto_increment,
  service_code varchar(10) default NULL,
  description varchar(255),
  value varchar(8) default NULL,
  percentage varchar(8) default NULL,
  update_date date default NULL,
  PRIMARY KEY  (id)
) ;

CREATE TABLE billing_payment_type (
  id int(11) NOT NULL auto_increment,
  payment_type varchar(25) NOT NULL default '',
  PRIMARY KEY  (id)
) ;

CREATE TABLE billing_on_errorCode (
  code varchar(5) NOT NULL,
  description varchar(255) NOT NULL default '',
  PRIMARY KEY  (code)
) ;

CREATE TABLE billing_on_3rdPartyAddress (
  id int(6) NOT NULL auto_increment,
  attention varchar(100) NOT NULL,
  company_name varchar(100) NOT NULL,
  address varchar(200) NOT NULL default '',
  city varchar(200) NOT NULL default '',
  province varchar(10) NOT NULL default '',
  postcode varchar(10) NOT NULL default '',
  telephone varchar(15) NOT NULL default '',
  fax varchar(15) NOT NULL default '',
  PRIMARY KEY  (id)
) ;

CREATE TABLE billing_on_eareport (
  id int(12) NOT NULL auto_increment,
  providerohip_no varchar(6),
  group_no varchar(6) default '0000',
  specialty char(2) default '00',
  process_date date,
  hin varchar(12),
  ver char(2),
  dob date,
  billing_no int(6),
  ref_no varchar(6),
  facility varchar(4),
  admitted_date varchar(8),
  claim_error varchar(20),
  code varchar(5),
  fee varchar(10), 
  unit varchar(2),
  code_date date,
  dx varchar(5),
  exp varchar(60),
  code_error varchar(20),
  report_name varchar(20)  default '',
  status char(1) default 'N',
  comment varchar(100),

  PRIMARY KEY  (id),
  key (providerohip_no),
  key (code_date),
  key (process_date)
) ;

CREATE TABLE billing_on_ext (
  id int(12) NOT NULL auto_increment,
  billing_no int(6),
  demographic_no int(10) NOT NULL default '0',
  key_val varchar(50),
  value varchar(255) ,
  date_time datetime,
  status char(1) default '1',
  PRIMARY KEY  (id),
  key (key_val),
  key (billing_no)
) ;

CREATE TABLE ctl_billingtype (
    servicetype varchar(10) not null,
    billtype    varchar(5)  not null,
    primary key (servicetype)
);

CREATE TABLE `formLabReq07` (
  	`ID` int(10) NOT NULL auto_increment,
	`formEdited` timestamp NOT NULL default CURRENT_TIMESTAMP on update CURRENT_TIMESTAMP,
	`b_glucose` tinyint(1) default NULL,
	`b_glucose_random` tinyint(1) default NULL,
	`b_glucose_fasting` tinyint(1) default NULL,
	`b_hba1c` tinyint(1) default NULL,
	`b_creatinine` tinyint(1) default NULL,
	`b_uricAcid` tinyint(1) default NULL,
	`b_sodium` tinyint(1) default NULL,
	`b_potassium` tinyint(1) default NULL,
	`b_chloride` tinyint(1) default NULL,
	`b_ck` tinyint(1) default NULL,
	`b_alt` tinyint(1) default NULL,
	`b_alkPhosphatase` tinyint(1) default NULL,
	`ohip` tinyint(1) default NULL,
	`formCreated` date default NULL,
	`patientFirstName` varchar(40) default NULL,
	`b_timeNextDose2` varchar(20) default NULL,
	`clinicCity` varchar(40) default NULL,
	`b_timeNextDose1` varchar(20) default NULL,
	`b_timeLastDose2` varchar(20) default NULL,
	`b_timeLastDose1` varchar(20) default NULL,
	`provider_no` int(11) default NULL,
	`m_vaginalRectal` tinyint(1) default NULL,
	`m_vaginal` tinyint(1) default NULL,
	`b_acRatioUrine` tinyint(1) default NULL,
	`healthNumber` varchar(20) default NULL,
	`patientCity` varchar(40) default NULL,
	`b_patientsTelNo` varchar(40) default NULL,
        `clinicianContactUrgent` varchar(40) default NULL,
	`b_childsAgeDays` varchar(20) default NULL,
	`b_tsh` tinyint(1) default NULL,
	`b_timeCollected2` varchar(20) default NULL,
	`b_timeCollected1` varchar(20) default NULL,
	`b_therapeuticDrugMonitoring` tinyint(1) default NULL,
	`i_rubella` tinyint(1) default NULL,
	`m_cervical` tinyint(1) default NULL,
	`patientAddress` varchar(60) default NULL,
	`b_vitaminB12` tinyint(1) default NULL,
	`m_blank` tinyint(1) default NULL,
	`reqProvName` varchar(60) default NULL,
	`v_chronicHepatitis` tinyint(1) default NULL,
	`version` varchar(6) default NULL,
	`oprn` varchar(40) default NULL,
	`b_albumin` tinyint(1) default NULL,
	`aci` text,
	`patientPC` varchar(10) default NULL,
	`b_urinalysis` tinyint(1) default NULL,
	`h_cbc` tinyint(1) default NULL,
	`form_class` tinyint(1) default NULL,
	`sex` varchar(8) default NULL,
	`i_pregnancyTest` tinyint(1) default NULL,
	`submit` tinyint(1) default NULL,
	`v_acuteHepatitis` tinyint(1) default NULL,
	`birthDate` date default NULL,
	`patientBirthMth` varchar(25) default NULL,
	`phoneNumber` varchar(20) default NULL,
	`m_otherSwabsSource` varchar(60) default NULL,
	`m_otherSwabsPus` tinyint(1) default NULL,
	`clinicAddress` varchar(100) default NULL,
	`m_gcSource` varchar(60) default NULL,
	`b_childsAgeHours` varchar(20) default NULL,
	`m_throat` tinyint(1) default NULL,
	`patientLastName` varchar(40) default NULL,
	`m_sputum` tinyint(1) default NULL,
	`b_neonatalBilirubin` tinyint(1) default NULL,
	`m_fecalOccultBlood` tinyint(1) default NULL,
	`m_urine` tinyint(1) default NULL,
        `m_blankText` varchar(100) default NULL,
	`b_nameDrug2` varchar(100) default NULL,
	`m_stoolOvaParasites` tinyint(1) default NULL,
	`b_nameDrug1` varchar(100) default NULL,
	`m_gc` tinyint(1) default NULL,
	`i_prenatal` tinyint(1) default NULL,
	`h_prothrombinTime` tinyint(1) default NULL,
	`patientBirthYear` varchar(10) default NULL,
	`m_chlamydiaSource` varchar(60) default NULL,
	`i_repeatPrenatalAntibodies` tinyint(1) default NULL,
	`b_ferritin` tinyint(1) default NULL,
	`wcb` tinyint(1) default NULL,
	`v_immuneStatus` tinyint(1) default NULL,
	`m_stoolCulture` tinyint(1) default NULL,
	`province` varchar(20) default NULL,
	`m_woundSource` varchar(60) default NULL,
	`patientBirthDay` varchar(30) default NULL,
	`demographic_no` int(11) default NULL,
	`i_mononucleosisScreen` tinyint(1) default NULL,
	`b_lipidAssessment` tinyint(1) default NULL,
	`m_wound` tinyint(1) default NULL,
	`provName` varchar(60) default NULL,
	`thirdParty` tinyint(1) default NULL,
	`clinicName` varchar(60) default NULL,
	`b_bilirubin` tinyint(1) default NULL,
        `m_specimenCollectionTime` varchar(15) default NULL,
	`o_otherTests16` varchar(150) default NULL,
	`o_otherTests15` varchar(150) default NULL,
	`o_otherTests14` varchar(150) default NULL,
	`o_otherTests13` varchar(150) default NULL,
	`o_otherTests12` varchar(150) default NULL,
	`o_otherTests11` varchar(150) default NULL,
	`o_otherTests10` varchar(150) default NULL,
	`o_otherTests9` varchar(150) default NULL,
	`o_otherTests8` varchar(150) default NULL,
	`o_otherTests7` varchar(150) default NULL,
	`o_otherTests6` varchar(150) default NULL,
	`o_specimenCollectionDate` date default NULL,
	`o_otherTests5` varchar(150) default NULL,
	`clinicPC` varchar(10) default NULL,
	`o_otherTests4` varchar(150) default NULL,
	`o_otherTests3` varchar(150) default NULL,
	`o_otherTests2` varchar(150) default NULL,
	`b_cliniciansTelNo` varchar(40) default NULL,
	`o_otherTests1` varchar(150) default NULL,
	`patientName` varchar(40) default NULL,
	`b_dateSigned` date default NULL,
	`practitionerNo` varchar(20) default NULL,
	`m_chlamydia` tinyint(1) default NULL,
	`v_immune_HepatitisC` tinyint(1) default NULL,
	`v_immune_HepatitisB` tinyint(1) default NULL,
	`v_immune_HepatitisA` tinyint(1) default NULL,
	PRIMARY KEY  (`ID`)
) ;


