package org.oscar.model;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * Provider generated by hbm2java
 */
@Entity
@Table(name = "provider", catalog = "oscar_devel")
public class Provider implements java.io.Serializable {

	private String providerNo;
	private String lastName;
	private String firstName;
	private String providerType;
	private String specialty;
	private String team;
	private char sex;
	private Date dob;
	private String address;
	private String phone;
	private String workPhone;
	private String ohipNo;
	private String rmaNo;
	private String billingNo;
	private String hsoNo;
	private Character status;
	private String comments;
	private String providerActivity;
	private String practitionerNo;
	private Set<Integratorconsent> integratorconsents = new HashSet<Integratorconsent>(
			0);

	public Provider() {
	}

	public Provider(String providerNo, String lastName, String firstName,
			String providerType, String specialty, char sex) {
		this.providerNo = providerNo;
		this.lastName = lastName;
		this.firstName = firstName;
		this.providerType = providerType;
		this.specialty = specialty;
		this.sex = sex;
	}
	public Provider(String providerNo, String lastName, String firstName,
			String providerType, String specialty, String team, char sex,
			Date dob, String address, String phone, String workPhone,
			String ohipNo, String rmaNo, String billingNo, String hsoNo,
			Character status, String comments, String providerActivity,
			String practitionerNo, Set<Integratorconsent> integratorconsents) {
		this.providerNo = providerNo;
		this.lastName = lastName;
		this.firstName = firstName;
		this.providerType = providerType;
		this.specialty = specialty;
		this.team = team;
		this.sex = sex;
		this.dob = dob;
		this.address = address;
		this.phone = phone;
		this.workPhone = workPhone;
		this.ohipNo = ohipNo;
		this.rmaNo = rmaNo;
		this.billingNo = billingNo;
		this.hsoNo = hsoNo;
		this.status = status;
		this.comments = comments;
		this.providerActivity = providerActivity;
		this.practitionerNo = practitionerNo;
		this.integratorconsents = integratorconsents;
	}

	@Id
	@Column(name = "provider_no", unique = true, nullable = false, length = 6)
	@NotNull
	@Length(max = 6)
	public String getProviderNo() {
		return this.providerNo;
	}

	public void setProviderNo(String providerNo) {
		this.providerNo = providerNo;
	}

	@Column(name = "last_name", nullable = false, length = 30)
	@NotNull
	@Length(max = 30)
	public String getLastName() {
		return this.lastName;
	}

	public void setLastName(String lastName) {
		this.lastName = lastName;
	}

	@Column(name = "first_name", nullable = false, length = 30)
	@NotNull
	@Length(max = 30)
	public String getFirstName() {
		return this.firstName;
	}

	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}

	@Column(name = "provider_type", nullable = false, length = 15)
	@NotNull
	@Length(max = 15)
	public String getProviderType() {
		return this.providerType;
	}

	public void setProviderType(String providerType) {
		this.providerType = providerType;
	}

	@Column(name = "specialty", nullable = false, length = 20)
	@NotNull
	@Length(max = 20)
	public String getSpecialty() {
		return this.specialty;
	}

	public void setSpecialty(String specialty) {
		this.specialty = specialty;
	}

	@Column(name = "team", length = 20)
	@Length(max = 20)
	public String getTeam() {
		return this.team;
	}

	public void setTeam(String team) {
		this.team = team;
	}

	@Column(name = "sex", nullable = false, length = 1)
	@NotNull
	public char getSex() {
		return this.sex;
	}

	public void setSex(char sex) {
		this.sex = sex;
	}
	@Temporal(TemporalType.DATE)
	@Column(name = "dob", length = 10)
	public Date getDob() {
		return this.dob;
	}

	public void setDob(Date dob) {
		this.dob = dob;
	}

	@Column(name = "address", length = 40)
	@Length(max = 40)
	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	@Column(name = "phone", length = 20)
	@Length(max = 20)
	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	@Column(name = "work_phone", length = 50)
	@Length(max = 50)
	public String getWorkPhone() {
		return this.workPhone;
	}

	public void setWorkPhone(String workPhone) {
		this.workPhone = workPhone;
	}

	@Column(name = "ohip_no", length = 20)
	@Length(max = 20)
	public String getOhipNo() {
		return this.ohipNo;
	}

	public void setOhipNo(String ohipNo) {
		this.ohipNo = ohipNo;
	}

	@Column(name = "rma_no", length = 20)
	@Length(max = 20)
	public String getRmaNo() {
		return this.rmaNo;
	}

	public void setRmaNo(String rmaNo) {
		this.rmaNo = rmaNo;
	}

	@Column(name = "billing_no", length = 20)
	@Length(max = 20)
	public String getBillingNo() {
		return this.billingNo;
	}

	public void setBillingNo(String billingNo) {
		this.billingNo = billingNo;
	}

	@Column(name = "hso_no", length = 10)
	@Length(max = 10)
	public String getHsoNo() {
		return this.hsoNo;
	}

	public void setHsoNo(String hsoNo) {
		this.hsoNo = hsoNo;
	}

	@Column(name = "status", length = 1)
	public Character getStatus() {
		return this.status;
	}

	public void setStatus(Character status) {
		this.status = status;
	}

	@Column(name = "comments", length = 65535)
	@Length(max = 65535)
	public String getComments() {
		return this.comments;
	}

	public void setComments(String comments) {
		this.comments = comments;
	}

	@Column(name = "provider_activity", length = 3)
	@Length(max = 3)
	public String getProviderActivity() {
		return this.providerActivity;
	}

	public void setProviderActivity(String providerActivity) {
		this.providerActivity = providerActivity;
	}

	@Column(name = "practitionerNo", length = 20)
	@Length(max = 20)
	public String getPractitionerNo() {
		return this.practitionerNo;
	}

	public void setPractitionerNo(String practitionerNo) {
		this.practitionerNo = practitionerNo;
	}
	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "provider")
	public Set<Integratorconsent> getIntegratorconsents() {
		return this.integratorconsents;
	}

	public void setIntegratorconsents(Set<Integratorconsent> integratorconsents) {
		this.integratorconsents = integratorconsents;
	}

}
