/**
 *
 * Copyright (c) 2005-2012. Centre for Research on Inner City Health, St. Michael's Hospital, Toronto. All Rights Reserved.
 * This software is published under the GPL GNU General Public License.
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; either version 2
 * of the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA 02111-1307, USA.
 *
 * This software was written for
 * Centre for Research on Inner City Health, St. Michael's Hospital,
 * Toronto, Ontario, Canada
 */

//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-793 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.05.24 at 10:52:14 PM EDT 
//


package oscar.ocan.domain.staff;

import java.math.BigInteger;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}C1__Does_the_person_have_problems_with_drug_misuse___If_rated_0_or_9__skip_questions_2___3_and_p"/>
 *         &lt;element ref="{}C2__How_much_help_with_drug_misuse_does_the_person_receive_from_friends_or_relatives_"/>
 *         &lt;element ref="{}C3a__How_much_help_with_drug_misuse_does_the_person_receive_from_local_services_"/>
 *         &lt;element ref="{}C3b__How_much_help_with_drug_misuse_does_the_person_need_from_local_services_"/>
 *         &lt;element ref="{}CComments_"/>
 *         &lt;element ref="{}CActions_"/>
 *         &lt;element ref="{}CBy_whom_"/>
 *         &lt;element ref="{}CReview_date_"/>
 *         &lt;element ref="{}CWhich_of_the_following_drugs_have_you_used___check_all_that_apply_"/>
 *         &lt;element ref="{}CIndicate_the_stage_of_change_client_is_at__Optional__select_one_"/>
 *         &lt;element ref="{}CHow_has_the_substance_s__of_choice_had_an_impact_on_your_life_"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "c1DoesThePersonHaveProblemsWithDrugMisuseIfRated0Or9SkipQuestions23AndP",
    "c2HowMuchHelpWithDrugMisuseDoesThePersonReceiveFromFriendsOrRelatives",
    "c3AHowMuchHelpWithDrugMisuseDoesThePersonReceiveFromLocalServices",
    "c3BHowMuchHelpWithDrugMisuseDoesThePersonNeedFromLocalServices",
    "cComments",
    "cActions",
    "cByWhom",
    "cReviewDate",
    "cWhichOfTheFollowingDrugsHaveYouUsedCheckAllThatApply",
    "cIndicateTheStageOfChangeClientIsAtOptionalSelectOne",
    "cHowHasTheSubstanceSOfChoiceHadAnImpactOnYourLife"
})
@XmlRootElement(name = "C13__Drugs__Do_you_take_drugs_that_aren_t_prescribed__Are_there_any_drugs_you_would_find_hard_to")
public class C13DrugsDoYouTakeDrugsThatArenTPrescribedAreThereAnyDrugsYouWouldFindHardTo {

    @XmlElement(name = "C1__Does_the_person_have_problems_with_drug_misuse___If_rated_0_or_9__skip_questions_2___3_and_p", required = true)
    protected BigInteger c1DoesThePersonHaveProblemsWithDrugMisuseIfRated0Or9SkipQuestions23AndP;
    @XmlElement(name = "C2__How_much_help_with_drug_misuse_does_the_person_receive_from_friends_or_relatives_", required = true)
    protected BigInteger c2HowMuchHelpWithDrugMisuseDoesThePersonReceiveFromFriendsOrRelatives;
    @XmlElement(name = "C3a__How_much_help_with_drug_misuse_does_the_person_receive_from_local_services_", required = true)
    protected BigInteger c3AHowMuchHelpWithDrugMisuseDoesThePersonReceiveFromLocalServices;
    @XmlElement(name = "C3b__How_much_help_with_drug_misuse_does_the_person_need_from_local_services_", required = true)
    protected BigInteger c3BHowMuchHelpWithDrugMisuseDoesThePersonNeedFromLocalServices;
    @XmlElement(name = "CComments_", required = true)
    protected CComments cComments;
    @XmlElement(name = "CActions_", required = true)
    protected String cActions;
    @XmlElement(name = "CBy_whom_", required = true)
    protected String cByWhom;
    @XmlElement(name = "CReview_date_", required = true)
    protected String cReviewDate;
    @XmlElement(name = "CWhich_of_the_following_drugs_have_you_used___check_all_that_apply_", required = true)
    protected CWhichOfTheFollowingDrugsHaveYouUsedCheckAllThatApply cWhichOfTheFollowingDrugsHaveYouUsedCheckAllThatApply;
    @XmlElement(name = "CIndicate_the_stage_of_change_client_is_at__Optional__select_one_", required = true)
    protected CIndicateTheStageOfChangeClientIsAtOptionalSelectOne cIndicateTheStageOfChangeClientIsAtOptionalSelectOne;
    @XmlElement(name = "CHow_has_the_substance_s__of_choice_had_an_impact_on_your_life_", required = true)
    protected CHowHasTheSubstanceSOfChoiceHadAnImpactOnYourLife cHowHasTheSubstanceSOfChoiceHadAnImpactOnYourLife;

    /**
     * Gets the value of the c1DoesThePersonHaveProblemsWithDrugMisuseIfRated0Or9SkipQuestions23AndP property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getC1DoesThePersonHaveProblemsWithDrugMisuseIfRated0Or9SkipQuestions23AndP() {
        return c1DoesThePersonHaveProblemsWithDrugMisuseIfRated0Or9SkipQuestions23AndP;
    }

    /**
     * Sets the value of the c1DoesThePersonHaveProblemsWithDrugMisuseIfRated0Or9SkipQuestions23AndP property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setC1DoesThePersonHaveProblemsWithDrugMisuseIfRated0Or9SkipQuestions23AndP(BigInteger value) {
        this.c1DoesThePersonHaveProblemsWithDrugMisuseIfRated0Or9SkipQuestions23AndP = value;
    }

    /**
     * Gets the value of the c2HowMuchHelpWithDrugMisuseDoesThePersonReceiveFromFriendsOrRelatives property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getC2HowMuchHelpWithDrugMisuseDoesThePersonReceiveFromFriendsOrRelatives() {
        return c2HowMuchHelpWithDrugMisuseDoesThePersonReceiveFromFriendsOrRelatives;
    }

    /**
     * Sets the value of the c2HowMuchHelpWithDrugMisuseDoesThePersonReceiveFromFriendsOrRelatives property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setC2HowMuchHelpWithDrugMisuseDoesThePersonReceiveFromFriendsOrRelatives(BigInteger value) {
        this.c2HowMuchHelpWithDrugMisuseDoesThePersonReceiveFromFriendsOrRelatives = value;
    }

    /**
     * Gets the value of the c3AHowMuchHelpWithDrugMisuseDoesThePersonReceiveFromLocalServices property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getC3AHowMuchHelpWithDrugMisuseDoesThePersonReceiveFromLocalServices() {
        return c3AHowMuchHelpWithDrugMisuseDoesThePersonReceiveFromLocalServices;
    }

    /**
     * Sets the value of the c3AHowMuchHelpWithDrugMisuseDoesThePersonReceiveFromLocalServices property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setC3AHowMuchHelpWithDrugMisuseDoesThePersonReceiveFromLocalServices(BigInteger value) {
        this.c3AHowMuchHelpWithDrugMisuseDoesThePersonReceiveFromLocalServices = value;
    }

    /**
     * Gets the value of the c3BHowMuchHelpWithDrugMisuseDoesThePersonNeedFromLocalServices property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getC3BHowMuchHelpWithDrugMisuseDoesThePersonNeedFromLocalServices() {
        return c3BHowMuchHelpWithDrugMisuseDoesThePersonNeedFromLocalServices;
    }

    /**
     * Sets the value of the c3BHowMuchHelpWithDrugMisuseDoesThePersonNeedFromLocalServices property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setC3BHowMuchHelpWithDrugMisuseDoesThePersonNeedFromLocalServices(BigInteger value) {
        this.c3BHowMuchHelpWithDrugMisuseDoesThePersonNeedFromLocalServices = value;
    }

    /**
     * Gets the value of the cComments property.
     * 
     * @return
     *     possible object is
     *     {@link CComments }
     *     
     */
    public CComments getCComments() {
        return cComments;
    }

    /**
     * Sets the value of the cComments property.
     * 
     * @param value
     *     allowed object is
     *     {@link CComments }
     *     
     */
    public void setCComments(CComments value) {
        this.cComments = value;
    }

    /**
     * Gets the value of the cActions property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCActions() {
        return cActions;
    }

    /**
     * Sets the value of the cActions property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCActions(String value) {
        this.cActions = value;
    }

    /**
     * Gets the value of the cByWhom property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCByWhom() {
        return cByWhom;
    }

    /**
     * Sets the value of the cByWhom property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCByWhom(String value) {
        this.cByWhom = value;
    }

    /**
     * Gets the value of the cReviewDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCReviewDate() {
        return cReviewDate;
    }

    /**
     * Sets the value of the cReviewDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCReviewDate(String value) {
        this.cReviewDate = value;
    }

    /**
     * Gets the value of the cWhichOfTheFollowingDrugsHaveYouUsedCheckAllThatApply property.
     * 
     * @return
     *     possible object is
     *     {@link CWhichOfTheFollowingDrugsHaveYouUsedCheckAllThatApply }
     *     
     */
    public CWhichOfTheFollowingDrugsHaveYouUsedCheckAllThatApply getCWhichOfTheFollowingDrugsHaveYouUsedCheckAllThatApply() {
        return cWhichOfTheFollowingDrugsHaveYouUsedCheckAllThatApply;
    }

    /**
     * Sets the value of the cWhichOfTheFollowingDrugsHaveYouUsedCheckAllThatApply property.
     * 
     * @param value
     *     allowed object is
     *     {@link CWhichOfTheFollowingDrugsHaveYouUsedCheckAllThatApply }
     *     
     */
    public void setCWhichOfTheFollowingDrugsHaveYouUsedCheckAllThatApply(CWhichOfTheFollowingDrugsHaveYouUsedCheckAllThatApply value) {
        this.cWhichOfTheFollowingDrugsHaveYouUsedCheckAllThatApply = value;
    }

    /**
     * Gets the value of the cIndicateTheStageOfChangeClientIsAtOptionalSelectOne property.
     * 
     * @return
     *     possible object is
     *     {@link CIndicateTheStageOfChangeClientIsAtOptionalSelectOne }
     *     
     */
    public CIndicateTheStageOfChangeClientIsAtOptionalSelectOne getCIndicateTheStageOfChangeClientIsAtOptionalSelectOne() {
        return cIndicateTheStageOfChangeClientIsAtOptionalSelectOne;
    }

    /**
     * Sets the value of the cIndicateTheStageOfChangeClientIsAtOptionalSelectOne property.
     * 
     * @param value
     *     allowed object is
     *     {@link CIndicateTheStageOfChangeClientIsAtOptionalSelectOne }
     *     
     */
    public void setCIndicateTheStageOfChangeClientIsAtOptionalSelectOne(CIndicateTheStageOfChangeClientIsAtOptionalSelectOne value) {
        this.cIndicateTheStageOfChangeClientIsAtOptionalSelectOne = value;
    }

    /**
     * Gets the value of the cHowHasTheSubstanceSOfChoiceHadAnImpactOnYourLife property.
     * 
     * @return
     *     possible object is
     *     {@link CHowHasTheSubstanceSOfChoiceHadAnImpactOnYourLife }
     *     
     */
    public CHowHasTheSubstanceSOfChoiceHadAnImpactOnYourLife getCHowHasTheSubstanceSOfChoiceHadAnImpactOnYourLife() {
        return cHowHasTheSubstanceSOfChoiceHadAnImpactOnYourLife;
    }

    /**
     * Sets the value of the cHowHasTheSubstanceSOfChoiceHadAnImpactOnYourLife property.
     * 
     * @param value
     *     allowed object is
     *     {@link CHowHasTheSubstanceSOfChoiceHadAnImpactOnYourLife }
     *     
     */
    public void setCHowHasTheSubstanceSOfChoiceHadAnImpactOnYourLife(CHowHasTheSubstanceSOfChoiceHadAnImpactOnYourLife value) {
        this.cHowHasTheSubstanceSOfChoiceHadAnImpactOnYourLife = value;
    }

}
