//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-793 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.05.24 at 10:52:14 PM EDT 
//


package oscar.ocan.domain.staff;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}CDifficulty_in_getting_to_work_school_on_time"/>
 *         &lt;element ref="{}CProblems_difficulty_in_work_school"/>
 *         &lt;element ref="{}CLooking_to_quit_work_school"/>
 *         &lt;element ref="{}CFrequent_changes_in_work_school"/>
 *         &lt;element ref="{}CNone_or_not_applicable"/>
 *         &lt;element ref="{}COther"/>
 *         &lt;element ref="{}CUnknown"/>
 *         &lt;element ref="{}CClient_declined_to_answer"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "cDifficultyInGettingToWorkSchoolOnTime",
    "cProblemsDifficultyInWorkSchool",
    "cLookingToQuitWorkSchool",
    "cFrequentChangesInWorkSchool",
    "cNoneOrNotApplicable",
    "cOther",
    "cUnknown",
    "cClientDeclinedToAnswer"
})
@XmlRootElement(name = "CAre_you_at_risk_of_unemployment_or_disruped_education___check_all_that_apply_")
public class CAreYouAtRiskOfUnemploymentOrDisrupedEducationCheckAllThatApply {

    @XmlElement(name = "CDifficulty_in_getting_to_work_school_on_time", required = true)
    protected String cDifficultyInGettingToWorkSchoolOnTime;
    @XmlElement(name = "CProblems_difficulty_in_work_school", required = true)
    protected String cProblemsDifficultyInWorkSchool;
    @XmlElement(name = "CLooking_to_quit_work_school", required = true)
    protected String cLookingToQuitWorkSchool;
    @XmlElement(name = "CFrequent_changes_in_work_school", required = true)
    protected String cFrequentChangesInWorkSchool;
    @XmlElement(name = "CNone_or_not_applicable", required = true)
    protected String cNoneOrNotApplicable;
    @XmlElement(name = "COther", required = true)
    protected COther cOther;
    @XmlElement(name = "CUnknown", required = true)
    protected String cUnknown;
    @XmlElement(name = "CClient_declined_to_answer", required = true)
    protected String cClientDeclinedToAnswer;

    /**
     * Gets the value of the cDifficultyInGettingToWorkSchoolOnTime property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCDifficultyInGettingToWorkSchoolOnTime() {
        return cDifficultyInGettingToWorkSchoolOnTime;
    }

    /**
     * Sets the value of the cDifficultyInGettingToWorkSchoolOnTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCDifficultyInGettingToWorkSchoolOnTime(String value) {
        this.cDifficultyInGettingToWorkSchoolOnTime = value;
    }

    /**
     * Gets the value of the cProblemsDifficultyInWorkSchool property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCProblemsDifficultyInWorkSchool() {
        return cProblemsDifficultyInWorkSchool;
    }

    /**
     * Sets the value of the cProblemsDifficultyInWorkSchool property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCProblemsDifficultyInWorkSchool(String value) {
        this.cProblemsDifficultyInWorkSchool = value;
    }

    /**
     * Gets the value of the cLookingToQuitWorkSchool property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCLookingToQuitWorkSchool() {
        return cLookingToQuitWorkSchool;
    }

    /**
     * Sets the value of the cLookingToQuitWorkSchool property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCLookingToQuitWorkSchool(String value) {
        this.cLookingToQuitWorkSchool = value;
    }

    /**
     * Gets the value of the cFrequentChangesInWorkSchool property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCFrequentChangesInWorkSchool() {
        return cFrequentChangesInWorkSchool;
    }

    /**
     * Sets the value of the cFrequentChangesInWorkSchool property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCFrequentChangesInWorkSchool(String value) {
        this.cFrequentChangesInWorkSchool = value;
    }

    /**
     * Gets the value of the cNoneOrNotApplicable property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCNoneOrNotApplicable() {
        return cNoneOrNotApplicable;
    }

    /**
     * Sets the value of the cNoneOrNotApplicable property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCNoneOrNotApplicable(String value) {
        this.cNoneOrNotApplicable = value;
    }

    /**
     * Gets the value of the cOther property.
     * 
     * @return
     *     possible object is
     *     {@link COther }
     *     
     */
    public COther getCOther() {
        return cOther;
    }

    /**
     * Sets the value of the cOther property.
     * 
     * @param value
     *     allowed object is
     *     {@link COther }
     *     
     */
    public void setCOther(COther value) {
        this.cOther = value;
    }

    /**
     * Gets the value of the cUnknown property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCUnknown() {
        return cUnknown;
    }

    /**
     * Sets the value of the cUnknown property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCUnknown(String value) {
        this.cUnknown = value;
    }

    /**
     * Gets the value of the cClientDeclinedToAnswer property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCClientDeclinedToAnswer() {
        return cClientDeclinedToAnswer;
    }

    /**
     * Sets the value of the cClientDeclinedToAnswer property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCClientDeclinedToAnswer(String value) {
        this.cClientDeclinedToAnswer = value;
    }

}
