/**
 *
 * Copyright (c) 2005-2012. Centre for Research on Inner City Health, St. Michael's Hospital, Toronto. All Rights Reserved.
 * This software is published under the GPL GNU General Public License.
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; either version 2
 * of the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA 02111-1307, USA.
 *
 * This software was written for
 * Centre for Research on Inner City Health, St. Michael's Hospital,
 * Toronto, Ontario, Canada
 */

//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-793 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.05.24 at 10:52:14 PM EDT 
//


package oscar.ocan.domain.staff;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}CPrecontemplation"/>
 *         &lt;element ref="{}CContemplation"/>
 *         &lt;element ref="{}CAction"/>
 *         &lt;sequence minOccurs="0">
 *           &lt;element ref="{}CMaintenance"/>
 *           &lt;element ref="{}CRelapse_Prevention"/>
 *         &lt;/sequence>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "cPrecontemplation",
    "cContemplation",
    "cAction",
    "cMaintenance",
    "cRelapsePrevention"
})
@XmlRootElement(name = "CIndicate_the_stage_of_change_client_is_at__Optional__select_one_")
public class CIndicateTheStageOfChangeClientIsAtOptionalSelectOne {

    @XmlElement(name = "CPrecontemplation", required = true)
    protected String cPrecontemplation;
    @XmlElement(name = "CContemplation", required = true)
    protected String cContemplation;
    @XmlElement(name = "CAction", required = true)
    protected String cAction;
    @XmlElement(name = "CMaintenance")
    protected String cMaintenance;
    @XmlElement(name = "CRelapse_Prevention")
    protected String cRelapsePrevention;

    /**
     * Gets the value of the cPrecontemplation property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCPrecontemplation() {
        return cPrecontemplation;
    }

    /**
     * Sets the value of the cPrecontemplation property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCPrecontemplation(String value) {
        this.cPrecontemplation = value;
    }

    /**
     * Gets the value of the cContemplation property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCContemplation() {
        return cContemplation;
    }

    /**
     * Sets the value of the cContemplation property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCContemplation(String value) {
        this.cContemplation = value;
    }

    /**
     * Gets the value of the cAction property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCAction() {
        return cAction;
    }

    /**
     * Sets the value of the cAction property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCAction(String value) {
        this.cAction = value;
    }

    /**
     * Gets the value of the cMaintenance property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCMaintenance() {
        return cMaintenance;
    }

    /**
     * Sets the value of the cMaintenance property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCMaintenance(String value) {
        this.cMaintenance = value;
    }

    /**
     * Gets the value of the cRelapsePrevention property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCRelapsePrevention() {
        return cRelapsePrevention;
    }

    /**
     * Sets the value of the cRelapsePrevention property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCRelapsePrevention(String value) {
        this.cRelapsePrevention = value;
    }

}
