/**
 *
 * Copyright (c) 2005-2012. Centre for Research on Inner City Health, St. Michael's Hospital, Toronto. All Rights Reserved.
 * This software is published under the GPL GNU General Public License.
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; either version 2
 * of the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA 02111-1307, USA.
 *
 * This software was written for
 * Centre for Research on Inner City Health, St. Michael's Hospital,
 * Toronto, Ontario, Canada
 */

//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-793 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.05.24 at 10:52:14 PM EDT 
//


package oscar.ocan.domain.staff;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}CInitial_assessment"/>
 *         &lt;element ref="{}CReassessment_at_6_months"/>
 *         &lt;element ref="{}C_Prior_to__discharge"/>
 *         &lt;element ref="{}COther__significant_change__client_request_"/>
 *         &lt;element ref="{}CSpecify_other_"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "cInitialAssessment",
    "cReassessmentAt6Months",
    "cPriorToDischarge",
    "cOtherSignificantChangeClientRequest",
    "cSpecifyOther"
})
@XmlRootElement(name = "CReason_for_Assessment__Select_One_")
public class CReasonForAssessmentSelectOne {

    @XmlElement(name = "CInitial_assessment", required = true)
    protected String cInitialAssessment;
    @XmlElement(name = "CReassessment_at_6_months", required = true)
    protected String cReassessmentAt6Months;
    @XmlElement(name = "C_Prior_to__discharge", required = true)
    protected String cPriorToDischarge;
    @XmlElement(name = "COther__significant_change__client_request_", required = true)
    protected String cOtherSignificantChangeClientRequest;
    @XmlElement(name = "CSpecify_other_", required = true)
    protected String cSpecifyOther;

    /**
     * Gets the value of the cInitialAssessment property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCInitialAssessment() {
        return cInitialAssessment;
    }

    /**
     * Sets the value of the cInitialAssessment property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCInitialAssessment(String value) {
        this.cInitialAssessment = value;
    }

    /**
     * Gets the value of the cReassessmentAt6Months property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCReassessmentAt6Months() {
        return cReassessmentAt6Months;
    }

    /**
     * Sets the value of the cReassessmentAt6Months property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCReassessmentAt6Months(String value) {
        this.cReassessmentAt6Months = value;
    }

    /**
     * Gets the value of the cPriorToDischarge property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCPriorToDischarge() {
        return cPriorToDischarge;
    }

    /**
     * Sets the value of the cPriorToDischarge property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCPriorToDischarge(String value) {
        this.cPriorToDischarge = value;
    }

    /**
     * Gets the value of the cOtherSignificantChangeClientRequest property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCOtherSignificantChangeClientRequest() {
        return cOtherSignificantChangeClientRequest;
    }

    /**
     * Sets the value of the cOtherSignificantChangeClientRequest property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCOtherSignificantChangeClientRequest(String value) {
        this.cOtherSignificantChangeClientRequest = value;
    }

    /**
     * Gets the value of the cSpecifyOther property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCSpecifyOther() {
        return cSpecifyOther;
    }

    /**
     * Sets the value of the cSpecifyOther property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCSpecifyOther(String value) {
        this.cSpecifyOther = value;
    }

}
