/**
 *
 * Copyright (c) 2005-2012. Centre for Research on Inner City Health, St. Michael's Hospital, Toronto. All Rights Reserved.
 * This software is published under the GPL GNU General Public License.
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; either version 2
 * of the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA 02111-1307, USA.
 *
 * This software was written for
 * Centre for Research on Inner City Health, St. Michael's Hospital,
 * Toronto, Ontario, Canada
 */

//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-793 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.05.24 at 10:52:14 PM EDT 
//


package oscar.ocan.domain.staff;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}CAbuse_neglect"/>
 *         &lt;element ref="{}CAccidental_self_harm"/>
 *         &lt;element ref="{}CDeliberate_self_harm"/>
 *         &lt;element ref="{}CExploitation_risk"/>
 *         &lt;element ref="{}COther_"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "cAbuseNeglect",
    "cAccidentalSelfHarm",
    "cDeliberateSelfHarm",
    "cExploitationRisk",
    "cOther"
})
@XmlRootElement(name = "CRisks__select_all_that_apply_")
public class CRisksSelectAllThatApply {

    @XmlElement(name = "CAbuse_neglect", required = true)
    protected String cAbuseNeglect;
    @XmlElement(name = "CAccidental_self_harm", required = true)
    protected String cAccidentalSelfHarm;
    @XmlElement(name = "CDeliberate_self_harm", required = true)
    protected String cDeliberateSelfHarm;
    @XmlElement(name = "CExploitation_risk", required = true)
    protected String cExploitationRisk;
    @XmlElement(name = "COther_", required = true)
    protected String cOther;

    /**
     * Gets the value of the cAbuseNeglect property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCAbuseNeglect() {
        return cAbuseNeglect;
    }

    /**
     * Sets the value of the cAbuseNeglect property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCAbuseNeglect(String value) {
        this.cAbuseNeglect = value;
    }

    /**
     * Gets the value of the cAccidentalSelfHarm property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCAccidentalSelfHarm() {
        return cAccidentalSelfHarm;
    }

    /**
     * Sets the value of the cAccidentalSelfHarm property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCAccidentalSelfHarm(String value) {
        this.cAccidentalSelfHarm = value;
    }

    /**
     * Gets the value of the cDeliberateSelfHarm property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCDeliberateSelfHarm() {
        return cDeliberateSelfHarm;
    }

    /**
     * Sets the value of the cDeliberateSelfHarm property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCDeliberateSelfHarm(String value) {
        this.cDeliberateSelfHarm = value;
    }

    /**
     * Gets the value of the cExploitationRisk property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCExploitationRisk() {
        return cExploitationRisk;
    }

    /**
     * Sets the value of the cExploitationRisk property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCExploitationRisk(String value) {
        this.cExploitationRisk = value;
    }

    /**
     * Gets the value of the cOther property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCOther() {
        return cOther;
    }

    /**
     * Sets the value of the cOther property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCOther(String value) {
        this.cOther = value;
    }

}
