/**
 *
 * Copyright (c) 2005-2012. Centre for Research on Inner City Health, St. Michael's Hospital, Toronto. All Rights Reserved.
 * This software is published under the GPL GNU General Public License.
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; either version 2
 * of the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA 02111-1307, USA.
 *
 * This software was written for
 * Centre for Research on Inner City Health, St. Michael's Hospital,
 * Toronto, Ontario, Canada
 */

//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-793 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.05.24 at 10:52:14 PM EDT 
//


package oscar.ocan.domain.staff;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}CNone"/>
 *         &lt;element ref="{}CAbnormal_affect"/>
 *         &lt;element ref="{}CAbnormal_thought_process_form"/>
 *         &lt;element ref="{}CAnger"/>
 *         &lt;element ref="{}CAnxiety"/>
 *         &lt;element ref="{}CCommand_hallucinations"/>
 *         &lt;element ref="{}CCompulsive_behaviour"/>
 *         &lt;element ref="{}CDecreased_energy"/>
 *         &lt;element ref="{}CDelusions"/>
 *         &lt;element ref="{}CEpisodes_of_panic"/>
 *         &lt;element ref="{}CFears"/>
 *         &lt;element ref="{}CGuilt_shame"/>
 *         &lt;element ref="{}CHallucinations"/>
 *         &lt;element ref="{}CHopelessness"/>
 *         &lt;element ref="{}CHygiene"/>
 *         &lt;element ref="{}CInability_t_o_experience_joy_pleasure"/>
 *         &lt;element ref="{}CInflated_self_worth"/>
 *         &lt;element ref="{}CIntrusive_thoughts"/>
 *         &lt;element ref="{}CIrritability"/>
 *         &lt;element ref="{}CObsessive_thoughts"/>
 *         &lt;element ref="{}CPhobias"/>
 *         &lt;element ref="{}CPressured_speech"/>
 *         &lt;element ref="{}CRacing_thoughts"/>
 *         &lt;element ref="{}CRapid_mood_changes"/>
 *         &lt;element ref="{}CReliving_traumatic_memories"/>
 *         &lt;element ref="{}CSelf_deprecation"/>
 *         &lt;element ref="{}CSleep_problems"/>
 *         &lt;element ref="{}CTearfulness"/>
 *         &lt;element ref="{}CUnusual_or_abnormal_physical_movements"/>
 *         &lt;element ref="{}CUnknown"/>
 *         &lt;element ref="{}COther"/>
 *         &lt;element ref="{}CSpecify"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "cNone",
    "cAbnormalAffect",
    "cAbnormalThoughtProcessForm",
    "cAnger",
    "cAnxiety",
    "cCommandHallucinations",
    "cCompulsiveBehaviour",
    "cDecreasedEnergy",
    "cDelusions",
    "cEpisodesOfPanic",
    "cFears",
    "cGuiltShame",
    "cHallucinations",
    "cHopelessness",
    "cHygiene",
    "cInabilityTOExperienceJoyPleasure",
    "cInflatedSelfWorth",
    "cIntrusiveThoughts",
    "cIrritability",
    "cObsessiveThoughts",
    "cPhobias",
    "cPressuredSpeech",
    "cRacingThoughts",
    "cRapidMoodChanges",
    "cRelivingTraumaticMemories",
    "cSelfDeprecation",
    "cSleepProblems",
    "cTearfulness",
    "cUnusualOrAbnormalPhysicalMovements",
    "cUnknown",
    "cOther",
    "cSpecify"
})
@XmlRootElement(name = "CSymptom_checklist")
public class CSymptomChecklist {

    @XmlElement(name = "CNone", required = true)
    protected String cNone;
    @XmlElement(name = "CAbnormal_affect", required = true)
    protected String cAbnormalAffect;
    @XmlElement(name = "CAbnormal_thought_process_form", required = true)
    protected String cAbnormalThoughtProcessForm;
    @XmlElement(name = "CAnger", required = true)
    protected String cAnger;
    @XmlElement(name = "CAnxiety", required = true)
    protected String cAnxiety;
    @XmlElement(name = "CCommand_hallucinations", required = true)
    protected String cCommandHallucinations;
    @XmlElement(name = "CCompulsive_behaviour", required = true)
    protected String cCompulsiveBehaviour;
    @XmlElement(name = "CDecreased_energy", required = true)
    protected String cDecreasedEnergy;
    @XmlElement(name = "CDelusions", required = true)
    protected String cDelusions;
    @XmlElement(name = "CEpisodes_of_panic", required = true)
    protected String cEpisodesOfPanic;
    @XmlElement(name = "CFears", required = true)
    protected String cFears;
    @XmlElement(name = "CGuilt_shame", required = true)
    protected String cGuiltShame;
    @XmlElement(name = "CHallucinations", required = true)
    protected String cHallucinations;
    @XmlElement(name = "CHopelessness", required = true)
    protected String cHopelessness;
    @XmlElement(name = "CHygiene", required = true)
    protected String cHygiene;
    @XmlElement(name = "CInability_t_o_experience_joy_pleasure", required = true)
    protected String cInabilityTOExperienceJoyPleasure;
    @XmlElement(name = "CInflated_self_worth", required = true)
    protected String cInflatedSelfWorth;
    @XmlElement(name = "CIntrusive_thoughts", required = true)
    protected String cIntrusiveThoughts;
    @XmlElement(name = "CIrritability", required = true)
    protected String cIrritability;
    @XmlElement(name = "CObsessive_thoughts", required = true)
    protected String cObsessiveThoughts;
    @XmlElement(name = "CPhobias", required = true)
    protected String cPhobias;
    @XmlElement(name = "CPressured_speech", required = true)
    protected String cPressuredSpeech;
    @XmlElement(name = "CRacing_thoughts", required = true)
    protected String cRacingThoughts;
    @XmlElement(name = "CRapid_mood_changes", required = true)
    protected String cRapidMoodChanges;
    @XmlElement(name = "CReliving_traumatic_memories", required = true)
    protected String cRelivingTraumaticMemories;
    @XmlElement(name = "CSelf_deprecation", required = true)
    protected String cSelfDeprecation;
    @XmlElement(name = "CSleep_problems", required = true)
    protected String cSleepProblems;
    @XmlElement(name = "CTearfulness", required = true)
    protected String cTearfulness;
    @XmlElement(name = "CUnusual_or_abnormal_physical_movements", required = true)
    protected String cUnusualOrAbnormalPhysicalMovements;
    @XmlElement(name = "CUnknown", required = true)
    protected String cUnknown;
    @XmlElement(name = "COther", required = true)
    protected COther cOther;
    @XmlElement(name = "CSpecify", required = true)
    protected String cSpecify;

    /**
     * Gets the value of the cNone property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCNone() {
        return cNone;
    }

    /**
     * Sets the value of the cNone property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCNone(String value) {
        this.cNone = value;
    }

    /**
     * Gets the value of the cAbnormalAffect property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCAbnormalAffect() {
        return cAbnormalAffect;
    }

    /**
     * Sets the value of the cAbnormalAffect property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCAbnormalAffect(String value) {
        this.cAbnormalAffect = value;
    }

    /**
     * Gets the value of the cAbnormalThoughtProcessForm property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCAbnormalThoughtProcessForm() {
        return cAbnormalThoughtProcessForm;
    }

    /**
     * Sets the value of the cAbnormalThoughtProcessForm property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCAbnormalThoughtProcessForm(String value) {
        this.cAbnormalThoughtProcessForm = value;
    }

    /**
     * Gets the value of the cAnger property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCAnger() {
        return cAnger;
    }

    /**
     * Sets the value of the cAnger property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCAnger(String value) {
        this.cAnger = value;
    }

    /**
     * Gets the value of the cAnxiety property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCAnxiety() {
        return cAnxiety;
    }

    /**
     * Sets the value of the cAnxiety property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCAnxiety(String value) {
        this.cAnxiety = value;
    }

    /**
     * Gets the value of the cCommandHallucinations property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCCommandHallucinations() {
        return cCommandHallucinations;
    }

    /**
     * Sets the value of the cCommandHallucinations property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCCommandHallucinations(String value) {
        this.cCommandHallucinations = value;
    }

    /**
     * Gets the value of the cCompulsiveBehaviour property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCCompulsiveBehaviour() {
        return cCompulsiveBehaviour;
    }

    /**
     * Sets the value of the cCompulsiveBehaviour property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCCompulsiveBehaviour(String value) {
        this.cCompulsiveBehaviour = value;
    }

    /**
     * Gets the value of the cDecreasedEnergy property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCDecreasedEnergy() {
        return cDecreasedEnergy;
    }

    /**
     * Sets the value of the cDecreasedEnergy property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCDecreasedEnergy(String value) {
        this.cDecreasedEnergy = value;
    }

    /**
     * Gets the value of the cDelusions property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCDelusions() {
        return cDelusions;
    }

    /**
     * Sets the value of the cDelusions property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCDelusions(String value) {
        this.cDelusions = value;
    }

    /**
     * Gets the value of the cEpisodesOfPanic property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCEpisodesOfPanic() {
        return cEpisodesOfPanic;
    }

    /**
     * Sets the value of the cEpisodesOfPanic property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCEpisodesOfPanic(String value) {
        this.cEpisodesOfPanic = value;
    }

    /**
     * Gets the value of the cFears property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCFears() {
        return cFears;
    }

    /**
     * Sets the value of the cFears property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCFears(String value) {
        this.cFears = value;
    }

    /**
     * Gets the value of the cGuiltShame property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCGuiltShame() {
        return cGuiltShame;
    }

    /**
     * Sets the value of the cGuiltShame property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCGuiltShame(String value) {
        this.cGuiltShame = value;
    }

    /**
     * Gets the value of the cHallucinations property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCHallucinations() {
        return cHallucinations;
    }

    /**
     * Sets the value of the cHallucinations property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCHallucinations(String value) {
        this.cHallucinations = value;
    }

    /**
     * Gets the value of the cHopelessness property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCHopelessness() {
        return cHopelessness;
    }

    /**
     * Sets the value of the cHopelessness property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCHopelessness(String value) {
        this.cHopelessness = value;
    }

    /**
     * Gets the value of the cHygiene property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCHygiene() {
        return cHygiene;
    }

    /**
     * Sets the value of the cHygiene property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCHygiene(String value) {
        this.cHygiene = value;
    }

    /**
     * Gets the value of the cInabilityTOExperienceJoyPleasure property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCInabilityTOExperienceJoyPleasure() {
        return cInabilityTOExperienceJoyPleasure;
    }

    /**
     * Sets the value of the cInabilityTOExperienceJoyPleasure property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCInabilityTOExperienceJoyPleasure(String value) {
        this.cInabilityTOExperienceJoyPleasure = value;
    }

    /**
     * Gets the value of the cInflatedSelfWorth property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCInflatedSelfWorth() {
        return cInflatedSelfWorth;
    }

    /**
     * Sets the value of the cInflatedSelfWorth property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCInflatedSelfWorth(String value) {
        this.cInflatedSelfWorth = value;
    }

    /**
     * Gets the value of the cIntrusiveThoughts property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCIntrusiveThoughts() {
        return cIntrusiveThoughts;
    }

    /**
     * Sets the value of the cIntrusiveThoughts property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCIntrusiveThoughts(String value) {
        this.cIntrusiveThoughts = value;
    }

    /**
     * Gets the value of the cIrritability property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCIrritability() {
        return cIrritability;
    }

    /**
     * Sets the value of the cIrritability property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCIrritability(String value) {
        this.cIrritability = value;
    }

    /**
     * Gets the value of the cObsessiveThoughts property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCObsessiveThoughts() {
        return cObsessiveThoughts;
    }

    /**
     * Sets the value of the cObsessiveThoughts property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCObsessiveThoughts(String value) {
        this.cObsessiveThoughts = value;
    }

    /**
     * Gets the value of the cPhobias property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCPhobias() {
        return cPhobias;
    }

    /**
     * Sets the value of the cPhobias property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCPhobias(String value) {
        this.cPhobias = value;
    }

    /**
     * Gets the value of the cPressuredSpeech property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCPressuredSpeech() {
        return cPressuredSpeech;
    }

    /**
     * Sets the value of the cPressuredSpeech property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCPressuredSpeech(String value) {
        this.cPressuredSpeech = value;
    }

    /**
     * Gets the value of the cRacingThoughts property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCRacingThoughts() {
        return cRacingThoughts;
    }

    /**
     * Sets the value of the cRacingThoughts property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCRacingThoughts(String value) {
        this.cRacingThoughts = value;
    }

    /**
     * Gets the value of the cRapidMoodChanges property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCRapidMoodChanges() {
        return cRapidMoodChanges;
    }

    /**
     * Sets the value of the cRapidMoodChanges property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCRapidMoodChanges(String value) {
        this.cRapidMoodChanges = value;
    }

    /**
     * Gets the value of the cRelivingTraumaticMemories property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCRelivingTraumaticMemories() {
        return cRelivingTraumaticMemories;
    }

    /**
     * Sets the value of the cRelivingTraumaticMemories property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCRelivingTraumaticMemories(String value) {
        this.cRelivingTraumaticMemories = value;
    }

    /**
     * Gets the value of the cSelfDeprecation property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCSelfDeprecation() {
        return cSelfDeprecation;
    }

    /**
     * Sets the value of the cSelfDeprecation property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCSelfDeprecation(String value) {
        this.cSelfDeprecation = value;
    }

    /**
     * Gets the value of the cSleepProblems property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCSleepProblems() {
        return cSleepProblems;
    }

    /**
     * Sets the value of the cSleepProblems property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCSleepProblems(String value) {
        this.cSleepProblems = value;
    }

    /**
     * Gets the value of the cTearfulness property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCTearfulness() {
        return cTearfulness;
    }

    /**
     * Sets the value of the cTearfulness property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCTearfulness(String value) {
        this.cTearfulness = value;
    }

    /**
     * Gets the value of the cUnusualOrAbnormalPhysicalMovements property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCUnusualOrAbnormalPhysicalMovements() {
        return cUnusualOrAbnormalPhysicalMovements;
    }

    /**
     * Sets the value of the cUnusualOrAbnormalPhysicalMovements property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCUnusualOrAbnormalPhysicalMovements(String value) {
        this.cUnusualOrAbnormalPhysicalMovements = value;
    }

    /**
     * Gets the value of the cUnknown property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCUnknown() {
        return cUnknown;
    }

    /**
     * Sets the value of the cUnknown property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCUnknown(String value) {
        this.cUnknown = value;
    }

    /**
     * Gets the value of the cOther property.
     * 
     * @return
     *     possible object is
     *     {@link COther }
     *     
     */
    public COther getCOther() {
        return cOther;
    }

    /**
     * Sets the value of the cOther property.
     * 
     * @param value
     *     allowed object is
     *     {@link COther }
     *     
     */
    public void setCOther(COther value) {
        this.cOther = value;
    }

    /**
     * Gets the value of the cSpecify property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCSpecify() {
        return cSpecify;
    }

    /**
     * Sets the value of the cSpecify property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCSpecify(String value) {
        this.cSpecify = value;
    }

}
