/**
 *
 * Copyright (c) 2005-2012. Centre for Research on Inner City Health, St. Michael's Hospital, Toronto. All Rights Reserved.
 * This software is published under the GPL GNU General Public License.
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; either version 2
 * of the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA 02111-1307, USA.
 *
 * This software was written for
 * Centre for Research on Inner City Health, St. Michael's Hospital,
 * Toronto, Ontario, Canada
 */

//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-793 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.05.21 at 12:06:38 PM EDT 
//


package oscar.ocan.domain.submission;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}clientHopesForFuture"/>
 *         &lt;element ref="{}clientNeedToGetThere"/>
 *         &lt;element ref="{}clientViewMentalHealth"/>
 *         &lt;element ref="{}clientSpiritualityImportance"/>
 *         &lt;element ref="{}clientCultureHeritageImportance"/>
 *         &lt;element ref="{}presentingIssueList"/>
 *         &lt;element ref="{}actionList" minOccurs="0"/>
 *         &lt;element ref="{}referralList" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "clientHopesForFuture",
    "clientNeedToGetThere",
    "clientViewMentalHealth",
    "clientSpiritualityImportance",
    "clientCultureHeritageImportance",
    "presentingIssueList",
    "actionList",
    "referralList"
})
@XmlRootElement(name = "additionalElements")
public class AdditionalElements {

    @XmlElement(required = true)
    protected String clientHopesForFuture;
    @XmlElement(required = true)
    protected String clientNeedToGetThere;
    @XmlElement(required = true)
    protected String clientViewMentalHealth;
    @XmlElement(required = true)
    protected String clientSpiritualityImportance;
    @XmlElement(required = true)
    protected String clientCultureHeritageImportance;
    @XmlElement(required = true)
    protected PresentingIssueList presentingIssueList;
    protected ActionList actionList;
    protected ReferralList referralList;

    /**
     * Gets the value of the clientHopesForFuture property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getClientHopesForFuture() {
        return clientHopesForFuture;
    }

    /**
     * Sets the value of the clientHopesForFuture property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setClientHopesForFuture(String value) {
        this.clientHopesForFuture = value;
    }

    /**
     * Gets the value of the clientNeedToGetThere property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getClientNeedToGetThere() {
        return clientNeedToGetThere;
    }

    /**
     * Sets the value of the clientNeedToGetThere property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setClientNeedToGetThere(String value) {
        this.clientNeedToGetThere = value;
    }

    /**
     * Gets the value of the clientViewMentalHealth property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getClientViewMentalHealth() {
        return clientViewMentalHealth;
    }

    /**
     * Sets the value of the clientViewMentalHealth property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setClientViewMentalHealth(String value) {
        this.clientViewMentalHealth = value;
    }

    /**
     * Gets the value of the clientSpiritualityImportance property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getClientSpiritualityImportance() {
        return clientSpiritualityImportance;
    }

    /**
     * Sets the value of the clientSpiritualityImportance property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setClientSpiritualityImportance(String value) {
        this.clientSpiritualityImportance = value;
    }

    /**
     * Gets the value of the clientCultureHeritageImportance property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getClientCultureHeritageImportance() {
        return clientCultureHeritageImportance;
    }

    /**
     * Sets the value of the clientCultureHeritageImportance property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setClientCultureHeritageImportance(String value) {
        this.clientCultureHeritageImportance = value;
    }

    /**
     * Gets the value of the presentingIssueList property.
     * 
     * @return
     *     possible object is
     *     {@link PresentingIssueList }
     *     
     */
    public PresentingIssueList getPresentingIssueList() {
        return presentingIssueList;
    }

    /**
     * Sets the value of the presentingIssueList property.
     * 
     * @param value
     *     allowed object is
     *     {@link PresentingIssueList }
     *     
     */
    public void setPresentingIssueList(PresentingIssueList value) {
        this.presentingIssueList = value;
    }

    /**
     * Gets the value of the actionList property.
     * 
     * @return
     *     possible object is
     *     {@link ActionList }
     *     
     */
    public ActionList getActionList() {
        return actionList;
    }

    /**
     * Sets the value of the actionList property.
     * 
     * @param value
     *     allowed object is
     *     {@link ActionList }
     *     
     */
    public void setActionList(ActionList value) {
        this.actionList = value;
    }

    /**
     * Gets the value of the referralList property.
     * 
     * @return
     *     possible object is
     *     {@link ReferralList }
     *     
     */
    public ReferralList getReferralList() {
        return referralList;
    }

    /**
     * Sets the value of the referralList property.
     * 
     * @param value
     *     allowed object is
     *     {@link ReferralList }
     *     
     */
    public void setReferralList(ReferralList value) {
        this.referralList = value;
    }

}
