/**
 *
 * Copyright (c) 2005-2012. Centre for Research on Inner City Health, St. Michael's Hospital, Toronto. All Rights Reserved.
 * This software is published under the GPL GNU General Public License.
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; either version 2
 * of the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA 02111-1307, USA.
 *
 * This software was written for
 * Centre for Research on Inner City Health, St. Michael's Hospital,
 * Toronto, Ontario, Canada
 */

//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-793 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.05.21 at 12:06:38 PM EDT 
//


package oscar.ocan.domain.submission;

import java.math.BigInteger;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.datatype.XMLGregorianCalendar;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the oscar.ocan.domain.submission package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _ServiceDeliveryLHIN_QNAME = new QName("", "serviceDeliveryLHIN");
    private final static QName _OtherIllness_QNAME = new QName("", "otherIllness");
    private final static QName _ConcernArea_QNAME = new QName("", "concernArea");
    private final static QName _StageOfChangeAlcohol_QNAME = new QName("", "stageOfChangeAlcohol");
    private final static QName _EmployStatus_QNAME = new QName("", "employStatus");
    private final static QName _SafetyToSelfRisk_QNAME = new QName("", "safetyToSelfRisk");
    private final static QName _SuicideThoughts_QNAME = new QName("", "suicideThoughts");
    private final static QName _SourceOfIncome_QNAME = new QName("", "sourceOfIncome");
    private final static QName _ServiceRecipientLHIN_QNAME = new QName("", "serviceRecipientLHIN");
    private final static QName _LivingArrangementType_QNAME = new QName("", "livingArrangementType");
    private final static QName _ClientHopesForFuture_QNAME = new QName("", "clientHopesForFuture");
    private final static QName _LegalStatus_QNAME = new QName("", "legalStatus");
    private final static QName _Gender_QNAME = new QName("", "gender");
    private final static QName _AddictionType_QNAME = new QName("", "addictionType");
    private final static QName _ResidenceType_QNAME = new QName("", "residenceType");
    private final static QName _Diagnostic_QNAME = new QName("", "diagnostic");
    private final static QName _ChangedSocialPatterns_QNAME = new QName("", "changedSocialPatterns");
    private final static QName _ResidenceSupport_QNAME = new QName("", "residenceSupport");
    private final static QName _LegalIssues_QNAME = new QName("", "legalIssues");
    private final static QName _AboriginalOrigin_QNAME = new QName("", "aboriginalOrigin");
    private final static QName _TotalHospitalDays_QNAME = new QName("", "totalHospitalDays");
    private final static QName _ClientNeedToGetThere_QNAME = new QName("", "clientNeedToGetThere");
    private final static QName _ExitDisposition_QNAME = new QName("", "exitDisposition");
    private final static QName _CommunityTreatOrder_QNAME = new QName("", "communityTreatOrder");
    private final static QName _ServiceRecipientLocation_QNAME = new QName("", "serviceRecipientLocation");
    private final static QName _Symptom_QNAME = new QName("", "symptom");
    private final static QName _StageOfChangeDrugs_QNAME = new QName("", "stageOfChangeDrugs");
    private final static QName _ClientViewMentalHealth_QNAME = new QName("", "clientViewMentalHealth");
    private final static QName _SideEffectsDetail_QNAME = new QName("", "sideEffectsDetail");
    private final static QName _ClientPhone_QNAME = new QName("", "clientPhone");
    private final static QName _MaritalStatus_QNAME = new QName("", "maritalStatus");
    private final static QName _MedicalCondition_QNAME = new QName("", "medicalCondition");
    private final static QName _DailyLivingAffected_QNAME = new QName("", "dailyLivingAffected");
    private final static QName _ClientSpiritualityImportance_QNAME = new QName("", "clientSpiritualityImportance");
    private final static QName _ReferralSource_QNAME = new QName("", "referralSource");
    private final static QName _TotalAdmissions_QNAME = new QName("", "totalAdmissions");
    private final static QName _CitizenshipStatus_QNAME = new QName("", "citizenshipStatus");
    private final static QName _PhysicalHealthConcern_QNAME = new QName("", "physicalHealthConcern");
    private final static QName _SideEffects_QNAME = new QName("", "sideEffects");
    private final static QName _SuicideAttempt_QNAME = new QName("", "suicideAttempt");
    private final static QName _HighestEducationLevel_QNAME = new QName("", "highestEducationLevel");
    private final static QName _ServiceLang_QNAME = new QName("", "serviceLang");
    private final static QName _StageOfChangeAddictions_QNAME = new QName("", "stageOfChangeAddictions");
    private final static QName _EducationProgramStatus_QNAME = new QName("", "educationProgramStatus");
    private final static QName _ClientCulture_QNAME = new QName("", "clientCulture");
    private final static QName _ClientDOB_QNAME = new QName("", "clientDOB");
    private final static QName _HospitalizedPastTwoYears_QNAME = new QName("", "hospitalizedPastTwoYears");
    private final static QName _ClientCultureHeritageImportance_QNAME = new QName("", "clientCultureHeritageImportance");
    private final static QName _RiskUnemployment_QNAME = new QName("", "riskUnemployment");
    private final static QName _PrefLang_QNAME = new QName("", "prefLang");
    private final static QName _SafetyConcernSelf_QNAME = new QName("", "safetyConcernSelf");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: oscar.ocan.domain.submission
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link OrganizationRecord }
     * 
     */
    public OrganizationRecord createOrganizationRecord() {
        return new OrganizationRecord();
    }

    /**
     * Create an instance of {@link DrinkAlcohol }
     * 
     */
    public DrinkAlcohol createDrinkAlcohol() {
        return new DrinkAlcohol();
    }

    /**
     * Create an instance of {@link MISFunction }
     * 
     */
    public MISFunction createMISFunction() {
        return new MISFunction();
    }

    /**
     * Create an instance of {@link OtherPractitionerContact }
     * 
     */
    public OtherPractitionerContact createOtherPractitionerContact() {
        return new OtherPractitionerContact();
    }

    /**
     * Create an instance of {@link DrugUse }
     * 
     */
    public DrugUse createDrugUse() {
        return new DrugUse();
    }

    /**
     * Create an instance of {@link OtherAgencyContact }
     * 
     */
    public OtherAgencyContact createOtherAgencyContact() {
        return new OtherAgencyContact();
    }

    /**
     * Create an instance of {@link ClientName }
     * 
     */
    public ClientName createClientName() {
        return new ClientName();
    }

    /**
     * Create an instance of {@link ReasonForAssessment }
     * 
     */
    public ReasonForAssessment createReasonForAssessment() {
        return new ReasonForAssessment();
    }

    /**
     * Create an instance of {@link ClientCapacity }
     * 
     */
    public ClientCapacity createClientCapacity() {
        return new ClientCapacity();
    }

    /**
     * Create an instance of {@link InformalHelpRecvd }
     * 
     */
    public InformalHelpRecvd createInformalHelpRecvd() {
        return new InformalHelpRecvd();
    }

    /**
     * Create an instance of {@link AdditionalElements }
     * 
     */
    public AdditionalElements createAdditionalElements() {
        return new AdditionalElements();
    }

    /**
     * Create an instance of {@link NeedRating }
     * 
     */
    public NeedRating createNeedRating() {
        return new NeedRating();
    }

    /**
     * Create an instance of {@link OCANDomains }
     * 
     */
    public OCANDomains createOCANDomains() {
        return new OCANDomains();
    }

    /**
     * Create an instance of {@link RiskUnemploymentList }
     * 
     */
    public RiskUnemploymentList createRiskUnemploymentList() {
        return new RiskUnemploymentList();
    }

    /**
     * Create an instance of {@link DiagnosticList }
     * 
     */
    public DiagnosticList createDiagnosticList() {
        return new DiagnosticList();
    }

    /**
     * Create an instance of {@link PsychiatristContact }
     * 
     */
    public PsychiatristContact createPsychiatristContact() {
        return new PsychiatristContact();
    }

    /**
     * Create an instance of {@link FormalHelpRecvd }
     * 
     */
    public FormalHelpRecvd createFormalHelpRecvd() {
        return new FormalHelpRecvd();
    }

    /**
     * Create an instance of {@link ClientOHIP }
     * 
     */
    public ClientOHIP createClientOHIP() {
        return new ClientOHIP();
    }

    /**
     * Create an instance of {@link ReferralList }
     * 
     */
    public ReferralList createReferralList() {
        return new ReferralList();
    }

    /**
     * Create an instance of {@link LegalStatusList }
     * 
     */
    public LegalStatusList createLegalStatusList() {
        return new LegalStatusList();
    }

    /**
     * Create an instance of {@link MedicationList }
     * 
     */
    public MedicationList createMedicationList() {
        return new MedicationList();
    }

    /**
     * Create an instance of {@link ServiceOrg }
     * 
     */
    public ServiceOrg createServiceOrg() {
        return new ServiceOrg();
    }

    /**
     * Create an instance of {@link DiscrimExpList }
     * 
     */
    public DiscrimExpList createDiscrimExpList() {
        return new DiscrimExpList();
    }

    /**
     * Create an instance of {@link OCANSubmissionFile }
     * 
     */
    public OCANSubmissionFile createOCANSubmissionFile() {
        return new OCANSubmissionFile();
    }

    /**
     * Create an instance of {@link FormalHelpNeed }
     * 
     */
    public FormalHelpNeed createFormalHelpNeed() {
        return new FormalHelpNeed();
    }

    /**
     * Create an instance of {@link PresentingIssueList }
     * 
     */
    public PresentingIssueList createPresentingIssueList() {
        return new PresentingIssueList();
    }

    /**
     * Create an instance of {@link SafetyToSelfRiskList }
     * 
     */
    public SafetyToSelfRiskList createSafetyToSelfRiskList() {
        return new SafetyToSelfRiskList();
    }

    /**
     * Create an instance of {@link DoctorContact }
     * 
     */
    public DoctorContact createDoctorContact() {
        return new DoctorContact();
    }

    /**
     * Create an instance of {@link Referral }
     * 
     */
    public Referral createReferral() {
        return new Referral();
    }

    /**
     * Create an instance of {@link DrugUseList }
     * 
     */
    public DrugUseList createDrugUseList() {
        return new DrugUseList();
    }

    /**
     * Create an instance of {@link ActionList }
     * 
     */
    public ActionList createActionList() {
        return new ActionList();
    }

    /**
     * Create an instance of {@link Action }
     * 
     */
    public Action createAction() {
        return new Action();
    }

    /**
     * Create an instance of {@link ClientID }
     * 
     */
    public ClientID createClientID() {
        return new ClientID();
    }

    /**
     * Create an instance of {@link Domain }
     * 
     */
    public Domain createDomain() {
        return new Domain();
    }

    /**
     * Create an instance of {@link ConcernAreaList }
     * 
     */
    public ConcernAreaList createConcernAreaList() {
        return new ConcernAreaList();
    }

    /**
     * Create an instance of {@link ImmigExpList }
     * 
     */
    public ImmigExpList createImmigExpList() {
        return new ImmigExpList();
    }

    /**
     * Create an instance of {@link ClientRecord }
     * 
     */
    public ClientRecord createClientRecord() {
        return new ClientRecord();
    }

    /**
     * Create an instance of {@link PresentingIssue }
     * 
     */
    public PresentingIssue createPresentingIssue() {
        return new PresentingIssue();
    }

    /**
     * Create an instance of {@link MedicalConditionList }
     * 
     */
    public MedicalConditionList createMedicalConditionList() {
        return new MedicalConditionList();
    }

    /**
     * Create an instance of {@link Program }
     * 
     */
    public Program createProgram() {
        return new Program();
    }

    /**
     * Create an instance of {@link OCANSubmissionRecord }
     * 
     */
    public OCANSubmissionRecord createOCANSubmissionRecord() {
        return new OCANSubmissionRecord();
    }

    /**
     * Create an instance of {@link SideEffectsDetailList }
     * 
     */
    public SideEffectsDetailList createSideEffectsDetailList() {
        return new SideEffectsDetailList();
    }

    /**
     * Create an instance of {@link AddictionTypeList }
     * 
     */
    public AddictionTypeList createAddictionTypeList() {
        return new AddictionTypeList();
    }

    /**
     * Create an instance of {@link SymptomList }
     * 
     */
    public SymptomList createSymptomList() {
        return new SymptomList();
    }

    /**
     * Create an instance of {@link TimeLivedInCanada }
     * 
     */
    public TimeLivedInCanada createTimeLivedInCanada() {
        return new TimeLivedInCanada();
    }

    /**
     * Create an instance of {@link MedicationDetail }
     * 
     */
    public MedicationDetail createMedicationDetail() {
        return new MedicationDetail();
    }

    /**
     * Create an instance of {@link ClientContact }
     * 
     */
    public ClientContact createClientContact() {
        return new ClientContact();
    }

    /**
     * Create an instance of {@link ClientAddress }
     * 
     */
    public ClientAddress createClientAddress() {
        return new ClientAddress();
    }

    /**
     * Create an instance of {@link OtherIllnessList }
     * 
     */
    public OtherIllnessList createOtherIllnessList() {
        return new OtherIllnessList();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Integer }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "serviceDeliveryLHIN")
    public JAXBElement<Integer> createServiceDeliveryLHIN(Integer value) {
        return new JAXBElement<Integer>(_ServiceDeliveryLHIN_QNAME, Integer.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "otherIllness")
    public JAXBElement<String> createOtherIllness(String value) {
        return new JAXBElement<String>(_OtherIllness_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "concernArea")
    public JAXBElement<String> createConcernArea(String value) {
        return new JAXBElement<String>(_ConcernArea_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "stageOfChangeAlcohol")
    public JAXBElement<String> createStageOfChangeAlcohol(String value) {
        return new JAXBElement<String>(_StageOfChangeAlcohol_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "employStatus")
    public JAXBElement<String> createEmployStatus(String value) {
        return new JAXBElement<String>(_EmployStatus_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "safetyToSelfRisk")
    public JAXBElement<String> createSafetyToSelfRisk(String value) {
        return new JAXBElement<String>(_SafetyToSelfRisk_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "suicideThoughts")
    public JAXBElement<String> createSuicideThoughts(String value) {
        return new JAXBElement<String>(_SuicideThoughts_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "sourceOfIncome")
    public JAXBElement<String> createSourceOfIncome(String value) {
        return new JAXBElement<String>(_SourceOfIncome_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Integer }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "serviceRecipientLHIN")
    public JAXBElement<Integer> createServiceRecipientLHIN(Integer value) {
        return new JAXBElement<Integer>(_ServiceRecipientLHIN_QNAME, Integer.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "livingArrangementType")
    public JAXBElement<String> createLivingArrangementType(String value) {
        return new JAXBElement<String>(_LivingArrangementType_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "clientHopesForFuture")
    public JAXBElement<String> createClientHopesForFuture(String value) {
        return new JAXBElement<String>(_ClientHopesForFuture_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "legalStatus")
    public JAXBElement<String> createLegalStatus(String value) {
        return new JAXBElement<String>(_LegalStatus_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "gender")
    public JAXBElement<String> createGender(String value) {
        return new JAXBElement<String>(_Gender_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "addictionType")
    public JAXBElement<String> createAddictionType(String value) {
        return new JAXBElement<String>(_AddictionType_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "residenceType")
    public JAXBElement<String> createResidenceType(String value) {
        return new JAXBElement<String>(_ResidenceType_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "diagnostic")
    public JAXBElement<String> createDiagnostic(String value) {
        return new JAXBElement<String>(_Diagnostic_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "changedSocialPatterns")
    public JAXBElement<String> createChangedSocialPatterns(String value) {
        return new JAXBElement<String>(_ChangedSocialPatterns_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "residenceSupport")
    public JAXBElement<String> createResidenceSupport(String value) {
        return new JAXBElement<String>(_ResidenceSupport_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "legalIssues")
    public JAXBElement<String> createLegalIssues(String value) {
        return new JAXBElement<String>(_LegalIssues_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "aboriginalOrigin")
    public JAXBElement<String> createAboriginalOrigin(String value) {
        return new JAXBElement<String>(_AboriginalOrigin_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "totalHospitalDays")
    public JAXBElement<BigInteger> createTotalHospitalDays(BigInteger value) {
        return new JAXBElement<BigInteger>(_TotalHospitalDays_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "clientNeedToGetThere")
    public JAXBElement<String> createClientNeedToGetThere(String value) {
        return new JAXBElement<String>(_ClientNeedToGetThere_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "exitDisposition")
    public JAXBElement<String> createExitDisposition(String value) {
        return new JAXBElement<String>(_ExitDisposition_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "communityTreatOrder")
    public JAXBElement<String> createCommunityTreatOrder(String value) {
        return new JAXBElement<String>(_CommunityTreatOrder_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "serviceRecipientLocation")
    public JAXBElement<String> createServiceRecipientLocation(String value) {
        return new JAXBElement<String>(_ServiceRecipientLocation_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "symptom")
    public JAXBElement<String> createSymptom(String value) {
        return new JAXBElement<String>(_Symptom_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "stageOfChangeDrugs")
    public JAXBElement<String> createStageOfChangeDrugs(String value) {
        return new JAXBElement<String>(_StageOfChangeDrugs_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "clientViewMentalHealth")
    public JAXBElement<String> createClientViewMentalHealth(String value) {
        return new JAXBElement<String>(_ClientViewMentalHealth_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "sideEffectsDetail")
    public JAXBElement<String> createSideEffectsDetail(String value) {
        return new JAXBElement<String>(_SideEffectsDetail_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "clientPhone")
    public JAXBElement<String> createClientPhone(String value) {
        return new JAXBElement<String>(_ClientPhone_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "maritalStatus")
    public JAXBElement<String> createMaritalStatus(String value) {
        return new JAXBElement<String>(_MaritalStatus_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "medicalCondition")
    public JAXBElement<String> createMedicalCondition(String value) {
        return new JAXBElement<String>(_MedicalCondition_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "dailyLivingAffected")
    public JAXBElement<String> createDailyLivingAffected(String value) {
        return new JAXBElement<String>(_DailyLivingAffected_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "clientSpiritualityImportance")
    public JAXBElement<String> createClientSpiritualityImportance(String value) {
        return new JAXBElement<String>(_ClientSpiritualityImportance_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "referralSource")
    public JAXBElement<String> createReferralSource(String value) {
        return new JAXBElement<String>(_ReferralSource_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "totalAdmissions")
    public JAXBElement<BigInteger> createTotalAdmissions(BigInteger value) {
        return new JAXBElement<BigInteger>(_TotalAdmissions_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "citizenshipStatus")
    public JAXBElement<String> createCitizenshipStatus(String value) {
        return new JAXBElement<String>(_CitizenshipStatus_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "physicalHealthConcern")
    public JAXBElement<String> createPhysicalHealthConcern(String value) {
        return new JAXBElement<String>(_PhysicalHealthConcern_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "sideEffects")
    public JAXBElement<String> createSideEffects(String value) {
        return new JAXBElement<String>(_SideEffects_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "suicideAttempt")
    public JAXBElement<String> createSuicideAttempt(String value) {
        return new JAXBElement<String>(_SuicideAttempt_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "highestEducationLevel")
    public JAXBElement<String> createHighestEducationLevel(String value) {
        return new JAXBElement<String>(_HighestEducationLevel_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "serviceLang")
    public JAXBElement<String> createServiceLang(String value) {
        return new JAXBElement<String>(_ServiceLang_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "stageOfChangeAddictions")
    public JAXBElement<String> createStageOfChangeAddictions(String value) {
        return new JAXBElement<String>(_StageOfChangeAddictions_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "educationProgramStatus")
    public JAXBElement<String> createEducationProgramStatus(String value) {
        return new JAXBElement<String>(_EducationProgramStatus_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "clientCulture")
    public JAXBElement<String> createClientCulture(String value) {
        return new JAXBElement<String>(_ClientCulture_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "clientDOB")
    public JAXBElement<XMLGregorianCalendar> createClientDOB(XMLGregorianCalendar value) {
        return new JAXBElement<XMLGregorianCalendar>(_ClientDOB_QNAME, XMLGregorianCalendar.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "hospitalizedPastTwoYears")
    public JAXBElement<String> createHospitalizedPastTwoYears(String value) {
        return new JAXBElement<String>(_HospitalizedPastTwoYears_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "clientCultureHeritageImportance")
    public JAXBElement<String> createClientCultureHeritageImportance(String value) {
        return new JAXBElement<String>(_ClientCultureHeritageImportance_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "riskUnemployment")
    public JAXBElement<String> createRiskUnemployment(String value) {
        return new JAXBElement<String>(_RiskUnemployment_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "prefLang")
    public JAXBElement<String> createPrefLang(String value) {
        return new JAXBElement<String>(_PrefLang_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "safetyConcernSelf")
    public JAXBElement<String> createSafetyConcernSelf(String value) {
        return new JAXBElement<String>(_SafetyConcernSelf_QNAME, String.class, null, value);
    }

}
