/**
 *
 * Copyright (c) 2005-2012. Centre for Research on Inner City Health, St. Michael's Hospital, Toronto. All Rights Reserved.
 * This software is published under the GPL GNU General Public License.
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; either version 2
 * of the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA 02111-1307, USA.
 *
 * This software was written for
 * Centre for Research on Inner City Health, St. Michael's Hospital,
 * Toronto, Ontario, Canada
 */

//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-793 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.05.21 at 12:06:38 PM EDT 
//


package oscar.ocan.domain.submission;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}organizationRecord"/>
 *         &lt;element ref="{}clientRecord"/>
 *         &lt;element ref="{}OCANDomains"/>
 *         &lt;element ref="{}additionalElements"/>
 *       &lt;/sequence>
 *       &lt;attribute name="startDate" use="required">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}date">
 *             &lt;pattern value="((000[1-9])|(00[1-9][0-9])|(0[1-9][0-9]{2})|([1-9][0-9]{3}))-((0[1-9])|(1[012]))-((0[1-9])|([12][0-9])|(3[01]))(Z)"/>
 *             &lt;minInclusive value="1900-01-01Z"/>
 *             &lt;maxInclusive value="2079-06-06Z"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="completionDate" use="required">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}date">
 *             &lt;pattern value="((000[1-9])|(00[1-9][0-9])|(0[1-9][0-9]{2})|([1-9][0-9]{3}))-((0[1-9])|(1[012]))-((0[1-9])|([12][0-9])|(3[01]))(Z)"/>
 *             &lt;minInclusive value="1900-01-01Z"/>
 *             &lt;maxInclusive value="2079-06-06Z"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="assessmentID" use="required">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;maxLength value="64"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="assessmentStatus" use="required">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;enumeration value="Complete"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "organizationRecord",
    "clientRecord",
    "ocanDomains",
    "additionalElements"
})
@XmlRootElement(name = "OCANSubmissionRecord")
public class OCANSubmissionRecord {

    @XmlElement(required = true)
    protected OrganizationRecord organizationRecord;
    @XmlElement(required = true)
    protected ClientRecord clientRecord;
    @XmlElement(name = "OCANDomains", required = true)
    protected OCANDomains ocanDomains;
    @XmlElement(required = true)
    protected AdditionalElements additionalElements;
    @XmlAttribute(required = true)
    protected XMLGregorianCalendar startDate;
    @XmlAttribute(required = true)
    protected XMLGregorianCalendar completionDate;
    @XmlAttribute(required = true)
    protected String assessmentID;
    @XmlAttribute(required = true)
    protected String assessmentStatus;

    /**
     * Gets the value of the organizationRecord property.
     * 
     * @return
     *     possible object is
     *     {@link OrganizationRecord }
     *     
     */
    public OrganizationRecord getOrganizationRecord() {
        return organizationRecord;
    }

    /**
     * Sets the value of the organizationRecord property.
     * 
     * @param value
     *     allowed object is
     *     {@link OrganizationRecord }
     *     
     */
    public void setOrganizationRecord(OrganizationRecord value) {
        this.organizationRecord = value;
    }

    /**
     * Gets the value of the clientRecord property.
     * 
     * @return
     *     possible object is
     *     {@link ClientRecord }
     *     
     */
    public ClientRecord getClientRecord() {
        return clientRecord;
    }

    /**
     * Sets the value of the clientRecord property.
     * 
     * @param value
     *     allowed object is
     *     {@link ClientRecord }
     *     
     */
    public void setClientRecord(ClientRecord value) {
        this.clientRecord = value;
    }

    /**
     * Gets the value of the ocanDomains property.
     * 
     * @return
     *     possible object is
     *     {@link OCANDomains }
     *     
     */
    public OCANDomains getOCANDomains() {
        return ocanDomains;
    }

    /**
     * Sets the value of the ocanDomains property.
     * 
     * @param value
     *     allowed object is
     *     {@link OCANDomains }
     *     
     */
    public void setOCANDomains(OCANDomains value) {
        this.ocanDomains = value;
    }

    /**
     * Gets the value of the additionalElements property.
     * 
     * @return
     *     possible object is
     *     {@link AdditionalElements }
     *     
     */
    public AdditionalElements getAdditionalElements() {
        return additionalElements;
    }

    /**
     * Sets the value of the additionalElements property.
     * 
     * @param value
     *     allowed object is
     *     {@link AdditionalElements }
     *     
     */
    public void setAdditionalElements(AdditionalElements value) {
        this.additionalElements = value;
    }

    /**
     * Gets the value of the startDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getStartDate() {
        return startDate;
    }

    /**
     * Sets the value of the startDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setStartDate(XMLGregorianCalendar value) {
        this.startDate = value;
    }

    /**
     * Gets the value of the completionDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getCompletionDate() {
        return completionDate;
    }

    /**
     * Sets the value of the completionDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setCompletionDate(XMLGregorianCalendar value) {
        this.completionDate = value;
    }

    /**
     * Gets the value of the assessmentID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAssessmentID() {
        return assessmentID;
    }

    /**
     * Sets the value of the assessmentID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAssessmentID(String value) {
        this.assessmentID = value;
    }

    /**
     * Gets the value of the assessmentStatus property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAssessmentStatus() {
        return assessmentStatus;
    }

    /**
     * Sets the value of the assessmentStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAssessmentStatus(String value) {
        this.assessmentStatus = value;
    }

}
