/**
 *
 * Copyright (c) 2005-2012. Centre for Research on Inner City Health, St. Michael's Hospital, Toronto. All Rights Reserved.
 * This software is published under the GPL GNU General Public License.
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; either version 2
 * of the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA 02111-1307, USA.
 *
 * This software was written for
 * Centre for Research on Inner City Health, St. Michael's Hospital,
 * Toronto, Ontario, Canada
 */

//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-793 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.05.21 at 12:06:38 PM EDT 
//


package oscar.ocan.domain.submission;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *       &lt;/sequence>
 *       &lt;attribute name="optimal">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;enumeration value=""/>
 *             &lt;enumeration value="0AS"/>
 *             &lt;enumeration value="ADD"/>
 *             &lt;enumeration value="0AB"/>
 *             &lt;enumeration value="ACT"/>
 *             &lt;enumeration value="0CM"/>
 *             &lt;enumeration value="CHI"/>
 *             &lt;enumeration value="CLU"/>
 *             &lt;enumeration value="0CD"/>
 *             &lt;enumeration value="CMH"/>
 *             &lt;enumeration value="0IR"/>
 *             &lt;enumeration value="CON"/>
 *             &lt;enumeration value="C&amp;T"/>
 *             &lt;enumeration value="DDx"/>
 *             &lt;enumeration value="EAR"/>
 *             &lt;enumeration value="EAT"/>
 *             &lt;enumeration value="0FI"/>
 *             &lt;enumeration value="FOR"/>
 *             &lt;enumeration value="HPA"/>
 *             &lt;enumeration value="HPW"/>
 *             &lt;enumeration value="HSC"/>
 *             &lt;enumeration value="CRI"/>
 *             &lt;enumeration value="PSH"/>
 *             &lt;enumeration value="0DN"/>
 *             &lt;enumeration value="GER"/>
 *             &lt;enumeration value="CSB"/>
 *             &lt;enumeration value="0SR"/>
 *             &lt;enumeration value="0SH"/>
 *             &lt;enumeration value="EMP"/>
 *             &lt;enumeration value="CAC"/>
 *             &lt;enumeration value="CMS"/>
 *             &lt;enumeration value="DNT"/>
 *             &lt;enumeration value="FHG"/>
 *             &lt;enumeration value="AGS"/>
 *             &lt;enumeration value="OPT"/>
 *             &lt;enumeration value="POL"/>
 *             &lt;enumeration value="PRI"/>
 *             &lt;enumeration value="SCH"/>
 *             &lt;enumeration value="SHG"/>
 *             &lt;enumeration value="0SC"/>
 *             &lt;enumeration value="SSs"/>
 *             &lt;enumeration value="YSs"/>
 *             &lt;enumeration value="0CP"/>
 *             &lt;enumeration value="0PP"/>
 *             &lt;enumeration value="FBS"/>
 *             &lt;enumeration value="0LC"/>
 *             &lt;enumeration value="0IS"/>
 *             &lt;enumeration value="FCP"/>
 *             &lt;enumeration value="FIT"/>
 *             &lt;enumeration value="AHO"/>
 *             &lt;enumeration value="PSC"/>
 *             &lt;enumeration value="CAS"/>
 *             &lt;enumeration value="HOS"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="specifyOptimal">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="actual">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;enumeration value=""/>
 *             &lt;enumeration value="0AS"/>
 *             &lt;enumeration value="ADD"/>
 *             &lt;enumeration value="0AB"/>
 *             &lt;enumeration value="ACT"/>
 *             &lt;enumeration value="0CM"/>
 *             &lt;enumeration value="CHI"/>
 *             &lt;enumeration value="CLU"/>
 *             &lt;enumeration value="0CD"/>
 *             &lt;enumeration value="CMH"/>
 *             &lt;enumeration value="0IR"/>
 *             &lt;enumeration value="CON"/>
 *             &lt;enumeration value="C&amp;T"/>
 *             &lt;enumeration value="DDx"/>
 *             &lt;enumeration value="EAR"/>
 *             &lt;enumeration value="EAT"/>
 *             &lt;enumeration value="0FI"/>
 *             &lt;enumeration value="FOR"/>
 *             &lt;enumeration value="HPA"/>
 *             &lt;enumeration value="HPW"/>
 *             &lt;enumeration value="HSC"/>
 *             &lt;enumeration value="CRI"/>
 *             &lt;enumeration value="PSH"/>
 *             &lt;enumeration value="0DN"/>
 *             &lt;enumeration value="GER"/>
 *             &lt;enumeration value="CSB"/>
 *             &lt;enumeration value="0SR"/>
 *             &lt;enumeration value="0SH"/>
 *             &lt;enumeration value="EMP"/>
 *             &lt;enumeration value="CAC"/>
 *             &lt;enumeration value="CMS"/>
 *             &lt;enumeration value="DNT"/>
 *             &lt;enumeration value="FHG"/>
 *             &lt;enumeration value="AGS"/>
 *             &lt;enumeration value="OPT"/>
 *             &lt;enumeration value="POL"/>
 *             &lt;enumeration value="PRI"/>
 *             &lt;enumeration value="SCH"/>
 *             &lt;enumeration value="SHG"/>
 *             &lt;enumeration value="0SC"/>
 *             &lt;enumeration value="SSs"/>
 *             &lt;enumeration value="YSs"/>
 *             &lt;enumeration value="0CP"/>
 *             &lt;enumeration value="0PP"/>
 *             &lt;enumeration value="FBS"/>
 *             &lt;enumeration value="0LC"/>
 *             &lt;enumeration value="0IS"/>
 *             &lt;enumeration value="FCP"/>
 *             &lt;enumeration value="FIT"/>
 *             &lt;enumeration value="AHO"/>
 *             &lt;enumeration value="PSC"/>
 *             &lt;enumeration value="CAS"/>
 *             &lt;enumeration value="HOS"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="specifyActual">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="differenceReason">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;enumeration value=""/>
 *             &lt;enumeration value="RD-1"/>
 *             &lt;enumeration value="RD-2"/>
 *             &lt;enumeration value="RD-3"/>
 *             &lt;enumeration value="RD-4"/>
 *             &lt;enumeration value="RD-5"/>
 *             &lt;enumeration value="RD-6"/>
 *             &lt;enumeration value="RD-7"/>
 *             &lt;enumeration value="RD-8"/>
 *             &lt;enumeration value="RD-9"/>
 *             &lt;enumeration value="RD-10"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="status">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;enumeration value=""/>
 *             &lt;enumeration value="RS-1"/>
 *             &lt;enumeration value="RS-2"/>
 *             &lt;enumeration value="RS-3"/>
 *             &lt;enumeration value="RS-4"/>
 *             &lt;enumeration value="RS-5"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "")
@XmlRootElement(name = "referral")
public class Referral {

    @XmlAttribute
    protected String optimal;
    @XmlAttribute
    protected String specifyOptimal;
    @XmlAttribute
    protected String actual;
    @XmlAttribute
    protected String specifyActual;
    @XmlAttribute
    protected String differenceReason;
    @XmlAttribute
    protected String status;

    /**
     * Gets the value of the optimal property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOptimal() {
        return optimal;
    }

    /**
     * Sets the value of the optimal property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOptimal(String value) {
        this.optimal = value;
    }

    /**
     * Gets the value of the specifyOptimal property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSpecifyOptimal() {
        return specifyOptimal;
    }

    /**
     * Sets the value of the specifyOptimal property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSpecifyOptimal(String value) {
        this.specifyOptimal = value;
    }

    /**
     * Gets the value of the actual property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getActual() {
        return actual;
    }

    /**
     * Sets the value of the actual property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setActual(String value) {
        this.actual = value;
    }

    /**
     * Gets the value of the specifyActual property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSpecifyActual() {
        return specifyActual;
    }

    /**
     * Sets the value of the specifyActual property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSpecifyActual(String value) {
        this.specifyActual = value;
    }

    /**
     * Gets the value of the differenceReason property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDifferenceReason() {
        return differenceReason;
    }

    /**
     * Sets the value of the differenceReason property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDifferenceReason(String value) {
        this.differenceReason = value;
    }

    /**
     * Gets the value of the status property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStatus() {
        return status;
    }

    /**
     * Sets the value of the status property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStatus(String value) {
        this.status = value;
    }

}
