drop view v_lookup_table;
truncate table app_lookuptable;
truncate table app_lookuptable_fields;

INSERT INTO APP_LOOKUPTABLE T (TABLEID, MODULEID, TABLE_NAME, DESCRIPTION, ISTREE, TREECODE_LENGTH, ACTIVEYN)
  VALUES ('AST', '5', 'lst_admission_status', 'Admission Status', 0, 0, 0);
INSERT INTO APP_LOOKUPTABLE T (TABLEID, MODULEID, TABLE_NAME, DESCRIPTION, ISTREE, TREECODE_LENGTH, ACTIVEYN)
  VALUES ('BTY', '4', 'bed_type', 'Bed Type', 0, 0, 0);
INSERT INTO APP_LOOKUPTABLE T (TABLEID, MODULEID, TABLE_NAME, DESCRIPTION, ISTREE, TREECODE_LENGTH, ACTIVEYN)
  VALUES ('DRN', '5', 'lst_discharge_reason', 'Discharge Reason', 0, 0, 1);
INSERT INTO APP_LOOKUPTABLE T (TABLEID, MODULEID, TABLE_NAME, DESCRIPTION, ISTREE, TREECODE_LENGTH, ACTIVEYN)
  VALUES ('FAC', '5', 'facility', 'Facility', 0, 0, 0);
INSERT INTO APP_LOOKUPTABLE T (TABLEID, MODULEID, TABLE_NAME, DESCRIPTION, ISTREE, TREECODE_LENGTH, ACTIVEYN)
  VALUES ('FCT', '1', 'lst_field_category', 'Field Category', 0, 0, 1);
INSERT INTO APP_LOOKUPTABLE T (TABLEID, MODULEID, TABLE_NAME, DESCRIPTION, ISTREE, TREECODE_LENGTH, ACTIVEYN)
  VALUES ('GEN', '4', 'lst_gender', 'Gender', 0, 0, 1);
INSERT INTO APP_LOOKUPTABLE T (TABLEID, MODULEID, TABLE_NAME, DESCRIPTION, ISTREE, TREECODE_LENGTH, ACTIVEYN)
  VALUES ('LKT', '1', 'app_lookuptable', 'Available Fields', 0, 0, 1);
INSERT INTO APP_LOOKUPTABLE T (TABLEID, MODULEID, TABLE_NAME, DESCRIPTION, ISTREE, TREECODE_LENGTH, ACTIVEYN)
  VALUES ('OGN', '2', 'lst_organization', 'Organization', 0, 0, 1);
INSERT INTO APP_LOOKUPTABLE T (TABLEID, MODULEID, TABLE_NAME, DESCRIPTION, ISTREE, TREECODE_LENGTH, ACTIVEYN)
  VALUES ('ORG', '1', 'v_lk_org', 'Organization Chart', 0, 0, 0);
INSERT INTO APP_LOOKUPTABLE T (TABLEID, MODULEID, TABLE_NAME, DESCRIPTION, ISTREE, TREECODE_LENGTH, ACTIVEYN)
  VALUES ('PRO', '5', 'program', 'Program', 0, 0, 0);
INSERT INTO APP_LOOKUPTABLE T (TABLEID, MODULEID, TABLE_NAME, DESCRIPTION, ISTREE, TREECODE_LENGTH, ACTIVEYN)
  VALUES ('PTY', '5', 'lst_program_type', 'Program Type', 0, 0, 0);
INSERT INTO APP_LOOKUPTABLE T (TABLEID, MODULEID, TABLE_NAME, DESCRIPTION, ISTREE, TREECODE_LENGTH, ACTIVEYN)
  VALUES ('SEC', '2', 'lst_sector', 'Sector', 0, 0, 1);
INSERT INTO APP_LOOKUPTABLE T (TABLEID, MODULEID, TABLE_NAME, DESCRIPTION, ISTREE, TREECODE_LENGTH, ACTIVEYN)
  VALUES ('SRT', '3', 'lst_service_restriction', 'Service Restriction', 0, 0, 1);
COMMIT;

INSERT INTO APP_LOOKUPTABLE_FIELDS T (TABLEID, FIELDNAME, FIELDDESC, EDITYN, FIELDTYPE, LOOKUPTABLE, FIELDSQL, FIELDINDEX, UNIQUEYN, GENERICIDX, AUTOYN)
  VALUES ('BTY', 'BED_TYPE_ID', 'Id', '0', 'N', NULL, 'bed_type_id', 1, 1, 1, 1);
INSERT INTO APP_LOOKUPTABLE_FIELDS T (TABLEID, FIELDNAME, FIELDDESC, EDITYN, FIELDTYPE, LOOKUPTABLE, FIELDSQL, FIELDINDEX, UNIQUEYN, GENERICIDX, AUTOYN)
  VALUES ('BTY', 'DFLT', 'Default Capacity', '1', 'N', NULL, 'dflt', 3, 0, 6, 0);
INSERT INTO APP_LOOKUPTABLE_FIELDS T (TABLEID, FIELDNAME, FIELDDESC, EDITYN, FIELDTYPE, LOOKUPTABLE, FIELDSQL, FIELDINDEX, UNIQUEYN, GENERICIDX, AUTOYN)
  VALUES ('BTY', 'NAME', 'Name', '1', 'S', NULL, 'name', 2, 0, 2, 0);
INSERT INTO APP_LOOKUPTABLE_FIELDS T (TABLEID, FIELDNAME, FIELDDESC, EDITYN, FIELDTYPE, LOOKUPTABLE, FIELDSQL, FIELDINDEX, UNIQUEYN, GENERICIDX, AUTOYN)
  VALUES ('DRN', 'DESCRIPTION', 'Description', '1', 'S', NULL, 'description', 2, 0, 2, 0);
INSERT INTO APP_LOOKUPTABLE_FIELDS T (TABLEID, FIELDNAME, FIELDDESC, EDITYN, FIELDTYPE, LOOKUPTABLE, FIELDSQL, FIELDINDEX, UNIQUEYN, GENERICIDX, AUTOYN)
  VALUES ('DRN', 'DISPLAYORDER', 'Dispaly Order', '1', 'N', NULL, 'displayorder', 5, 0, 4, 0);
INSERT INTO APP_LOOKUPTABLE_FIELDS T (TABLEID, FIELDNAME, FIELDDESC, EDITYN, FIELDTYPE, LOOKUPTABLE, FIELDSQL, FIELDINDEX, UNIQUEYN, GENERICIDX, AUTOYN)
  VALUES ('DRN', 'ID', 'Id', '0', 'N', NULL, 'id', 1, 1, 1, 1);
INSERT INTO APP_LOOKUPTABLE_FIELDS T (TABLEID, FIELDNAME, FIELDDESC, EDITYN, FIELDTYPE, LOOKUPTABLE, FIELDSQL, FIELDINDEX, UNIQUEYN, GENERICIDX, AUTOYN)
  VALUES ('DRN', 'ISACTIVE', 'Active?', '1', 'B', NULL, 'isactive', 4, 0, 3, 0);
INSERT INTO APP_LOOKUPTABLE_FIELDS T (TABLEID, FIELDNAME, FIELDDESC, EDITYN, FIELDTYPE, LOOKUPTABLE, FIELDSQL, FIELDINDEX, UNIQUEYN, GENERICIDX, AUTOYN)
  VALUES ('DRN', 'NEEDSECONDARY', 'Has Associated Secondary Reason?', '1', 'N', NULL, 'needsecondary', 3, 0, 6, 0);
INSERT INTO APP_LOOKUPTABLE_FIELDS T (TABLEID, FIELDNAME, FIELDDESC, EDITYN, FIELDTYPE, LOOKUPTABLE, FIELDSQL, FIELDINDEX, UNIQUEYN, GENERICIDX, AUTOYN)
  VALUES ('FCT', 'DESCRIPTION', 'Description', '1', 'S', NULL, 'description', 2, 0, 2, 0);
INSERT INTO APP_LOOKUPTABLE_FIELDS T (TABLEID, FIELDNAME, FIELDDESC, EDITYN, FIELDTYPE, LOOKUPTABLE, FIELDSQL, FIELDINDEX, UNIQUEYN, GENERICIDX, AUTOYN)
  VALUES ('FCT', 'DISPLAYORDER', 'Dispaly Order', '1', 'N', NULL, 'displayorder', 4, 0, 4, 0);
INSERT INTO APP_LOOKUPTABLE_FIELDS T (TABLEID, FIELDNAME, FIELDDESC, EDITYN, FIELDTYPE, LOOKUPTABLE, FIELDSQL, FIELDINDEX, UNIQUEYN, GENERICIDX, AUTOYN)
  VALUES ('FCT', 'ID', 'Id', '0', 'N', NULL, 'id', 1, 1, 1, 1);
INSERT INTO APP_LOOKUPTABLE_FIELDS T (TABLEID, FIELDNAME, FIELDDESC, EDITYN, FIELDTYPE, LOOKUPTABLE, FIELDSQL, FIELDINDEX, UNIQUEYN, GENERICIDX, AUTOYN)
  VALUES ('FCT', 'ISACTIVE', 'Active?', '1', 'B', NULL, 'isactive', 3, 0, 3, 0);
INSERT INTO APP_LOOKUPTABLE_FIELDS T (TABLEID, FIELDNAME, FIELDDESC, EDITYN, FIELDTYPE, LOOKUPTABLE, FIELDSQL, FIELDINDEX, UNIQUEYN, GENERICIDX, AUTOYN)
  VALUES ('GEN', 'CODE', 'Code', '1', 'S', NULL, 'code', 1, 1, 1, 0);
INSERT INTO APP_LOOKUPTABLE_FIELDS T (TABLEID, FIELDNAME, FIELDDESC, EDITYN, FIELDTYPE, LOOKUPTABLE, FIELDSQL, FIELDINDEX, UNIQUEYN, GENERICIDX, AUTOYN)
  VALUES ('GEN', 'DESCRIPTION', 'Description', '1', 'S', NULL, 'description', 2, 0, 2, 0);
INSERT INTO APP_LOOKUPTABLE_FIELDS T (TABLEID, FIELDNAME, FIELDDESC, EDITYN, FIELDTYPE, LOOKUPTABLE, FIELDSQL, FIELDINDEX, UNIQUEYN, GENERICIDX, AUTOYN)
  VALUES ('GEN', 'DISPLAYORDER', 'Dispaly Order', '1', 'N', NULL, 'displayorder', 4, 0, 4, 0);
INSERT INTO APP_LOOKUPTABLE_FIELDS T (TABLEID, FIELDNAME, FIELDDESC, EDITYN, FIELDTYPE, LOOKUPTABLE, FIELDSQL, FIELDINDEX, UNIQUEYN, GENERICIDX, AUTOYN)
  VALUES ('GEN', 'ISACTIVE', 'Active?', '1', 'B', NULL, 'isactive', 3, 0, 3, 0);
INSERT INTO APP_LOOKUPTABLE_FIELDS T (TABLEID, FIELDNAME, FIELDDESC, EDITYN, FIELDTYPE, LOOKUPTABLE, FIELDSQL, FIELDINDEX, UNIQUEYN, GENERICIDX, AUTOYN)
  VALUES ('LKT', 'ACTIVEYN', 'Active?', '1', 'B', NULL, 'activeyn', 7, 0, 3, 0);
INSERT INTO APP_LOOKUPTABLE_FIELDS T (TABLEID, FIELDNAME, FIELDDESC, EDITYN, FIELDTYPE, LOOKUPTABLE, FIELDSQL, FIELDINDEX, UNIQUEYN, GENERICIDX, AUTOYN)
  VALUES ('LKT', 'DESCRIPTION', 'Description', '1', 'S', NULL, 'description', 4, 0, 2, 0);
INSERT INTO APP_LOOKUPTABLE_FIELDS T (TABLEID, FIELDNAME, FIELDDESC, EDITYN, FIELDTYPE, LOOKUPTABLE, FIELDSQL, FIELDINDEX, UNIQUEYN, GENERICIDX, AUTOYN)
  VALUES ('LKT', 'ISTREE', 'Is Tree Structured?', '1', 'B', NULL, 'istree', 5, 0, 0, 0);
INSERT INTO APP_LOOKUPTABLE_FIELDS T (TABLEID, FIELDNAME, FIELDDESC, EDITYN, FIELDTYPE, LOOKUPTABLE, FIELDSQL, FIELDINDEX, UNIQUEYN, GENERICIDX, AUTOYN)
  VALUES ('LKT', 'MODULEID', 'Category', '1', 'S', 'FCT', 'moduleid', 2, 0, 5, 0);
INSERT INTO APP_LOOKUPTABLE_FIELDS T (TABLEID, FIELDNAME, FIELDDESC, EDITYN, FIELDTYPE, LOOKUPTABLE, FIELDSQL, FIELDINDEX, UNIQUEYN, GENERICIDX, AUTOYN)
  VALUES ('LKT', 'TABLEID', 'Id', '0', 'S', NULL, 'tableid', 1, 1, 1, 0);
INSERT INTO APP_LOOKUPTABLE_FIELDS T (TABLEID, FIELDNAME, FIELDDESC, EDITYN, FIELDTYPE, LOOKUPTABLE, FIELDSQL, FIELDINDEX, UNIQUEYN, GENERICIDX, AUTOYN)
  VALUES ('LKT', 'TABLE_NAME', 'Table Name', '1', 'S', NULL, 'table_name', 3, 0, 6, 0);
INSERT INTO APP_LOOKUPTABLE_FIELDS T (TABLEID, FIELDNAME, FIELDDESC, EDITYN, FIELDTYPE, LOOKUPTABLE, FIELDSQL, FIELDINDEX, UNIQUEYN, GENERICIDX, AUTOYN)
  VALUES ('LKT', 'TREECODE_LENGTH', 'Tree Code Length (if is tree)', '1', 'N', NULL, 'treecode_length', 6, 0, 0, 0);
INSERT INTO APP_LOOKUPTABLE_FIELDS T (TABLEID, FIELDNAME, FIELDDESC, EDITYN, FIELDTYPE, LOOKUPTABLE, FIELDSQL, FIELDINDEX, UNIQUEYN, GENERICIDX, AUTOYN)
  VALUES ('OGN', 'DESCRIPTION', 'Description', '1', 'S', NULL, 'description', 2, 0, 2, 0);
INSERT INTO APP_LOOKUPTABLE_FIELDS T (TABLEID, FIELDNAME, FIELDDESC, EDITYN, FIELDTYPE, LOOKUPTABLE, FIELDSQL, FIELDINDEX, UNIQUEYN, GENERICIDX, AUTOYN)
  VALUES ('OGN', 'DISPLAYORDER', 'Dispaly Order', '1', 'N', NULL, 'displayorder', 4, 0, 4, 0);
INSERT INTO APP_LOOKUPTABLE_FIELDS T (TABLEID, FIELDNAME, FIELDDESC, EDITYN, FIELDTYPE, LOOKUPTABLE, FIELDSQL, FIELDINDEX, UNIQUEYN, GENERICIDX, AUTOYN)
  VALUES ('OGN', 'ID', 'Id', '0', 'N', NULL, 'id', 1, 1, 1, 1);
INSERT INTO APP_LOOKUPTABLE_FIELDS T (TABLEID, FIELDNAME, FIELDDESC, EDITYN, FIELDTYPE, LOOKUPTABLE, FIELDSQL, FIELDINDEX, UNIQUEYN, GENERICIDX, AUTOYN)
  VALUES ('OGN', 'ISACTIVE', 'Active?', '1', 'B', NULL, 'isactive', 3, 0, 3, 0);
INSERT INTO APP_LOOKUPTABLE_FIELDS T (TABLEID, FIELDNAME, FIELDDESC, EDITYN, FIELDTYPE, LOOKUPTABLE, FIELDSQL, FIELDINDEX, UNIQUEYN, GENERICIDX, AUTOYN)
  VALUES ('SEC', 'DESCRIPTION', 'Description', '1', 'S', NULL, 'description', 2, 0, 2, 0);
INSERT INTO APP_LOOKUPTABLE_FIELDS T (TABLEID, FIELDNAME, FIELDDESC, EDITYN, FIELDTYPE, LOOKUPTABLE, FIELDSQL, FIELDINDEX, UNIQUEYN, GENERICIDX, AUTOYN)
  VALUES ('SEC', 'DISPLAYORDER', 'Dispaly Order', '1', 'N', NULL, 'displayorder', 4, 0, 4, 0);
INSERT INTO APP_LOOKUPTABLE_FIELDS T (TABLEID, FIELDNAME, FIELDDESC, EDITYN, FIELDTYPE, LOOKUPTABLE, FIELDSQL, FIELDINDEX, UNIQUEYN, GENERICIDX, AUTOYN)
  VALUES ('SEC', 'ID', 'Id', '0', 'N', NULL, 'id', 1, 1, 1, 1);
INSERT INTO APP_LOOKUPTABLE_FIELDS T (TABLEID, FIELDNAME, FIELDDESC, EDITYN, FIELDTYPE, LOOKUPTABLE, FIELDSQL, FIELDINDEX, UNIQUEYN, GENERICIDX, AUTOYN)
  VALUES ('SEC', 'ISACTIVE', 'Active?', '1', 'B', NULL, 'isactive', 3, 0, 3, 0);
INSERT INTO APP_LOOKUPTABLE_FIELDS T (TABLEID, FIELDNAME, FIELDDESC, EDITYN, FIELDTYPE, LOOKUPTABLE, FIELDSQL, FIELDINDEX, UNIQUEYN, GENERICIDX, AUTOYN)
  VALUES ('SRT', 'DESCRIPTION', 'Description', '1', 'S', NULL, 'description', 2, 0, 2, 0);
INSERT INTO APP_LOOKUPTABLE_FIELDS T (TABLEID, FIELDNAME, FIELDDESC, EDITYN, FIELDTYPE, LOOKUPTABLE, FIELDSQL, FIELDINDEX, UNIQUEYN, GENERICIDX, AUTOYN)
  VALUES ('SRT', 'DISPLAYORDER', 'Dispaly Order', '1', 'N', NULL, 'displayorder', 4, 0, 4, 0);
INSERT INTO APP_LOOKUPTABLE_FIELDS T (TABLEID, FIELDNAME, FIELDDESC, EDITYN, FIELDTYPE, LOOKUPTABLE, FIELDSQL, FIELDINDEX, UNIQUEYN, GENERICIDX, AUTOYN)
  VALUES ('SRT', 'ID', 'Id', '0', 'N', NULL, 'id', 1, 1, 1, 1);
INSERT INTO APP_LOOKUPTABLE_FIELDS T (TABLEID, FIELDNAME, FIELDDESC, EDITYN, FIELDTYPE, LOOKUPTABLE, FIELDSQL, FIELDINDEX, UNIQUEYN, GENERICIDX, AUTOYN)
  VALUES ('SRT', 'ISACTIVE', 'Active?', '1', 'B', NULL, 'isactive', 3, 0, 3, 0);
COMMIT;
