CREATE OR REPLACE TRIGGER TRI_relationships_id
BEFORE INSERT
ON relationships
FOR EACH ROW
DECLARE
       IDX NUMBER;
BEGIN

     SELECT HIBERNATE_SEQUENCE.NEXTVAL INTO IDX FROM DUAL;
     :new.id := IDX;
END;
