package org.oscarehr.casemgmt.model.base;

import java.io.Serializable;


/**
 * This class has been automatically generated by Hibernate Synchronizer.
 * For more information or documentation, visit The Hibernate Synchronizer page
 * at http://www.binamics.com/hibernatesync or contact Joe Hudson at joe@binamics.com.
 *
 * This is an object that contains data related to the casemgmt_tmpsave table.
 * Do not modify this class because it will be overwritten if the configuration file
 * related to this class is modified.
 *
 * @hibernate.class
 *  table="casemgmt_tmpsave"
 */
public abstract class BaseCaseManagementTmpSave  implements Serializable {

	public static String PROP_UPDATE_DATE = "update_date";
	public static String PROP_PROVIDER_NO = "providerNo";
	public static String PROP_PROGRAM_ID = "programId";
	public static String PROP_DEMOGRAPHIC_NO = "demographicNo";
	public static String PROP_NOTE = "note";
	public static String PROP_ID = "id";


	private int hashCode = Integer.MIN_VALUE;

	// primary key
	private java.lang.Long _id;

	// fields
	private long _demographicNo;
	private java.lang.String _providerNo;
	private long _programId;
	private java.lang.String _note;
	private java.util.Date _update_date;


	// constructors
	public BaseCaseManagementTmpSave () {
		initialize();
	}

	/**
	 * Constructor for primary key
	 */
	public BaseCaseManagementTmpSave (java.lang.Long _id) {
		this.setId(_id);
		initialize();
	}

	protected void initialize () {}



	/**
	 * Return the unique identifier of this class
     * @hibernate.id
     *  generator-class="native"
     *  column="id"
     */
	public java.lang.Long getId () {
		return _id;
	}

	/**
	 * Set the unique identifier of this class
	 * @param _id the new ID
	 */
	public void setId (java.lang.Long _id) {
		this._id = _id;
		this.hashCode = Integer.MIN_VALUE;
	}


	/**
	 * Return the value associated with the column: demographic_no
	 */
	public long getDemographicNo () {
		return _demographicNo;
	}

	/**
	 * Set the value related to the column: demographic_no
	 * @param _demographicNo the demographic_no value
	 */
	public void setDemographicNo (long _demographicNo) {
		this._demographicNo = _demographicNo;
	}


	/**
	 * Return the value associated with the column: provider_no
	 */
	public java.lang.String getProviderNo () {
		return _providerNo;
	}

	/**
	 * Set the value related to the column: provider_no
	 * @param _providerNo the provider_no value
	 */
	public void setProviderNo (java.lang.String _providerNo) {
		this._providerNo = _providerNo;
	}


	/**
	 * Return the value associated with the column: program_id
	 */
	public long getProgramId () {
		return _programId;
	}

	/**
	 * Set the value related to the column: program_id
	 * @param _programId the program_id value
	 */
	public void setProgramId (long _programId) {
		this._programId = _programId;
	}


	/**
	 * Return the value associated with the column: note
	 */
	public java.lang.String getNote () {
		return _note;
	}

	/**
	 * Set the value related to the column: note
	 * @param _note the note value
	 */
	public void setNote (java.lang.String _note) {
		this._note = _note;
	}


	/**
	 * Return the value associated with the column: update_date
	 */
	public java.util.Date getUpdate_date () {
		return _update_date;
	}

	/**
	 * Set the value related to the column: update_date
	 * @param _update_date the update_date value
	 */
	public void setUpdate_date (java.util.Date _update_date) {
		this._update_date = _update_date;
	}


	public boolean equals (Object obj) {
		if (null == obj) return false;
		if (!(obj instanceof org.oscarehr.casemgmt.model.base.BaseCaseManagementTmpSave)) return false;
		else {
			org.oscarehr.casemgmt.model.base.BaseCaseManagementTmpSave mObj = (org.oscarehr.casemgmt.model.base.BaseCaseManagementTmpSave) obj;
			if (null == this.getId() || null == mObj.getId()) return false;
			else return (this.getId().equals(mObj.getId()));
		}
	}


	public int hashCode () {
		if (Integer.MIN_VALUE == this.hashCode) {
			if (null == this.getId()) return super.hashCode();
			else {
				String hashStr = this.getClass().getName() + ":" + this.getId().hashCode();
				this.hashCode = hashStr.hashCode();
			}
		}
		return this.hashCode;
	}


	public String toString () {
		return super.toString();
	}

}